### PR TITLE
cleanup(repo): remove unused dependencies

### PR DESCRIPTION
**Pull request by Phillip9587**
See individual commits

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by Phillip9587** [comment]
Hi @JamesHenry,

I hope you're doing well! I just wanted to kindly follow up on this PR as it has been open for about a month without any reviews. Whenever you have a chance, could you please take a look? Let me know if there’s anything I can do to help move this forward.

Thanks again for your time and consideration!

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
LGTM, thanks, sorry just needs a conflict fix up in the lock file

**Comment by JamesHenry** [comment]
I pushed it up myself

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
@Phillip9587 I'm afraid it looks like `webpack-sources` is used after all now. I think it's because the rspack plugin was promoted from labs into this repo. Please could you take another look?

**Review by JamesHenry — CHANGES_REQUESTED** [review]
See comment

**Comment by Phillip9587** [comment]
I opened #28447 to remove the `webpack-sources` import to maybe get this merged sooner.

**Comment by JamesHenry** [comment]
@Phillip9587 is this one still relevant? Does it just need a rebase?

**Comment by Phillip9587** [comment]
@JamesHenry Yes it is. I'm going to rebase it. Should i open a PR for each individual removal? Would it be easier to merge multiple PRs?

**Comment by Phillip9587** [comment]
@JamesHenry Can we merge this now? Rebasing takes quite some time and the dependencies are unused so there are no source code changes

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
Thanks again!

**Pull request merged**
