### PR TITLE
Fix/storybook root config js file

### LINKED ISSUE #3136: @nrwl/storybook: support global config.js like addons.js
## Description

storybook `configuration` schematic should support generation of a root `config.js` and import it per project storybook similarly to [addons.js](https://github.com/nrwl/nx/blob/master/packages/storybook/src/schematics/configuration/lib-files/.storybook/addons.js__tmpl__)

This behaviour could by a default one or opt in via schematic flag

## Motivation

There might be use case scenario that one wants provide common setup of storybook across organisation without need of manual intervention.

**For instance:**

- we wanna support e2e testing against storybook with support of `cypress-storybook`
- having common defaults regarding decorators

## Suggested Implementation

```sh
nx g @nrwl/react:storybook-configuration --sb-config --name=test-project
```

1. Would create ROOT `config.js` -> `<workspace-root>/.storybook/config.js`

- with following content:

```js
// for angular it would use '@storybook/angular' etc...
import { addDecorator } from '@storybook/react';
import { withKnobs } from '@storybook/addon-knobs';

addDecorator(withKnobs);
```

2. create `libs/test-project/.storybook/config.js` with following content:

```js
// for angular it would use '@storybook/angular' etc...
import { configure } from '@storybook/react';

import '<%= offsetFromRoot %>../.storybook/config';

configure(require.context('../src/lib', true, /\.stories\.(j|t)sx?$/), module);
```

### PR DESCRIPTION
**Pull request by mandarini**
## Related Issue(s)

Fixes #3136

### CODE REVIEW

**Comment by juristr** [comment]
As discussed, we might wait with this one since the #3434 should solve it already.

**Comment by juristr** [comment]
_Note: keeping this open for now, 'cause depending on our Storybook 6 upgrade strategy we might want to fix this in v5 as well_

**Comment by mandarini** [comment]
@juristr Should we close this PR? I think it's no longer relevant..

**Comment by juristr** [comment]
Yeah I think we can close this one as v6 doesn't have this issue any more 👍

**Pull request closed without merging**
