### PR TITLE
docs(core): use latest for create-nx-workspace

### PR DESCRIPTION
**Pull request by arjunyel**
## Current Behavior

Not pointing to latest create-nx-workspace

## Expected Behavior

When creating a new project, should use latest version 😄

### CODE REVIEW

**Comment by arjunyel** [comment]
Im not sure why the tests didn't pass, I don't think it was anything I did

**Comment by isaacplmann** [comment]
The problem is the commit message.  `nxdev` is not valid.  You should use `docs(core)`

**Comment by arjunyel** [comment]
Sorry for the trouble, I was following the file history

Screenshot_20230320-105549

**Comment by arjunyel** [comment]
Fixed commit message

**Review by isaacplmann — APPROVED** [review]
Thanks!

**Pull request merged**
