### PR TITLE
fix(webpack): Fixed `libraryTarget` option not being set for node targets

### LINKED ISSUE #182: Google Cloud functions framework not working when upgrading Nx from 17.0.3 -> 17.1.3
Running a cloud function used to work with v17.0.x

```
npx @google-cloud/functions-framework --source=dist/apps/cloud-functions --target=CloudFunctions

Function 'CloudFunctions' is not defined in the provided module.
Did you specify the correct target function to execute?
Could not load the function, shutting down.
```

From what I realized: the build in the `dist` is different between the two versions:

Nx Report (17.0.3):

```
 Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx (global)        : 17.0.3
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/esbuild        : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/nest           : 17.0.3
   @nx/node           : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-extend/gcp-functions : 10.0.1
```

Compiled version before update (17.0.3):

```
/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it uses a non-standard name for the exports (exports).
(() => {
var exports = __webpack_exports__;

Object.defineProperty(exports, "__esModule", ({ value: true }));
exports.CloudFunctions = void 0;
const { foo = 'testBar' } = process.env;
const CloudFunctions = async (req, res) => {
    res.status(200).send(foo);
};
exports.CloudFunctions = CloudFunctions;

})();

var __webpack_export_target__ = exports;
for(var i in __webpack_exports__) __webpack_export_target__[i] = __webpack_exports__[i];
if(__webpack_exports__.__esModule) Object.defineProperty(__webpack_export_target__, "__esModule", { value: true });
/******/ })()
;
//# sourceMappingURL=main.js.map

```

Nx Report (17.1.3):

```
 Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx (global)        : 17.1.3
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/esbuild        : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/nest           : 17.1.3
   @nx/node           : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   nx-cloud           : 16.5.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-extend/gcp-functions : 10.0.1
```
Compiled version after update (17.1.3):

```
/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it uses a non-standard name for the exports (exports).
(() => {
var exports = __webpack_exports__;

Object.defineProperty(exports, "__esModule", ({ value: true }));
const { foo = 'testBar' } = process.env;
const CloudFunctions = async (req, res) => {
    res.status(200).send(foo);
};
exports.CloudFunctions = CloudFunctions;

})();

/******/ })()
;
//# sourceMappingURL=main.js.map

```

### LINKED ISSUE #20349: All my AWS Lambda functions stopped working after updating to 17.1.2 (@nx/webpack:webpack removed exports)
### Current Behavior

image
17.0.3 on the left side - 17.1.2 on the right side

### Expected Behavior

that the exports are there in the end ...

### GitHub Repo

_No response_

### Steps to Reproduce

1. New action does not export the exports from main.ts

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32-x64
   pnpm   : 8.10.2
   
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/angular        : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/nest           : 17.1.2
   @nx/node           : 17.1.2
   @nx/storybook      : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.1.2
   nx-cloud           : 16.5.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc     : 1.1.22
   @ngrx/component-store  : 16.3.0
   @ngrx/effects          : 16.3.0
   @ngrx/entity           : 16.3.0
   @ngrx/router-store     : 16.3.0
   @ngrx/schematics       : 16.3.0
   @ngrx/store            : 16.3.0
   @ngrx/store-devtools   : 16.3.0
   @nx-tools/nx-container : 5.1.0
   @storybook/angular     : 7.5.3
   ng-mocks               : 14.12.1
```

### Failure Logs

_No response_

### Package Manager Version

pnpm 8.10.5

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TriPSs**
## Current Behavior

When #19984 got merged it changed the implementation of Webpack.

## Expected Behavior

For node projects to compile like they always did.

## Related Issue(s)
Fixes #20349
Fixes TriPSs/nx-extend#182

### CODE REVIEW

**Comment by TriPSs** [comment]
@JamesHenry the CI fails on the commit messages, think this PR will be squashed?

**Comment by JamesHenry** [comment]
@TriPSs naturally you need to pass the CI checks in order to proceed, please update any relevant commits to pass the check. To avoid this issue, the check is applied locally in a prepush hook, so you must have been forcing your way through that

**Comment by TriPSs** [comment]
Those checks did not run at all since I did not have `pnpm` installed on my machine, was able to just normally "push".

**Comment by TriPSs** [comment]
@JamesHenry recreated the PR #20505, could it be checked so everyone can release their cloud functions again?

**Pull request closed without merging**
