### PR TITLE
chore(core): nx plugin submission nx-clone

### PR DESCRIPTION
**Pull request by AndrewRedican**
### Motivation
I've come across the need to automate creating certain types of projects, originally created and modified through some nrwl and community generator, and further manual tweaks. Rather than creating a step-by-step guide on how to create the same type of project again, I've moved that into a "templates" folder for it to become one of my "base" projects.

With nx-clone I can spin up another project using one of my existing "template" projects on demand.

### Other Technical Details
This generator is similar to the "move" built-in generator provided by Nx and certainly took inspiration from it.
However, there are some key distinctions:
* The "move" removes the files from the previous location obviously as it is not a "copy" operation.
* The "move" command is constrained to what the libsDir and appsDir are, "nx-clone" on the other hand, lets you copy from and into folders that are not necessarily in the official Nx workspace layout (libsDir, appsDir)
* The "nx-clone" limits itself to only replacing project paths and names in the content of the top-level configuration files and the folder names themselves. It does not follow up with post-processing to update the centralized configuration. (Hypothetical example; have some workspace-level file that tracks certain project or test configurations). Some may be added in due course when people request those.

### Relevant Links
* https://www.npmjs.com/package/@enio.ai/nx-clone
* https://github.com/enio-ireland/enio/tree/develop/packages/nx-clone

### CODE REVIEW

**Comment by AndrewRedican** [comment]
What is the average time someone from the Nx team gets back to you when you submit a plugin?

**Comment by AndrewRedican** [comment]
At the risk of sounding eager 😅 
Any chance this will get looked at soon?

**Review by AgentEnder — CHANGES_REQUESTED** [review]
See earlier comment.

**Comment by mandarini** [comment]
@isaacplmann I assigned you because it's "plugin submission request", although it seems that the plugin does not have e2e tests, which we require?

@AndrewRedican did you get a chance to add some e2e tests on your end?

**Comment by isaacplmann** [comment]
Closing this PR due to inactivity.  @AndrewRedican , please reopen it if you add some e2e tests and still want to have `nx-clone` listed in the plugin registry.

**Pull request closed without merging**
