### PR TITLE
fix(node): wait for subprocess to exit when `--watch=false` in execute executor

### LINKED ISSUE #7031: The node:execute builder immediately exits after build when --watch=false.
## Current Behavior

The `node:execute` builder immediately exits after build when `--watch=false`.

## Expected Behavior

The `node:execute` builder wait for the subprocess to exit, or SIGTERM to be received, before exiting. This is how things worked previously.

## Steps to Reproduce

```sh
npx create-nx-workspace --preset=express
# set app-name to node-test

npm start # works as expected, stays around until you kill it

npm start -- --watch=false # immediately exits after app is started
```

### Failure Logs

Screen Shot 2021-09-16 at 11 24 07

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 16.6.2
  OS   : darwin x64
  pnpm : 6.13.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : Not Found
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : 12.9.0
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

### PR DESCRIPTION
**Pull request by jlndk**
Fixes #7031

## Current Behavior
Before this fix, the node/execute executor would exit immediately and let the node subprocess continue in the background, if watch was set to false.

## Expected Behavior
This PR attempts to fix this problem, by implementing the patch suggested in https://github.com/nrwl/nx/issues/7031#issuecomment-921145744, adding event listeners on the subprocess if watch is false, such that the nx process simply waits until the subprocess exists (successfully or not).

Error handling has also been added such that the executor fails if a non-successful status code is returned by the program

### CODE REVIEW

**Comment by hcharley** [comment]
I think this may answer my question here: https://github.com/nrwl/nx/discussions/5726

**Comment by hcharley** [comment]
Is there anything preventing this from being merged and included in the next release?

**Comment by hcharley** [comment]
Is there anything preventing this from being merged and included in the next release?

**Review by FrozenPandaz — APPROVED** [review]

**Comment by FrozenPandaz** [comment]
This was fixed with #9180.

Thank you @jlndk

**Pull request closed without merging**
