### PR TITLE
feat(nextjs): support next 10.1.2

### PR DESCRIPTION
**Pull request by kirjai**
Support for latest Next.js - version `10.1.2`. 

[Among features released in `10.1`](https://nextjs.org/blog/next-10-1) is opt-in support for webpack 5.

> [More notes on next.js plan for webpack 5](https://nextjs.org/docs/messages/webpack5)

Enabling webpack 5 support in an Nx project fails the build / serve with the following error:
```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].module.rules[4].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
 - configuration[1].module.rules[4].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
```

So it doesn't seem feasible to support that configuration option without a wider webpack 5 support in Nx. So at the moment, we detect if user is using the new `webpack5` flag, and throw an error saying that it's not supported by Nx yet.

### CODE REVIEW

**Comment by npirotte** [comment]
Sure I will, thanks!

**Comment by npirotte** [comment]
Nevermind my question, after update to latest nrwl/next plugin everything is working fine :)

**Comment by kirjai** [comment]
@npirotte great! happy to hear that, thanks for the update

**Comment by webpro** [comment]
I'm still seeing the exact same issue, without any custom Webpack config in `next.config.js`:

```
  return {
    future: {
      webpack5: true,
    },
  };
```

Some versions from package.json:

```
{
    "next": "^10.1.3",
[...]
    "@nrwl/cypress": "11.6.1",
    "@nrwl/eslint-plugin-nx": "11.6.1",
    "@nrwl/express": "11.6.1",
    "@nrwl/jest": "11.6.1",
    "@nrwl/next": "11.6.1",
    "@nrwl/node": "11.6.1",
    "@nrwl/react": "11.6.1",
    "@nrwl/storybook": "11.6.1",
    "@nrwl/web": "11.6.1",
    "@nrwl/workspace": "11.6.1",
}
```

```
❯ nx serve [app]

> nx run [app]:serve 
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - automatically enabled Fast Refresh for 1 custom loader
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].module.rules[4].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
 - configuration[1].module.rules[4].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
```

Not sure how to debug this further, or what to look into. Any ideas welcome!

**Comment by kirjai** [comment]
hey @webpro . I believe it's probably because you're not using the `withNx` config plugin in your `next.config.json`. [Docs](https://nx.dev/latest/react/guides/nextjs#verify-the-project-39-s-next-config-js). Even though it's from a "Deploying to Vercel" section, it's applicable for any Next.js project really. We're working on updating the docs to explain it better

**Comment by webpro** [comment]
Thanks, @kirjai! Unfortunately, with this `next.config.js` I'm still getting the same error:

```js
const withNx = require('@nrwl/next/plugins/with-nx');

module.exports = phase => {
  const config = {
    future: {
      webpack5: true,
    },
  };

  return withNx(config);
};
```

**Comment by kirjai** [comment]
oh, apologies @webpro, I should've realized this earlier, but this fix hasn't been released yet 😅 should be out in the next version, but `11.6.1` doesn't contain the fix yet

**Comment by webpro** [comment]
Can confirm with @nrwl/next v12.0.0:

```
❯ nx build [app]

> nx run [app]
withNx() plugin: using the "webpack5" option with Nx is not supported yet
```

**Comment by kirjai** [comment]
great, thanks for checking and reporting back, @webpro ! Hopefully we'll get that webpack5 supported soon 💪

**Pull request merged**
