### PR TITLE
fix(nx-dev): options of the affected are messed up

### LINKED ISSUE #27893: Affected: The table of options is not formatted properly
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://github.com/nrwl/nx/blob/master/docs/generated/packages/nx/documents/affected.md

### Additional context or description

The table of options is not formatted properly

### PR DESCRIPTION
**Pull request by pawel-twardziak**
Closes #27893

## Current Behavior
see #27893

## Expected Behavior
see #27893

## Related Issue(s)
see #27893

Fixes #
- docs for affected

### CODE REVIEW

**Comment by isaacplmann** [comment]
You need to run `nx documentation` and commit the changes that the script creates

**Comment by isaacplmann** [comment]
I pushed up a commit after I ran the `nx documentation` script

**Comment by isaacplmann** [comment]
Running the `nx documentation` script just wiped out all your changes because you were modifying generated files.  I found the part of the script that was adding extra new lines and fixed it

**Review by isaacplmann — APPROVED** [review]

**Comment by pawel-twardziak** [comment]
Thanks @isaacplmann, good job! And sorry I was slugginsh a bit...

**Pull request merged**
