### PR TITLE
feat(nx): add ability to ignore files that fall outside the scope of any project. addresses #392

### PR DESCRIPTION
**Pull request by mcblum**
I threw together some semi-pseudocode to illustrate what I was describing with Issue #392. You are all way above my skill level so I don't expect this code to actually make it, but hopefully you can see what worked for us.

### CODE REVIEW

**Comment by vsavkin** [comment]
Sorry for the late response.

I've been thinking about it, and I am leaning towards making all files outside apps and libs excluded except:

* projects' assets (derived from .angular-cli.json)
* .angular-cli.json
* package.json
* tslint.json
* test.js 

and a couple of others.

It'll solve the issue you are having, right?

**Comment by mcblum** [comment]
@vsavkin no worries dude - appreciate your responding at all!

I've been thinking about it, too, and I feel like it goes both ways and it's really hard to know for sure if the modified files actually have any impact. In our case, I have a few scripts that actually do change the apps when building for AOT as well as our deploy scripts which specify the server/folder / etc... for each application. If I were to change one of those scripts, then if we wanted to see the changes we would need to rebuild.

Do you think it would be a good compromise do pick a default, either it builds everything or nothing when a changed file falls outside the scope of all projects, and then maybe introduce a `.nxignore` file or something that contained the list of files that either always needed to trigger a build or never, depending on which way you go for the default?

Maybe that adds complexity, but in reality it's not like there are 1,000 files that fall outside scope. For our first couple Nx projects it's basically our CI/CD stuff. I'd be happy to list either all of the files that Nx won't know what to do with by default. Then the current code could basically remain as is with one additional check to see if the file with no lib is listed in `.nxignore` and if so, then ignore it and don't build.

Let me know if there's anything I can do and once again thanks for the reply!

**Comment by vsavkin** [comment]
I thought about a bit more, and I think you are right. It's better to give folks some control over what Nx cares about and what it does not care about.

We can do it like this.

1. The workspace will come with .nxignore file, which should work similarly to .gitignore.
2. affected.ts and format.ts invoke "parseFiles", which returns the list of the changed files. We need to filter this list using the .nxignore file. 
3. shared.ts contains getProjectNodes, which should filter out the files matching one of the records .nxignore.

The default .nxignore should look like this:

```
tools
.gitignore
.editorconfig
```

If you can take on it, I'm happy to help out and then merge the PR. If you feel like you won't have time, I can take a stab at it myself.

**Comment by mcblum** [comment]
@vsavkin hey! Sorry for the delay, just started a new project so my brain is all over the place lately.

I think you're right on and totally agree with that approach. I also think that convention is so well-accepted that people shouldn't have to learn anything in order to make their repos do what they want. I'll see if I can get a PR submitted this week for your review.

Unrelated, I just saw that you and Jeff are going to be at the May 1 Minneapolis Angular meetup. I RSVP'd and am looking forward to seeing you guys there!

**Comment by vsavkin** [comment]
@mcblum any progress on this? It's an important feature, so maybe @FrozenPandaz can help you with this?

**Comment by mcblum** [comment]
@vsavkin would definitely appreciate the help. I started two projects and am seriously overcommitted which I'm sure is not at all common with developers. @FrozenPandaz any interest in taking this on?

**Comment by FrozenPandaz** [comment]
@mcblum No worries, it's totally understandable. Thank you so much for the offer to help in the first place.

It seems you have a full plate. I can take this over and keep you in the loop. :)

**Comment by mcblum** [comment]
@FrozenPandaz thanks dude. I'll jump in as soon as I can -- at the very least I owe it to Nx since we're currently using it in now 6 different projects. Gotta give back.

**Comment by vsavkin** [comment]
@mcblum Jason implemented a feature called implicitDependencies that, I believe, addresses the issues you were having (read more here: https://blog.nrwl.io/nrwl-nx-6-1-better-dev-ergonomics-faster-builds-3198bb310e39)

Thanks again for overing to help with this! And it was great to see in person in Minneapolis.

**Comment by mcblum** [comment]
@vsavkin @FrozenPandaz you guys are the best.

You too, Victor. Keep up the great work!

**Pull request closed without merging**
