### PR TITLE
docs(core): add pnpm command for storybook plugin

### PR DESCRIPTION
**Pull request by vadhe**
## Current Behavior

There is no shortcut pnpm to Add the Storybook plugin

## Expected Behavior

there is a shortcut pnpm to Add the Storybook plugin like Vite plugin page
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by mandarini** [comment]
@vadhe thanks for the contribution! Can you please rebase and run `pnpm documentation` to make sure all is up to date? :D

**Comment by vadhe** [comment]
> @vadhe thanks for the contribution! Can you please rebase and run `pnpm documentation` to make sure all is up to date? :D

Sure, But I got an Error And I'm not quite sure what happened to it
Jepretan Layar 2023-06-26 pukul 19 39 59

**Comment by mandarini** [comment]
You need to install dependencies! You can run `pnpm i`! :)

**Comment by vadhe** [comment]
I already did it
Jepretan Layar 2023-06-26 pukul 20 08 19

**Comment by mandarini** [comment]
Hmm I see. Can you delete `node_modules` and run `npx pnpm@8.5.1 i` again? If that does not do the trick, then I'll clone your repo and try it locallly to see what else may be wrong! Thanks!!! :D

**Comment by vadhe** [comment]
this is going well `npx pnpm@8.5.1 i` and then I run ` npx pnpm@8.5.1 documentation`
Maybe I'm doing something wrong because the result looks error
Thanks for Help
Jepretan Layar 2023-06-26 pukul 20 30 21

**Comment by vadhe** [comment]
After I commit the last changes It is going well
Jepretan Layar 2023-06-26 pukul 20 36 08

**Comment by mandarini** [comment]
Oh yeah that error is there to make sure you commit the generated files. All should be well after you add this file to your commit and push.

**Comment by vadhe** [comment]
I pushed the new changes but with a new commit.
Should I rebase and fixup the commit?

**Review by mandarini — APPROVED** [review]

**Pull request merged**
