### PR TITLE
feat(core): remove fast-levenshtein dep from tao

### PR DESCRIPTION
**Pull request by catfireparty**
Removes the `fast-levenshtein` package as a dependency from `tao` and uses the function from `@angular-devkit/core` instead.

### CODE REVIEW

**Comment by alfaproject** [comment]
Might I suggest splitting into two PRs?

**Comment by jdpearce** [comment]
@alfaproject Can do. One of them will be tiny though 😆

**Comment by vsavkin** [comment]
Thank you!

**Comment by vsavkin** [comment]
Could you rebase it? After that we can merge it.

**Pull request merged**
