### PR TITLE
feat(web): upgrade to postcss v8

### LINKED ISSUE #4044: Update to Postcss 8 in @nrwl/web
## Description

Postcss 8 has been released 2 months. It would be better to update the dependencies in web.

### PR DESCRIPTION
**Pull request by JamesHenry**
## Current Behavior

@nrwl/web does not allow you to use postcss v8, and therefore you cannot use Tailwind 2, and other libraries that have migrated to it over the last few months.

Angular CLI, Next.js and create-react-app have already merged postcss v8 support.

## Expected Behavior

@nrwl/web should use postcss v8.

## Related Issue(s)

Fixes #4044

**NOTE:** The change in indentation and formatting makes this diff seem more complex than it is.

I followed this blog post to make these changes: https://evilmartians.com/chronicles/postcss-8-plugin-migration and ultimately it boils down to implementing the equivalent of this plugin API change from that post:

```diff
- module.exports = postcss.plugin('postcss-dark-theme-class', (opts = {}) => {
-   checkOpts(opts)
-   return (root, result) => {
      root.walkAtRules(atrule => { … })
-   }
- })
```

```diff
+ module.exports = (opts = {}) => {
+   checkOpts(opts)
+   return {
+     postcssPlugin: 'postcss-dark-theme-class',
+     Once (root, { result }) {
        root.walkAtRules(atrule => { … })
+     }
+   }
+ }
+ module.exports.postcss = true
```

And then updating the usage of the plugin, because `postcss-loader` also had breaking changes in its API.

### CODE REVIEW

**Comment by JamesHenry** [comment]
Ok looks like we’ll need some more updates to complete this.

I’ll work on those this week

**Comment by JamesHenry** [comment]
I built a location version of the codebase and successfully created, served, and production built a react app using Tailwind 2 to test this out.

**Comment by JamesHenry** [comment]
NOTE: If users are currently using a custom webpack config with @nrwl/web and manipulating the `postcss-loader` instance then this will be a breaking change for them.

For other users there should be no breaking change.

How would you like to handle that?

**Comment by gperdomor** [comment]
@JamesHenry @vsavkin any update on this? Any ETA to be merged? :D

**Review by jaysoo — APPROVED** [review]

**Pull request merged**
