### PR TITLE
chore(repo): remove husky call to missing file

### PR DESCRIPTION
**Pull request by meeroslav**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by Phillip9587** [comment]
@meeroslav This file should not be missing. It gets installed by husky itself when husky gets installed by the npm `prepare` script (`is-ci || husky install`).

**Comment by Phillip9587** [comment]
@meeroslav I think this was a mistake ...

**Comment by Phillip9587** [comment]
@meeroslav Can you please explain the change? Just curious

**Comment by meeroslav** [comment]
@Phillip9587 true, the `husky.sh` file gets installed, but we do not need to run it in Nx. 

The PR name was a bit unfortunate. There were some unnecessary file changes around those hooks, so I realized we still have it there by default.

**Pull request merged**
