### PR TITLE
chore(core): nx plugin submission @nightwatch/nx

### PR DESCRIPTION
**Pull request by AutomatedTester**
# Community Plugin Submission

## @nightwatch/nx

NightwatchJS is a framework for doing E2E and Component testing on all major browsers and on mobile (emulator or real devices). 

This plugin is supported by the @NightwatchJS project to help make sure that web applications and mobile applications are shipped with confidence.

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
This is exciting!

However, I ran into some issues setting it up on nx-examples:

I ran

```
yarn add @nightwatch/nx --save-dev
nx g @nightwatch/nx:nightwatch-project
```

This was my terminal output:
image

**Comment by AutomatedTester** [comment]
@FrozenPandaz I've gone through and double checked things. It should work now with version 0.2.3.

**Comment by AgentEnder** [comment]
Hey @AutomatedTester! @FrozenPandaz is out on vacation for the holidays, but this should get looked at pretty quickly after he returns. Can you rebase and fix conflicts?

**Review by FrozenPandaz — APPROVED** [review]
Awesome, thank you for making the fixes.

**Pull request merged**
