### PR TITLE
chore(core): nx plugin submission @nx-clean/plugin-core

### PR DESCRIPTION
**Pull request by guiseek**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by guiseek** [comment]
should i write something explaining about the plugin?
I just followed the steps, using the command to submit...

[This is the project repository](https://github.com/guiseek/nx-clean)

This plugin is just for TypeScript scaffolding, I'm currently working on Angular generators
Let me know if you need anything else

**Comment by guiseek** [comment]
Hey man @FrozenPandaz , something wrong with the `pull request`? maybe the name? it's not my intention to sound like an official nx plugin, but the way Uncle Bob describes classes that shouldn't depend on third parties. Which is the purpose here, to remain decoupled, that is, framework agnostic. But I can change it too, no problem.

**Comment by vsavkin** [comment]
Really sorry for the late reply. Let me merge it. Thank you!

**Comment by vsavkin** [comment]
Merged here: https://github.com/nrwl/nx/commit/4f63089958b6cca387e67aa183578008e74a9f8a

**Comment by guiseek** [comment]
thank you so much for that @vsavkin , it is evolving and that motivates me even more to keep the project!

**Pull request closed without merging**
