### PR TITLE
fix(js): aliased packages are pruned from package-lock.json

### LINKED ISSUE #17653: generatePackageJson creates incompatible package.json and package-lock.json in certain scenarios.
### Current Behavior

When using `generatePackageJson: true` in the webpack plugin, nested dependencies can be missing from generated package-lock.json, causing `npm ci` to fail. 

Consider the following package-lock.json

```json
    "node_modules/auth0": {
      "version": "3.4.0",
      "resolved": "https://registry.npmjs.org/auth0/-/auth0-3.4.0.tgz",
      "integrity": "sha512-qaRVZfykFhROZlKa6i/G7Tlo4Df6GXdtMdvO41XuJ2XlJ/AMUAxL0u/FJJyII/HWwosVtypD92nHB2gqRwIbYg==",
      "dependencies": {
        "axios": "^0.27.2",
        "form-data": "^3.0.1", // <==== requires an older version of form-data
        "jsonwebtoken": "^9.0.0",
        "jwks-rsa": "^3.0.1",
        "lru-memoizer": "^2.1.4",
        "rest-facade": "^1.16.3",
        "retry": "^0.13.1",
        "uuid": "^9.0.0"
      },
      "engines": {
        "node": ">=14"
      }
    },
    "node_modules/auth0/node_modules/axios": {
      "version": "0.27.2",
      "resolved": "https://registry.npmjs.org/axios/-/axios-0.27.2.tgz",
      "integrity": "sha512-t+yRIyySRTp/wua5xEr+z1q60QmLq8ABsS5O9Me1AsE5dfKqgnCFzwiCZZ/cGNd1lq4/7akDWMxdhVlucjmnOQ==",
      "dependencies": {
        "follow-redirects": "^1.14.9",
        "form-data": "^4.0.0" <=== but this one requires a newer one
      }
    },
    
    //---------------- the below entry is missing (pruned) when using generatePackageJson, but will be added if you run `npm install` manually in the build folder
    
    "node_modules/auth0/node_modules/axios/node_modules/form-data": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz",
      "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",
      "dependencies": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      },
      "engines": {
        "node": ">= 6"
      }
    },
    // ---------------------------------------------------------------------------------------------------
    
    "node_modules/auth0/node_modules/form-data": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/form-data/-/form-data-3.0.1.tgz",
      "integrity": "sha512-RHkBKtLWUVwd7SqRIvCZMEvAMoGUp0XU+seQiZejj0COz3RI3hWP4sCv3gZWWLjJTd7rGwcsF5eKZGii0r/hbg==",
      "dependencies": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      },
      "engines": {
        "node": ">= 6"
      }
    },
    // ------------------------------------- Note that form-data@4.0.0 is here, but it should also be in 
    // "node_modules/auth0/node_modules/axios/node_modules/form-data" as well
     "node_modules/form-data": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz",
      "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",
      "dependencies": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      },
      "engines": {
        "node": ">= 6"
      }
    },
     "node_modules/openai": {
      "version": "3.2.1",
      "resolved": "https://registry.npmjs.org/openai/-/openai-3.2.1.tgz",
      "integrity": "sha512-762C9BNlJPbjjlWZi4WYK9iM2tAVAv0uUp1UmI34vb0CN5T2mjB/qM6RYBmNKMh/dN9fC+bxqPwWJZUTWW052A==",
      "dependencies": {
        "axios": "^0.26.0",
        "form-data": "^4.0.0" // <======== is responsible for the node_modules/form-data@4.0.0 install...
      }
    },
```

The missing package results in the following error when running `npm ci` (i.e. in a Dockerfile)

```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: form-data@4.0.0 from lock file
npm ERR! 
npm ERR! Clean install a project
```

### Expected Behavior

Generated package-lock.json is valid and `npm ci` succeeds.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create an nx project with an app/lib that has a imports dependencies that create two copies of the same version of the same package.  For example, `auth0` and `openai`, which both ultimately import `form-data@4.0.0` but will do so in different folders in node_modules, due to auth0 having a direct dependency on an earlier version of form-data.

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux arm64
   npm    : 9.5.0
   Hasher : Native
   
   nx (global)        : 16.2.2
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nx/plugin         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
```

### Failure Logs

```shell
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: form-data@4.0.0 from lock file
npm ERR! 
npm ERR! Clean install a project
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The root package-lock.json for the project is not missing the dependency.

Also, 

Because these have the same version, perhaps one is pruned by this code:

https://github.com/nrwl/nx/blob/0848031dd9c19672ab795e0494e54bbef61240c5/packages/nx/src/plugins/js/lock-file/project-graph-pruning.ts#L52-L57

### PR DESCRIPTION
**Pull request by kdawgwilk**
## Current Behavior

When enabling the `generatePackageJson` flag for js build targets the pruned `package-lock.json` file is invalid.  When `npm ci` is ran you get the following errors
```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: string-width-cjs@4.2.3 from lock file
npm ERR! Missing: strip-ansi-cjs@6.0.1 from lock file
npm ERR! Missing: wrap-ansi-cjs@7.0.0 from lock file
npm ERR! Missing: semver@6.3.1 from lock file
```

## Expected Behavior

The pruned `package-lock.json` generated is valid and can be installed via `npm ci`

## Related Issue(s)

Fixes #17653

### CODE REVIEW

**Comment by kdawgwilk** [comment]
Just have a failing test at this point but will be looking into fixing the failure

**Comment by meeroslav** [comment]
This PR doesn't seem to include any code changes, just additional test and fixture. Is that intended or this got lost during the rebase?

**Comment by kdawgwilk** [comment]
@meeroslav I was intending to come back and write the code to get the failing test passing but I am not longer working for the company that was running into this issue so I will likely not be coming back to this PR.  However I do think this is an issue that still needs to be addressed

**Comment by kdawgwilk** [comment]
@meeroslav did https://github.com/nrwl/nx/pull/23474 fix this as well?

**Comment by meeroslav** [comment]
Yes, the https://github.com/nrwl/nx/pull/23474 was fixing this exact problem

**Pull request closed without merging**
