### PR TITLE
chore(core): nx plugin submission [@nxazure/func]

### PR DESCRIPTION
**Pull request by AlexPshul**
# Community Plugin Submission

## @nxazure/func
This plugin adds support of Azure Functions to NX workspaces.
It allows to init function apps (Just like using the official func CLI) and also add to the apps new functions based on official templates.
The plugin executors allow to build, start and even publish (to azure) the functions.
Also, the plugin supports ts-paths, which is not officially supported by the official func tools, but is very much needed in an NX workspace.

### CODE REVIEW

**Comment by AgentEnder** [comment]
Hey @AlexPshul ! This is really cool, on top of being an Nx contributor, I'm also the author of nx-dotnet and AZ functions are something we've talked about supporting.

I've got some feedback on various aspects of your plugin, but for the most part it looks great 👍.

- @nxazure/func:build
  - this doesn't seem to do anything?
- @nxazure/func:publish
  - you can use removeSync from node fs with recursive set to true, that should be a lot nicer than the child process stuff you've currently got going on.
- @nxazure/func:init
  - this seems to be a little different than the typical "init" generator that an Nx plugin contains. There's not a requirement here necessarily, but conventionally a plugins init generator is idempotent and without arguments. It initializes any setup for the plugin. I may consider renaming the generator to "project" or similar.

Like I said though, this looks great 👍. I'll approve it, these are just considerations. If you ever want to add .NET support, I'd love to collaborate on it.

**Review by AgentEnder — APPROVED** [review]

**Comment by AlexPshul** [comment]
> Hey @AlexPshul ! This is really cool, on top of being an Nx contributor, I'm also the author of nx-dotnet and AZ functions are something we've talked about supporting.
> 
> I've got some feedback on various aspects of your plugin, but for the most part it looks great 👍.
> 
> * @nxazure/func:build
>   
>   * this doesn't seem to do anything?
> * @nxazure/func:publish
>   
>   * you can use removeSync from node fs with recursive set to true, that should be a lot nicer than the child process stuff you've currently got going on.
> * @nxazure/func:init
>   
>   * this seems to be a little different than the typical "init" generator that an Nx plugin contains. There's not a requirement here necessarily, but conventionally a plugins init generator is idempotent and without arguments. It initializes any setup for the plugin. I may consider renaming the generator to "project" or similar.
> 
> Like I said though, this looks great 👍. I'll approve it, these are just considerations. If you ever want to add .NET support, I'd love to collaborate on it.

Thanks @AgentEnder for the very quick response and the nice feedback! I really appreciate it. :) 
To reply to your points:
* @nxazure/func:build
This executor calls a helper function "Build" that I declared in a different file. I thought about using the existing executor or just calling a command, but this was the best option I've found to have a colorful output. 😜 If you know about another solution for that, please let me know.

* @nxazure/func:publish
Huh! Of course!! I just got carried away by some things and totally missed that. Thanks for the tip! :) 

* @nxazure/func:init
You are absolutely right and I was self debating this for quite a while. The reason I've went with the `init` generator after all is because I wanted to keep the same naming convention as the `func` CLI tool to make it more familiar to the Azure Functions community. If it will prove to be a problem, I'll gladly change it in a future release.


Again, thank you so much for the very fast and helpful review, I really appreciate it!

**Comment by AndrewRedican** [comment]
@AlexPshul Nice one! Are these dotnet or TypeScript Azure functions by any chance?

**Comment by AlexPshul** [comment]
> @AlexPshul Nice one! Are these dotnet or TypeScript Azure functions by any chance?

Those are TypeScript functions only, for now.
In the future, I might add support for other languages as well.

**Comment by AndrewRedican** [comment]
Nope. I was actually hoping for it to be TypeScript. I am delighted, the timing is just perfect. I am introducing Nx to the company and had a use case for TypeScript Azure Functions.

**Pull request merged**
