### PR TITLE
feat(storybook): support application type project

### LINKED ISSUE #2382: Storybook Install: "Could not read apps/ng-nest/tsconfig.lib.json"
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation (nx.dev) and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
The expected behavior is to be able to install Storybook integration given the documentation instructions.

## Current Behavior
The current behavior when following the instructions for installing Storybook integration ends with an error "Could not read apps/ng-nest/tsconfig.lib.json" (which makes no sense, because the only `tsconfig.lib.json` in the project is in the `libs/api-interfaces/tsconfig.lib.json`, and I do not believe there would ever be a `apps/ng-nest/tsconfig.lib.json` file).

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npx create-nx-workspace@latest nx-test-workspace`
Workspace: angular-nest
Application Name: ng-nest
Default style: SCSS (.scss)
2. `cd nx-test-workspace`
3. `npx -p @storybook/cli sb init`
4. `nx g @nrwl/angular:storybook-configuration ng-nest` which fails with an error "Could not find module "@nrwl/storybook" from "/Users/leifwells/Code/nx-test-workspace".
5. `npm i -D @nrwl/storybook` to avoid the error
6. `nx g @nrwl/angular:storybook-configuration ng-nest` which ends with the error "Could not read apps/ng-nest/tsconfig.lib.json"

### Context

Please provide any relevant information about your setup:
```
  @nrwl/angular : 8.11.2
  @nrwl/cli : 8.11.2
  @nrwl/cypress : 8.11.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.2
  @nrwl/linter : 8.11.2
  @nrwl/nest : 8.11.2
  @nrwl/next : Not Found
  @nrwl/node : 8.11.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.2
  @nrwl/web : Not Found
  @nrwl/workspace : 8.11.2
  typescript : 3.5.3
```

### LINKED ISSUE #3311: Enable project/app as parameter for storybook
## Description
Currently it is not possible to create different storybooks for different projects/apps within `nrwl`.

`nrwl/storybook` only enables us to use different libs from one app.

In our case we need to create storybooks with different themes and features for differet apps/projects, while the libs are shared. Right now storybook only supports a `default-project` value in `angular.json`. This problem is rooted in `@storybooks/angular`

## Motivation
I want to be able to run `nx run <project>:storybook`  in order to be able to run storybook with an angular project named `<project>`

## Suggested Implementation
One step would be to update storybooks implementation, as described here:
https://github.com/storybookjs/storybook/issues/11499

### PR DESCRIPTION
**Pull request by musou1500**
current, and expected behavior is described in https://github.com/nrwl/nx/issues/2382 

Fixes #2382

### CODE REVIEW

**Comment by skrzepij** [comment]
can anyone check this, please?

**Comment by mandarini** [comment]
Hello @musou1500 ! Thank you for this PR!

I tested your fix locally, and unfortunately it does not solve the issue. Although the `nx g @nrwl/react:storybook-configuration --name=YOUR-APP-NAME` command does NOT fail, as it is no longer looking for `tsconfig.lib.json` and it accepts `tsconfig.app.json`, it does NOT successfully produce `.stories.tsx` files. It only produces two `.storybook` directories, one in the root folder, and the other inside the app (as expected).

Let me tell you the steps I followed and you can tell me if this is what you followed and you got it working on your side.

1. `npx create-nx-workspace@YOUR_VERSION_OF_NX workspace-name` and _I chose `react`_
2. `yarn add YOUR_NX_DIRECTORY/build/packages/storybook`
3. `nx g @nrwl/react:component test-component --project=story-test-app`
4. Now I have no libs, just an app and a component called `test-component` in my app (`workspace-name/apps/story-test/src/app/test-component`)
5. I am now ready to run the `storybook-configuration` command on my app (`story-test`), and I would expect this command to produce two `.storybook` directories, one in the root of the project and one in the `story-test` app directory (`workspace-name/apps/story-test/.storybook`), and two `.stories.tsx` files next to the components of my application (one `app.stories.tsx` and one `test-component.stories.tsx`).
6. I run `nx g @nrwl/react:storybook-configuration --name=story-test`
7. I get a couple of minor issues with the options and the messages that appear to the user (eg. `Automatically generate story files for components declared in this library?` should become in this context `Automatically generate story files for components declared in this application?`, but then, only the two `.storybook` directories are generated and the config files updated (please see screenshot attached). I do not see any `.stories.tsx` files next to my components, as I would expect.

So, my question is, did this happen on your side as well? Did you follow a different scenario? Unfortunately, until the expected behaviour is achieved, and all the tests pass, we will not be able to merge this PR.

Please let me know if you need any guidance, or if you have some suggestions as to how we could make this work! Again, thank you very very much for contributing!

Screenshot 2020-07-23 at 5 17 56 PM

**Comment by musou1500** [comment]
@mandarini 
thank you for your review!

> Let me tell you the steps I followed and you can tell me if this is what you followed and you got it working on your side.

I could reproduce it. I had forgot to test option to generating stories.
it seems to assumed to use for library project.

I'll try to fix it.

**Comment by juristr** [comment]
@musou1500 let us know if you need any help getting this fixed

**Comment by webberwang** [comment]
using `tsconfig.app.json` has conflict with nrwl next, as that uses `tsconfig.json`

**Comment by webberwang** [comment]
@juristr This PR got stale, so I fixed the issue here https://github.com/nrwl/nx/pull/3611. Let me know your thoughts after taking a look, thanks.

**Comment by mandarini** [comment]
I think this PR should close, since it's the old version of https://github.com/nrwl/nx/pull/3611

**Review by mandarini — COMMENTED** [review]
There's another PR on the same subject

**Pull request closed without merging**
