### PR TITLE
fix(testing): update ts-jest to version 26.5.5

### PR DESCRIPTION
**Pull request by minijus**
## Current Behavior
`ts-jest` version 26.4.0

## Expected Behavior
`ts-jest` version 26.5.5 with no deprecation warnings for `tsConfig` property in `jest.config.js`.

### CODE REVIEW

**Comment by vsavkin** [comment]
@Cammisuli can you take a look? We might also need to add a migration to this.

**Comment by minijus** [comment]
> @Cammisuli can you take a look? We might also need to add a migration to this.

Added migration for this.

**Comment by minijus** [comment]
> hey @minijus thank you for the PR! I'm going to do some tests locally tomorrow. If everything is good, we'll merge this in. Thanks again!

Thanks!

While you at it, maybe you could have a look at #5377 as well? It is very similar PR.

**Review by Cammisuli — APPROVED** [review]
Thanks again @minijus! Things look good:
* tested migration
* tested new workspaces

No deprecation warnings or errors :D 

Can you just fix the merge conflict, and we can merge it in 🙂

**Review by Cammisuli — APPROVED** [review]

**Pull request merged**
