### PR TITLE
docs(storybook): update project param for react:stories

### PR DESCRIPTION
**Pull request by rek**
## Current Behavior

Documentation regarding generating stories for libs is not clear

## Expected Behavior

This attempts to clear up some minor doc issues for new contributors and for using `@nrwl/react:stories`

## Related Issue(s)

This covers the first part of: https://github.com/nrwl/nx/issues/12742 which is a documentation change.

### CODE REVIEW

**Comment by johannesschobel** [comment]
`nrwl v16` is not out yet ;)

**Comment by rek** [comment]
> `nrwl v16` is not out yet ;)

15 wasn't out when this was written either :) I updated it here to 16 to reflect a good option to use as the 'next' major, re:

> you can choose any nonexistent version number here, but it's recommended to use the next major

**Comment by johannesschobel** [comment]
> you can choose any nonexistent version number here, but it's recommended to use the next major

oh, very good.. did not know that this is an offical recommendation for the docs here ;) good to know 👍

**Comment by mandarini** [comment]
Hi @rek thanks for the contribution! The `--name` is not needed, `yargs` automatically resolves the first variable as the `name`, but I will accept this change, if you believe it clears up any misubnderstanding!! :)

**Comment by rek** [comment]
> Hi @rek thanks for the contribution! The `--name` is not needed, `yargs` automatically resolves the first variable as the `name`, but I will accept this change, if you believe it clears up any misubnderstanding!! :)

There might be some other issue somewhere then, because I think when omitting `--name`, this was not working for my lib.

**Comment by martdavidson** [comment]
> > Hi @rek thanks for the contribution! The `--name` is not needed, `yargs` automatically resolves the first variable as the `name`, but I will accept this change, if you believe it clears up any misubnderstanding!! :)
> 
> There might be some other issue somewhere then, because I think when omitting `--name`, this was not working for my lib.

Yes, stories weren't generating for me either without the --name arg being present.

**Pull request merged**
