### PR TITLE
chore(repo): update repo to Prettier V2

### PR DESCRIPTION
**Pull request by rarmatei**
This PR just updates our own repo's prettier version to V2
Updating the workspace Prettier version has been done [here](https://github.com/nrwl/nx/pull/2885)

To cut out the noise caused by all the small changes in formatting, here's the commit that increments the actual versions: https://github.com/nrwl/nx/commit/6969b192f1fe3938a3ae6460d032ae32cfc26c1e

### CODE REVIEW

**Comment by rarmatei** [comment]
@FrozenPandaz - do the CI failures make sense to you? The generated workspace for e2e tests should still be using the old version of Prettier, and therefore should not fail?

**Comment by FrozenPandaz** [comment]
> The generated workspace for e2e tests should still be using the old version of Prettier, and therefore should not fail?

The unit tests use the version of prettier in the repo though so that did change.

**Comment by rarmatei** [comment]
> > The generated workspace for e2e tests should still be using the old version of Prettier, and therefore should not fail?
> 
> The unit tests use the version of prettier in the repo though so that did change.

Ah yes, just the unit tests are failing 🤦 that makes sense!

**Comment by rarmatei** [comment]
@FrozenPandaz this will cause merge conflicts in a lot of other PRs - it will be simple for me to rebase this and do a reformat locally once others' code is merged in
so if there are any other big PRs open, I suggest we merge them in first

I can add some of these options to `.preitterrc` to reduce the number of conflicts from 538 to ~120, but they're not really [recommended](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-trailingcomma-to-es5-6963httpsgithubcomprettierprettierpull6963-by-fiskerhttpsgithubcomfisker):

```js
{ "trailingComma": "none" },
{ "arrowParens": "avoid" }
```

The remaining 123 re-formats are from from [this new rule](https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot)

**Pull request closed without merging**
