### PR TITLE
fix(web): upgrade dependency webpack-subresource-integrity to 1.5.1

### PR DESCRIPTION
**Pull request by InsaLili**
Upgrade dependency `webpack-subresource-integrity`
 from `1.1.0-rc.6` to `1.5.1` as there is a security issue under version `1.5.1`

Ref: https://www.npmjs.com/package/webpack-subresource-integrity/v/1.4.1

### CODE REVIEW

**Comment by InsaLili** [comment]
Fixes #3958

**Comment by vsavkin** [comment]
Thank you for your PR!

Could you also update packages/web/package.json?

**Comment by vsavkin** [comment]
And could you change the commit message to fix(web):...

**Comment by InsaLili** [comment]
> Thank you for your PR!
> 
> Could you also update packages/web/package.json?

Done!

**Comment by vsavkin** [comment]
Thank you! Could you squash the commits and I'll merge it?

**Comment by InsaLili** [comment]
@vsavkin Sorry I made a mess on rebasing... :( I opened a new PR #4004

**Pull request closed without merging**
