### PR TITLE
feat(core): updated dotenv and switched to import 'dotenv/config'

### PR DESCRIPTION
**Pull request by Phillip9587**
## Current Behavior
- `dotenv` 8.2.0

## Expected Behavior
- updated `dotenv` to 10.0.0
- added the migration to `@nrwl/workspace`
- switched from `require('dotenv').config()` to `import 'dotenv/config'`

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you! Could you resolve the conflict?

**Comment by Phillip9587** [comment]
@vsavkin The merge conflicts are resolved but there is the new version 14.17.0 of `@types/node`. Should i update the migration to install the latest types?

**Comment by puku0x** [comment]
There is a new PR for dotenv v10👀 #5754

**Comment by Phillip9587** [comment]
Updated this PR to `dotenv `10.0.0

**Comment by gperdomor** [comment]
Sorry I don't see this PR before, I will close the other :D

**Review by FrozenPandaz — APPROVED** [review]
Thank you!

**Pull request merged**
