### PR TITLE
docs(misc): Updated AST playground to TSQuery

### PR DESCRIPTION
**Pull request by AndrewOttavianoAbb**
## Current Behavior

The docs were linking to the AST Explorer, which is not the npm package referenced in the generator documentation (as AST Explorer does not support parsing TypeScript).
## Expected Behavior

The docs link to the demo site for the TSQuery Playground: https://tsquery-playground.firebaseapp.com/
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by AndrewOttavianoAbb** [comment]
So this is my first time contributing here (and really to any OSS :) so I'm not sure what the procedure is for merging this thing. It seems that the checks passed, but who do I get approval from? Does someone have to merge it for me? Thanks!
@FrozenPandaz

**Comment by isaacplmann** [comment]
ast-explorer does support parsing typescript if you set the parser to typescript, but that's probably confusing for some people.  I'll approve this PR if you also delete the sentence `Make sure the parser is set to typescript`

**Comment by isaacplmann** [comment]
Something went wrong with your last commit.  I don't think you meant to make all those changes.

**Comment by AndrewOttavianoAbb** [comment]
😬 Yeah, I'm working on that. Will ping this thread when it's ready.

**Comment by AndrewOttavianoAbb** [comment]
@isaacplmann should be good to go.

**Review by isaacplmann — COMMENTED** [review]
Approved

**Pull request merged**
