### PR TITLE
feat(core): generate static website with dep-graph --file=foldername.html

### LINKED ISSUE #3048: [Feature Request] generate static website with dep-graph output
## Expected Behavior

I'd like to be able to deploy the dep-graph website (the one we get when we run `nx dep-graph` and related commands) to wherever.

I'd also expect dep-graph with `--file` to fail if an unsupported extension is provided. Asking for a png (like in #2056) but getting a png file with json inside is very strange DX.

## Current Behavior

I can only either run it in the browser locally or output the json which I'm honestly not sure what to do with. I can also give the `--file` arg any file extension but always get the same json.

## Context

My main use case us that as part of running tests and deploying my apps for each PR on CI, I'd like to be able to deploy this site displaying the dependency graph of affected packages in that PR. Our QA team could then just click a link and see what packages need to be tested.

The implementation I'm suggesting is adding ~~a `--build` flag~~ support for `--file=foldername.html` to the `dep-graph` commands that would do the same things that it would do when starting the server, except instead it would output the files into ~~`dist/dep-graph`~~`foldername` where the end-user could do as they wish.

I've created a PR #3049 with an implementation for these changes, still missing some tests since I'm not sure how to approach that but I'm willing to make the effort if this implementation will be considered acceptable.

## Other

Related to #2005 although I believe my proposed solution is different from what they were asking for, considering the previous implementation behaved significantly differently. I'm fine with merging these issues if you disagree.

Worth mentioning #2056, although they're not really asking for the same thing.

### PR DESCRIPTION
**Pull request by benediktvaldez**
## Current Behavior

I can only either run it in the browser locally or output the json which I'm honestly not sure what to do with. I can also give the `--file` arg any file extension but always get the same json.

## Expected Behavior

I'd like to be able to deploy the dep-graph website (the one we get when we run `nx dep-graph` and related commands) to wherever.

I'd also expect dep-graph with `--file` to fail if an unsupported extension is provided. Asking for a png (like in #2056) but getting a png file with json inside is very strange DX.

### Support for html output

With these changes we'll be able to run something like

```bash
nx affected:dep-graph --base=master --head=HEAD --file=output.html
```

This will now generate a static website with the dep graph data, highlighting the projects affected by the changes between master and HEAD (e.g., PR). It will create a folder with the filename provided, in this example the folder would be called `output`.

This also applies to all other `dep-graph` commands. The website generated matches the one that usually runs locally using the `dep-graph` commands.

See #3048 for more context.

**NOTE: I have not written tests for this new behaviour, I'm not entirely sure how to approach that but I'm willing to make the effort if this implementation will be considered acceptable.**

### Display error if not `json` or `html`

Additionally the `dep-graph --file=*` command now errors out if an unsupported extension is provided.

## Issues
Closes #3048, #2005

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
Thank you for the PR!

I think a better API to achieve this would be to be able to pass `--file dep-graph.html` which would generate the html.

What do you think?

**Comment by philipjfulcher** [comment]
I talked with @FrozenPandaz earlier and agree. We should look at the file passed in as an argument and determine the output based on the file extension.

**Comment by benediktvaldez** [comment]
Originally I wanted to go that route, but that would have meant figuring out what to do with all the other files (styles and scripts) since I'd expect to get a single html file from running that command. Right now that includes all of the files within [packages/workspace/src/core/dep-graph](https://github.com/nrwl/nx/tree/master/packages/workspace/src/core/dep-graph), from what I can tell all of them are actively used by the html file. Would we host those independently somehow or embed them in the html file? Alternatively we could output a folder but is that not a bit weird when you specify `--file dep-graph.html`?

**Comment by benediktvaldez** [comment]
I've been thinking about it for a little longer and I do have a suggestion. What if we would use the filename as the folder name, minus the extension?

For example, `--file some-name.html` would output a folder called `some-name` containing all those files with an index.html. It's not what I would intuitively expect from running that command but if it's explained in the documentation and cli help output it should be fine.

Does that make sense to you?

**Comment by benediktvaldez** [comment]
I've updated my PR to match this suggestion since it was a relatively small change from the previous implementation. I also added a `output.success(...)` message to specify where the file/folder are located exactly for better UX.

Would this approach be better in your opinion?

I decided to only check if `html` was specified, otherwise always output JSON into whatever filename was provided (maintaining the existing functionality as is). **I do feel like it would be more intuitive if the script would simply fail if some other extension is provided** since there is only support for `json` and `html`, but wasn't sure if that's what you'd want. Thoughts on that?

**Comment by FrozenPandaz** [comment]
This is looking great! Thank you so much for your contribution!

> I also added a output.success(...) message to specify where the file/folder are located exactly for better DX.

Awesome! :+1:

> I do feel like it would be more intuitive if the script would simply fail if some other extension is provided

I agree. Thank you! :+1: 

> It's not what I would intuitively expect from running that command

I wouldn't expect that either... I think the user would be confused because the path that they requested the file to be outputted doesn't actually get produced. I would rather the static assets go into a `static` directory next to the html.

Examples:

Input: `dist/dep-graph.html`
Output: `dist/static/styles.css`, `dist/static/scripts.js`, `dist/dep-graph.html`, etc.

Input: `dep-graph.html`
Output: `static/styles.css`, `static/scripts.js`, `dep-graph.html`, etc.

I would also print where the static assets are outputted.

**Comment by benediktvaldez** [comment]
_Side note:_ there is a file in `core/dep-graph` called `dep-graph.svg` that doesn't seem to be used by the website or scripts and doesn't seem to be a valid svg file, but it has _a_ graph (which partially renders when I open the file in Sketch). Just wondering if was left there by accident or?

> > It's not what I would intuitively expect from running that command
> 
> I wouldn't expect that either... I think the user would be confused because the path that they requested the file to be outputted doesn't actually get produced. I would rather the static assets go into a `static` directory next to the html.
> 
> Examples:
> 
> Input: `dist/dep-graph.html`
> Output: `dist/static/styles.css`, `dist/static/scripts.js`, `dist/dep-graph.html`, etc.
> 
> Input: `dep-graph.html`
> Output: `static/styles.css`, `static/scripts.js`, `dep-graph.html`, etc.
> 
> I would also print where the static assets are outputted.

That would definitely feel more intuitive. I'm wondering if `assets` would be a better name, although it's a minor thing we can adjust, so I went with `static` for now.

Either way, I've amended my changes, the behaviour is now as follows.

```shell
$ nx dep-graph --file dep-graph.json

>  NX   SUCCESS  JSON output created in /path/to/approot

  /path/to/approot/dep-graph.json
```

```shell
$ nx dep-graph --file dep-graph.html

>  NX   SUCCESS  HTML output created in /path/to/approot

  /path/to/approot/dep-graph.html
  /path/to/approot/static/crosshair.svg
  /path/to/approot/static/dep-graph.css
  /path/to/approot/static/dep-graph.js
  /path/to/approot/static/dep-graph.svg
  /path/to/approot/static/vendor.js
```

```shell
$ nx dep-graph --file dist/dep-graph/index.html

>  NX   SUCCESS  HTML output created in /path/to/approot/dist/dep-graph

  /path/to/approot/dist/dep-graph/index.html
  /path/to/approot/dist/dep-graph/static/crosshair.svg
  /path/to/approot/dist/dep-graph/static/dep-graph.css
  /path/to/approot/dist/dep-graph/static/dep-graph.js
  /path/to/approot/dist/dep-graph/static/dep-graph.svg
  /path/to/approot/dist/dep-graph/static/vendor.js
```

And the failing message for non-supported extensions

```shell
$ nx dep-graph --file unsupported.png

>  NX   ERROR  Please specify a filename with either .json or .html extension.

  You provided --file=unsupported.png

error Command failed with exit code 1.
```

**Comment by beeman** [comment]
@benediktvaldez this is great stuff! Just last week I was looking if there was a way to do this!

**Review by FrozenPandaz — APPROVED** [review]
This looks great! I'm going to say the `dep-graph.svg` is unrelated to this change and we can address it separately.

Thank you so much for your contribution!

**Pull request merged**
