### PR TITLE
fix(core): rename implicitDependencies during move

### LINKED ISSUE #2906: bug: @nrlw/workspace:move - implicit dependencies tokens are not renamed
## Expected Behavior

update `implicitDependencies` token references, when executing `move` schematic

## Current Behavior

when running `move` schematic, nx.json `implicitDependencies` are not updated (if moved lib is referenced there)

**nx.json**

```jsonc
{
"projects": {
    "one": {
      "tags": [],
      // 🚨THIS WONT BE RENAMED
      "implicitDependencies": ["two"]
    },
    "two": {
      "tags": []
    }
  }
}
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest repro-workspace
2. nx g @nrwl/workspace:lib one
3. nx g @nrwl/workspace:lib two
4. update nx.json -> 
```
    "one": {
      "tags": [],
       "implicitDependencies": ["two"]
    },
```
5.  nx g @nrwl/workspace:move --projectName=two --destination=nested/two
6. check nx.json
```
    "one": {
      "tags": [],
      // 🚨THIS SHOULD BE nested-two
       "implicitDependencies": ["two"]
    },
```

### Context

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : 9.2.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.2
  @nrwl/react : 9.2.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : 9.2.2
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

### PR DESCRIPTION
**Pull request by antipalindrome**
ISSUES CLOSED: #2906 

## Current Behavior (This is the behavior we have today, before the PR is merged)

Currently any implicitDependencies do not get renamed when using the move schematic. This is a manual process at the moment.

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

implicitDependencies containing the name of the project we are renaming are updated accordingly.

## Issue

#2906 

### Note

This is my first contribution so let me know if I can do anything better! Thanks!

### CODE REVIEW

**Comment by hsw107** [comment]
Is someone able to rerun the two failing circleci tests? They seem unrelated to my chanegs.

**Comment by jdpearce** [comment]
@hsw107 This looks good thanks! Can you add an e2e test for this? I can help with that if necessary.

**Comment by hsw107** [comment]
@jdpearce I could use some help with that! I wasn't able to get tests running/debugging and so I didn't feel comfortable trying to add a test. Additionally I wasn't sure how I would add implicitDependencies into the test itself.

**Comment by jdpearce** [comment]
@hsw107 You want to look here for the appropriate e2e tests:

https://github.com/nrwl/nx/blob/3ecf6ea5a9a6469919e312657ceeee6f58a6daba/e2e/workspace-aux-commands.test.ts#L502

Rather than adding a new test, just modify the `nx.json` to add an implicit dependency and then check that it gets renamed in the same test. You may not have to create the project that the dependency is for, but if you do, just run the schematic as in line 512.

It occurs to me that we might not be doing this for the `remove` schematic either! If you could check and then do almost the same thing to that schematic as well (the tests are in the same place) that would be super amazing.

If you're having problems running the tests at all, let me know what problems you're coming up against and we can try to figure out what's up.

**Comment by hsw107** [comment]
@jdpearce I've tried following the video on running tests and running the command like so:
`node --inspect-brk ./node_modules/jest/bin/jest.js e2e/workspace-aux-commands.test.ts`

But it just says:
```
Debugger listening on ws://127.0.0.1:9229/307f8aac-2b3b-48bb-abc8-2a236f268ee2
For help, see: https://nodejs.org/en/docs/inspector
```
And doesn't debug within VSC.

**Comment by hsw107** [comment]
@jdpearce I've gone ahead and added the logic to remove the matching implicitDependencies from other projects on remove. 

And thanks for being so patient with me on all this testing stuff :)

**Comment by jdpearce** [comment]
@hsw107 - Which video were you watching?

Running the e2e tests should be in the CONTRIBUTING.md doc (I think it's `yarn nx e2e <file-name>`) are you finding a particular need to debug them?

It would probably be a good idea to add the unit test in `update-nx-json.spec.ts` as well, yes.

Thanks for looking into the `remove` schematic as well, that's really helpful.

**Comment by vsavkin** [comment]
@hsw107 @jdpearce folks, just checking if you need any help wrapping up this PR.

**Comment by hsw107** [comment]
@vsavkin Hey sorry! I haven't had the time to come back around on this yet due to other commitments. Hoping I will soon, otherwise of course I'm more than happy to have some help!

**Comment by jdpearce** [comment]
@hsw107 @vsavkin  - I've pushed some e2e and unit tests for these changes (also rebased onto latest upstream/master). 

I haven't been able to get the e2e tests to run locally though, so there's definitely something there that needs addressing. Fingers crossed I got them right first time 😆 (obvs I'll update if need be)

**Comment by hsw107** [comment]
@jdpearce Thanks so much for that! Sorry I didn't have the time to pull this over the finish line, I appreciate your help!

**Comment by jdpearce** [comment]
@hsw107 np. Thanks for making the PR. Hopefully we can get this merged today.

**Review by catfireparty — APPROVED** [review]

**Pull request merged**
