### PR TITLE
fix(storybook): properly resolve TS paths in storybook webpack config

### LINKED ISSUE #2320: React storybook: issue importing from other libraries
## Expected Behavior

When used with storybook it should be possible to import from other internal libraries.

## Current Behavior

Storybook doesn't allow importing from another internal library or allow code that imports from another library. 

## Failure Information (for bugs)

Library A has storybook configured. This will work fine if the library has no dependencies on another internal library, however it will fail if another internal library is referenced either in the story or code that the story references. 

### Steps to Reproduce

1. Create a react library
2. Add storybook configuration to it
3. Add a dependency on another internal lib

### Context

Please provide any relevant information about your setup:

```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.11.1
  @nrwl/cypress : 8.11.1
  @nrwl/eslint-plugin-nx : 8.11.1
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.1
  @nrwl/linter : 8.11.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 8.11.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.1
  @nrwl/web : 8.11.1
  @nrwl/workspace : 8.11.1
  typescript : 3.5.3
```

### Failure Logs
Output from storybook:
```

ERROR in ./libs/core/src/lib/core.tsx
Module not found: Error: Can't resolve '@storybook-issue/hello-world' in 'User\Documents\Github\storybook-issue\libs\core\src\lib'
 @ ./libs/core/src/lib/core.tsx 3:0-58 10:43-53
 @ ./libs/core/src/lib/core.stories.tsx
 @ ./libs/core/src/lib sync \.stories\.tsx?$
 @ ./libs/core/.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./libs/core/.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
```

## Other

I've recreated the bug here: https://github.com/allforabit/storybook-issue

### LINKED ISSUE #3287: Unable to have nested Storybook components
When running `nx run shared-storybook:storybook` i get a this error
```
ERROR in ./libs/shared/top-right-bar/src/lib/shared-top-right-bar.stories.tsx
Module not found: Error: Can't resolve '@ppm/shared/top-menu-button' in '/Volumes/Media/Dev Projects/Projects Started/2020-06-10 - PPM/PPM-back-end-nest-js/libs/shared/top-right-bar/src/lib'
 @ ./libs/shared/top-right-bar/src/lib/shared-top-right-bar.stories.tsx 3:0-66 39:38-57
 @ ./libs/shared sync \.stories\.(j|t)sx?$
 @ ./libs/shared/storybook/.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./libs/shared/storybook/.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```
My understanding is that the issue is with nested components in Storybook

Main components / storybook `SharedTopRightBar` 
```js
import React from 'react';
import { SharedTopRightBar } from './shared-top-right-bar';
import { SharedTopMenuButton } from '@ppm/shared/top-menu-button';
// import { SharedTopMenuButton } from '../../../top-menu-button/src/lib/shared-top-menu-button';

export default {
  component: SharedTopRightBar,
  title: 'SharedTopRightBar',
};

export const primary = () => {
  return (
    <SharedTopRightBar>
      <SharedTopMenuButton />
    </SharedTopRightBar>
  );
};
```

Nested component / storybook `SharedTopMenuButton`
```js 
import React from 'react';
import {
  SharedTopMenuButton,
  SharedTopMenuButtonProps,
} from './shared-top-menu-button';
import { object } from '@storybook/addon-knobs';

export default {
  component: SharedTopMenuButton,
  title: 'SharedTopMenuButton',
};
const data = [
  {
    _id: '',
    title: 'Title',
    path: '',
    timeStamp: '',
    isRead: true,
  },
];

export const primary = () => {
  const props: SharedTopMenuButtonProps = {
    items: data,
    children: object('children', ''),
  };

  return <SharedTopMenuButton items={props.items}></SharedTopMenuButton>;
};
```

But if i do import like this `import { SharedTopMenuButton } from '../../../top-menu-button/src/lib/shared-top-menu-button';` then it works but of course with that i get different issue 
```
Libraries cannot be imported by a relative or absolute path, and must begin with a npm scopeeslint@nrwl/nx/enforce-module-boundaries
```

What I'm missing?

### PR DESCRIPTION
**Pull request by muhajirdev**
## Current Behavior (This is the behavior we have today, before the PR is merged)
#2320 issue details can be found here
## Expected Behavior (This is the new behavior we can expect after the PR is merged)
Fixing this that issue
## Issue

Fixes #2320
Fixes #3287

### CODE REVIEW

**Comment by muhajirdev** [comment]
oh, actually this PR need to install `tsconfig-paths-webpack-plugin`. but I am not sure how to do it

**Comment by muhajirdev** [comment]
oh, never mind. I found it in @nrwl/storybook's `package.json`

**Comment by mandarini** [comment]
Hi @muhajirdev ! 

Thank you very much for this PR, I just tested it and I can successfully import other internal libraries in my stories! 

In order to get this merged, the commit message would have to be properly formatted. Please take a look [in this section](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#commit-message-guidelines) of the "Contributing" documentation. 

If you want, you can also use the `yarn commit` command, which will generate a commit for you in the expected format. In the prompts that will appear in the CLI, you can chose that your change is a `bug`, that it is related to `storybook`, then you can type a short commit message, potentially a description, and finally you can write the number of the issue (`#2320`) which this fix solves!

Please let me know if you have any questions, and I can help you through if you need!

**Review by mandarini — CHANGES_REQUESTED** [review]
Hello @muhajirdev ! 

It seems that everything is ok with your PR, [except for the commit message](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#commit-message-guidelines)! 

I tried to amend it and fix your PR, but it seems that your PR does not allow edits from maintainers, so I cannot amend the commit without your permission! 

Let me know if you need any help either amending your commit or enabling the "allow edits from maintainers" option on your PR! You can take a look at the [GitHub documentation here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by juristr** [comment]
@muhajirdev I just fixed the broken commit message and I'm going to add some e2e tests to make sure this is properly covered. Thanks a lot for your contribution 🙂

**Pull request merged**
