### PR TITLE
fix(esbuild): don't overwrite plugins in esbuildOptions

### PR DESCRIPTION
**Pull request by rkorrelboom**
## Current Behavior
plugins defined in esbuild.config.js are overwritten 

## Expected Behavior
plugins defined in esbuild.config.js are not overwritten 

## Related Issue(s)

Fixes #

### CODE REVIEW

**Review by mandarini — APPROVED** [review]
Thanks this change makes sense!

**Comment by mandarini** [comment]
Can you please rebase with latest and repush, there was some sort of issue with the pipelines!

**Comment by mandarini** [comment]
Hmm can you please run `nx format`? And see what else may be failing? @rkorrelboom

**Comment by mandarini** [comment]
@rkorrelboom I'll take a look today at what's going on here

**Comment by rkorrelboom** [comment]
Thanks @mandarini , I wasn't able to figure it out by looking at the logs

**Pull request merged**
