### PR TITLE
[WIP] feat(core): adds configurable base branch in nx.json

### LINKED ISSUE #1791: Default base should be configurable
When running NX command, the default base is master. However, when we use GitFlow, our mainline is develop branch, so that would be great if we can change that setting without using --base option.

is there any way we can customize the default base option?

### PR DESCRIPTION
**Pull request by Doginal**
new field in nx.json - defaultBranch

ISSUES CLOSED: #1791

### CODE REVIEW

**Comment by Doginal** [comment]
Oops, have to fix my tests

**Comment by vsavkin** [comment]
@Doginal Thank you for submitting this PR. I think it's a good change.

Some suggestions:

Maybe we can have this section in `nx.json`:

```
affected: {
    defaultBase: 'master',
    defaultHead: 'HEAD'
}
```

And I'd make the section optional. So if you don't have it, defaultBase is set to master and defaultHead is set to HEAD, so no migration is necessary.

**Comment by Doginal** [comment]
@vsavkin good ideas, ill update my pr something this weekend! 

I made sure that if the defaultBranch does not exist it defaults to master. I'll switch it to defaultBase and add defaultHead into nx.json. 

I didn't know if I needed a migration script so I wrote one. I'll remove it when I update the PR

**Comment by vsavkin** [comment]
@Doginal sounds good. Let me know if you need any help.

**Comment by FrozenPandaz** [comment]
Hi, did you need any help on this? Or are you too busy to work on this?

**Comment by vsavkin** [comment]
Unfortunately, I'll have to close the PR due to inactivity. If you reopen it, we will take a look asap.

**Comment by cice** [comment]
is someone continuing this? otherwise i'd incorporate the changes you requested and open a new PR

**Pull request closed without merging**
