### PR TITLE
feat(web): rename @nrwl/web:build to @nrwl/web:webpack

### PR DESCRIPTION
**Pull request by jaysoo**
This PR renames `@nrwl/web:build` to `@nrwl/web:webpack` in preparation for more webpack and SWC work.

**Changes**

- Add migration to rename `@nrwl/web:build` to `@nrwl/web:webpack`
- Update docs that referred to `@nrwl/web:build` to use `@nrwl/web:webpack`
- Fix old migrations  (8.10) that looked for `@nrwl/web:build` to also look for `@nrwl/web:webpack` just for unit tests (although this never should happen in practice).

### CODE REVIEW

**Review by kirjai — APPROVED** [review]

**Comment by pstepniewskiconfigit** [comment]
@jaysoo @vsavkin migration from this PR and others are not run when migrating from `13.3.0-beta.3` to `13.3.0-beta.4`

**Comment by kirjai** [comment]
@pstepniewskiconfigit thanks for letting us know

any other migrations not running for you that aren't fixed by https://github.com/nrwl/nx/pull/7996 ?

**Comment by pstepniewskiconfigit** [comment]
@kirjai When I upgraded from `13.3.0-beta.3` to `13.3.0-beta.4` there was no `migrations.json` file generated. So if there was more than this one and similar one related to renaming `@nrwl/web:package`. So they also wasn't picked up.

**Comment by AlexLeung** [comment]
This change violates semver because it's breaking existing project configurations without a major version upgrade.

**Pull request merged**
