### PR TITLE
fix(core): hash implicit dependencies considering the context

### LINKED ISSUE #6078: Nx cache hash calculation ignores the implicitDependencies configuration in nx.json
## Current Behavior

In `nx.json` there is a part where you can define only the `dependencies` matters from the `package.json` the rest of the file doesn't:

```json
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
  }
```

nx ignores this, rendering the cache useless in case of I want create a release via bumping the version in the `package.json`.
The whole `package.json` file is calculated in the hash, resulting an unnecessarily full build of the project.

## Expected Behavior

nx should respect the `implicitDependencies` and bumping the version should not affect caching.

## Steps to Reproduce

Create an empty project with at least a buildable lib:

```
npx create-nx-workspace foo --preset=empty --interactive=false --nx-cloud=false
cd foo
npx nx generate @nrwl/workspace:library --name=bar --buildable --no-interactive
npx nx run bar:build
```

Try the build again, it will come from the cache, but when you change the version in `package.json` it will do a rebuild.

This bug effects the latest 12.4.0 version too.

## Ugly quick fix via patch-package

Just to give you an idea. This patch only works for the top level of every defined `implicitDependencies`.

```patch
diff --git a/node_modules/@nrwl/workspace/src/core/hasher/hasher.js b/node_modules/@nrwl/workspace/src/core/hasher/hasher.js
index 61fa2cf..1af2f32 100644
--- a/node_modules/@nrwl/workspace/src/core/hasher/hasher.js
+++ b/node_modules/@nrwl/workspace/src/core/hasher/hasher.js
@@ -146,9 +146,20 @@ class Hasher {
                     '.gitignore',
                     '.nxignore',
                 ];
+                for (const [name, filter] of Object.entries(this.nxJson.implicitDependencies || {})) {
+                    if ('*' !== filter) {
+                        delete this.fileHasher.fileHashes[name];
+                    }
+                }
+                const transformFile = (file, text) => {
+                    const filter = this.nxJson.implicitDependencies[file];
+                    const keysToKeep = Object.keys(filter);
+                    const filteredObj = Object.entries(JSON.parse(text)).filter(([k,v]) => keysToKeep.includes(k));
+                    return JSON.stringify(Object.fromEntries(filteredObj), undefined, 2);
+                }
                 const fileHashes = [
                     ...fileNames.map((file) => {
-                        const hash = this.fileHasher.hashFile(file);
+                        const hash = this.fileHasher.hashFile(file, text => transformFile(file, text));
                         return { file, hash };
                     }),
                     ...this.hashGlobalConfig(),

```

### LINKED ISSUE #6273: Removing deps to package.json affects all projects
## Current Behavior
Since NX 12 was introduced, any removal of a dependency in package.json will result in all projects being affected regardless of what is configured in nx.json. For example if nx.json is configured as such, removal of deps still affect all projects and not just `my-app`
image

## Expected Behavior
Prior to nx 12, this was not an issue.
Nx should at least respect nx.json, it is confusing when the behaviours varies (i.e nx.json says package.json deps only affect my-app, but in reality they sometimes affect every app) even if nx has a "smarter" way to deal with certain files like nx.json, package.json, workspace.json post nx 12 (also, if there are any docs on how this works please let me know :) ) Perhaps if nx has a smarter way to deal with package.json, it should be defined somehow in nx.json

Ideally nx is smart enough to categorize project to be node or not as well to determine which projects are affected by package.json change. 

The primary reasoning behind this is that we have a monorepo with more then half of projects using non-node projects, so it cost CI time and local development time when these changes occur.

## Steps to Reproduce
1. Generate a blank repo
2. Generate two apps `my-app` and `my-app-2`
3. Modify nx.json in the following
image
4. Commit these changes.
5. Modify a dependency version and run `nx affected:apps`, notice only my-app is affected
6. Revert 5, remove a dependency and run `nx affected:apps` notice both my-app and my-app-2 are affected (non-ideal esepcially if my-app-2 is not a node app)

### LINKED ISSUE #6461: Hasher ignores implicitDependencies values in nx.json
## Current Behavior
For hashing, any key in nx.json implicitDependencies applies to _all_ projects. 

## Expected Behavior
The behavior described in https://nx.dev/latest/react/core-concepts/configuration#implicit-dependencies for globalFile.

## Steps to Reproduce

add an implicitDependencies entry like -
```
    "some/dir/**": [
      "some-project"
    ],
```

build all your projects, then change something in some/dir/ , and try to build again, it will build everything again instead of using cache.

The code related to this is here - https://github.com/nrwl/nx/blob/master/packages/workspace/src/core/hasher/hasher.ts#L193

it does not look like it has ever worked as intended.

### Failure Logs
none

  Node : 12.22.1
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.5.8
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.5.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : 12.5.8
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

All keys in the implicit dependencies configuration are being hashed regardless of the projects that are configured to be affected by it.

## Expected Behavior

Hashing the implicit dependencies of a task should take into account the task project and only hash the implicit dependencies keys that are set to affect the task project as described in https://nx.dev/configuration/packagejson#files--implicit-dependencies.

## Related Issue(s)

Fixes #6461 #6078 #6273 

Closes https://github.com/nrwl/nx/pull/6235

### CODE REVIEW

**Comment by ydmitry** [comment]
Any news on this fix?

**Comment by chrisui** [comment]
Any opportunity to help get this over the line? It's a pretty serious bug considering the documentation and potential impact to invalidate whole workspaces, that has led a few people down a [tricky-to-diagnose](https://github.com/nrwl/nx/issues/8506) rabbit hole.

**Comment by gioragutt** [comment]
Hi guys, bumping this as this is a major improvement 🙏🏻

**Comment by konstantinschuette** [comment]
Would be great if we could get an update on this :)

**Comment by FrozenPandaz** [comment]
Closing this as its very out of date and we have a new system of `inputs`

**Pull request closed without merging**
