### PR TITLE
fix(node): set noEmitOnError to always true, and show diagnostic messages from ts

### PR DESCRIPTION
**Pull request by Cammisuli**
## Current Behavior
TypeScript errors are not handled properly when compiling with the node/package builder. 
## Expected Behavior
Error messages are properly displayed (similar to the TypeScript compiler)

## Related Issue(s)

Fixes #

Output:
```bash

Compiling TypeScript files for library jest...
packages/jest/src/builders/jest/jest.impl.ts:12:21 - error TS2307: Cannot find module 'ng-packagr/lib/utils' or its corresponding type declarations.

12 import { log } from 'ng-packagr/lib/utils';
                       ~~~~~~~~~~~~~~~~~~~~~~

Copying asset files...

>  NX   CLOUD  See run details at https://nx.app/runs/UHp8nZqihTy

error Command failed with exit code 1.
```

### CODE REVIEW

**Review by juristr — APPROVED** [review]
LGTM. Can we **add some tests** to make sure we don't run into this any more? I'm thinking about compiling an invalid TS file with the node package and making sure it exits properly

**Comment by vsavkin** [comment]
I agree about adding an e2e tests. Otherwise, looks good.

**Comment by Cammisuli** [comment]
I need to make some time to add the e2e. It should be quick though.

**Comment by juristr** [comment]
> I need to make some time to add the e2e. It should be quick though.

cool, ping me on Slack once it is up and I can review it again

**Comment by juristr** [comment]
Awesome, lgtm 👍

**Pull request merged**
