### PR TITLE
feat(core): add strict as an option to workspace, nest and node lib schematics

### PR DESCRIPTION
**Pull request by yharaskrik**
## Current Behavior
There is no way to pass `strict` to the generation of a node or nest lib like you can with angular to enable ts strict mode

## Expected Behavior
Want to be able to generate new libraries with strict mode enabled

### CODE REVIEW

**Comment by yharaskrik** [comment]
@Cammisuli I see Victor assigned you to this, would you like me to rebase this?

**Comment by Cammisuli** [comment]
hey @yharaskrik, yea, looks like a rebase is needed. Thank you!

**Comment by yharaskrik** [comment]
@Cammisuli done and done!

**Review by Cammisuli — APPROVED** [review]
LGTM

**Pull request merged**
