### PR TITLE
fix(vite): handle both vite.config.ts and vitest.config.ts

### LINKED ISSUE #22244: Available tasks for a project missing after vite.config.ts
### Current Behavior

Available tasks for a fresh react app installed in a monorepo are only `lint` after editing `./apps/react-monorepo/vite.config.ts`

### Expected Behavior

They should be: `build`, `serve`, `preview`, `serve-static`, `test` and `lint`

### GitHub Repo

_No response_

### Steps to Reproduce

1. `npx create-nx-workspace@latest react-monorepo --preset=react-monorepo`
2. choose the following
```
✔ Application name · react-monorepo
✔ Which bundler would you like to use? · vite
✔ Test runner to use for end to end (E2E) tests · cypress
✔ Default stylesheet format · css
✔ Do you want Nx Cloud to make your CI fast? · github
```
3. `nx show project react-monorepo` give the following:
```
{"root":"apps/react-monorepo","targets":{"build":{"options":{"cwd":"apps/react-monorepo","command":"vite build"},"cache":true,"dependsOn":["^build"],"inputs":["production","^production",{"externalDependencies":["vite"]}],"outputs":["{workspaceRoot}/dist/apps/react-monorepo"],"executor":"nx:run-commands","configurations":{}},"serve":{"options":{"cwd":"apps/react-monorepo","command":"vite serve"},"executor":"nx:run-commands","configurations":{}},"preview":{"options":{"cwd":"apps/react-monorepo","command":"vite preview"},"executor":"nx:run-commands","configurations":{}},"serve-static":{"executor":"@nx/web:file-server","options":{"buildTarget":"build"},"configurations":{}},"test":{"options":{"cwd":"apps/react-monorepo","command":"vitest run"},"cache":true,"inputs":["default","^production",{"externalDependencies":["vitest"]}],"outputs":["{workspaceRoot}/coverage/apps/react-monorepo"],"executor":"nx:run-commands","configurations":{}},"lint":{"cache":true,"options":{"cwd":"apps/react-monorepo","command":"eslint ."},"inputs":["default","{workspaceRoot}/.eslintrc.json","{workspaceRoot}/apps/react-monorepo/.eslintrc.json","{workspaceRoot}/tools/eslint-rules/**/*",{"externalDependencies":["eslint"]}],"executor":"nx:run-commands","configurations":{}}},"name":"react-monorepo","$schema":"../../node_modules/nx/schemas/project-schema.json","sourceRoot":"apps/react-monorepo/src","projectType":"application","tags":[],"implicitDependencies":[]}
```
4. edit `./apps/react-monorepo/vite.config.ts`
```
-   outDir: '../../dist/apps/react-monorepo',
+   outDir: './build/react-store',
```
5. save
6. `nx show project react-monorepo` gives:
```
{"root":"apps/react-monorepo","targets":{"lint":{"cache":true,"options":{"cwd":"apps/react-monorepo","command":"eslint ."},"inputs":["default","{workspaceRoot}/.eslintrc.json","{workspaceRoot}/apps/react-monorepo/.eslintrc.json","{workspaceRoot}/tools/eslint-rules/**/*",{"externalDependencies":["eslint"]}],"executor":"nx:run-commands","configurations":{}}},"name":"react-monorepo","$schema":"../../node_modules/nx/schemas/project-schema.json","sourceRoot":"apps/react-monorepo/src","projectType":"application","tags":[],"implicitDependencies":[]}
```

### Nx Report

```shell
Node   : 18.13.0
OS     : linux-x64
npm    : 9.2.0

nx (global)        : 18.0.7
nx                 : 18.0.7
@nx/js             : 18.0.7
@nx/linter         : 18.0.7
@nx/eslint         : 18.0.7
@nx/workspace      : 18.0.7
@nx/cypress        : 18.0.7
@nx/devkit         : 18.0.7
@nx/eslint-plugin  : 18.0.7
@nx/react          : 18.0.7
@nrwl/tao          : 18.0.7
@nx/vite           : 18.0.7
@nx/web            : 18.0.7
typescript         : 5.3.3
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

However, if we delete `nx` cache: `rm -r .nx/cache`, the correct target list is seen.

### PR DESCRIPTION
**Pull request by MaximeBernard**
## Current Behavior
When a package has both `vite.config.ts` and `vitest.config.ts`, plugin fails to infer targets correctly (in my case, I had some packages with `test` targets, some with `build` targets). 

## Expected Behavior
Having both files should not bother nx plugin. 

## Related Issue(s)
Might fix #22244

### CODE REVIEW

**Comment by MaximeBernard** [comment]
For the record, the build was green before I rebased 😉

**Comment by MaximeBernard** [comment]
@AgentEnder since you recently worked on plugin configuration, maybe you could take a look at this PR?

**Comment by Coly010** [comment]
Closed in favour of: #22618

**Comment by MaximeBernard** [comment]
@Coly010 #22618 is a nice fix but my suggestion seems fair as well (at least for clarity). Unless I missed the point?

Anyway, thanks for the feedback and fixing the underlying issue. ❤️

**Comment by Coly010** [comment]
Hey @MaximeBernard!

Sorry, I should have elaborated more and I also should have said this: Thanks for the PR to attempt to fix this! 🎉 

There are two things really.

**1. The issue was less about _how_ the targets are created.**
I tried your example locally, and although on first run after the cache was reset _all_ targets were created successfully, subsequent runs only had the build, serve, preview etc targets. It was missing test for example.

The real issue was not about the conditional on the config file name. It was because both config files were generating the same hash as the parameters were the same, which led to one or the other of the config files overwriting the cache for the targets. Which config file did this was dictated by that conditional. Changing it only changed which config file overwrote the cache last.

**2. Code style**
There are two conditionals that dictate the targets that should be created. From a personal perspective, I find it easier to read code that does something for the truthy and falsey outcomes of that same conditional.

```
IF configFile != vitest THEN
 // Add Build Targets etc
 
 IF configFile == vitest THEN
// Add Test Target
```

So when it comes to reading it, you get an overall picture of what happens when the config file is or is not `vitest`.

Perhaps your suggestion would be more clear, but it's just semantics at that stage.

All this said, thank you again for taking a stab at this! Your suggestion in this PR helped me to identify the root cause of the issue more swiftly!

**Pull request closed without merging**
