### PR TITLE
chore(core): nx plugin submission nx-install

### PR DESCRIPTION
**Pull request by AndrewRedican**
# Community Plugin Submission

## nx-install

nx-install is a tiny generator that solves the issue of running dependency installation, especially for CI/CD pipelines, where a developer would like to run this for affected projects prior to running other processes, by automating setup for every projects' configuration with a custom command that calls npm install.

### CODE REVIEW

**Comment by AndrewRedican** [comment]
Any news with this PR?

**Comment by AgentEnder** [comment]
Hey @AndrewRedican! I'm looking over this now. When would someone use this over something like yarn workspaces for managing the install tasks?

**Comment by AndrewRedican** [comment]
Hi @AgentEnder,

`nx-install` allows you install dependencies for affected projects. [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) is not a suitable replacement, and I would not recommend it.

[That I know of](https://github.com/nrwl/nx/issues/1954), Nx's [affected](https://nx.dev/concepts/affected) is only available through cli. Instead of implementing my own `affected()` method in NodeJS, I am relying on a generator to set up an `nx-install` task in every project so that it can it later be called through nx, allowing me to pass the `affected` flag.

The reason I am using `npm` over `yarn` as the actor for installation is purely an arbitrary preference. I might parameterize this later should anyone raise a PR or submits a feature request. For now, it uses npm.

Regarding [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/), it is not a suitable drop-in replacement because it installs _everything_. That will not scale. The main use case I have for installing dependencies against affected projects only it to be able to run `test` and `build` later as part of PR checks.

Reading further ([caveats](https://classic.yarnpkg.com/lang/en/docs/workspaces/#toc-limitations-caveats)) it seems like it is goes against Nx's intended design. One of major pain points I've had with monorepos in the past is having a common shared configuration for all projects. For example, [Angular monorepos](https://angular.io/guide/file-structure#workspace-configuration-files)_ :shit:) which relies on a common workspace `package.json` file, this becomes a headache to maintain when you are to upgrade dependencies with breaking changes and you are forced to update _ALL_ projects. I think the scalable solution, IMHO is to automate configuration for each project separately, hence why `project.json` exists.

**Comment by AndrewRedican** [comment]
Any joy or additional feedback for this?

**Comment by AndrewRedican** [comment]
@AgentEnder

**Review by AgentEnder — APPROVED** [review]

**Pull request merged**
