### PR TITLE
fix(core): remove devDependencies in production build

### PR DESCRIPTION
**Pull request by robdonn**
## Current Behavior

When a local package.json is loaded with a `devDependencies` property, that property's contents end up in the final outputted `package.json`, even when `isProduction` is set to `true`.

## Expected Behavior

When `isProduction` is `true` then `devDependencies` should be removed.

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by mandarini** [comment]
oopppsss sorry everyone!!!

**Comment by mandarini** [comment]
Hi @robdonn ! I am closing this PR and will make a new one with your changes!

**Comment by mandarini** [comment]
The reason why I messed up your PR, and sorry about that @robdonn , is because you had set the target to `[15.9.x](https://github.com/nrwl/nx/tree/15.9.x)`. I changed the target to `master` and then tried to rebase, but obviously this would be too much trouble, so [I just created a new branch off of `master` and put your suggested changes there](https://github.com/nrwl/nx/pull/21428). I could not push to your repo, naturally. Apologies about that!!!! 😬 

If you want to make a PR in the future, please try to target the `master` branch, and pick a new branch name, it will be so much easier to update and rebase your PR! :) 

Again, thank you very much!!

**Comment by mandarini** [comment]
Again, SORRY everyone for the pings!!!!

😿😿😿😿

**Comment by robdonn** [comment]
Hi @mandarini, that's no problem. 

I was intentionally targeting `15.9.x` as I _think_ it was fixed in 16 but I wanted to patch version 15 as my company is still stuck on it.

**Pull request closed without merging**
