### PR TITLE
Support Next.js 9.1.x

### LINKED ISSUE #2106: Update Next to latest stable
## Expected Behavior
I should be able to upgrade the `next` dependency to the latest version.

## Current Behavior
I get an error when trying to run a `nrwl` repository with `next@9.1.4`.

## Failure Information (for bugs)
```
yarn run v1.19.1
$ nx serve
Cannot find module 'next-server/constants'
Require stack:
- /example-repo/node_modules/@nrwl/next/src/builders/dev-server/dev-server.impl.js
- /example-repo/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /example-repo/node_modules/@angular-devkit/architect/node/index.js
- /example-repo/node_modules/@nrwl/tao/src/commands/run.js
- /example-repo/node_modules/@nrwl/tao/index.js
- /example-repo/node_modules/@nrwl/cli/lib/init-local.js
- /example-repo/node_modules/@nrwl/cli/bin/nx.js
error Command failed with exit code 1.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone https://github.com/AryanJ-NYC/cannot-upgrade-next-with-nrwl
2. Run `yarn install`
3. Run `yarn start`

### Context
Please provide any relevant information about your setup:

  @nrwl/angular : Not Found
  @nrwl/cli : 8.8.2
  @nrwl/cypress : 8.8.2
  @nrwl/eslint-plugin-nx : 8.8.2
  @nrwl/express : Not Found
  @nrwl/jest : 8.8.2
  @nrwl/linter : 8.8.2
  @nrwl/nest : Not Found
  @nrwl/next : 8.8.2
  @nrwl/node : Not Found
  @nrwl/react : 8.8.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.8.2
  @nrwl/web : 8.8.2
  @nrwl/workspace : 8.8.2
  typescript : 3.5.3

### LINKED ISSUE #2174: TypeError: this[MODULE_TYPE] is not a function in built Next.js app with imported CSS
## Expected Behavior
Next apps with imported CSS render.

## Current Behavior
Next apps with imported CSS break.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to https://github.com/AryanJ-NYC/build-next-app-with-imported-css (brand new nrwl/next app)
2. Run `yarn nx serve build-next-app-with-imported-css --prod` 
3. Go to http://localhost:4200
Screen Shot 2019-12-11 at 12 04 25 AM

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : 8.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : 8.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 8.9.0
  @nrwl/node : Not Found
  @nrwl/react : 8.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : 8.9.0
  @nrwl/workspace : 8.9.0
  typescript : 3.5.3
```
https://github.com/AryanJ-NYC/build-next-app-with-imported-css

### Failure Logs
```
ModuleBuildError: Module build failed (from /build-next-app-with-imported-css/node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at /build-next-app-with-imported-css/node_modules/mini-css-extract-plugin/dist/loader.js:141:24
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compiler.js:343:11
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compiler.js:671:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/build-next-app-with-imported-css/node_modules/tapable/lib/Hook.js:154:20)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compiler.js:668:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/build-next-app-with-imported-css/node_modules/tapable/lib/Hook.js:154:20)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compilation.js:1385:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/build-next-app-with-imported-css/node_modules/tapable/lib/Hook.js:154:20)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compilation.js:1376:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/build-next-app-with-imported-css/node_modules/tapable/lib/Hook.js:154:20)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compilation.js:1371:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/NormalModule.js:313:20
    at /build-next-app-with-imported-css/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /build-next-app-with-imported-css/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/build-next-app-with-imported-css/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /build-next-app-with-imported-css/node_modules/mini-css-extract-plugin/dist/loader.js:143:14
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compiler.js:343:11
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compiler.js:671:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/build-next-app-with-imported-css/node_modules/tapable/lib/Hook.js:154:20)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compiler.js:668:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/build-next-app-with-imported-css/node_modules/tapable/lib/Hook.js:154:20)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compilation.js:1385:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/build-next-app-with-imported-css/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/build-next-app-with-imported-css/node_modules/tapable/lib/Hook.js:154:20)
    at /build-next-app-with-imported-css/node_modules/next/node_modules/webpack/lib/Compilation.js:1376:32
```

## Other

Related to https://github.com/webpack-contrib/mini-css-extract-plugin/issues/73

### PR DESCRIPTION
**Pull request by elliottsj**
## Current Behavior (This is the behavior we have today, before the PR is merged)

Only Next.js v9.0.x is supported.

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

Next.js 9.1.5 is supported. Next.js 9.0.x is _no longer supported_ due to changed internal module paths.

## Issue

Fixes #2106
Fixes #2174

### CODE REVIEW

**Comment by AryanJ-NYC** [comment]
Does https://github.com/nrwl/nx/blob/master/packages/next/src/utils/versions.ts need to be updated to include `9.1.5`?

**Comment by elliottsj** [comment]
@AryanJ-NYC ah I missed that; now added

**Comment by FrozenPandaz** [comment]
Hi, thank you so much for your contrubtion!

Can you please also add a migration so that existing workspaces that use next 9.0.x will be automatically migrated to v9.1.x?

Can you also please also add a `peerDependency` on `next` so that it is clear what range is compatible with the `@nrwl/next` package?

**Comment by elliottsj** [comment]
Added to `peerDependencies`.

Sorry still a bit new to Nx; how would I go about adding the migration? The only change necessary is that users need to upgrade their `"next": "9.0.5"` package.json entry to `"next": "9.1.5"`.

**Comment by FrozenPandaz** [comment]
No worries:

Here is an example of react deps being updated to latest versions.

1. Create an entry in migrations.json:

https://github.com/nrwl/nx/pull/2089/files#diff-bc52854c5fa7780710213436792293baR18

2. Add packageJsonUpdates to migrations.json:

https://github.com/nrwl/nx/pull/2089/files#diff-bc52854c5fa7780710213436792293baR58

3. Write migration schematic:

https://github.com/nrwl/nx/pull/2089/files#diff-4968d014a3530305aab1a3296081ba8dR28

`updatePackagesInPackageJson` is the important rule here.

**Comment by elliottsj** [comment]
@FrozenPandaz Thanks! This Next.js 9.1.5 upgrade will likely end up in a new minor release, correct? Should the migration's version number be `8.10.0`?

**Comment by elliottsj** [comment]
Added a migration with version 8.10.0. Let me know if this works.

**Comment by FrozenPandaz** [comment]
The migration worked wonderfully, @elliottsj. Great job!

I merged the changes with #2216

**Comment by asherccohen** [comment]
Hi. I'm new to nx and I faced an issue tht is resolved with this PR. 
I tried running nx migrate @nrwl/workspace and nx migrate @nrwl/workspace@latest (8.9.0) but no migration is created.
If this PR has been already merged how come I cannot update my workspace?

**Comment by elliottsj** [comment]
@asherccohen The changes in this PR are not yet released. They've [landed in the master branch](https://github.com/nrwl/nx/commit/6c83f2dc5964d1bde31c5f8e9ef72a80161f6941), but the 8.10.0 release has not yet been created.

**Comment by asherccohen** [comment]
@elliottsj Cool, thanks a lot. Production builds depend on this so I'm happy to see that steady solutions are out there already!

**Pull request closed without merging**
