### PR TITLE
feat(nextjs): allow custom server to be written in TypeScript

### PR DESCRIPTION
**Pull request by juristr**
## Current Behavior

It is possible to provide a custom Next.js server, but only written in JS

## Expected Behavior

This PR allows for both, writing the custom server in JS & TS

## Related Issue(s)

This has previously been discussed here #2227

### CODE REVIEW

**Comment by juristr** [comment]
@jaysoo @kirjai let me know what you think about it. We should probably add some tests around it as well (like in general around the custom server part). Can provide those later in case

**Comment by jaysoo** [comment]
It's a good idea, folks would definitely want to use TS if possible.

Can add an e2e test to cover this case.

I know @kirjai was also looking into custom server and how the custom server file that Nx expects is different than the Next.js one (Nx wants a function that creates the server, whereas Next.js expects the file to start the server without function call). Maybe we can look at making it more compatible?

**Comment by juristr** [comment]
@jaysoo @kirjai added an e2e test. If we can merge this, I can mention it in my article as well

**Comment by nsmith7989** [comment]
Excellent, just what I needed! 

Does this allow a customSever to consume an nx node package written in ts? 

Say I have a middleware in libs/my-middleware and I want to use it in my custom next server

```ts
import { myMiddleware } from '@root-scope/myMiddleware';

export default async function nextCustomServer(app, settings, proxyConfig) {
   
  const handle = app.getRequestHandler();        
  await app.prepare();
  const server = express();

  server.use(myMiddleware);

  server.all('*', (req, res) => handle(req, res));

  server.listen(settings.port, settings.hostname)
}
```

**Comment by juristr** [comment]
@nsmith7989 It should be possible, otherwise let us know

**Pull request merged**
