### PR TITLE
Update 08-create-libs.md

### PR DESCRIPTION
**Pull request by jlcampbell**
fix(nx): fix incorrect path in doc

## Current Behavior
Current path in tutorial is 'libs/src/lib/todos/todos.component.ts', which does not exist.

## Expected Behavior
Instead, the path should be `libs/ui/src/lib/todos/todos.component.ts`

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you for your PR!

Could you update the commit message so the link check passes?

**Comment by jlcampbell** [comment]
Ok, will do!

**Comment by jlcampbell** [comment]
@vsavkin checks pass now!

**Comment by vsavkin** [comment]
Thank you!

**Pull request merged**
