### PR TITLE
feat(core): add support for wildcards in dependsOn

### LINKED ISSUE #19414: dependencyOf - the inverse of dependsOn
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I'd like to add the `dependencyOf` field to the `TargetConfiguration` interface, which would allow users and plugins to add additional targets that would automatically add themselves to other targets' `dependsOn` lists.

## Motivation
Main motivation is to programmatically (in plugins) add targets that would execute before other targets. This would allow to easily implement `preBuild` functionality without needed to modify the existing `build` target or even know if it exists.

## Suggested Implementation
The idea is to add a `dependencyOf` field to the `TargetConfiguration` and transform such dependencies to the `dependsOn` ones on the ProjectGraph creation step, so that everything that works with the ProjectGraph itself would not care about the `dependencyOf` and continue to rely only on `dependsOn`. It can be done after building full projectGraph here: https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/build-project-graph.ts#L196 by iterating over all projects like this:

```
for (const project in finalGraph.nodes) {
  const targets = finalGraph.nodes[project].targets;
  if (targets) {
    for (const dependencyName in targets) {
      if (targets[dependencyName].dependencyOf) {
        for (const name of targets[dependencyName].dependencyOf) {
          if (targets[name]) {
            targets[name].dependsOn || (targets[name].dependsOn = []);
            targets[name].dependsOn.push(dependencyName);
          }
        }
        delete(targets[dependencyName].dependencyOf)
      }
    }
  }
}
```

## Alternate Implementations
...

### PR DESCRIPTION
**Pull request by fxposter**
Now it is possible to define targets like this:

```
{
  "targets": {
    "build-css": {},
    "build-js": {},
    "test": {
      "dependsOn": ["build-*"]
    },
  }
}
```

## Current Behavior
No support for wildcard target dependencies.

## Expected Behavior
This PR is an example of what I described here: https://github.com/nrwl/nx/issues/19414.

## Related Issue(s)
Closes #19414

### CODE REVIEW

**Comment by fxposter** [comment]
@AgentEnder @FrozenPandaz guys, can you evaluate this idea, please?

**Comment by fxposter** [comment]
@AgentEnder @FrozenPandaz guys?..

**Comment by fxposter** [comment]
@FrozenPandaz @AgentEnder maybe now is the better time to look at it? It even passed all the tests :)

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]

**Review by FrozenPandaz — APPROVED** [review]
Thank you for your contribution! LGTM :tada:

**Pull request merged**
