### PR TITLE
Update schema.json

### PR DESCRIPTION
**Pull request by stckcrsh**
fix(nx): staticDir is supposed to be array of strings

### CODE REVIEW

**Comment by Cammisuli** [comment]
Thanks for the PR @stckcrsh, but it looks like one of our checks is failing 🙁 

Can you amend your commit to that it follows the structure mentioned here:
https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#commit-message-guidelines

**Comment by stckcrsh** [comment]
Sorry about that ill update and submit

**Comment by vsavkin** [comment]
@stckcrsh Hey there. Any progress?

**Comment by vsavkin** [comment]
@stckcrsh could you update the PR so the checks pass? Thank you!

**Comment by vsavkin** [comment]
It looks it has already been fixed here: https://github.com/nrwl/nx/commit/3646b6209ed415ce9107e3fdfb5b846eddbf05df

I'm going to close this PR.

**Pull request closed without merging**
