### PR TITLE
[Cypress] support customizing the webpack config

### PR DESCRIPTION
**Pull request by elliottsj**
## Current Behavior (This is the behavior we have today, before the PR is merged)

[`@cypress/webpack-preprocessor` is applied via `preprocessTypescript`](https://github.com/nrwl/nx/blob/90117910df75bddbcbcd99c1a79e7ec80bddd69a/packages/cypress/src/plugins/preprocessor.ts), but the encapsulated webpack config is not customizable by the user. This means that it's not possible to set up plugins like [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor), since they require [customizations to the webpack config](https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/blob/ebcfd0f746fa2507cd61fb7b7bbe6fd866fe261e/cypress/plugins/index.js#L5).

```js
// apps/myapp-e2e/src/plugins/index.js

const {
  preprocessTypescript
} = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
  on(
    'file:preprocessor',
    preprocessTypescript(config)
  );
  return config;
};
```

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

Now, a 2nd argument to `preprocessTypescript` is available: a function which accepts a webpack config object and returns a webpack config object. It may be mutated in this function, e.g.

```js
// apps/myapp-e2e/src/plugins/index.js

const {
  preprocessTypescript
} = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
  on(
    'file:preprocessor',
    preprocessTypescript(config, webpackConfig => {
      webpackConfig.node = {
        fs: 'empty',
        child_process: 'empty',
        readline: 'empty'
      };
      webpackConfig.module.rules.push({
        test: /\.feature$/,
        use: [
          {
            loader: 'cypress-cucumber-preprocessor/loader'
          }
        ]
      });
      webpackConfig.module.rules.push({
        test: /\.features$/,
        use: [
          {
            loader: 'cypress-cucumber-preprocessor/lib/featuresLoader'
          }
        ]
      });
      return webpackConfig;
    })
  );
  return config;
};
```

### CODE REVIEW

**Review by Cammisuli — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you please update the `preprocessors.spec.ts` file to include the new functionality?

**Comment by elliottsj** [comment]
@Cammisuli Added a couple basic tests; lmk what you think

**Comment by elliottsj** [comment]
I'm confused about the [current E2E test failure](https://circleci.com/gh/nrwl/nx/3898):

```
      Running:  app.spec.ts                                                                     (1 of 1)
    Starting type checking service...
    Using 1 worker with 2048MB memory limit
    
    
      myapp3043720
    
    1) should display welcome message
    
    
      0 passing (719ms)
      1 failing
    
      1) myapp3043720 should display welcome message:
         TypeError: cy.login is not a function
          at Context.<anonymous> (http://localhost:4200/__cypress/tests?p=src/integration/app.spec.ts-728:110:12)
```

As far as I can tell, I haven't changed anything that would cause `cy.login` to raised a type error. Any advice is appreciated.

**Comment by FrozenPandaz** [comment]
> As far as I can tell, I haven't changed anything that would cause `cy.login` to raised a type error.

@bcabanes Can you take a look at this?

**Comment by vsavkin** [comment]
Had to adjust the implementation. Merged it here: https://github.com/nrwl/nx/pull/2503

**Comment by vsavkin** [comment]
@elliottsj Thank you for your PR!

**Pull request closed without merging**
