### PR TITLE
fix(schematics): support empty ngModule imports

### LINKED ISSUE #9: NgRx Schematic doesn't add imports property when an ngmodule is empty
Say we have `app.module.ts ` look something like this:

```ts
import {NgModule} from '@angular/core';

@NgModule({})
export class AppModule {}
```

Run something like this:

```console
schematics @nrwl/schematics:ngrx --module=apps/client/src/app/app.module.ts 
```

And invalid code will be generated.

Change the module to look like and rerun the same schematic:

```ts
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';

@NgModule({
  imports: [
    CommonModule
  ]
})
export class AppModule {}
```

And it will work

### PR DESCRIPTION
**Pull request by ThomasBurleson**
* Auto-inject BrowserModule or CommonModule when not present in the NgModule imports:
```ts
    import {NgModule} from '@angular/core';
    @NgModule({ })
    export class AppModule {
    }
```
* Supports ngModules with:
  *  missing `imports` or `providers` metaKey(s)
  *  missing  `imports : [CommonModule]` or `imports: [BrowserModule]` entries
* Add spec tests for `add-imports-to-module` and the `remove` rule

Fixes #9.

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
Still need to fix scenario when the ngModule is missing the `imports` metadata key.

**Comment by vsavkin** [comment]
@ThomasBurleson can you take a look?

**Comment by ThomasBurleson** [comment]
@vsavkin - I will fix this today. 
> For some reason, I did not realize you had pinged me on this.

**Comment by vsavkin** [comment]
Hey @ThomasBurleson. I'm closing this PR because it's a pre-Nx-6 PR. 

If you decide to fix the issue,  please send an updated PR.

Thanks!

**Pull request closed without merging**
