### PR TITLE
feat(angular): add an option to use eslint

### PR DESCRIPTION
**Pull request by vsavkin**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by Akxe** [comment]
This is an amazing feat, but... How do I migrate an existing project from TSLint to ESLint? I mostly care about not having both installed and VSCode knowing it should lint using ESLint.

**Comment by Lonli-Lokli** [comment]
Also there is no any notification how to use it. I've created workspace and it still contains tslint.json

**Comment by Lonli-Lokli** [comment]
Ok I was able to generate it but few notes about this PR: application schematic by default use taking while library is switched to tslint, and second tslint and codelyzer are still added to dev dependencies.

**Comment by TobiasKrogh** [comment]
@vsavkin any update on how to migrate an existing project?

**Comment by doliG** [comment]
@vsavkin I have the same question as @TobiasKrogh

**Pull request merged**
