### PR TITLE
feat(devkit): reexport package manager methods in devkit

### PR DESCRIPTION
**Pull request by Phillip9587**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
What is the use-case of exposing this? Can you please create an issue first to layout the motivation for this behavior?

**Comment by Phillip9587** [comment]
@FrozenPandaz I'm sorry that i provided no context. 

The intention of this feature is to provide users of the devkit and the `@nrwl/*` packages the 2 extra methods `detectPackageManager` and `getPackageManagerVersion`. Packages depending on the devkit may need a certain version or feature of a package manager. With the 2 methods exported from devkit the plugin author can easily check the version and used package manager and may throw an error. 

Maybe a `needsPackageManagerVersion` helper method should be exported from devkit which allows the user to define a semantic version range for each package manager and throws an error if the version does not match. 

I know that it is possible to define engines in `package.json` but it does not enforce the package manager version and only shows a warning during the installation step. see https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thank you, I agree. :+1: 

Please add some TSDocs to the newly public functions?

**Comment by Phillip9587** [comment]
@FrozenPandaz I added the TSDoc for the 2 methods. 

I also refactored the `getPackageManagerCommand` method to use a object literal instead of the switch case. Please review these changes as well.

**Review by FrozenPandaz — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
