### PR TITLE
feat(linter): new eslint builder

### PR DESCRIPTION
**Pull request by JamesHenry**
## Current Behavior

The current ESLint builder that ships with Nx is a port of a port of the TSLint builder from angular-devkit. This originally made sense as a starting point to get things working.

However, that initial implementation has shown its limitations and it is doing a bunch of work that, whilst appropriate in the TSLint case, is not appropriate in the ESLint case.

## Expected Behavior

This PR adds a new builder implementation alongside the existing one. This will give us the easiest path to providing the new functionality without requiring users to migrate straight away (although this PR will also provide an automated migration). By having two separate implementations, we can avoid having a single, complex implementation with a messy and hard to validate schema definition for the builder.

## Related Issue(s)

This new builder should resolve (or at least help with):

#3310
#2784

### CODE REVIEW

**Review by FrozenPandaz — APPROVED** [review]
LGTM! Thanks!

**Comment by EvtK** [comment]
@JamesHenry this might be a fairly stupid question, but If i wanted to migrate my NX installation from tslint to eslint, how can I apply the great stuff you have added recently. 

I've tried: nx migrate update-eslint-builder-and-config on 10.3.0, but it tells me there are no migrations to run.

Any help appreciated!

**Comment by JamesHenry** [comment]
@EvtK specifically here we are referring to using the new eslint builder in Nx vs the old eslint builder in Nx - tslint is not involved.

There is a larger effort I am working on around tslint -> eslint migration within Nx workspaces but that is not yet available and is a manual process for now.

**Comment by EvtK** [comment]
@JamesHenry okay james, thanks for reporting. I be watching any development progress on the TS -> ES migration part, since that is definitely something it would like to use NX for!

**Pull request merged**
