### PR TITLE
fix(linter): standalone projects should be detectable with eslint

### PR DESCRIPTION
**Pull request by meeroslav**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Review by FrozenPandaz — APPROVED** [review]

**Comment by rathpc** [comment]
it would be nice to have some context for this change. Now when running a generator for an app, lib, remote etc which uses this, it generates an `.eslintrc.json` for that project extending the root `.eslintrc.base.json` file by default now instead of the root `.eslintrc.json` which it should be extending based on all previously created projects. In particular my root `.eslintrc.json` includes the base one by means of extending under certain conditions. is this no longer the preferred approach? If not shouldn't there be a migration to change the project files' extends array for any existing project?

**Comment by meeroslav** [comment]
This is only a hard request for nested projects to make pure eslint runs and IDE services also possible.

Since `.eslintrc.json` is bound to the root project (to make it work with eslint and IDE), we need to use the auxiliary name (`.eslintrc.base.json`).

If some projects were not properly migrated, please open a new issue and provide a reproduction repo so we can address it.

**Comment by rathpc** [comment]
I am not entirely sure I understand - do you mean that apps/libs **should** be extending the base instead of the root `.eslintrc.json`?

**Comment by meeroslav** [comment]
@rathpc, in a typical monorepo setup each project has its own folder and in that folder, they have e.g. `.eslintrc.json`.
In order to avoid repeating the configuration and potentially misconfiguring stuff, we have root level `.eslintrc.json` which all of them extend.

The standalone application is not sitting in the folder but rather generated directly in the root folder. In order to make the linter work automatically in the IDE and when running `eslint` its configuration file needs to follow the `.eslintrc` naming convention. This gets into a clash with the root-level configuration file that all projects should extend from.

That's why we decided, in the case of standalone applications to rename the base configuration to `.eslintrc.base.json`. This conversion happens when you add a second project to the monorepo. Also, all the existing projects should be migrated.

As I mentioned, if you have a scenario where this solution is not working, please open a new issue so we can address it.

**Pull request merged**
