### PR TITLE
feat(nest): update NestJS version to 7.0.0

### PR DESCRIPTION
**Pull request by beeman**
This PR updates NestJS to the latest version. I've added the same versions that are used when creating a new app using the NestJS cli, including RxJS.

I've tested it in a playground and all seems to work as expected.

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
@beeman

Would you mind listing out any Breaking Changes in NestJS 7.0.0 and highlight any changes that were made? I see rxjs is now a peer dependency?

**Comment by beeman** [comment]
@FrozenPandaz thanks for reviewing!

(As far as I can tell...)

The only real breaking change in NestJS core is dropping support for Node v8.

Other than that, users of the packages `@nestjs/microservices`, `@nestjs/graphql` and  @nestjs/terminus are advised to read the [migration guide](https://docs.nestjs.com/migration-guide) see what changed for them.

I've been using Nest v7 it since it's release in my Nx projects and I only needed to change how I used GraphQL. 

Since Kamil did an awesome job keeping `@nestjs/graphql` backwards compatible, migration is trivial: 

- Search/replace `type-graphql` with `@nestjs/graphql`
- Search/replace `ResolveProperty` with `ResolveField`.

After that we can get rid of the `type-graphql` dependency and the migration is done.


Let me know if you need anything else, or if you want me to list this somewhere specific.

**Comment by beeman** [comment]
@FrozenPandaz I pushed and updated version. The PR now also updates the dependencies in the top-level package.json, and I gave a shot at a migration script. Not sure if that's something that's desired, happy to remove again it if not :)

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thank you for adding the migration file.

I think we should also provide migrations for the changes to imports.

Would you be able to give that a shot?

**Comment by beeman** [comment]
@FrozenPandaz for sure happy to take a look at that. Do you know of a similar migration that I could use as an example?

**Comment by FrozenPandaz** [comment]
Here is somewhere you can start? You may want to be more careful about which Symbols are brought over?

https://github.com/nrwl/nx/blob/master/packages/react/src/migrations/update-8-3-0/update-8-3-0.ts#L98

**Comment by beeman** [comment]
@FrozenPandaz that was a great pointer, I updated the migration to update the import from `type-graphql` to `@nestjs/graphql`, and remove the `type-graphql` dependency from package.json.

However, I have tried to rename the decorator (`ResolveProperty` -> `ResolveField`) but I could not get it working, my AST knowledge is not sufficient yet. Any pointers on how we can do that?

**Comment by juristr** [comment]
@beeman just adjusted a couple of things on top of ur PR. Thx again for all ur contributions 🙏 .

I also added a link to the NestJS migration docs, so ppl can check it out.

image

If the pipeline looks good I'll merge it tomorrow

**Pull request merged**
