### PR TITLE
feat(core): adding separate .test.env file for tests instead of …

### PR DESCRIPTION
**Pull request by rkreienbuehl**
## Current Behavior
For tests the same env variables are loaded as for serving an app.

## Expected Behavior
To be able to set different env variables during tests, a separate `.env` file should be provided. With the change it is possible to have a separate `.test.env` file in the root and in the project folder.

## Related Issue(s)
#5426 

Fixes #

### CODE REVIEW

**Comment by vsavkin** [comment]
Hi there! Thank you for your PR!

What's your use case for having a separate env per target?

**Comment by rkreienbuehl** [comment]
We provide database connection options via env variables. When developing, we want to have a database filled with data, but when testing the code, always a clean database should be used. The cleanest way in my opinion is to use separate `.env` files, instead of producing uncovered code everywhere, where this should be differentiated.

**Comment by vsavkin** [comment]
Really sorry for the late response. My thoughts:

I don't like special casing targets. For instance, the use case above with the database will more likely to apply to things like e2e tests, so the target name won't be test by default (most folks use e2e as the target name in this case). 

We could of course change it such that it loads every target name. For instance, if you run nx e2e blah it will load .e2e.env. Something like this:

```
    const envsFromFiles = {
      ...parseEnv('.env'),
      ...parseEnv('.local.env'),
      ...parseEnv(`${task.projectRoot}/.env`),
      ...parseEnv(`${task.projectRoot}/.local.env`),
      ...parseEnv(`${task.projectRoot}/.${task.target.target}.env`),
    };
```

The problem with this is that target often invoke other targets. nx e2e often invokes nx serve. I believe it will work (the env variable passed from the e2e target will take precedence) but it might be confusing. What do you think?

**Comment by rkreienbuehl** [comment]
I think this approach would be much better with more flexibility. Maybe there should also be a possibility for a global .env for targets:
``` ts
const envsFromFiles = {
      ...parseEnv('.env'),
      ...parseEnv('.local.env'),
      ...parseEnv(`.${task.target.target}.env`),
      ...parseEnv(`${task.projectRoot}/.env`),
      ...parseEnv(`${task.projectRoot}/.local.env`),
      ...parseEnv(`${task.projectRoot}/.${task.target.target}.env`),
    };
```

**Comment by vsavkin** [comment]
```
const envsFromFiles = {
      ...parseEnv('.env'),
      ...parseEnv('.local.env'),
      ...parseEnv(`.${task.target.target}.env`),
      ...parseEnv(`${task.projectRoot}/.env`),
      ...parseEnv(`${task.projectRoot}/.local.env`),
      ...parseEnv(`${task.projectRoot}/.${task.target.target}.env`),
    };
    
```

Looks good.

**Comment by vsavkin** [comment]
Sorry, could you rebase the PR?

**Comment by webberwang** [comment]
can't wait for this PR!

**Comment by vsavkin** [comment]
@rkreienbuehl do you need any help rebasing?

**Comment by rkreienbuehl** [comment]
I'm sorry, was very busy. I tried to rebase, but as I see the section to set `envsFromFiles` is missing now.

**Comment by leosvelperez** [comment]
@rkreienbuehl I tried to rebase this, but I got some weird issues while doing so. I'll close this in favor of #6453.

Thanks for contributing!

**Pull request closed without merging**
