### PR TITLE
feat(angular): add support for angular v19

### LINKED ISSUE #29028: Support for Angular 19 LTS
### Discussed in https://github.com/nrwl/nx/discussions/29013

<div type='discussions-op-text'>

<sup>Originally posted by **MGREMY** November 20, 2024</sup>
I could be great to have support for the new angular version
image
</div>

### PR DESCRIPTION
**Pull request by leosvelperez**
## Third-party deps support for Angular v19

- [x] `jest-preset-angular`
  - [x] PRs:
    - [x] https://github.com/thymikee/jest-preset-angular/pull/2835
  - [x] Released:
    - [x] RC: https://github.com/thymikee/jest-preset-angular/releases/tag/v14.4.0-rc.0
    - [x] Stable: https://github.com/thymikee/jest-preset-angular/releases/tag/v14.4.0
- [x] Angular ESLint
  - [x] PRs:
    - [x] https://github.com/angular-eslint/angular-eslint/pull/2109
  - [x] Released:
    - [x] https://github.com/angular-eslint/angular-eslint/releases/tag/v19.0.0
- [x] Storybook
  - [x] PRs:
    - [x] https://github.com/storybookjs/storybook/pull/29659
    - [x] https://github.com/storybookjs/storybook/pull/29677
  - [x] Released:
    - [x] https://github.com/storybookjs/storybook/pull/29679
- [ ] NgRx
  - [x] PRs:
    - [x] https://github.com/ngrx/platform/pull/4602
  - [ ] Released:
    - [x] Beta: https://github.com/ngrx/platform/blob/main/CHANGELOG.md#1900-beta0-2024-11-20
    - [ ] Stable:
- [ ] Analog
  - [x] PRs:
    - [x] https://github.com/analogjs/analog/pull/1447
    - [x] https://github.com/analogjs/analog/pull/1451
  - [ ] Released:
    - [x] Beta: https://github.com/analogjs/analog/releases/tag/v1.10.0-beta.6
    - [ ] Stable:

## Current Behavior

Angular v19 is not supported.

## Expected Behavior

Angular v19 should be supported.

## Related Issue(s)

 
Fixes #29028

### CODE REVIEW

**Review by Coly010 — APPROVED** [review]
It's so nice to see the ng-packagr adjustments removed

**Comment by DaSchTour** [comment]
I wouldn't have expected that many changes. Nice to see that this is already prepared. Thanks for the great work 💪🏼

**Comment by kbrilla** [comment]
Eslint alpha with Angular 19: 
```
    "@angular-eslint/builder": "^19.0.0-alpha.4",
    "@angular-eslint/eslint-plugin": "^19.0.0-alpha.4",
    "@angular-eslint/eslint-plugin-template": "^19.0.0-alpha.4",
    "@angular-eslint/schematics": "^19.0.0-alpha.4",
    "@angular-eslint/template-parser": "^19.0.0-alpha.4",
```

**Comment by friedhelm-youniverse** [comment]
I think eslint is ready as well: https://github.com/angular-eslint/angular-eslint/releases/tag/v19.0.0

**Review by FrozenPandaz — APPROVED** [review]
Please add a migration to disable the now enabled by default preferStandalone rule.

**Comment by robertIsaac** [comment]
when is that planned to be released?

**Comment by PieterjanDeClippel** [comment]
image

**Comment by dguisinger** [comment]
They just merged and deleted the feature branch not more than 4 hours ago.  I'm sure its coming soon.

**Comment by robertIsaac** [comment]
I'm not pushing anyone for anything, it's a benign question :)

**Comment by woppa684** [comment]
After migrating to 20.2.0-beta.5:

image

**Comment by Marat-Gumerov** [comment]
> Curious what the nx protocol is with new versions of _insert framework here_. With angular, there are a bunch of release candidates and beta builds available prior to the GA release. I would assume nx would have no problem pushing out support for version x within a day or two of the GA release. But, angular was released on November 19th and nx hasn't pushed anything angular 19 related out yet.
> 
> Is there a doc for "response time" with new releases? I fully understand each release differs in complexity given what features/changes are shipped with it. just seems between the the release candidates and beta builds there would be ample time to get something going that releases within a day or two of when the framework gets released.

I think that the answer is in the pull request description. We are waiting for corresponding releases of NgRx and Analog right now

**Comment by lppedd** [comment]
Can I stay on Angular 18.x with Nx 20.2.X?  
I'd like to update Nx, but not Angular ATM.

**Comment by bohoffi** [comment]
> Can I stay on Angular 18.x with Nx 20.2.X? I'd like to update Nx, but not Angular ATM.

Yes this should be possible as of [Interactively opting out of package updates](https://nx.dev/recipes/tips-n-tricks/advanced-update#interactively-opting-out-of-package-updates)

**Comment by isaacplmann** [comment]
The latest version of Nx supports the [actively supported versions of Angular (current and LTS versions)](https://angular.dev/reference/releases#actively-supported-versions).

From: https://nx.dev/nx-api/angular/documents/angular-nx-version-matrix

This docs page has already been updated on `master` to show that the latest version of Nx supports back to Angular 17.0.0.

See: https://canary.nx.dev/nx-api/angular/documents/angular-nx-version-matrix

**Comment by marc-wilson** [comment]
> > Curious what the nx protocol is with new versions of _insert framework here_. With angular, there are a bunch of release candidates and beta builds available prior to the GA release. I would assume nx would have no problem pushing out support for version x within a day or two of the GA release. But, angular was released on November 19th and nx hasn't pushed anything angular 19 related out yet.
> > Is there a doc for "response time" with new releases? I fully understand each release differs in complexity given what features/changes are shipped with it. just seems between the the release candidates and beta builds there would be ample time to get something going that releases within a day or two of when the framework gets released.
> 
> I think that the answer is in the pull request description. We are waiting for corresponding releases of NgRx and Analog right now

Yea, but that's _this_ PR. I'd like to understand what the overall process is. Having NgRx hold up a release is odd... not everyone uses NgRx with Angular so it's wierd to hold a core component (angular) up because of an unrelated dependency (NgRx). Obviously, if you have NgRx in your angular app, you're not going to get too far in the upgrade path since NgRx and Angular have compatibility requirements.

I'm about a year into using Nx and like it for the most part. However, I am not a fan of an unrelated thing blocking an upgrade path of a regular app. If we migrate to a new angular version and some crazy bug was found, not only do we have to wait on Angular to push out a fix, we have to wait on Nx to push out of a fix, for a fix. Understanding how they prioritize versions and decide how quick they work on it would be great information.

**Pull request merged**
