### PR TITLE
style(schematics): add empty line after imports

### LINKED ISSUE #614: Empty line after imports
[V] Enhancement

Please add empty line after imports in new generated libs' modules. (`ng g lib`)
Currently its added without.

 
image

### PR DESCRIPTION
**Pull request by cristianmartinez**
fix #614

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
@cristianmartinez Everything looks good, just change your commit message so it does not start with a capital character.

ex. `style(schematics): add empty line after imports`

**Comment by cristianmartinez** [comment]
Then will need a new pull request, it's that right?

**Comment by FrozenPandaz** [comment]
@cristianmartinez You can do:
```sh
git commit --amend -a
(change the message)
git push -f
```

**Comment by cristianmartinez** [comment]
@FrozenPandaz Thank you for your help! I just changed my commit message.

**Pull request merged**
