### PR TITLE
fix(storybook): add staticDirs object schema

### PR DESCRIPTION
**Pull request by leon**
Storybook has renamed staticDir to staticDirs.

The have also added a way to specify an object:
```
module.exports = {
  staticDirs: [{ from: '../my-custom-assets/images', to: '/assets' }],
};
```

This PR adds the schema for staticDirs, and x-deprecates staticDir.
I don't know if we should do this, because they just fallback if they find staticDir

https://github.com/storybookjs/storybook/blob/92b23c080d03433765cbc7a60553d036a612a501/lib/core-server/src/utils/server-statics.ts#L30

## Background
I needed to copy multiple directories and rename them.
the current string[] makes this impossible.

## Questions

* Should we deprecate `staticDir`?

### CODE REVIEW

**Comment by ChazUK** [comment]
Would be nice if this went in as they have added features that would be nice to use in the storybook executor

**Comment by mandarini** [comment]
Hi all! @leon sorry for some reason I just saw this. Can you please rebase and push again, and I will approve!

**Comment by ChazUK** [comment]
@leon I think the staticDirs can also take a plain string instead of the `{ from: '', to: ''}` pattern. https://storybook.js.org/docs/react/configure/images-and-assets#serving-static-files-via-storybook-configuration

**Comment by leon** [comment]
@ChazUK Yes, this is accounted for by having the "oneOf" here
https://github.com/leon/nx/blob/fix/storybook-static-dir-object-schema/packages/storybook/src/executors/storybook/schema.json#L166

**Comment by ChazUK** [comment]
My bad, missed that line, thank you!

**Review by mandarini — APPROVED** [review]

**Comment by ChazUK** [comment]
@mandarini I've noticed the build has not passed, will this effect the auto-merge?

**Comment by leon** [comment]
@mandarini I don't know why my PR didn't want to build.
I tried pushing to the branch to trigger a new build, but now it says the auto merge has been disabled.
so you will have to have a look at it :)

let me know if you want me to do something.

**Comment by mandarini** [comment]
Hi there @leon ! Can you please try to rebase and push once again? If it fails again, I'll do it, and hopefully all will be ok!

**Comment by leon** [comment]
Yeey 🥳🙌

**Comment by iamrommel** [comment]
This thing breaks my storybook. The storybooks even encourage the use of main.js for staticDirs and deprecated the CLI
image


Currently I'm using the main.js for my staticDirs, but it got conflicts with the project.json storybook config
image

**Comment by mandarini** [comment]
Ooops! Thanks @iamrommel ! @leon do you want to look into this? Or should I?

**Comment by leon** [comment]
@mandarini @iamrommel


When I did the PR it was only to fix that you could not pass along multiple strings via the nx storybook plugin.

It's up to you to choose where you want to add the staticDirs setting.

the reason for nx having the option in their config, is so you can have multiple configurations and setup different staticDirs depending on stage, prod environments.

but I generally think it's better to keep it as close to the authors standard as possible, because their documentation is often better kept.

So to your problem.
just choose where you want to add it and remove it from the other place and you will be fine 👍🏻

**Comment by iamrommel** [comment]
I chose to add it on the main.js, and as you can see from the project.json
(as shown from the previous image), there is nothing there defined about
staticDirs, but still I have issues. It was working fine on 13.8.5 and not
on 13.8.7

*Rommel C. Manalo*

**Comment by vrady** [comment]
@leon 

The same happens for me.
Property `staticDir` is always empty array
So storybook checks for deprecated and new properties from config, and deprecated field always return true in this if statement (empty array is not false)

image

When I trying to pass `null` in `project.json` for deprecated field, the executor pass default value (empty array)

So its impossible to use not deprecated filed `staticDirs`, cause deprecated field `staticDir` always return true in if statement

image


Please fix it

**Pull request merged**
