### PR TITLE
feat(js): support wildcard/nested tsconfig paths

### LINKED ISSUE #11050: TypeScript build fails when using wildcard in tsconfig paths
## Current Behavior
I've created a project following the [NX and TypeScript setup guide](https://nx.dev/getting-started/nx-and-typescript). I added an application using the `nx generate @nrwl/node:app demoapp` command, and kept the package that was initially there. I also converted the library to using SWC as the compiler with the `nx generate @nrwl/js:convert-to-swc --name=hello-tsc` command, and then i copied over the `executor` to my application so it also uses SWC.

My `tsconfig.base.json` file has the following `paths` configuration:

```json
{
    "paths": {
      "@nx-and-ts/hello-tsc": ["packages/hello-tsc/src/index.ts"],
      "@nx-and-ts/hello-tsc/*": ["packages/hello-tsc/src/*"]
    }
}
```

My application entry file has the following content

```ts
import { helloTsc } from '@nx-and-ts/hello-tsc/lib/hello-tsc';

console.log(helloTsc());
```

Now when i run `nx build demoapp`, i see the following error message:

Screenshot 2022-07-07 at 11 17 36

The weird thing is that i can build if i only use the entry import `@nx-and-ts/hello-tsc`, but using any imports that match the wildcard path does not work. It seems like the compiler does not understand my paths config from the `tsconfig.base.json` file.

## Expected Behavior
Project should build normally.

## Steps to Reproduce
I've created a minimal repro that will trigger the error explained above: 
- https://github.com/MathiasWP/nx-and-typescript-compilation-bug

### Failure Logs
```
Compiling TypeScript files for project "demoapp"...
apps/demoapp/src/main.ts:1:26 - error TS2307: Cannot find module '@nx-and-ts/hello-tsc/lib/hello-tsc' or its corresponding type declarations.

1 import { helloTsc } from '@nx-and-ts/hello-tsc/lib/hello-tsc';

 >  NX   Ran target build for project demoapp and 1 task(s) it depends on (3s)
 
    ✖    1/2 failed
    ✔    1/2 succeeded [0 read from cache]
```
### Environment
```
Node : 16.15.1
   OS   : darwin x64
   npm  : 8.13.1
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by SeanSanker**
## Current Behavior

Path references in the `tsconfig.base.json` file do not support nested references or wildcards.  
This is due the current logic stripping the references and overwriting them with the `dep.outputs` array.

If you attempt to configure a wildcard path like so:
```json
{
    "paths": {
      "@nx-and-ts/hello-tsc": ["packages/hello-tsc/src/index.ts"],
      "@nx-and-ts/hello-tsc/*": ["packages/hello-tsc/src/*"]
    }
}
```
Then reference it from a project: 
```ts
import { helloTsc } from '@nx-and-ts/hello-tsc/lib/hello-tsc';

console.log(helloTsc());
```
When the project is built, the following error will be emitted:
> Cannot find module '@nx-and-ts/hello-tsc/lib/hello-tsc' or its corresponding type declarations.

## Expected Behavior

Nested/wildcard references should work identically to the top-level package references and should build without error.

## Related Issue(s)

Fixes #11050
Related #1223
Related #10082

## Note
This is my first time contributing to `nx`, if I did anything wrong here or missed any steps please let me know and I'll update the PR. 

Thank you!

### CODE REVIEW

**Comment by namdien177** [comment]
Waiting for this to be merged. Importing all to a single `index.ts` file is just too burdensome for large libraries.

**Comment by nartc** [comment]
@SeanSanker hey, thanks for the PR. Can we add an e2e test for this?

**Comment by udnes99** [comment]
Amazing! 👏 This would make Nx viable for us :)

**Comment by namdien177** [comment]
please active again author

**Comment by rafael-g-depaulo** [comment]
This is amazing! One my biggest gripes with how Nx libraries work was the lack of wildcard imports. If this PR is merged, my DX will skyrocket! Thank you, author

**Comment by nartc** [comment]
Since the PR author hasn't been active for the past 2 weeks, I'll try to add some e2e tests to this PR. Thank you for your patience everyone

**Comment by SeanSanker** [comment]
Whoops! Sorry everyone! 

I've had a tight deadline to meet for my job and wasn't able to get back to this sooner.
In the future I'll make this clear by updating the thread with my status 😅 

@nartc 
If you haven't already taken care of it, I'm more than happy to implement the tests.
Would you mind giving some guidance on what those tests would look like and where they would go?
My main inhibitor here is that I'm not too familiar with this codebase.

I assume they'd belong here? 
https://github.com/nrwl/nx/blob/master/e2e/js/src/js.test.ts

For the implementation, I'd:
1. run the generators to create a project
2. modify the `tsconfig.base.json` to reference wildcard paths with `updateJson`
3. run a library generator
4. add some source files with `updateFile` 
5. run the build and confirm the source compiles? (something like)

```js
expect(runCLI(`build ${lib}`)).toContain(
  'Successfully compiled: 2 files with swc'
);
```

I'll try to keep up with my PRs in the future!

**Comment by nartc** [comment]
@SeanSanker Hi Sean, thank you for reporting back. I haven't started but I have some free-time carved out for this PR so I'm going to write the test based on your implementation. Will be updating the PR soon

**Pull request merged**
