### PR TITLE
fix(nx): parse schema boolean properties as booleans for workspace-sc…

### LINKED ISSUE #1952: Nx does not respect types defined in schema.json
## Expected Behavior

Running a custom schematic using `npm run workspace-schematic -- custom-schematic --routing false` with a schema.json of
```
{
  "$schema": "http://json-schema.org/schema",
  "id": "custom-schematic",
  "type": "object",
  "properties": {
    "routing": {
      "type": "boolean",
      "description": "Add routing",
      "default": true
    }
  },
  "required": ["routing"]
}
```
should run without error.

## Current Behavior

The schematic fails with error:
```
Error: Schematic input does not validate against the Schema: {blah-blah}
Errors:

  Data path ".routing" should be boolean.
```

### Steps to Reproduce

Create a custom schematic that has a boolean property that defaults to true and overwrite the property to false on the command line.

### Context

The AngularCLI implements its own parser for command line inputs. Nx uses `yargs` and the handoff the the parsed `yargs` args to the AngularCLI for running schematics does not mesh well. The reason the schematic fails is the `routing` boolean is parsed as `'false'`, a string rather than a boolean.

This can be remedied by always having boolean properties default to `false` in the schema.json and passing just the flag i.e. `npm run workspace-schematic -- custom-schematic --routing`, but this is limiting. This problem compounds if schematic schemas are more complex. For example, it is not possible to pass an array without comma delimiting it and splitting the string.

The boolean problem can be fixed by reading the schema.json associated with the schematic being run and adding the properties with `type === boolean` to the `yargs-parser` config seen [here](https://github.com/nrwl/nx/blob/1c7b8dce8ce469e8aff3cea665428b047a540cd1/packages/workspace/src/command-line/workspace-schematic.ts#L338). This isn't a perfect solution, but building an equivalency between nx and the angular cli is a bit involved.

Let me know what you think. I can submit a PR fixing the boolean problem.

### PR DESCRIPTION
**Pull request by ZachJW34**
fix #1952

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you for the PR! 

This is a good change, but even thought it's a bug fix, I think it can break existing workspace schematics. If an existing workspace schematic has a "boolean" field, right now it will be a string, whereas with this change it will be a boolean.

Maybe we can add a migration that will scan existing workspace schematics, check if they have boolean flags, and if they do, will print something like that:

```
WARN: This release fixes an issue with workspace schematics where boolean values were treated as strings. See here for more info: LINK_TO_ISSUE. We noticed that you have the following workspace schematics have boolean fields. 

- tools/schematics/blah
- tools/schematics/blah2 

Review the schematics to make sure they will work with boolean values.
```

You can use this as a start for the migration:

```

export default function () {
  return (host: Tree) => {
    const schematicsWithBooleans = [];
    host.visit(path => {
      if (! path.startsWith('tools/schematics')) return;
      if (path.endsWith('schema.json')) {
        const json = host.read(path).toJSON();
        // scan for all boolean fields
        if (hasBoolean) {
          schematicsWithBooleans.push(path)
        }
      }
    })
  };
}
```

**Comment by ZachJW34** [comment]
I'm not against adding the migration script (It would be a good learning process for me), but I'm a bit unsure if this change would indeed break existing schematics since the angular cli would throw an error if the schema couldn't be validated. Currently, there is no way to pass in a boolean into an nx workspace schematic without either:
* Defaulting the boolean property in the schema
* Passing _only_ the flag i.e `--flag` rather than `--flag true`
If you can give an example of a schematic that would break due to this change than I'll update the PR.

**Comment by vsavkin** [comment]
oh I see. I thought that passing `--flag true` will work and the schematic will receive `"true"` as a string. You are right. It isn't a breaking change.

**Comment by vsavkin** [comment]
@ZachJW34 thank you!

**Pull request merged**
