### PR TITLE
fix(nx): Correct path of TSLint config. Fixes #1435

### LINKED ISSUE #1435: @nrwl/workspace - library creates TSLint config path with double slash
This is minor problem. Running `@nrwl/workspace - library` schema generates a TSLint path with double slashes. 

Template:
https://github.com/nrwl/nx/blob/master/packages/workspace/src/schematics/library/files/lib/tslint.json#L2

# Prerequisites
n/a
## Expected Behavior

The path within library `tslint.json` should not contain double slash

```json
{
  "extends": "../../tslint.json",
  "rules": []
}
```

## Current Behavior

The path contains double slash:

```json
{
  "extends": "../..//tslint.json",
  "rules": []
}
```

## Failure Information (for bugs)

n/a, minor issue

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run `@nrwl/workspace - library` to get TS only library
2. open library `tslint.json` file

### Context

- version of Nx used:  8.1.0
- version of Angular CLI used: 8.0.1
- `angular.json` configuration: n/a
- version of Angular DevKit used: n/a
- 3rd-party libraries and their versions: n/a
- and most importantly - a use-case that fails: n/a

### Failure Logs

n/a

## Other

Mac OS, *nix based file system

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This change:
- fixes path in TSLint config template
- add tests coverage for creation and content of the library
`tslint.json` configuration file

Thanks!

Fixes #1435

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
Changes look good!

Your commit message should not start with a capital:

`fix(nx): correct path of tslint config.`

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Please amend comment

**Comment by peterblazejewicz** [comment]
> Please amend comment

Done, thx!

**Comment by FrozenPandaz** [comment]
Sorry one more thing. Please run `yarn format` to format the code.

**Comment by peterblazejewicz** [comment]
@FrozenPandaz 
Obviously, my fault. Done, squashed. Sorry for inconvenience!

**Comment by FrozenPandaz** [comment]
You seem to be having some `git` issues so I fixed it here: https://github.com/nrwl/nx/pull/1451

In the future, if you need to reformat you can do the following:

```sh
yarn format
git status
git commit --amend -a
git push -f
```

**Comment by peterblazejewicz** [comment]
closing in favour of #1451

**Pull request closed without merging**
