### PR TITLE
fix(schematics): app generator tsconfig types iterable error

### PR DESCRIPTION
**Pull request by NathanWalker**
## Description

App generator will fail under some circumstances due to tsconfig setup.

## Issue

Generating an `app` would error with the following when the tsconfig did not contain any `compilerOptions.types` property:
```
compilerOptions.types is not iterable
```

I went ahead and updated the other locations that could fall victim as well.

/cc @FrozenPandaz

### CODE REVIEW

**Review by FrozenPandaz — APPROVED** [review]
These changes look fine. Just curious, when did you run into this?

**Comment by NathanWalker** [comment]
I had run ng add into an angular project (was an older project) to add Nx and then had run the generator.

**Comment by FrozenPandaz** [comment]
Cool, can you run `yarn format` and rebase the PR please?

**Comment by NathanWalker** [comment]
@FrozenPandaz formatted and rebased now 👍

**Pull request merged**
