### PR TITLE
Add throw of error if a dependency is not in the graph.

### PR DESCRIPTION
**Pull request by richtera**
Ref https://github.com/nrwl/nx/issues/11077

Add error throw in the case a dependency is not found in the project graph.

NOTES:
For some reason the azure CI config scripts fail because of master vs main base branch; I didn't change any of that.
I executed jest with -u to update some of the snapshots, but I wasn't sure if that's something to do as part of a PR or not. It seems someone was running -u with the main branch being main and not master like on github.

image

Various other tests also fail
image
There is no /root/dist/apps folder under normal circumstances and definitely not user read/writable.

Creating a folder at /root/dist/apps and chmod each segment to 0777 does work.

### CODE REVIEW

**Comment by richtera** [comment]
For some reasons there are access denied errors on the agent builds other than macOS.

**Comment by richtera** [comment]
What happened to this pr? These builds are failing because of some permission issue it seems.

**Comment by richtera** [comment]
Is there something I can do to have this go anywhere?

**Review by AgentEnder — APPROVED** [review]

**Comment by AgentEnder** [comment]
Applying in #11652, since I don't have permissions to push changes to fork and some were required for CI to pass.

**Pull request closed without merging**
