### PR TITLE
chore(misc): wip to test out bun in e2e tests

### PR DESCRIPTION
**Pull request by jaysoo**
Throwaway branch to test Bun in e2e tests.

### CODE REVIEW

**Comment by Jordan-Hall** [comment]
Have you tired using https://github.com/oven-sh/setup-bun

**Comment by jaysoo** [comment]
> Have you tired using https://github.com/oven-sh/setup-bun

It was just easier to `npm i -g bun` since this is on Nx agents, not GitHub Actions.

**Comment by Jordan-Hall** [comment]
Fair enough in the github action generator I'm using oven setup. For the others it's npm I g bun. Should this be changed to npm install

**Comment by jaysoo** [comment]
Summarized failures here: https://github.com/nrwl/nx/pull/25112

Majority of e2e tests are passing, and the failures are mostly due to us not supporting pruned`bun.lockb`. Could do a follow-up on whehter we should generate `yarn.lock` file instead for Bun. 

The [PR](https://github.com/nrwl/nx/pull/22602) is good to merge IMO, will sync with @FrozenPandaz on it.

**Pull request closed without merging**
