### PR TITLE
fix(core): remove duplicate `js-yaml` packages

### PR DESCRIPTION
**Pull request by Phillip9587**
## Current Behavior

`nx` package depends on both `js-yaml` and `@zkochan/js-yaml`

## Expected Behavior

`nx` should only depend on one of the both

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by meeroslav** [comment]
Thank you @Phillip9587 for this PR. 

The two failing lint tasks are related to a limitation in the `dependency-checks` rule. Can you please add `js-yaml` to the list of `ignoredDependencies` in the corresponding `.eslintrc.json`, and we will address that issue separately?

You also need to rebase with the latest pnpm-lock file changes.

**Review by meeroslav — CHANGES_REQUESTED** [review]
The `dependency-checks` rule is failing with alias dependencies. This should be resolved elsewhere.

Just include the override in the `ignoredDependencies` to get this PR over the line and we will address this issue separately.

**Comment by Phillip9587** [comment]
@meeroslav Done. I created #23469 to track the issue with the lint rule

**Review by meeroslav — APPROVED** [review]

**Comment by meeroslav** [comment]
Thank you! Merging it in as soon as the build it green.

**Comment by Phillip9587** [comment]
@meeroslav CI is finally green

**Review by leosvelperez — APPROVED** [review]

**Review by JamesHenry — APPROVED** [review]

**Comment by nzacca** [comment]
@Phillip9587 

Hello! May I inquire why Nx is using the package from zkochan vs the official package?

We are using `js-yaml` directly in our project but this change is now causing a conflict as it expects zkochan's package as a peer dependency. I can't seem to find the actual source for the zkochan package to compare what is different to assess if it is OK to change.

Any insight for the differences would be appreciated! Thank you!

**Pull request merged**
