### PR TITLE
feat(storybook): add html to supported 6.2 uiFrameworks

### PR DESCRIPTION
**Pull request by spaceribs**
## Current Behavior
Attempting to use `@storybook/html` as a framework fails

## Expected Behavior
`@storybook/html` builds and serves correctly

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by spaceribs** [comment]
I could also solve this via a default path for anything that doesn't match the major supported storybook renderers, let me know if you guys think that's a good idea.

**Comment by corysmc** [comment]
Would love to see this merged. I just ran into this same issue today as I'm using stencil in nx and want to get storybook running 👍 this PR fixes it

**Comment by DominikPieper** [comment]
I’d love to see this merged for the same reason like @corysmc. This would really helpful

**Comment by juristr** [comment]
Sorry I totally missed this one. Going to have a look at this today/tomorrow.

**Comment by mandarini** [comment]
Hi @spaceribs, Thanks for this PR! 

I tested it locally, and it works. I'll approve it, because it looks good and it's not breaking any existing functionalities. However, one should configure a `@storybook/html` project manually, on their own, if they want it to work, since we only support generators for `@storybook/react` and `@storybook/angular`. 

I know you know, I am just adding this comment here as a disclaimer. So, one would have to add their own Storybook configuration and write their own stories, and add the `storybook` and `build-storybook` targets for the desired projects manually in their `workspace.json`.

**Comment by spaceribs** [comment]
@mandarini makes sense! If it does make sense to lock that down more, I noticed that the `schema.json` accepts a string rather than an enum, as does the `schema.d.ts`. Right now the error for using any generators outside the described set returns a very mysterious/hard to debug error.

**Comment by DominikPieper** [comment]
Except the story Generation it shouldn’t be to hard to add the storybook/html Module to the project generator. The init generator already accept it

**Comment by mandarini** [comment]
@spaceribs Which `schema.json` file are you referring to? And what does the error look like, how could I reproduce? We could fix it, I think! :)

**Comment by spaceribs** [comment]
@mandarini see the linked bug for the error message and current behavior: https://github.com/nxext/nx-extensions/issues/241

here are the schema configs as they exist right now: https://github.com/nrwl/nx/blob/master/packages/storybook/src/executors/storybook/schema.json#L8
https://github.com/nrwl/nx/blob/master/packages/storybook/src/executors/storybook/storybook.impl.ts#L18

I'd agree with @DominikPieper though, I think we'll see other cases including Vue, web-components, Svelte come out of the woodwork in the coming weeks.

**Comment by DominikPieper** [comment]
@spaceribs & @mandarini  maybe an other solution could be make the serverOptionPaths external configurable. The old executor/builder was to be able to run the html storybook configuration without a problem, but the uiFrameworks wasn’t needed for the executor. If you’re able to set that option it should be able to run all storybook configurations as well I think

**Comment by spaceribs** [comment]
@DominikPieper it's not a bad idea! I think what @mandarini was mostly concerned about was the ever expanding list of rendering frameworks the storybook plugin would need to support, and what testing/supporting that integration would look like moving forward. If that's the problem, I think it might make more architectural sense to split up the renderers and their associated configs into their own plugins that call this plugin.

Definitely more work but there are obviously some things that are framework specific and some that are global?

**Comment by DominikPieper** [comment]
@spaceribs I understand the problem with that. Maybe a hybrid solution, officially supported list of plugins and be able to extend  the static list with a note that other storybook packages are not official supported? 🤔 not sure what’s the best solution here

**Pull request merged**
