### PR TITLE
fix(node): allow use multiple config in custom webpack configuration file

### LINKED ISSUE #9453: @nx/node:webpack Cannot export multiple configurations
## Current Behavior
Assigning a custom webpack configuration file does not support the ability to use multiple configurations, as webpack allows.

## Expected Behavior
Being able to define multiple configurations in my custom webpack.config.ts file to feed to webpack.

## Steps to Reproduce

1. set a custom webpack config option in build target options on project.json.
```
  "targets": {
     "build": {
       "executor": "@nrwl/node:webpack",
       "outputs": ["{options.outputPath}"],
       "defaultConfiguration": "production",
       "options": {
        ...
         "webpackConfig": "apps/app-name/webpack.config.ts"
       },
```
3. define custom webpack configuration.
```js
  // ...
  module.exports = (config: Configuration, context: any) => {
     const firstConfig= {
         // ...
         output: {
             path: 'path',
             libraryTarget: 'amd',
             //...
         },
         // ...
     }
     const secondConfig= {
         // ...
         output: {
             path: 'other/path',
             libraryTarget: 'commonjs',
             //...
         },
         // ...
     }
     return [firstConfig,secondConfig];
  }
  // ...
```
5. Run nx run app-name:build

### Failure Logs
```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property '0'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
   -> Options object as provided by the user.
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           0: …
         }
       })
     ]
```
### Environment
```
   Node : 14.18.0
   OS   : win32 x64
   npm  : 8.5.3

   nx : 13.8.6
   @nrwl/angular : 13.8.6
   @nrwl/cli : 13.8.6
   @nrwl/cypress : 13.8.6
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.6
   @nrwl/eslint-plugin-nx : 13.8.6
   @nrwl/express : undefined
   @nrwl/jest : 13.8.6
   @nrwl/js : 13.8.6
   @nrwl/linter : 13.8.6
   @nrwl/nest : 13.8.6
   @nrwl/next : undefined
   @nrwl/node : 13.8.6
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.6
   @nrwl/tao : 13.8.6
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.6
   typescript : 4.4.4
   rxjs : 7.5.5
```
## Remark
The issue is very similar to the one that was resolved by @sidmonta on the web executor (#9188 , #9186)

### PR DESCRIPTION
**Pull request by sidmonta**
When use a custom configuration file for node webpack build target. 
Allow running webpack with multiple configuration options.

## Current Behavior
Assigning a custom webpack configuration file does not support the ability to use multiple configurations, as webpack allows.

## Expected Behavior
Being able to define multiple configurations in my custom webpack.config.ts file to feed to webpack
## Related Issue(s)

Fixes #9453

### CODE REVIEW

**Comment by everops-kalarrs** [comment]
Just noticed this will be a conflict with my PR which introduces async for custom configurations. 
#9641

@sidmonta maybe we can combine these?

**Comment by sidmonta** [comment]
Hi @everops-kalarrs, thanks for the heads up. I saw your pull request and maybe I missed something, but I don't see any functional conflicts. The only change I made in the part that you also changed concerns the specification of the Config type which in both cases remains the same.

So definitely we can combine the changes, it should be enough either on my end to remove the specification or on your end to add it.

If I missed something, sorry, and report it to me without any problem.

**Comment by nartc** [comment]
@sidmonta I think something's up with this PR. It shouldn't be 1000+ files changed should it?

**Comment by sidmonta** [comment]
Hi @nartc, you're right, I messed up by not making a separate branch. I close this pull request and open another one with only my changes.

**Pull request closed without merging**
