### PR TITLE
feat(repo): replace tslint with eslint in recommended extensions

### LINKED ISSUE #5308: Remove tslint vscode plugin
When generating a new nx workspace a .vscode/extensions.json gets created alongside it with `ms-vscode.vscode-typescript-tslint-plugin` in there.

Nx no longer defaults to tslint but rather uses eslint. Please remove the recommended extension

### PR DESCRIPTION
**Pull request by Ravi-Rajpurohit**
## Related Issue(s)

Fixes #5308

### CODE REVIEW

**Comment by Ravi-Rajpurohit** [comment]
let me know if we should keep the tslint extension as well

**Comment by FrozenPandaz** [comment]
Thank you for the change!

I think it's fine if we remove the `tslint` plugin entirely as it's deprecated.

I think adding the lint plugins should be moved outside of `workspace` and into `@nrwl/linter` actually.

You can do something similar to this:
https://github.com/nrwl/nx/blob/8ad94fa434eeb19fcd84b67acebb0bd90cf50fa3/packages/jest/src/generators/init/init.ts#L78

in this file:
https://github.com/nrwl/nx/blob/8ad94fa434eeb19fcd84b67acebb0bd90cf50fa3/packages/linter/src/generators/init/init.ts#L195

This will make it so that empty workspaces won't recommend the plugin. Until they create a project that uses `eslint` that is. Does that make sense?

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thank you for the change!

I think it's fine if we remove the `tslint` plugin entirely as it's deprecated.

I think adding the lint plugins should be moved outside of `workspace` and into `@nrwl/linter` actually.

You can do something similar to this:
https://github.com/nrwl/nx/blob/8ad94fa434eeb19fcd84b67acebb0bd90cf50fa3/packages/jest/src/generators/init/init.ts#L78

in this file:
https://github.com/nrwl/nx/blob/8ad94fa434eeb19fcd84b67acebb0bd90cf50fa3/packages/linter/src/generators/init/init.ts#L195

This will make it so that empty workspaces won't recommend the plugin. Until they create a project that uses `eslint` that is. Does that make sense?

**Comment by FrozenPandaz** [comment]
@Ravi-Rajpurohit are you able to make the change? If not, I can take over.

**Comment by Ravi-Rajpurohit** [comment]
> @Ravi-Rajpurohit are you able to make the change? If not, I can take over.

@FrozenPandaz just started working on it.

**Comment by Ravi-Rajpurohit** [comment]
@FrozenPandaz let me know if any other change is required.

**Review by FrozenPandaz — APPROVED** [review]
Thanks for making those changes! This LGTM! :tada:

**Pull request merged**
