### PR TITLE
fix(angular): correct typo in NgRx reducer template

### PR DESCRIPTION
**Pull request by cbejensen**
"None" is a type-o and should be "known". This PR fixes that one single word.

### CODE REVIEW

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update the commit message to `fix(angular): correct typo in NgRx reducer template`

**Review by cbejensen — COMMENTED** [review]
Updated commit message.

**Comment by brandonroberts** [comment]
@cbejensen the commit message still looks the same to me. You can see the commit message that gets checked here https://github.com/nrwl/nx/pull/3266/commits

**Comment by cbejensen** [comment]
My bad - please check again now.

**Review by brandonroberts — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @cbejensen!

**Pull request merged**
