### PR TITLE
feat(core): be able to depend on a configuration of a target

### LINKED ISSUE #15064: be able to depend on a configuration of a target
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Right now dependsOn syntax allows to specify only the name of the target. However, there're certain scenarios where it would be beneficial to have an ability to depend on a certain configuration of this target
## Motivation

Consider the following scenario (it is a bit simplified just to get an idea): 
- there's a build target, that should use a certain config based on the configuration
- there're 2 build targets, that use different executors, one of them uses custom logic to run a deployment script, another uses a certain 3rd-party executor

With this setup it is not possible to properly specify the dependsOn, because for `deploy.custom` I need to depend on `myapp:build` and for `deploy.cloudflare` I need to depend on `myapp:build:cloudflare`. Of course, there're several workarounds: 

- I can define an empty configuration `cloudflare` for the `deploy.cloudflare` target, but it will only work if command is run as `nx run myapp:deploy.cloudflare:cloudflare`, because even a default configuration is not inherited by dependant tasks. 
- I can define an intermediate target and depend on it (this is demonstrated in the config sample below with a separate `build-cloudflare` target.

```json
{
    "name": "myapp",
    "projectType": "application",
    "sourceRoot": "apps/myapp/src",
    "targets": {
      "build": {
        "executor": "my-executor",
        "options": {
          "configFile": "apps/myapp/config.ts"
        },
        "configurations": {
          "cloudflare": {
            "configFile": "apps/myapp/config.cloudflare.ts"
          }
        }
      },
      "deploy.custom": {
        "executor": "nx:run-commands",
        "options": {
          "command": "node scripts/deploy.js"
        },
        "dependsOn": ["build"]
      },
      "deploy.cloudflare": {
        "executor": "@k11r/nx-cloudflare-wrangler:deploy-page",
        "options": {
          "branch": "master",
          "projectName": "myapp",
          "dist": "dist/apps/myapp/client"
        },
        "dependsOn": ["build-cloudflare"]
      },
      "build-cloudflare": {
        "executor": "nx:run-commands",
        "options": {
          "command": "npx nx run myapp:build:cloudflare"
        }
      }
    }
  }
 ```
There're some additional arguments mentioned in this discussion https://github.com/nrwl/nx/discussions/9236

## Suggested Implementation

An ideal scenario would be to specify a certain configuration explicitly in the dependsOn
```json
      "deploy.cloudflare": {
        "executor": "@k11r/nx-cloudflare-wrangler:deploy-page",
        "options": {
          "branch": "master",
          "projectName": "myapp",
          "dist": "dist/apps/myapp/client"
        },
        "dependsOn": ["build:cloudflare"]
      },
```

I have even started implementing this, but reached a point where I guess it needs to be discussed. 

The way I'm expecting this to work is:
- If target configuration is explicitly specified, it should be applied to this target and all descendants
- If any further descendant target has another "dependsOn" with explicit configuration, this explicit configuration should override the parent one

The problem is that this approach creates certain ambiguity, because there's a chance that certain target is specified as a dependency of multiple other targets with different configurations. So that dependency map may look like this
```
{
  'app1:build': ['lib1:build:production', 'lib3:build:production'],
  'lib1:build:production': ['lib3:build:ci'],
  'lib3:build:ci': [],
  'lib3:build:production': [],
}
```
Obviously we should avoid the scenario where `lib3:build` is invoked twice with different configurations. I've considered inheriting configuration from the root target and ignore all other occurrences or throwing an error in case such ambiguity is identified, but neither of those seem like a way to go.

So would you consider this functionality as something that is worth adding? If yes, what would be an expected behavior in the scenario described above?

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Current Behavior

Right now dependsOn syntax allows to specify only the name of the target. However, there're certain scenarios where it would be beneficial to have an ability to depend on a certain configuration of this target
## Expected Behavior

See details here https://github.com/nrwl/nx/issues/15064 
## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/15064

### CODE REVIEW

**Review by ZhmenZH — APPROVED** [review]

**Comment by dmitry-stepanenko** [comment]
@vsavkin @FrozenPandaz @AgentEnder @juristr any update on this one?

**Comment by AgentEnder** [comment]
This is made a bit complex by the edge cases when depending on different configurations of the same target etc, I'll talk it over with @FrozenPandaz and see his thoughts.

**Comment by temarusanov** [comment]
hello, any updates here?

**Comment by tnrich** [comment]
@AgentEnder also looking for updates on this one. Seems like an awesome feature to have!

**Comment by SebastianSedzik** [comment]
@AgentEnder @FrozenPandaz Could you share any updates on this? Are you still considering this approach, or is it a no-go, and we shouldn't expect it in future releases? I got pretty confused when `dependsOn: ["build:development"]` didn't work out of the box.
Also, the changes from the pull request are hidden behind the `nx-accept-same-target-variations` flag, so they shouldn't (theoretically) mess up anything in existing projects.

**Comment by illyakaynov** [comment]
Is there any updates on this? Would be very useful!

**Comment by ciriousjoker** [comment]
Can someone review this please?

**Comment by tnrich** [comment]
@vsavkin @FrozenPandaz @AgentEnder @juristr @Cammisuli sorry to spam y'all but can we please get this in?

**Comment by gabrielbryk** [comment]
Would love to see this in the next version, big hassle not having it

**Comment by AgentEnder** [comment]
I hate closing this out after so long, but I believe that its the best next step. Sorry for dragging this out @dmitry-stepanenko - your contributions are appreciated. See more detail in the linked issue, which we are leaving open.

**Pull request closed without merging**
