### PR TITLE
feat(module-federation): use nx run-many to build static remotes in parallel

### PR DESCRIPTION
**Pull request by Coly010**
- feat(angular): use nx run-many to build remotes in parallel
- feat(react): use nx run-many to build remotes in parallel

## Current Behavior

We currently spin up a new forked process for every build of a static remote. This impacts resources and memory consumption when there are a lot of remotes in the workspace.

## Expected Behavior

We should use nx run-many instead to manage parallel builds of static remotes allowing for users to find the perfect number of parallel processes that they can use to build static remotes locally.

## Related Issue(s)

Fixes #

### CODE REVIEW

**Review by ndcunningham — COMMENTED** [review]
Looks fine just not sure what `ANSII_CODE_REGEX` means.

**Review by ndcunningham — APPROVED** [review]
Looks fine just not sure what `ANSII_CODE_REGEX` means.

**Comment by Coly010** [comment]
It's a regex to find the color codes that output certain strings in the terminal in different colors or as bold text. 

They aren't being stripped without that regex and therefore matching strings fails because

`Successfully ran target build` is actually `[32mSuccessfully ran target \u001b[1mbuild`

**Comment by ndcunningham** [comment]
> It's a regex to find the codes that output certain strings in the terminal in different colors or as bold text.
> 
> They aren't being stripped without that regex and therefore matching strings fails because
> 
> `Successfully ran target build` is actually `[32mSuccessfully ran target \u001b[1mbuild` it just gets rendered correctly in the terminal but the raw output contains them, so doing any kind of equality or lookup fails.

**Review by jaysoo — APPROVED** [review]

**Pull request merged**
