### PR TITLE
chore(repo): [ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Message from automatic PR by @imgbot (as seen in https://github.com/MichaelDeBoey/nx/pull/7):

> ## Beep boop. Your images are optimized!
> 
> Your image file size has been reduced by **17%** 🎉
> 
> <details>
> <summary>
> Details
> </summary>
> 
> | File | Before | After | Percent reduction |
> |:--|:--|:--|:--|
> | /nx-logo.png | 27.14kb | 11.97kb | 55.89% |
> | /packages/devkit/src/generators/test-files/image.png | 27.14kb | 11.97kb | 55.89% |
> | /images/nx-logo.png | 27.14kb | 11.97kb | 55.89% |
> | /docs/angular/migration/migration-angularjs-unit-tests-passing.png | 37.40kb | 17.31kb | 53.72% |
> | /docs/shared/ci-graph.png | 178.43kb | 102.85kb | 42.36% |
> | /docs/shared/nest-logo.png | 24.40kb | 15.35kb | 37.09% |
> | /docs/shared/nx-console-screenshot.png | 196.73kb | 125.07kb | 36.43% |
> | /docs/shared/storybook-logo.png | 23.14kb | 14.87kb | 35.73% |
> | /docs/shared/jest-logo.png | 31.65kb | 20.54kb | 35.10% |
> | /images/nx-cloud-card.png | 32.52kb | 21.53kb | 33.79% |
> | /images/nx-angular-video.png | 709.65kb | 480.88kb | 32.24% |
> | /docs/shared/api/cypress.jpg | 93.91kb | 66.36kb | 29.33% |
> | /docs/shared/api/jest.jpg | 97.62kb | 69.18kb | 29.13% |
> | /docs/shared/prettier-logo.png | 22.96kb | 16.65kb | 27.46% |
> | /packages/gatsby/src/generators/application/files/src/pages/star.svg | 0.34kb | 0.25kb | 27.09% |
> | /packages/next/src/generators/application/files/public/star.svg | 0.34kb | 0.25kb | 27.09% |
> | /packages/react/src/generators/application/files/common/src/app/star.svg | 0.34kb | 0.25kb | 27.09% |
> | /docs/shared/api/node.jpg | 123.12kb | 91.25kb | 25.88% |
> | /docs/shared/api/express.jpg | 125.05kb | 92.86kb | 25.74% |
> | /docs/shared/affected.png | 113.26kb | 84.80kb | 25.13% |
> | /images/nx-react-video.png | 222.66kb | 166.96kb | 25.02% |
> | /docs/shared/api/react.jpg | 180.55kb | 135.50kb | 24.95% |
> | /docs/shared/api/nest.jpg | 142.71kb | 107.17kb | 24.91% |
> | /docs/shared/api/angular.jpg | 142.58kb | 107.45kb | 24.64% |
> | /docs/shared/api/web.jpg | 144.25kb | 109.44kb | 24.14% |
> | /docs/shared/dependency-graph.png | 109.07kb | 85.01kb | 22.06% |
> | /images/nx-gatsby.png | 44.33kb | 34.70kb | 21.72% |
> | /images/nx-next.png | 109.37kb | 92.98kb | 14.98% |
> | /docs/react/getting-started/EGH_ScalingReactNx.png | 58.15kb | 49.98kb | 14.06% |
> | /images/nx-react.png | 131.80kb | 113.29kb | 14.04% |
> | /images/how-to-contribute.png | 780.71kb | 678.29kb | 13.12% |
> | /images/nx.png | 245.64kb | 216.19kb | 11.99% |
> | /packages/react/src/generators/application/files/common/src/app/logo.svg | 2.86kb | 2.56kb | 10.68% |
> | /docs/shared/incremental-build-webpack-vs-incremental.png | 13.14kb | 11.88kb | 9.60% |
> | /packages/next/src/generators/application/files/public/nx-logo-white.svg | 2.82kb | 2.56kb | 9.35% |
> | /docs/shared/ci-graph-one-affected.png | 116.22kb | 107.67kb | 7.35% |
> | /docs/shared/ci-graph-everything-affected.png | 106.98kb | 99.17kb | 7.29% |
> | /docs/angular/examples/react-serve.png | 34.36kb | 31.88kb | 7.21% |
> | /packages/gatsby/src/generators/application/files/src/pages/logo.svg | 2.72kb | 2.56kb | 6.13% |
> | /docs/shared/github.png | 280.86kb | 264.04kb | 5.99% |
> | /docs/angular/examples/react-dep-graph.png | 9.71kb | 9.24kb | 4.87% |
> | /docs/angular/examples/react-affected.png | 9.77kb | 9.33kb | 4.50% |
> | /docs/angular/examples/react-affected2.png | 9.68kb | 9.25kb | 4.46% |
> | /docs/angular/getting-started/create-workspace.gif | 1,894.28kb | 1,820.34kb | 3.90% |
> | /docs/shared/all-cache-inputs.png | 32.23kb | 31.18kb | 3.25% |
> | /docs/shared/continue-light.svg | 0.25kb | 0.25kb | 1.16% |
> | /docs/angular/getting-started/dep-graph.png | 134.28kb | 132.97kb | 0.98% |
> | /docs/shared/folder-light.svg | 0.60kb | 0.60kb | 0.49% |
> | /packages/gatsby/src/generators/application/files/src/images/logo.svg | 2.05kb | 2.04kb | 0.38% |
> | | | | |
> | **Total :** | **6,856.90kb** | **5,690.62kb** | **17.01%** |
> </details>
> 
> ---
> 
> **Black Lives Matter** | [💰 donate](https://blm-bookmarks.carrd.co/#donate) | [🎓 learn](https://blm-bookmarks.carrd.co/#learn) | [✍🏾 sign](https://blm-bookmarks.carrd.co/#sign)
> 
> [📝 docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋🏾 issues](https://github.com/dabutvin/ImgBot/issues) | [🏅 swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪 marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by vsavkin** [comment]
Hi there. Thank you for your PR. Could you change the commit message to pass the CI? Thank you!

**Comment by MichaelDeBoey** [comment]
@vsavkin This is an automatic commit by @ImgBotApp, so I'm not in control of it

**Comment by MichaelDeBoey** [comment]
@imgbot rebase

**Pull request closed without merging**
