### PR TITLE
feat(react): add --simpleLintConfig flag to generate only base lint c…

### LINKED ISSUE #2908: feat: @nrwl/react:lib - provide option to skip inlining lint configuration for libraries
# This is a feature request

## Expected Behavior

- provide new cli flag/workspace schematic config to skip emitting inline eslint config for every library

`nx g @nrlw/react:lib react-one --simple-config`
->
```
// .eslintrc
{ "extends": "../../.eslintrc", "rules": {}, "ignorePatterns": ["!**/*"] }
```

## Current Behavior
- every time new library (react/angular) is generated, lint config rules are being added(inlined) every time
image

**Why is this a problem?:**

- while it's true that every lib should exist as isolated entity, there might be usecases that company is using common root eslint config, and various teams are using slight modifications per library if at all

### Context

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : 9.2.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.2
  @nrwl/react : 9.2.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : 9.2.2
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

### PR DESCRIPTION
**Pull request by Hotell**
…onfig

ISSUES CLOSED: #2908

### Additional Notes

- if you're ok with this API I can add this to all other relevant schematics
  - next
  - nest

### CODE REVIEW

**Review by BigAB — APPROVED** [review]

**Comment by jaysoo** [comment]
Hey @Hotell thanks for the PR as always!

I wonder if we should improve the generated eslint config, instead of adding a schematic option. 

If the concern is that the default `.eslintrc` file is large, and needs to be customized anyway, perhaps we can collect the defaults into a `eslint-plugin-nx-react` package and extend from that (rather than inlining rules).

**Review by jaysoo — CHANGES_REQUESTED** [review]
Getting clarity on the problem so we can evaluate the approach.

**Comment by jaysoo** [comment]
Going to close this PR. We will be simplifying the generated eslint configs so they are easiest to customize afterwards.

**Comment by Hotell** [comment]
> perhaps we can collect the defaults into a eslint-plugin-nx-react package and extend from that (rather than inlining rules).

That's definitely better approach than inlining all those rules every time but solves different problem.

I thought the issue that this is closing, is clear enough and describes the use case. Dunno what else you wanted to clarify, if you prefer that contributors should copy paste description from issue to PR I'd recommend to explicitly mention it in contributing guide. Thank you 🙏

**Comment by jaysoo** [comment]
@Hotell We're trying to limit the amount of schematics options, so we would consider it if the workaround or alternative is too hard on the part of the user. In this case I feel like you would create a workspace schematic to empty out the eslintrc file for apps/libs. Maybe we can have a quick chat about this if you want.

**Pull request closed without merging**
