### PR TITLE
feat(angular): support esbuild-based executors/builders in @nx/angular:dev-server

### LINKED ISSUE #20267: feat: ✨ Creating @nx/angular:esbuild-dev-server - Incremental build dev server for esbuild with Angular 17
## Description
With the introduction of Angular 17 and the new default builder: @angular-devkit/build-angular:application, we no longer have an incremental serve story with Nx. If you try to use the webpack-dev-server, you'll see the error:

`NX   The `application` and `browser-esbuild` builders do not support Webpack transforms.`

## Motivation
When using the new esbuild feature from Angular 17 and TailwindCss, it takes us 500+ seconds to start up a large application. When we make a simple code change, it takes 280+ seconds for esbuild to rebuild.

The esbuild build story is GREAT. Working with esbuild and TailwindCSS on a daily basis is a completely different story.

Wondering what's possible here. The current situation is not currently tenable. 

Thoughts from the great Nx Team highly requested 🍺
Bjorn

### LINKED ISSUE #20332: Use vite with Angular
Angular 17 is using vite by default. How can we use it with Nx? including the index transformer. It seems like Angular exposes the API https://github.com/angular/angular-cli/pull/26212/files

### PR DESCRIPTION
**Pull request by leosvelperez**
- Rename `@nx/angular:webpack-dev-server` to `@nx/angular:dev-server`
  - Add migration
- Force the underlying `@angular-devkit/build-angular:dev-server` to use esbuild when the build target executor is `@nx/angular:browser-esbuild`

## Current Behavior

The `@nx/angular:webpack-dev-server` is a webpack-specific executor that doesn't support the esbuild-based executors/builders.

## Expected Behavior

The `@nx/angular:webpack-dev-server` should be renamed to `@nx/angular:dev-server` and support the esbuild-based executors/builders.

## Related Issue(s)

Fixes #20267 
Fixes #20332

### CODE REVIEW

**Review by Coly010 — APPROVED** [review]

**Comment by ArielGueta** [comment]
@leosvelperez thanks for the PR? Two questions:

- It will support the index transformer?
- It will allow passing plugins?

**Comment by leosvelperez** [comment]
> * It will support the index transformer?

Yes.

> * It will allow passing plugins?

Not yet. We'll look into supporting that separately.

Please note the Angular CLI builders only support plugins when consuming the builder programmatically, not when running a target through the CLI. So, with the changes on this PR you'll already have the same functionality the Angular CLI builders have to run your project targets. Later, Nx executors will add on top of that and expose a way to provide plugins in your project target configuration.

**Review by isaacplmann — APPROVED** [review]

**Review by jaysoo — APPROVED** [review]

**Review by FrozenPandaz — APPROVED** [review]

**Comment by ArielGueta** [comment]
@leosvelperez I get a schema error when using  `"executor": "@nx/angular:browser-esbuild"`:

 Data path "" must NOT have additional properties(indexFileTransformer).

If I comment the code in the Angular source code it works. How do we solve it without changing the Angular source code?

**Comment by ArielGueta** [comment]
One more issue when run nx build production:

NX 'indexFileTransformer' is not found in schema

**Comment by ArielGueta** [comment]
I also get warnings:

Project 'ui' contains extension with invalid name ($schema).
Project 'ui' contains extension with invalid name (tags).

**Pull request merged**
