### PR TITLE
[frozen] Angular cli v6 upgrade

### PR DESCRIPTION
**Pull request by nweldev**
**This PR was just a starting point, and was frozen after https://github.com/nrwl/nx/pull/419#issuecomment-382004783**

see https://github.com/nrwl/nx/issues/412 for more informations

### CODE REVIEW

**Comment by vsavkin** [comment]
Thanks for you work on this!

A few notes:
- This is a major upgrade and will probably require a multi-phase rollout. 
- The architect infrastructure (including library support etc) is still in the early preview stage and shouldn't be used. It's going to change a lot in CLI 6.1. So cannot do anything interesting with it right now.

I'm at NgConf where I'm having a few meetings with the CLI team to discuss the best ways to use the CLI 6 features in Nx. I'm going to post a detailed upgrade plan next week.

**Comment by noelmace** [comment]
I'm replacing "WIP" by "frozen", as I'm not working on this PR anymore, given that I haven't any information on the process @vsavkin want to follow. I switched to angular-cli v6 in the meantime. I will now focus on a step by step approach, starting with https://github.com/nrwl/nx/pull/445.

**Comment by vsavkin** [comment]
Really sorry for the late response.

Migrating to CLI6 has a lot of moving parts, so we have been working on it for some time, while talking to the CLI time to make sure we take what is coming next into account. We cut an alpha release yesterday that works on CLI6 (you can install like this `yarn global add @nrwl/schematics@next`), and we will cut a stable release next week.

I really appreciate your trying to help with the development of Nx. Picking up and fixing smaller issues (e.g., https://github.com/nrwl/nx/issues?q=is%3Aopen+is%3Aissue+label%3Apriority) might be a better way to start though.

**Comment by shlomiassaf** [comment]
@noelmace I'm not sure the CLI is there yet...

Library development is there but somewhat limited...

1) It's very hard to tame it to work with sub-packages (e.g. `@angular/common/http`)
2) It does not support (by design) hot library reloading, i.e. it requires re-compiling and building for every change in the lib then reload the demo app.

I have to say, that this no hot rebuild thing for libs (2) will not last long the CLI guys will realise it soon enough :)

There are more things probably, didn't try them all...

@vsavkin When you port, please keep sub-package library support. It works on nx 1+... I hate to see it gone.

Also, forcing upon the developer to compile before being able to run on demo that's a lot of trouble and will not work for most library dev's, it's makes the work triple hard. I don't get it.

I understand the reason behind it but it's not a valid one.

**Comment by noelmace** [comment]
@shlomiassaf about (2), you can see https://github.com/angular/devkit/issues/730. Main issues on this for now compared to Nx is the lake of "internal libraries" (ie without ng-packagr, like the one Nx lib provide), and, you're right, some good way to work with both apps and  libraries. About this, https://github.com/angular/devkit/pull/739 could be a starting point.

About (1), I can't remember any issue with this specific to Angular CLI, as custom tsconfig files support for libraries was added (https://github.com/angular/devkit/pull/750), and ["secondary entry points"](https://github.com/dherges/ng-packagr#secondary-entry-points) support is only brought by ng-packagr. Could you provide some examples ?

**Pull request closed without merging**
