### PR TITLE
fix(linter): use import to check for secondary entrypoint in angular

### LINKED ISSUE #8059: Rule 'enforce-module-boundaries' should not error 'noSelfCircularDependencies' for angular libs with secondary entrypoints
## Current Behavior
When using angular libraries with secondary entrypoints and importing things from another secondary entrypoint of the same library, the eslint rule 'enforce-module-boundaries' errors with the violation 'noSelfCircularDependencies'.

## Expected Behavior
The rule 'enforce-module-boundaries' should not get violated by a secondary entrypoint importing another entrypoints exports, because those are complete independant modules, in theory.

## Steps to Reproduce
See PR [in https://github.com/nrwl/nx-examples.](https://github.com/nrwl/nx-examples/pull/179)

Basic steps for reproduction:
1. Generate angular library (Note that it has to generate a package.json and allow secondary entrypoints)
nx generate @nrwl/angular:library --name=example-lib --importPath=@example/lib --publishable

2. Generate two secondary entrypoints for library (models/abstract and models/implementations)
nx generate @nrwl/angular:library-secondary-entry-point --name=models/abstract --library=example-lib --skipModule
nx generate @nrwl/angular:library-secondary-entry-point --name=models/implementations --library=example-lib --skipModule

3. Create some exported file in first entrypoint. Example example-model.ts:

```typescript
export interface ExampleModel {
  someField: string;
}
```

4. Use exported file in second entrypoint:

```typescript
import {ExampleModel as IExampleModel} from '@example/lib/models/abstract';

export class ExampleModel implements IExampleModel {
  someField!: string;
}
```

5. Second file in secondary entrypoint should get a linting error

### Failure Logs
ESLint: Projects should use relative imports to import from other files within the same project. Use &quot;./path/to/file&quot; instead of import from &quot;@example/lib/models/abstract&quot; (@nrwl/nx/enforce-module-boundaries)

image

### Environment
```

>  NX  Report complete - copy this into the issue template

  Node : 14.17.6
  OS   : win32 x64
  yarn : 1.22.15

  nx : 13.2.0-rc.4
  @nrwl/angular : 13.2.0-rc.4
  @nrwl/cli : 13.2.0-rc.4
  @nrwl/cypress : 13.2.0-rc.4
  @nrwl/devkit : 13.2.0-rc.4
  @nrwl/eslint-plugin-nx : 13.2.0-rc.4
  @nrwl/express : undefined
  @nrwl/jest : 13.2.0-rc.4
  @nrwl/linter : 13.2.0-rc.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : 13.2.0-rc.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.0-rc.4
  @nrwl/web : 13.2.0-rc.4
  @nrwl/workspace : 13.2.0-rc.4
  @nrwl/storybook : 13.2.0-rc.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.5.5
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @ngrx/component-store: 13.0.1
         @ngrx/effects: 13.0.1
         @ngrx/entity: 13.0.1
         @ngrx/router-store: 13.0.1
         @ngrx/store: 13.0.1
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @ngrx/store-devtools: 13.0.1
```

### PR DESCRIPTION
**Pull request by meeroslav**
## Related Issue(s)

Fixes #8059 

Related to https://github.com/nrwl/nx-examples/pull/179

### CODE REVIEW

**Review by Coly010 — APPROVED** [review]
LGTM 🎉

**Comment by codephobia** [comment]
@meeroslav Am I correct in my assumption that this fix will not work for wildcard paths used for secondary entry points?

**Comment by meeroslav** [comment]
I would expect it to work @codephobia. Do you have a repro that shows otherwise?

**Comment by codephobia** [comment]
@meeroslav The problem I am seeing is if I try to use a wildcard path for any nested folder within the lib I get the relative path error for the secondary entry point. I've got about 50 entry points for components, some of which are using other components as children. I would prefer to avoid putting them in the root folder of the library since there is other things in the library currently (storybook, schematics, docs, etc) and it makes it look like a mess.

Example path:
`"@lib/*": ["libs/lib-name/some-folder/*/src/index.ts"],`

Error:
Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "@lib/secondary-entry-point".

I can try to make some time today to repro the issue if that helps.

**Comment by codephobia** [comment]
@meeroslav I made a repro of the issue and it seems to work as expected. Must be something in the current setup I have, or the fact that we are still on Nx 13.10.5. At least I know that it should work now, just need to figure out what is needed to get there. Repro: https://stackblitz.com/edit/nx-sgjrmx

**Comment by codephobia** [comment]
@meeroslav Upon further investigation, I have a feeling that the folder (libs/my-library/some-folder) is not being linted as expected. It seems that if you include the folder in the lintFilePatterns you then start to see the errors I am experiencing in my project. I have updated the repro accordingly. If you go to https://stackblitz.com/edit/nx-sgjrmx and run the command `nx run my-library:lint` you will see the error I am experiencing.

**Pull request merged**
