### PR TITLE
fix(vite): prevent vite:build copying package.json when generatePackageJson false

### LINKED ISSUE #19758: vite:build copies package.json to outputPath
### Current Behavior

Current behavior defined here:
https://github.com/nrwl/nx/blob/master/packages/vite/src/executors/build/build.impl.ts#L103-L121

When `generatePackageJson` is set to `false`, `vite:build` insists that the output dir should still have a package.json. 

This is not desirable in cases where the outputPath is `{projectRoot}/dist` because this would mean that the `{projectRoot}/package.json` will match `{projectRoot}/dist/package.json` which makes `npm install` break with workspaces due to the conflicting names.

### Expected Behavior

No package.json is generated in the `dist` folder

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create the following config:
```json
"buildLib": {
    "executor": "@nx/vite:build",
    "dependsOn": ["^build", "^buildLib"],
    "outputs": ["{options.outputPath}"],
    "options": {
        "outputPath": "{projectRoot}/dist",
        "skipTypeCheck": true,
        "force": false,
        "generatePackageJson": false,
    }
}
```
2. Run the `buildLib` task for a project

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.0
   OS     : darwin-arm64
   npm    : 8.19.1

   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/vite           : 16.5.5
   @nx/webpack        : 16.3.2
   typescript         : 4.9.5
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [x] Linux
- [x] Windows
- [x] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by vneogi199**
closed #19758

## Current Behavior

When generatePackageJson is set to false, vite:build copies package.json to output directory.

## Expected Behavior

No package.json is generated in the dist folder

## Related Issue(s)

Fixes #19758

### CODE REVIEW

**Comment by vergilfromadyen** [comment]
Hey @vneogi199 (and @jaysoo I suppose), are there any more changes here or can we expect this to land in the codebase soonish?

Thanks and happy holidays :)

**Review by mandarini — APPROVED** [review]
thanks, makes sense to me

**Comment by mandarini** [comment]
Thanks for this PR @vneogi199 ! Keep in mind that very very soon we will be moving away from executors, so this change will not have much effect!

**Comment by jsmecham** [comment]
> Keep in mind that very very soon we will be moving away from executors, so this change will not have much effect!

Could you elaborate more on what this means?

**Comment by mandarini** [comment]
@jsmecham we will elaborate soon, next week, that is! :) It's a new feature!

I'm merging your PR, though, in any case, so you will be able to move forward with your issue!

**Pull request merged**
