### PR TITLE
fix(nx-dev): add background on pricing tiles & blog link to pricing page #27157

### PR DESCRIPTION
**Pull request by ndcunningham**

### CODE REVIEW

**Review by bcabanes — APPROVED** [review]

**Comment by isaacplmann** [comment]
The pipeline failure is a problem with the link checker script, not an actual broken link.  I'm working on fixing the script now.

**Comment by isaacplmann** [comment]
I updated the link checker in this PR instead

**Review by isaacplmann — APPROVED** [review]

**Comment by ndcunningham** [comment]
> I updated the link checker in this PR instead

@isaacplmann 
It looks like when we define a navigation to any page that is inside `nx-dev/app/` with a  `#` included it will cause the checker to fail. Is it possible to improve this in another PR without ignoring the routes?

**Comment by isaacplmann** [comment]
Yes, definitely possible to make the link checker smarter.  We used to not have very many hand-coded pages, so it wasn't as important.  Now that nx.app pages are merged in, it matters more.

**Pull request merged**
