### PR TITLE
fix(storybook): react eslint ignores for storybook

### LINKED ISSUE #3867: Linter fails after adding storybook config files
## Current Behavior

Linting a library which has storybook configurations causes lint errors. 

## Expected Behavior

Linter should success without errors.

## Steps to Reproduce

1. Create a workspace
```
npx create-nx-workspace workspace

? What to create in the new workspace react
? Application name                    web
? Default stylesheet format           emotion
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
```

2. Add a library
```
npm run nx g lib components
```

3. Add Storybook configurations
```
npm i -D @nrwl/storybook
npm run nx g storybook-configuration components

? Configure a cypress e2e app to run against the storybook instance? Yes
? Automatically generate story files for components declared in this library? Yes
? Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure schematic? Yes
```

4. Run lint
```
npm run lint components
```

### Failure Logs

```
> nx workspace-lint && nx lint "components"


> nx run components:lint 

Linting "components"...

/Users/puku0x/Desktop/workspace/libs/components/.storybook/main.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: libs/components/.storybook/main.js.
The file must be included in at least one of the projects provided

/Users/puku0x/Desktop/workspace/libs/components/.storybook/preview.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: libs/components/.storybook/preview.js.
The file must be included in at least one of the projects provided

/Users/puku0x/Desktop/workspace/libs/components/.storybook/webpack.config.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: libs/components/.storybook/webpack.config.js.
The file must be included in at least one of the projects provided

✖ 3 problems (3 errors, 0 warnings)

Lint errors found in the listed files.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! workspace@0.0.0 lint: `nx workspace-lint && nx lint "components"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the workspace@0.0.0 lint script.
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3
```

### LINKED ISSUE #4104: storybook schematics friendliness
When adding storybook support to an "ESlinted" project, I identified a boilerplate steps that could be added to the install schematics.  
Sub files `.eslintrc.json` of storybook enabled libraries should also specifically refer to storybook's `tsconfig`:

```json
{
  "extends": "../../.eslintrc.json",
  "ignorePatterns": [
    "!**/*"
  ],
  "rules": {},
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      "parserOptions": { "project": ["./tsconfig.*?.json", "./.storybook/tsconfig.json"] }
    }
  ]
}
```
### Failure Logs
in IntelliJ, I get this ESLint error when opening a `.stories.ts` file

```console
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src\lib\frame\frame.component.stories.ts.
The file must be included in at least one of the projects provided.
```

### Environment
  nx : Not Found
  @nrwl/angular : 10.4.1
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.4.1
  @nrwl/eslint-plugin-nx : 10.4.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.1
  @nrwl/linter : 10.4.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.1
  typescript : 4.0.5

### PR DESCRIPTION
**Pull request by juristr**
## Related Issue(s)

Fixes #3867

### CODE REVIEW

**Comment by juristr** [comment]
So while this would work & fix the linting issue, it doesn't fix the root cause. Investigating if I can find a proper fix to avoid the error ppl are experiencing

**Comment by vsavkin** [comment]
@juristr are you still working on it? Or do you think our ESLint setup evolved where it is no longer an issue?

**Comment by juristr** [comment]
@vsavkin I'm just working in closing the storybook PR which needs some adjustments and then I wanted to check whether this one has been solved meanwhile.

**Comment by juristr** [comment]
Closing this one in favor of a new that'll be opened soon

**Comment by SerkanSipahi** [comment]
@juristr is this topic just covers react? what about angular?

See also: https://github.com/nrwl/nx/issues/3867#issuecomment-759465271

**Pull request closed without merging**
