### PR TITLE
fix(core): make sanitizePath cross-platform

### LINKED ISSUE #6280: nx dep-graph not generating graph
## Current Behavior

The graph is served to http://127.0.0.1:4211, but no graph is visible.

## Expected Behavior

`nx dep-graph` should generate or use the files it needs in order to display the dependency graph

## Steps to Reproduce

1. `npx nx create-nx-workspace deps-repro`
2. Answer prompts:
    ```
    √ What to create in the new workspace · angular
    √ Application name                    · admin
    √ Default stylesheet format           · scss
    √ Use Nx Cloud? (It's free and doesn't require registration.) · No
    ```
3. `cd deps-repro`
4. ` ng generate @nrwl/angular:library --name=test-lib`
5. Add `import { TestLibModule } from '@deps-repro/test-lib'` to `app.module.ts`
6. `nx dep-graph`

**Repo that reproduces error:**
https://github.com/djbreen7/deps-repro

### Failure Logs

**Browser Console Errors:**
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught (in promise) SyntaxError: Unexpected token F in JSON at position 0
```

**Browser Network Errors:**
```
File C:\code\deps-repro\node_modules\@nrwl\workspace\src\core\dep-graph\projectGraph.json not found!
```

### Environment

```
  Node : 14.16.1
  OS   : win32 x64
  npm  : 6.14.12

  nx : Not Found
  @nrwl/angular : 12.5.7
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
  ```

### PR DESCRIPTION
**Pull request by dapperdandev**
## Current Behavior

See linked issue

## Expected Behavior

See linked issue

## Related Issue(s)

Fixes #6280

### CODE REVIEW

**Comment by djbreen7** [comment]
I've never used Vercel and "Details" gives me a 404. If there's anything I need to do for the build to run properly, please let me know.

**Comment by philipjfulcher** [comment]
Thanks for your contribution! I think this change looks good, I'm trying to work out the CI issue.

**Comment by rahulz-wasnik** [comment]
I am still facing this issue. 
In fact I just pulled in the nx-example repo and ran nx dep graph on this repo and its still generating a blank page - 
https://github.com/nrwl/nx-examples

**Comment by philipjfulcher** [comment]
@rahulz-wasnik this change was just added to one of our beta releases: 12.6.0-beta.6. Unless the repo you're using is on that version or greater, you'll continue to see the issue.

**Pull request merged**
