### PR TITLE
feat(next.config.js): use custom next.config.js file if it exists in …

### PR DESCRIPTION
**Pull request by dmitriy-baltak**
## Current Behavior
next.config.js is not used when it exists in nextjs app's root (feature of nextjs itself)

## Expected Behavior 
next.config.js is picked up and run after default nx configuration if it exists in nextjs app's root

## Issue
#1895

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you very much for your PR!

Could please you add an e2e test?

Also, we switched from Travis to Circle, so you rebase, GitHub will be able to pick up the circle config.

**Comment by Alivejke** [comment]
Sure, I will update the pr

**Comment by elliottsj** [comment]
I believe that this change is not necessary, because the existing `loadConfig` call will load the config file:

https://github.com/nrwl/nx/blob/734acefeb21ac7429f65425e95f96cd064fa3094/packages/next/src/utils/config.ts#L37

This comes from here:

https://github.com/zeit/next.js/blob/55e966bb81f0a9c64bd8db7b0e9b85247c34306f/packages/next/next-server/server/config.ts#L123-L133

```ts
const path = findUp.sync(CONFIG_FILE, {
  cwd: dir,
})
```

**Comment by Alivejke** [comment]
Sorry I was on a vacation for a week. @elliottsj can you please provide a repo with working example? So far as I checked it it doesn't work without the change that I did

**Comment by elliottsj** [comment]
@Alivejke Try this https://github.com/elliottsj/nx-nextjs-example

**Comment by Alivejke** [comment]
@elliottsj thanks, after some digging I realised that next.config.js does actually work, but has an issue, because of this code:
```
config.module.rules.push({
  test: /\.tsx/,
  use: [defaultLoaders.babel]
});
```
in `@nrwl/next/src/utils/config.js` file my loader that I apply in custom config for `/\.tsx/` files doesn't work. It's happening because of the order as far as I could understand, custom config file is used first, and then mentioned code above is applied, so it will be always applied as last. Also if I console contents of `config.module.rules` I see that `defaultLoaders.babel` is there twice first for this reg exp: `/\.(tsx|ts|js|mjs|jsx)$/` and then to this `/\.tsx/` again, so probably we don't need to add it second time in `@nrwl/next/src/utils/config.js`? I will close this mr and open another one.

**Pull request closed without merging**
