### PR TITLE
fix(core): resolve webpack loaders with `require.resolve()`

### PR DESCRIPTION
**Pull request by elliottsj**
Same as https://github.com/nrwl/nx/pull/3341

With strict package managers such as pnpm or Yarn PnP, transitive dependencies are *not* hoisted to the root node_modules folder. This means that a webpack config defined within a package like '@nrwl/cypress' cannot resolve loaders like 'ts-loader', unless 'ts-loader' is declared in the workspace's own package.json.

This is a problem because the workspace might define a different version of 'ts-loader', incompatible with the version declared by '@nrwl/cypress/package.json'. The workspace should not need to declare a dependency on 'ts-loader' anyway.

By using `require.resolve()`, Node.js's module resolution is used instead of webpack's, so this issue is avoided.

See also:
* https://github.com/pnpm/pnpm/issues/801
* https://github.com/webpack/webpack/issues/5087

## Current Behavior

Workspaces using pnpm must declare dependencies on loaders used by `@nrwl/*` packages, and manually keep the versions in sync. Or, a [`public-hoist-pattern`](https://pnpm.js.org/en/npmrc#public-hoist-pattern) must be defined to hoist webpack loaders.

## Expected Behavior

pnpm users should not have to declare transitive dependencies or customize package hoisting.

### CODE REVIEW

**Comment by elliottsj** [comment]
@jaysoo I've published these changes to my local registry following https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md?rgh-link-date=2020-07-20T18%3A06%3A53Z#publishing-to-a-local-registry, and created an app using `@nrwl/react`. Seems to serve and build without error.

**Comment by jaysoo** [comment]
Thanks, I'm going to take a look this this week.

**Comment by jaysoo** [comment]
@elliottsj looks like the same issue of apps not being styled is happening. I'm not sure why, but if you can investigate that'd be super helpful. Otherwise I may have time next week to take a look.

Once you have it published to your local registry, run this:
```
npx create-nx-workspace@latest styling-demo --preset=react --appName=demo --style=css --no-nx-cloud
```

Let it finish, and then run `nx serve demo` from the new workspace. When you open the page it'll be unstyled.

Screen Shot 2020-08-07 at 2 12 34 PM

**Comment by elliottsj** [comment]
Found the issue; pushed a commit with the fix. Styling works again:

Screen Shot 2020-08-07 at 3 06 14 PM

**Comment by jaysoo** [comment]
Awesome. Just waiting for the CI to finish.

**Review by jaysoo — APPROVED** [review]

**Pull request merged**
