### PR TITLE
Improve `@nrwl/next:server` `customServerPath` docs

### PR DESCRIPTION
**Pull request by andre-matulionis-ifood**
This adds more details on what is the `customServerPath` option, and how to use it.

Some of my problems were:
1) I created a server.js, that did not export a function, instead, it was a file that was run: `node server.js`. It showed an error that "customServer is not a function"
2) I changed server.js to export a default function. Now it did run, but it still didn't work as expected
3) I noticed a [specific comment in an specific issue](https://github.com/nrwl/nx/issues/1933#issuecomment-566738495) that showed what was the function signature, and an example on how to use it, which fixed all errors

Because the issue has a public solution but it is not documented, I added it to the documentation

### CODE REVIEW

**Comment by joaowillamy** [comment]
great

**Comment by ndcunningham** [comment]
Hey! Thanks for contributing can you rebase your branch with the latest master?

**Comment by ndcunningham** [comment]
rebase again please

**Comment by jaysoo** [comment]
Deprecated the feature.

**Pull request closed without merging**
