### PR TITLE
fix(angular): support maxParallel, parallel, and withDeps options in webpack-browser schema

### PR DESCRIPTION
**Pull request by LayZeeDK**
## Current Behavior

The `withDeps` option is required for incremental build when using the `@nrwl/angular:webpack-browser` executor as briefly mentioned in [Setup incremental builds for Angular applications > Running and serving incremental builds](https://nx.dev/latest/angular/guides/ci/setup-incremental-builds-angular).

This guide also mentions that we can configure `withDeps` and `parallel` in the options of the incremental `serve` target of our workspace configuration. It doesn't mention this for the `build` target.

However, the `maxParallel`, `parallel`, or `withDeps` options are not declared in the executor schema or its documentation.

## Expected Behavior

Seeing as `withDeps` is required for the incremental `build` target to work, we should add support for the `maxParallel`, `parallel`, and `withDeps` options in the schema of `@nrwl/angular:webpack-browser`.

## Related Issue(s)

Fixes #

## Other information
We're building an Nx plugin to convert an application and its library dependencies to use incremental build and this is blocking us from implementing it for the best end-developer experience.

See https://github.com/nx-worker/nxworker/pull/5.

### CODE REVIEW

**Comment by LayZeeDK** [comment]
Looking for guidance on how to pass this test failure:
```
>  NX   ERROR  Running target "build" failed
      
        Failed projects:
        
        - app7978734
      
       - Compiling TypeScript sources through NGC
      ✔ Compiling TypeScript sources through NGC
      - Writing package metadata
      ✔ Writing package metadata
      ℹ Built @proj/buildlib16237231
      Schema validation failed with the following errors:
        Data path "" should NOT have additional properties(withDeps).
      npm ERR! code ELIFECYCLE
      npm ERR! errno 1
      npm ERR! proj@0.0.0 nx: `nx "build" "app7978734" "--with-deps"`
      npm ERR! Exit status 1
      npm ERR! 
      npm ERR! Failed at the proj@0.0.0 nx script.
      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
      
      npm ERR! A complete log of this run can be found in:
      npm ERR!     /home/circleci/.npm/_logs/2021-01-17T12_56_34_000Z-debug.log

      at Object.runCLI (../utils/index.ts:308:15)
```

**Comment by vsavkin** [comment]
@LayZeeDK sorry for the late reply and thank you for the PR. 

`maxParallel`, `parallel`, or `withDeps` are used by the Nx tasks runner, and are not used by the executor. The executor doesn't schedule the tasks to build the dependencies, the tasks runner does. You can set maxParallel and parallel in nx.json in the runner's options. You cannot set `withDeps` right now. 

Is you concern the lack of docs? Or the fact that you have to do: `nx build myapp --with-deps`?

**Comment by LayZeeDK** [comment]
Hello @vsavkin,

Thank you for your reply.

I was confused because you yourself added these options to the `@nrwl/web:file-server` executor in this commit:
https://github.com/nrwl/nx/commit/7d3627ab27f7ee2f23e5ea10b89d280a54159607

Isn't it possible to add these parameters to target options in `workspace.json`?

**Comment by vsavkin** [comment]
When nx runs any command it reads the tasks runner config from nx.json. This is how it knows what tasks runner to use, what options it has etc. The workspace.json file lists the tasks and configures the executors/builders.  

The file-server target is a special case cause it actually invokes `nx run` under the hood, so it can pass --parallel and --maxParallel to it. Maybe I should have named those properties `buildParallel` and `buildMaxParallel` to indicate that those just happen to match the stuff in nx.json, but they didn't have to match. The `file-server` executor could have had its own way of  running things in parallel which had nothing to do with the tasks runner. It just happened to invoke Nx under the hood.

**Comment by LayZeeDK** [comment]
I see, @vsavkin. Is there any way we can add these options to for example `build` targets in `workspace.json`?

**Comment by vsavkin** [comment]
@LayZeeDK it depends on the build target. You can have a build target that actually invokes Nx under the hood (as the file-server target does), in this case we could add them. The executor implementing the target has to be able to interpret those params. For instance, the jest executor has a param called maxWorkers, which is analogous to maxParallel. 

The options in workspace.json configure targets' executors. When you run things like `nx build myapp --with-deps --parallel`, you actually run many targets, so many executors are invoked with their own configurations. myapp, in this case, isn't built in parallel. The set of [myapp, mylib, mylib2, ..] is built in parallel. The parallel flag in this isn't associated with any of them, but rather with invoking this command that builds all of them. 

I imagine your use case is something like this:

When building myapp, I'd like to always build it with deps and build all the targets in parallel. But I don't want this to affect other targets and other apps. It's a legitimate use case. Right now we allow you to set parallel and maxParallel for all commands, but you cannot set the defaults for some commands.

**Comment by LayZeeDK** [comment]
@vsavkin

>I imagine your use case is something like this:
>
>When building myapp, I'd like to always build it with deps and build all the targets in parallel. But I don't want this to affect other targets and other apps. It's a legitimate use case. Right now we allow you to set parallel and maxParallel for all commands, but you cannot set the defaults for some commands.

Yes, we wanted to set `withDeps` and `parallel` for an application using the `@nrwl/angular:webpack-browser` executor for its `build` target when it has buildable workspace library dependencies which are using the `@nrwl/angular:ng-packagr-lite` executor for their `build` targets.

The schema of `@nrwl/angular:webpack-browser` doesn't allow the `withDeps` and `parallel` options to be set in `workspace.json`, so it seems that there's no way to ensure these options are always added to the `nx build` for the application project in question. However, if `withDeps` isn't added, it can result in an application build using stale dependencies.

**Pull request closed without merging**
