### PR TITLE
chore(core): nx plugin submission [@gperdomor/nx-docker]

### PR DESCRIPTION
**Pull request by gperdomor**
Propose a simple docker builder to be able to build images of your affected apps

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

# Community Plugin Submission

Thanks for submitting your Nx Plugin to our community plugins list. Make sure to follow these steps to ensure that your PR is approved in a timely manner.

## Steps to Submit Your Plugin
- Use the following commit message template: `chore(core): nx plugin submission [PLUGIN_NAME]`
- Update the `community/approved-plugins.json` file with a new entry for your plugin that includes `name`, `url`, `description`:

Example:

```json
// community/approved-plugins.json

[{
    "name": "@community/plugin",
    "url": "https://github.com/community/plugin",
    "description": "This plugin provides the following capabilities."
}]
```

Once merged, your will plugin will be available when running the `nx list` command, and will also be available in the Plugin browser on [nx.dev](https://nx.dev)

### CODE REVIEW

**Comment by Cammisuli** [comment]
@gperdomor thanks for your PR! Can you squash your commits (or amend the last commit) so that we can get ✅'s on all the CI checks?

**Comment by Cammisuli** [comment]
Also, the plugin looks awesome!

As a suggestion, maybe you could add a schematic that allows people to add the `docker` build architect to their projects without having to manually add it 😄 

Something like; `yarn nx g @gperdomor/nx-docker:setup --project my-app`, then modify the workspace or angular.json.

**Comment by gperdomor** [comment]
@Cammisuli rebased and squashed...

**Comment by gperdomor** [comment]
> Also, the plugin looks awesome!
> 
> As a suggestion, maybe you could add a schematic that allows people to add the `docker` build architect to their projects without having to manually add it 😄
> 
> Something like; `yarn nx g @gperdomor/nx-docker:setup --project my-app`, then modify the workspace or angular.json.

thanks for your suggestion... I will try to find some time to do it :D

**Pull request merged**
