### PR TITLE
feat(backend): set nestjs target to es2017 and add incremental flag

### LINKED ISSUE #1002: NestJs need to have es6 in tsconfig target
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I merged my api repository using nest to my nrwl repository with the 7.3 version.
The ng serve nestjs-project is suppose to correctly run the API

## Current Behavior

Nest wasn't able to handle request when using Nest middleware (infinite loading).
I found out the issue : https://github.com/nestjs/nest/issues/266.
Nestjs need to have tsconfig target set to es6, but by default the tsconfig generated by nrwl inherit from the global tsconfig (es5).

## Other

I think it would be nice to override nrwl default tsconfig with the default nestjs tsconfig options when generating a new nestjs project

### PR DESCRIPTION
**Pull request by mehrad-rafigh**
## Current Behavior (This is the behavior we have today, before the PR is merged)
target is set to es2015
## Expected Behavior (This is the new behavior we can expect after the PR is merged)
target is set to es2017 and incremental flag has been set to true
## Issue
Closes #1002

### CODE REVIEW

**Comment by vsavkin** [comment]
The PR looks good. One thing that is left is adding a migration that will update the version of nest in existing projects. This is an example:

https://github.com/nrwl/nx/blob/master/packages/workspace/src/migrations/update-8-3-0/update-ng-cli-8-1.ts

**Comment by mehrad-rafigh** [comment]
Hi @vsavkin. Thank you for reviewing the PR. I will update this PR asap

**Comment by mehrad-rafigh** [comment]
Hi @vsavkin. I updated my PR. It includes a migration and I added a test for it as well. 
Should we also update the corresponding tsconfig.json files to include the target and incremental flag?

**Comment by vsavkin** [comment]
@mehrad-rafigh 

Quick question. Since we are bunlding nestjs apps with webpack, how does "incremental" work together with webpack? Cause all the compilation happens in memory.

**Comment by mehrad-rafigh** [comment]
Hi @vsavkin.
I took a closer look into ts-loader and it seems, the incremental flag would be ignored by the ts-loader. The incremental flag has not been implemented by the ts-loader and there is an [open issue](https://github.com/TypeStrong/ts-loader/issues/999)

I would suggest to remove the incremental flag for the time being and open a PR, once the issue has been resolved. 

What do you think?

**Comment by vsavkin** [comment]
@mehrad-rafigh it sounds good. let's wait for it to land and then open the PR.

**Comment by vsavkin** [comment]
I'm sorry but I'm going to close this. We changed the way we are handling package updates to use `updatePackagesInPackageJson`.

**Pull request closed without merging**
