### PR TITLE
feat(core): split nx config to project files

### LINKED ISSUE #2643: Splitting nx.json and angular.json per project
Hey! 

It would be very cool if we could have a tool to split configuration files like angular.json or nx.json per app/lib
Currently we are working in the same repo with a lot of different projects and a lot of people, we always end up having to solve conflicts on these files.

Angular CLI does not support splitting angular.json by default, so we could put a angular-project.ts inside each lib or app and then run a script to concatenate every entry into angular.json

The same idea would work for nx.json, or maybe on nx.json just a flag to search in the directories for a nx.json file or something.

Is there anyone with a similar solution to share?

### PR DESCRIPTION
**Pull request by AgentEnder**
## Current Behavior
nx.json and workspace.json work together to provide the full project configuration's for every project in the monorepo

## Expected Behavior
nx.json is optional, perhaps deprecated. Workspace.json, combined with nx-project.json files make up the total workspace config. nx-project.json files contain all of the configuration needed for a project and its targets. Workspace.json contains project agnostic settings, as well as a list of the nx-project.json files and any inline configurations.

## Related Issue(s)

Fixes #2643

### CODE REVIEW

**Comment by PetarKirov** [comment]
@AgentEnder have you considered allowing the contents of `{apps,libs}/*/project.json` to embedded in `{apps,libs}/*/package.json`, thereby removing the need for a separate file?

**Comment by AgentEnder** [comment]
@PetarKirov the project.json files being an exact copy of what was inside workspace.json and nx.json makes it easy to inline the configuration at runtime and present the same public api (effectively allowing this to be a nonbreaking change). While package.json could be used, it would make the wrapping layers around angular CLI and read / write to be much harder. With it being a separate file, its easy to check if the file exists and know whether or not the project is using a split config.

This is definitely something that could be done, but I do not think the added complexity and long term maintenance costs associated would be worth it in this case.

**Comment by PetarKirov** [comment]
Makes sense, thanks for the detailed explanation. I am a bit biased, as I have experience with other language ecosystems where the package manager is also the build system and there's no need to spread/duplicate information about the layout of the mono repo across multiple files.

**Comment by jogelin** [comment]
@AgentEnder Good job thanks, waiting for that since long time !

Any article or documentation on the way we could use that ?

**Comment by AgentEnder** [comment]
Hey, thanks. This is mentioned in the configuration section of the docs, but there is also a good explanation in the 12.5 release blog: https://blog.nrwl.io/per-project-configuration-storybook-support-for-angular-12-auto-refresh-for-dependency-graph-and-bcd2d1e06658

**Pull request merged**
