### PR TITLE
fix(core): add forwardallargs option to run-commands builder

### LINKED ISSUE #3335: Run-Commands: Arguments are incorrectly appended when using multiple commands
## Current Behavior

When attempting to run multiple commands with arguments as shown in the [docs](https://nx.dev/angular/plugins/workspace/builders/run-commands#properties), there are two scenarios:
1. Commands that use argument(s):
     * These run fine and are parsed correctly assuming you use `{args.some_arg}`
2. Commands that do not use argument(s):
    * These commands always get the raw arguments appended to it
     * Ex: Passing the argument `--name=testing`, the command `mkdir scripts` would actually run `mkdir scripts --name=testing`
     * This can cause commands to fail

* **Note:** This became a problem for us after upgrading Nx from 9.3.0 to 9.5.1.

## Expected Behavior

Commands that do not use arguments should not have raw arguments appended to them as it can cause them to fail.

## Steps to Reproduce
https://github.com/nrwl/nx-examples/pull/109

### Failure Logs

Reference repro PR.

### Environment

@nrwl/angular : Not Found
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : 9.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : 9.5.1
  @nrwl/nest : 9.5.1
  @nrwl/next : 9.5.1
  @nrwl/node : 9.5.1
  @nrwl/react : 9.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : 9.5.1
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3

### PR DESCRIPTION
**Pull request by techgerm**
* add a `forwardAllArgs` option to `run-commands` builder that defaults to `true` when using `command` and
`false` when using `commands`
* My first time contributing a PR to this repo ... I read through all contributing documentation but please let me know if I missed something.

ISSUES CLOSED: #3335

## Current Behavior

* All arguments passed down to the `run-commands` builder are always forwarded to all commands which can break user commands

## Expected Behavior

* Users should have an option to control this behavior and can now do so with the `fowardAllArgs` option

## Related Issue(s)

Fixes #
Closes #3335

### CODE REVIEW

**Comment by germanp173** [comment]
I could really use a bit of help in debugging the one failed unit test.
The `git-hasher` "should work" unit test appears to be failing on line 70 after running `run('git add .')` but I've got no clue as to why this would be failing or how my changes affected this test.
To add to the confusion, `run('git add .')` on line 35 just above seems to be working just fine 😕

**Comment by bekos** [comment]
hi @germanp173, thx a lot for the PR 👍  reading the discussion with @vsavkin on the issue, i have a following comments:

- single command should keep behaving as before, but I don't think it's a problem supporting a `forwardAllArgs` also as you did
- multiple commands should support the `forwardAllArgs` parameter per command, as a global parameter would have the same problems, ie some commands want to pass all and other's not. So the supported syntax should be like this:
```
commands: [
  {
    command: 'command one',
    forwardAllArgs: true
  },
  {
    command: 'command two',
    forwardAllArgs: false
  },
 ...
]
```
- I believe that `forwardAllArgs` should default to `true` in all cases for now, otherwise it will be a breaking change 🤔 

WDYT? Tell me if there is anything that needs clarification.

**Comment by germanp173** [comment]
hey @bekos, thanks for taking a look at my PR! 
I agree with what you've proposed and have updated my branch. Let me know if I missed something.

**Comment by bekos** [comment]
hi @germanp173 thanks for your changes 💪  sorry for that, but one thing that I didn't realize on my previous comment, is what will happen if someone by mistake uses the `commands` (plural) with the `forwardAllArgs` like this:
```
commands: [...],
forwardAllArgs: false,
```
Atm, we don't throw any error and the `forwardAllArgs` is actually ignored, and this will be confusing 😞 IMO we have the option to either throw an error if `commands` and `forwardAllArgs` is used together, or totally drop the `forwardAllArgs` in `command` (which would probably make more sense, as it is derived from it's actual usage) and keep the `forwardAllArgs` inside each of the `commands`. This will also decrease the API/schema surface which is generally a good thing 😃 ie `command` is a shortcut for `commands: [ { command, forwardAllArgs: true }]`, and if any adjustment is needed anyone can use directly the `commands`. WDYT?

**Comment by germanp173** [comment]
ah good call, yeah makes sense and it does make it easier to follow from a user perspective 👌

**Comment by bekos** [comment]
@germanp173 Thanks for your contribution 😃 Awesome job 🎉

**Comment by germanp173** [comment]
@bekos thanks!

**Comment by cliffmeyers** [comment]
I would love to see this backported to 9.x. As far as I can tell it's not supported in 9.7.0:

```
An unhandled exception occurred: Schema validation failed with the following errors:
  Data path ".commands[0]" should NOT have additional properties(forwardAllArgs).
```

**Pull request merged**
