### PR TITLE
[wip] fix(web): Prioritize bowserslist over script target

### LINKED ISSUE #2209: React application not running in IE11
## Expected Behavior

The App to load polyfills and run in IE11, possibly in both development and prod mode.

## Current Behavior

**Dev mode:** IE11 raises syntax errors (related to ES6 arrow functions) and stops
**Prod mode:** blank screen, scripts are loaded but nothing seems to be evaluated, judging from performance timeline. 

#### Dev mode scenario

1. `npx --ignore-existing create-nx-workspace nx-ie11-test --preset=react`
2. `npm serve`  (or yarn, for what is worth)

Scripts are loaded and evaluated:

timeline

But the resulting outcome is a syntax error pointing to the first evaluated function presenting ES6 arrow notation:

console
bundle

I've tried to tackle the issue from a few different angles:
- "downgrading" the `target` parameter value to `"es5"` in `tsconfig.json`;
- adding a `"browserslist"` section in `package.json` and make sure IE11 is explicitly listed;
- addding `react-app-polyfill` and cleaning `node-modules/.cache` before rebuilding as suggested [here](https://medium.com/@matwankarmalay/create-react-app-ie11-script1002-syntax-error-how-to-get-rid-of-it-d70000c53ddf);

Same result 🤕

#### Build mode scenario

1. `npx --ignore-existing create-nx-workspace nx-ie11-test --preset=react`
2. `npm build`  (or yarn, for what is worth)

Rendered page is empty and console is clean:
 
Imgur

This time scripts are loaded but not evaluated, from what I can see.:

Imgur
Imgur

Any suggestions?

### PR DESCRIPTION
**Pull request by sushruth**
Browser support should dictate differential loading more importantly, compared to tsconfig target

## Current Behavior

`browserslist` is ignored for IE11

## Expected Behavior

`browserslist` should not be ignored for IE11

## Related Issue(s)

Fixes #2209 #3422 #3836

### CODE REVIEW

**Comment by jaysoo** [comment]
@sushruth I think some e2e tests are warranted here. Let me know if you need any help with that. We should make sure the built bundle contains the correct polyfills  for IE11 based on browserslist.

**Comment by sushruth** [comment]
@jaysoo Agreed. However, these changes alone dont seem to be sufficient. There are some issues with generating runtime.js for both es5 and esm for a project when using this setting. I am still trying to fix that.

**Comment by mandarini** [comment]
Hi @sushruth ! Are there any updates on this PR? Are you still working on things?

**Comment by sushruth** [comment]
Still working on this. Last piece of the puzzle is how to enable both runtime.js and runtime.esm.js to be generated. That I'm not able to figure out yet.

**Comment by jaysoo** [comment]
@sushruth Do you need any help on this?

**Comment by jaysoo** [comment]
I'm going to assign someone else to take a look at this. @sushruth If you are still working on it please let me know.

**Comment by sushruth** [comment]
I am not actively looking at this anymore. Please reassign. Also close this PR. Thanks.

**Comment by hakimio** [comment]
@brandonroberts @vsavkin can you make this happen. Having `browserslist` ignored is really annoying.
Ref #5392

**Pull request closed without merging**
