### PR TITLE
feat(core): update prettier to v2.2.1

### PR DESCRIPTION
**Pull request by mehrad-rafigh**
## Current Behavior
prettier is at v2.1.2

## Expected Behavior
prettier is at v2.2.1

### CODE REVIEW

**Comment by mehrad-rafigh** [comment]
@vsavkin should I rebase this?

**Comment by vsavkin** [comment]
@mehrad-rafigh could you rebase this and I'll merge it.

**Comment by mehrad-rafigh** [comment]
@vsavkin Done

**Comment by mehrad-rafigh** [comment]
@vsavkin I have no clue why some checks fail. Locally everything works just fine :( Can you please rerun the pipeline?

**Comment by bekos** [comment]
@mehrad-rafigh probably the documentation check fails because of the prettier update causing format changes in other files in the repo. can you try to run `yarn nx format --all` or explicitly for these files? 
```
📄 Documentation has been modified, you need to commit the changes.
 M docs/angular/api-next/executors/export.md
 M docs/node/api-next/executors/export.md
 M docs/react/api-next/executors/export.md
```

**Comment by mehrad-rafigh** [comment]
@bekos I already did that. Running the command locally results in no changes. I will take a look at this tonight

**Comment by bekos** [comment]
@mehrad-rafigh ok I see, you have to run `yarn documentation` with 2.2.1 installed. The problem is here:
image

**Comment by mehrad-rafigh** [comment]
Thank you @bekos 
I updated the migrations to match the next release version 
I hope this is mergeable now :)

**Comment by vsavkin** [comment]
Thank you!

**Pull request merged**
