### PR TITLE
feat: allow optional configuration in infix run command

### LINKED ISSUE #28335: `nx run` infix syntax not working with configurations
### Current Behavior

Given a target with configurations defined in `project.json` it is not possible to run a task with a specific configuration when using the infix syntax.

See "Steps to Reproduce" for the minimal reproduction.

- `nx run foobar:migration:run` works fine ✔ 

  ``` 
  > nx run foobar:migration:run 
  
  > echo running migrations
  
  running migrations
  
   NX   Successfully ran target migration for project foobar (38ms)
  ```
  
- `nx migration foobar` works fine ✔ 

  ```
  > nx run foobar:migration:run
  
  > echo running migrations
  
  running migrations
  
   NX   Successfully ran target migration for project foobar (40ms)
  ```
  
- `nx migration:run foobar` does not work 🐛 :x:

  ```
  NX   Cannot find configuration for task foobar:migration:run
  
  Pass --verbose to see the stacktrace.
  ```
  

### Expected Behavior

`nx migration:run foobar` as well as `nx migration:generate foobar` work in the same way as `nx run foobar:migration:run` and `nx run foobar:migration:generate`.

### GitHub Repo

_No response_

### Steps to Reproduce

Use this `project.json`:

```json
{
  "name": "foobar",
  "targets": {
    "migration": {
      "executor": "nx:run-commands",
      "defaultConfiguration": "run",
      "configurations": {
        "run": {
          "commands": ["echo running migrations"]
        },
        "generate": {
          "commands": ["echo generating migrations"]
        }
      }
    }
  }
}
```

### Nx Report

```
Node           : 18.20.4
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.22

nx (global)  : 19.6.4
nx           : 20.0.0
```

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The same issue exists on both `19.6.4` and `20.0.0`.

### PR DESCRIPTION
**Pull request by akwodkiewicz**
As explained in the linked issue, I cannot leverage `yargs` positional arguments syntax in the command template, because the configuration is an _optional_ argument in the middle of the invocation. I must use custom parsing in the handler. Thankfully it's just about splitting the argument on the first `:`.

## Current Behavior

Infix notation does not allow passing target configuration.

## Expected Behavior

Infix notation allows passing target configuration.

## Related Issue(s)

Fixes #28335

### CODE REVIEW

**Comment by akwodkiewicz** [comment]
Hey, @xiongemi -- why was the PR closed? Is it just that my implementation is not OK, or is the whole #28335 a "won't fix"?

**Comment by xiongemi** [comment]
> Hey, @xiongemi -- why was the PR closed? Is it just that my implementation is not OK, or is the whole #28335 a "won't fix"?

i press close pr by accident. could you reopen?

**Comment by akwodkiewicz** [comment]
Actually I cannot, I'll create a new one

**Comment by akwodkiewicz** [comment]
Squashed the commits into a single one and updated the PR description in #28375

**Pull request closed without merging**
