### PR TITLE
feat(core): allow setting file permissions while writing with `Tree`

### LINKED ISSUE #5680: [Feature Request] Allow Tree to write file with permissions
## Description

Similar to the feature request here https://github.com/angular/angular-cli/issues/11781, it would be nice if the Nrwl DevKit's `Tree.write()|overwrite()` could allow setting the permissions on the file being written.

## Motivation

Sometimes, you need to create a file with  specific permissions, like for example, being *executable*. This is currently not possible with the Tree API.

## Suggested Implementation

1 - The `Tree.write()|overwrite()` could be overwritten to accept an optional `"mode?: string | number"` parameter (see  [fs.chmodSync()](https://nodejs.org/api/fs.html#fs_fs_chmodsync_path_mode) API), that would allow setting the required permissions on the file.

2 - Then the [FileChange](https://github.com/nrwl/nx/blob/ff691343737d4b470aef89723c597769e7299799/packages/tao/src/shared/tree.ts#L66) could be enhanced to store that `mode` parameter, 

3 - and finally after line:
https://github.com/nrwl/nx/blob/ff691343737d4b470aef89723c597769e7299799/packages/tao/src/shared/tree.ts#L289
and line:
https://github.com/nrwl/nx/blob/ff691343737d4b470aef89723c597769e7299799/packages/tao/src/shared/tree.ts#L291
we could add a call to `fs.chmodSync(fPath, f.mode)` if `f.mode` is defined.

## Alternate Implementations

If this feature request gets accepted, I can start working on it and provide a PR.

### PR DESCRIPTION
**Pull request by tinesoft**
Closes #5680

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
@vsavkin should we match the node API and accept an options object instead of separate parameters?

**Comment by vsavkin** [comment]
@tinesoft Could you do what @FrozenPandaz is suggesting an wrap it into an options object. I imagine we might other options added in the future.

And thank you for your PR!

**Comment by tinesoft** [comment]
Hi @vsavkin 

No problem, I can gladly do that ;-)
Any suggestion on the type name for that `options` object?
I'm thinking of `TreeWriteOptions` ...

```ts
export interface TreeWriteOptions {
    mode? : string | number;
}
```

**Comment by edbzn** [comment]
Hey, we are looking for this! :+1: Does it means that those changes will not be retro compatible with the regular Angular CLI?

**Comment by vsavkin** [comment]
Thank you!

**Pull request merged**
