### PR TITLE
fix(testing): include cypress commands in tsconfig

### LINKED ISSUE #12148: Cypress component testing "Property 'myCommand' does not exist on type 'cy & CyEventEmitter'"
## Current Behavior
When using Cypress component testing generator, command types are not detected causing "Property 'myCommand' does not exist on type 'cy & CyEventEmitter'" error.

## Expected Behavior
Command types defined in `${projectRoot}/cypress/support/**/*.ts` should be detected.

## Steps to Reproduce
1. `nx g @nrwl/angular:cypress-component-configuration --project app`
2. Add the following to `cypress/support/commands.ts`:
```ts
import { mount } from 'cypress/angular';

declare global {
  namespace Cypress {
    interface Chainable<Subject> {
      mount: typeof mount;
    }
  }
}

Cypress.Commands.add('mount', mount);
```
3. Add test `example.cy.ts`
3. Call `cy.mount()`

### Environment

```
   Node : 18.3.0
   OS   : darwin x64
   yarn : 3.2.3
   
   nx : 14.7.8
   @nrwl/angular : 14.7.8
   @nrwl/cypress : 14.7.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.8
   @nrwl/eslint-plugin-nx : 14.7.8
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.8
   @nrwl/js : 14.7.8
   @nrwl/linter : 14.7.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.7.8
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.8
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.8
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/cypress-angular: 0.9.22
         @testing-library/angular: 11.0.4
```

### PR DESCRIPTION
**Pull request by yjaaidi**
closes #12148

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by barbados-clemens** [comment]
Hi @yjaaidi I tested locally and for me it "just worked" without having to change the `tsconfig.cy.json`. 

This is because under the hood cypress uses its own tsconfig that should include all support files. 

I'm find with merging it if it fixes things on your end, as it has no adverse affects either. just wanted to let you know.

**Review by barbados-clemens — APPROVED** [review]

**Comment by yjaaidi** [comment]
Oh! Interesting. 
Actually, it "worked" on my end too due to the Cypress override but IDEs are not happy with that because the support files are excluded from the tsconfig solution.

Is that right?

Thank you for the approval.

**Comment by yjaaidi** [comment]
Oh! Interesting. 
Actually, it "worked" on my end too due to the Cypress override but IDEs are not happy with that because the support files are excluded from the tsconfig solution.

Is that right?

Thank you for the approval.

**Comment by barbados-clemens** [comment]
@yjaaidi Oh interesting. I haven't seen that.
What editor are you using? I've tried webstorm/vscode and not seen the error.
Are you using in an app or lib? sometimes there's an issues with jest + cypress types colliding, but that doesn't sound like this error.

**Comment by yjaaidi** [comment]
I didn't try on a lib yet but I tried on both WebStorm & VSCode.
I was able to reproduce this from scratch like this:
```ts
yarn create nx-workspace --preset angular --appName demo
nx g @nrwl/angular:cypress-component-configuration --project=demo --generateTests
```
then call `cy.login('', '')` in the generated `app.component.cy.ts`

Are you able to reproduce it?

Also, you are right about the jest / cypress conflict.
I had it fixed in my workspace https://github.com/marmicode/whiskmate/blob/testing-23-visual-regression-testing/apps/whiskmate/tsconfig.editor.json  by excluding `cypress/**/*.ts` and `**/*.cy.ts` in the `tsconfig.editor.json` when using Cypress 9  + @jscutlery/cypress-angular (I think we had an issue open to add it to our generator https://github.com/jscutlery/devkit/tree/main/packages/cypress-angular/src/generators/setup-ct)
As you raised the issue again, I checked and I noticed that the "exclude" is not enough.
I had to replace `include: **/*.ts` by `include: src/**/*.ts` even if `cypress/**/*.ts` and `**/*.cy.ts` are excluded. 
BTW, I wonder if tsconfig.editor.json is really needed as typing works great thanks to all other tsconfigs when tsconfig.editor.json is removed.

**Pull request merged**
