### PR TITLE
fix(node): use proper watch value with the node:execute executor

### LINKED ISSUE #4054: Node script not exiting
## Current Behavior

When running a NodeJS script (NX application), it keeps rebuilding when I change something in the `main.ts` file while `watch` mode is set to `false` (also note that my script is not exiting).
` "serve": {
          "builder": "@nrwl/node:execute",
          "options": {
            "buildTarget": "engine:build",
            "inspect": false,
            "watch": false
          }
        },`
This script connects to an FTP server, downloads some files, parses them, and interacts with a database.

It exits fine when just using `node dist/apps/script/main.js` but not when using `nx serve script`, so it's definitely not my script.

## Expected Behavior

I expect my NodeJS script to run once and exit (it works when just executing `node dist/apps/script/main.js`). 
I don't want a script to be rebuilding when I'm just running it.

## Steps to Reproduce

1. Create a NodeJS app
2. Copy the following code in the `main.ts` file:
`async function main() {
  await new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, 5000);
  });
}`

`main()
  .catch((err) => console.log(`Something went wrong: ${err}`))
  .finally(() => {
    console.log('Script executed!!');
  });`

3. Go to your `workspace.json` and target your `serve` command for the NodeJS app you created and add the following options:
`
            "inspect": false,
            "watch": false
`

### Failure Logs

No failure logs.

### Environment

nx : Not Found

  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : 10.3.2
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : 10.3.2
  @nrwl/next : Not Found
  @nrwl/node : 10.3.2
  @nrwl/react : 10.3.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : 10.3.2
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5

### PR DESCRIPTION
**Pull request by CurtisHughes**
## Current Behavior
When running a node app, the execute builder continues to watch for file changes when the watch mode is set to false.
```json
"serve": {
    "builder": "@nrwl/node:execute",
    "options": {
        "buildTarget": "infra:build",
        "watch": false
    }
},
```
## Expected Behavior
The node application to run once and exit.

## Related Issue(s)

Fixes #4054

### CODE REVIEW

**Review by Cammisuli — CHANGES_REQUESTED** [review]
Hmm.. we'll probably need a migration for this. Existing projects should have their workspace.json updated so that `watch: true` is set, and doesn't break any existing expectations. 

New projects will not have watch by default. 

If you need help with the migration, let me know and I can guide you!

**Comment by CurtisHughes** [comment]
Sounds good, I'll take a look at adding the migration and reach out if I need any help. Thanks @Cammisuli

**Comment by CurtisHughes** [comment]
@Cammisuli I took at shot at the migration (mainly following [set-build-libs-from-source.ts](https://github.com/nrwl/nx/blob/master/packages/node/src/migrations/update-9-2-0/set-build-libs-from-source.ts) as a reference).

Wasn't sure what version this would fall under so I just used `10.4.5` assuming it would be in the next patch. Please let me know if I should change that to something else.

**Comment by Cammisuli** [comment]
Alright, thank you! We'll probably get this in after v11. I'll check up again soon.

**Comment by Cammisuli** [comment]
I'm finally coming around to this and I seem to have found an issue with the execute watch setting not actually working...

I'll see if I can fix it with this pr. 

Thanks again for your patience!

**Comment by Cammisuli** [comment]
So I had to remove the migration because the underlying issue is actually fixed. Now we pass the proper option from the execute builder to whatever underlying builder that's being called. 

I also changed a couple more things so that things are properly watched and reloaded when you do want to have `watch: true`

**Comment by CurtisHughes** [comment]
Nice! Thanks for pushing those changes @Cammisuli
Let me know if there is anything else that needs to be done and I can work on.

**Review by Cammisuli — APPROVED** [review]

**Pull request merged**
