### PR TITLE
docs(deploy-nextjs-to-vercel.md): Adding bash execution info

### PR DESCRIPTION
**Pull request by mthines**
This adds information regarding the execution of Vercel Ignore Script.

### References 
- https://github.com/nrwl/nx/discussions/8448

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
That's a valid solution but I'd prefer if we instruct the user to run `chmod +x tools/ignore-vercel-build.sh` in their repo.

**Comment by mthines** [comment]
> That's a valid solution but I'd prefer if we instruct the user to run `chmod +x tools/ignore-vercel-build.sh` in their repo.

Are you sure that's possible on the CI as well? 

`chmod +x tools/ignore-vercel-build.sh` makes a lot of sense on your local machine :)

**Comment by mthines** [comment]
Should we move on this? :)
Either agree or disagree on the propsal

**Comment by FrozenPandaz** [comment]
Once you change the file permissions, the permissions will also be pushed to `git`. So when vercel pulls it down, it will have the right permissions to be executed.

If you'd like to change the hint, please open a new PR.

**Pull request closed without merging**
