### PR TITLE
feat(repo): update axios to 0.21.1

### LINKED ISSUE #4439: Vulnerability in peer dependency (axios)
Currently nx packages are using axios in v 0.19.2 which is affected: https://www.npmjs.com/advisories/1594
Please update to 0.21.1 or latest

Also it would be nice if fix will be applied to the older major versions (v10.x.x, v9.x.x). I think that many users still using them (for Angular v10, NX v10 should be used etc.)

### PR DESCRIPTION
**Pull request by mehrad-rafigh**
ISSUES CLOSED: #4439

## Current Behavior
Axios is at v0.19
## Expected Behavior
Axios is at v0.21.1

## Related Issue(s)
#4439

### CODE REVIEW

**Comment by mehrad-rafigh** [comment]
@vsavkin Do I have to write a migration for this?

**Comment by vsavkin** [comment]
Thank you for the PR. 

Could you change the commit message to `chore(core): update axios..`? And you don't need to write a migration because the workspace itself doesn't have axios in its package.json.

**Comment by mehrad-rafigh** [comment]
@vsavkin Done

**Comment by vsavkin** [comment]
Thank you!

**Pull request merged**
