### PR TITLE
fix(core): building project graphs is broken for Windows

### PR DESCRIPTION
**Pull request by mayfieldiv**
## Current Behavior
The new native hasher introduced in #14476 doesn't properly handle back-slashes on Windows, resulting in it always returning an empty collection of files. This breaks things like `nx graph` and the `affected` commands.

This issue can be readily reproduced by following the angular tutorial through step 2 in a Windows environment with the latest pre-release of nx: https://nx.dev/angular-tutorial/2-project-graph

Following that tutorial, running `nx graph` or `nx print-affected` only displays the implicit dependency declared in `core-e2e`, since it never properly inspects any of the source files (*.ts or package.json).

## Expected Behavior
The native hasher should behave as expected on all platforms.

### CODE REVIEW

**Comment by Cammisuli** [comment]
Thanks for the PR!


We discussed the slashes while this was in development and I made an extra effort to test this on windows. And it passed for me 😮 

What shell/terminal were you using? Powershell, pwsh, git bash, or cmd?

**Comment by mayfieldiv** [comment]
Oh interesting! I'm using pwsh (not on WSL). I'm on the latest stable versions (or close to latest) of PowerShell Core v7, nodejs v18, git, nx, Windows 10, etc.

**Comment by Cammisuli** [comment]
Hmm the only big difference I see is that I'm on Windows 11. 

I wonder if Microsoft finally fixed the paths with 11 😂

Anyway, I'll give this a thorough check on Monday. 

Thanks again

**Review by Cammisuli — APPROVED** [review]
Thanks again! 

I tested the changes on Windows (11), macOS 13, and Ubuntu 20 and 22 and it's all good 🙂

**Pull request merged**
