### PR TITLE
fix(misc): add message suggesting to install a plugin in an empty workspace

### PR DESCRIPTION
**Pull request by beeman**
## Current Behavior
When installing an empty workspace there is not message that you should install a plugin to add actual functionality to you workspace.

## Expected Behavior

There should be a message suggesting the user to install a plugin.

## Related Issue(s)

Related issue #2953 where people suggest we add a message when creating empty workspaces.

Please let me know if you like to see any changes in the language.

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you for your PR! I think it's good to show something for an empty workspace, but I'm not sure if just saying "add a plugin" is sufficient. I'd rather create a guide on nx.dev and point to it.

**Comment by vsavkin** [comment]
@isaacplmann can you help @beeman how to create a guide and point to it?

**Comment by isaacplmann** [comment]
@beeman 

I'm working on a WRITING_DOCS.md file that I'll put in the `/docs` folder, but I'll do a rough draft here so that you can get the general idea.

In the `/docs` folder there are 3 types of files that work together to make the docs that end up on nx.dev:

- automatically generated api docs
  - Any `.md` files in an `api*` or `cli` folder are automatically generated on `git push` by the `yarn documentation` script.
- manually created guides
  - Every other `.md` file is manually created.  Generally, docs that will be common to all 3 flavors should go under the `docs/shared` folder.
- map.json
    This file is manually maintained and has 3 different sections (one for angular, react and node).  If a doc should be available in all 3 flavors, it needs to be included in all 3 sections in map.json.

Once the docs PR is merged (and then nx.dev is published) you can link to a framework agnostic version of the doc (using whatever flavor the user last visited) by linking to `nx.dev/latest/f/[path to doc]`.  In that path `f` could be any string as long as it doesn't match an existing flavor.

**Comment by vsavkin** [comment]
@isaacplmann could you work with @beeman to help him finish the PR?

**Comment by isaacplmann** [comment]
@beeman , I'm closing this PR, but feel free to reopen it if you're interested in linking to a guide

**Comment by beeman** [comment]
I'm not really interested in writing a guide, however I do thing it's useful to mention something to the users that install an empty workspace.

From looking at [this issue](https://github.com/nrwl/nx/issues/2953#issuecomment-727008271) it's a very common issue and for those user it would be great to have some guidance on what is wrong. This PR was an attempt to help those users understand what they're missing.

**Pull request closed without merging**
