### PR TITLE
feat(expo): upgrade expo to 47

### PR DESCRIPTION
**Pull request by xiongemi**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Review by jaysoo — COMMENTED** [review]
LGTM

**Review by jaysoo — APPROVED** [review]

**Comment by yonitou** [comment]
Hey ! 
Seems like you forgot to update the expo version in the peer dependencies of the @nrwl/expo package. When will it be updated ? It's causing issues that make us use `--legacy-peer-deps` with npm. 
Thanks

**Comment by xiongemi** [comment]
> 

Yes. i forgot to update it. i just submit pr to update it https://github.com/nrwl/nx/pull/13780

**Comment by Phillip9587** [comment]
@xiongemi There was already a PR to update that: #13747

**Pull request merged**
