### PR TITLE
fix(js): switch from fast-glob to tinyglobby

### PR DESCRIPTION
**Pull request by benmccann**
## Current Behavior
17 dependencies: https://npmgraph.js.org/?q=fast-glob

## Expected Behavior
2 dependencies: https://npmgraph.js.org/?q=tinyglobby

## Related Issue(s)

https://github.com/es-tooling/ecosystem-cleanup/issues/117

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks @benmccann got some task failures to take a look

**Comment by benmccann** [comment]
Thanks @JamesHenry. When I run `pnpm install` it's not updating the `package-lock.json` file. Is there some special setup this repository has around that? It seems the be the cause of the CI errors. I'm not sure if this is just some issue specific to my machine. If you're not familiar with this issue, any chance you could push a commit updating the lockfile for me?

> /home/workflows/workspace/packages/js/package.json
  61:5  error  The version specifier does not contain the installed version of "tinyglobby" package: 0.2.6  @nx/dependency-checks

**Comment by JamesHenry** [comment]
@benmccann The issue is that you haven't added `tinyglobby` to the root `package.json`

The repo doesn't (yet) use package manager workspaces, so your reference in the `@nx/js` package.json doesn't influence the installed packages in any way.

You can verify this with `pnpm why`:

```sh
❯ pnpm why tinyglobby                                                                                                                х 1 24s
Legend: production dependency, optional only, dev only

@nx/nx-source /Users/james/Repos/open-source/nrwl/nx-alt

devDependencies:
nuxt 3.13.2
├─┬ @nuxt/devtools 1.4.2
│ └── tinyglobby 0.2.6
└── tinyglobby 0.2.6
```

Right now the only way tinyglobby gets into the workspace is via a direct and transitive dependency from the `nuxt` package.

Therefore the fix is to run `pnpm add tinyglobby@^0.2.10`

**Review by JamesHenry — CHANGES_REQUESTED** [review]
Thanks @benmccann, sorry I should have remembered this earlier:

Every time we make one of these kinds of PRs we should add a lint entry to prevent regressions: https://github.com/nrwl/nx/blob/5d6119199937b8552655745d39b075cbe4a7df6c/packages/js/.eslintrc.json#L8

(It would be easy for a member of the team not familiar with this effort to add fast-glob back in again)

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
FYI I made it a fix pre merge so it gets called out in the changelog

**Pull request merged**
