### PR TITLE
fix(storybook): look for config dir/files relative to the project dir

### LINKED ISSUE #9115: Storybook executors cannot find config files in certain cases
## Current Behavior

The `@nrwl/storybook:*` executors allow for specifying the `options.config` object (which allows for defining `configFolder`, `configPath`, `srcRoot`, and `pluginPath`).  When used in a target, running `nx <target> <project-name>` will look for the paths defined in those configs, relative to where the command was run.

**Example**

libs/mylib/project.json snippet
```json
{
  "targets": {
    "executor": "@nrwl/storybook:storybook",
    "options": {
      "config": {
        "configFolder": "libs/mylib/.storybook"
      }
    }
  }
}
```

Will yield the following results:

```sh
pwd
# outputs: /absolute/path/.../my-monorepo

nx serve mylib
# looks for the config file located at: /absolute/path/.../my-monorepo/libs/mylib/.storybook

cd libs/mylib
pwd
# outputs: /absolute/path/.../my-monorepo/libs/mylib

nx serve mylib
# looks for the config file located at: /absolute/path/.../my-monorepo/libs/mylib/libs/mylib/.storybook
```

This behavior is inconsistent with most repository-based tooling, as well as with other @nrwl executors, like Jest.

## Expected Behavior

I expect to be able to run the Storybook-based targets/executors from any directory in the monorepo and have the configuration file resolve correctly with the same project.json file snippet provided above.  Ideally, there would need to be no changes to my project.json file (to avoid breaking others' projects).

### Failure Logs

```
> nx run mylib:serve --verbose
ENOENT: no such file or directory, stat 'libs/mylib/.storybook'
Error: ENOENT: no such file or directory, stat 'libs/mylib/.storybook'
    at statSync (node:fs:1527:3)
    at findOrCreateConfig (/Users/imyourmanzi/monorepo/node_modules/@nrwl/storybook/src/utils/utilities.js:106:50)
    at resolveCommonStorybookOptionMapper (/Users/imyourmanzi/monorepo/node_modules/@nrwl/storybook/src/executors/utils.js:119:64)
    at storybookOptionMapper (/Users/imyourmanzi/monorepo/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js:59:140)
    at storybookExecutor_1 (/Users/imyourmanzi/monorepo/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js:12:24)
    at storybookExecutor_1.next (<anonymous>)
    at resume (/Users/imyourmanzi/monorepo/node_modules/tslib/tslib.js:225:48)
    at fulfill (/Users/imyourmanzi/monorepo/node_modules/tslib/tslib.js:227:35)

———————————————————————————————————————————————

>  NX   ERROR  Running target "mylib:serve" failed
```

### Environment

```
  Node : 16.1.0
  OS   : darwin x64
  npm  : 7.11.2

  nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : 13.4.6
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : undefined
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : 13.4.6
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : 13.4.6
  @nrwl/gatsby : undefined
  typescript : 4.5.5
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

```

### PR DESCRIPTION
**Pull request by imyourmanzi**
## Summary

When specifying a config file/dir path in the executor options.config object, the `statSync()` call fails if the user does not run the `nx ...` command from the root of the repository/workspace. This is confusing and inconsistent with the way that other executors work, like `@nrwl/jest`.

## Current Behavior

_See related issue_

## Expected Behavior

_See related issue_

## Related Issue(s)

Fixes #9115

### CODE REVIEW

**Comment by mandarini** [comment]
Hi @imyourmanzi , thanks for this PR.

So, I tested your PR and I do not think it works as expected.

Say we have the following workspace structure:

```
my-root
--apps
  --app-angular-one
  --app-angular-two
  --app-react-one
  --app-react-two
--libs
  --lib-angular-one
  --lib-angular-two
  --lib-react-one
  --lib-react-two
```

and all these projects have Storybook configured.

Use cases:

* I am in root dir and I run `nx storybook <ANY-PROJECT>`: all works as expected.

## Running `storybook` from inside `apps/app-angular-one`
* I am in `apps/app-angular-one` and I run `nx storybook app-angular-one`: fails 
   -> The error is `no such file or directory, open 'package.json'` and it's triggered from [this line here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/utils/utilities.ts#L89)
* I am in `apps/app-angular-one` and I run `nx storybook app-angular-two`: fails 
   -> The error is `no such file or directory, open 'package.json'` and it's triggered from [this line here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/utils/utilities.ts#L89)
* I am in `apps/app-angular-one` and I run `nx storybook lib-angular-one`: fails 
   -> The error is `no such file or directory, open 'package.json'` and it's triggered from [this line here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/utils/utilities.ts#L89)
* I am in `apps/app-angular-one` and I run `nx storybook app-react-one`: almost works. Storybook fails with a syntax error, which does not get thrown when I run `nx storybook app-react-one` from root.

## Running `storybook` from inside `libs/lib-angular-one`
* I am in `libs/lib-angular-one` and I run `nx storybook lib-angular-one`: fails 
   -> The error is `no such file or directory, open 'package.json'` and it's triggered from [this line here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/utils/utilities.ts#L89)
* I am in `libs/lib-angular-one` and I run `nx storybook lib-angular-two`: fails 
   -> The error is `no such file or directory, open 'package.json'` and it's triggered from [this line here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/utils/utilities.ts#L89)
* I am in `libs/lib-angular-one` and I run `nx storybook app-angular-one`: fails 
   -> The error is `no such file or directory, open 'package.json'` and it's triggered from [this line here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/utils/utilities.ts#L89)
* I am in `libs/lib-angular-one` and I run `nx storybook lib-react-one`: almost works. Storybook fails with a syntax error, which does not get thrown when I run `nx storybook lib-react-one` from root.

## Running `storybook` from inside `apps/app-react-one`
* I am in `apps/app-react-one` and I run `nx storybook app-react-one`: works great
* I am in `apps/app-react-one` and I run `nx storybook app-react-two`: almost works. Storybook fails with a syntax error, which does not get thrown when I run `nx storybook app-react-two` from root.
* I am in `apps/app-react-one` and I run `nx storybook lib-react-one`: almost works. Storybook fails with a syntax error, which does not get thrown when I run `nx storybook lib-react-one` from root.

## Running `storybook` from inside `libs/lib-react-one`
* I am in `libs/lib-react-one` and I run `nx storybook lib-react-one`: works great
* I am in `libs/lib-react-one` and I run `nx storybook lib-react-two`: almost works. Storybook fails with a syntax error, which does not get thrown when I run `nx storybook lib-react-two` from root.
* I am in `libs/lib-react-one` and I run `nx storybook app-react-one`: almost works. Storybook fails with a syntax error, which does not get thrown when I run `nx storybook app-react-one` from root.

## Conclusion

This PR enables me to run Storybook from within the directory of the *React* app/lib I want to run Storybook for. I mean, it only works if:
* I am in `libs/lib-react-one` and I run `nx storybook lib-react-one`
* I am in `apps/app-react-one` and I run `nx storybook app-react-one`

In all the other cases it does not work.

Let me know if you want help debugging further. 

Again, thank you so much for contributing to Nx!!! :)

**Review by mandarini — CHANGES_REQUESTED** [review]
Needs changes to address comment I added in the PR.

**Comment by imyourmanzi** [comment]
Hi @mandarini, thank you for the extremely detailed review!  I'll be sure to check out that test repo you've setup and see if I can't get these use cases smoothed out!

**Comment by mandarini** [comment]
Perfect, thanks! :D

**Comment by imyourmanzi** [comment]
Hi Nx team, this fix turned into a much larger can of worms than anticipated and how it works independently with both React and Angular and then also with the other packages in Nx.  I'm closing this now to communicate that I'm no longer working on it.

This is as far as I've gotten:

## Notes

- [x]  Relative paths for config folder/files
    - v999.0.6
- [x]  Relative path for **package.json**
    - v999.0.7
- [x]  Relative path for output dir
    - v999.0.8
- [x]  Relative path for **tsconfig.json**?
    - v999.0.12
- [ ]  Relative path for a **.angular/** folder?
- [ ]  There’s a `cwd` in the Storybook config that probably isn’t set correctly
- [ ]  Running Storybook in v999.0.12 messes up Angular imports

### v999.0.12

- runs the storybook server and everything just fine but there’s a problem with Angular component imports via HTML/template selector in Storybook

### Storybook Dependency Graph

- Start Storybook
- Angular (Ivy)
- Webpack 5

IMG_3703

## Test Cases

The are two libs, one React and one Angular, and two apps, one React and one Angular.

### From Workspace/Monorepo Root

#### Run `storybook`

  | React | Angular
-- | -- | --
lib | ✅ (v999.0.8) | ✅ (v999.0.8)
app | ✅ (v999.0.8) | ✅ (v999.0.8)

#### `build-storybook`

  | React | Angular
-- | -- | --
lib | ✅ (v999.0.8) | ✅ (v999.0.8)
app | ✅ (v999.0.8) | ✅ (v999.0.8)

### From React Lib

#### Run `storybook`

  | React | Angular
-- | -- | --
lib | ✅ (v999.0.8) | ❌ (v999.0.12)
app | ✅ (v999.0.12) | ❌ (v999.0.12)

#### `build-storybook`

  | React | Angular
-- | -- | --
lib | ✅ (v999.0.8) | ⚠️ (v999.0.8)
app | ❌ (v999.0.8) | ❌ (v999.0.8)

### From Angular Lib

#### Run `storybook`

  | React | Angular
-- | -- | --
lib | ❌ (v999.0.8) | ⚠️ (v999.0.8)
app | ❌ (v999.0.8) | ❌ (v999.0.8)

#### `build-storybook`

  | React | Angular
-- | -- | --
lib | ❌ (v999.0.8) | ⚠️ (v999.0.8)
app | ❌ (v999.0.8) | ❌ (v999.0.8)

### From React App

#### Run `storybook`

  | React | Angular
-- | -- | --
lib | ❌ (v999.0.8) | ⚠️ (v999.0.8)
app | ✅ (v999.0.8) | ❌ (v999.0.8)

#### `build-storybook`

  | React | Angular
-- | -- | --
lib | ❌ (v999.0.8) | ⚠️ (v999.0.8)
app | ✅ (v999.0.8) | ❌ (v999.0.8)

### From Angular App

#### Run `storybook`

  | React | Angular
-- | -- | --
lib | ❌ (v999.0.8) | ⚠️ (v999.0.8)
app | ❌ (v999.0.8) | ❌ (v999.0.8)

#### `build-storybook`

  | React | Angular
-- | -- | --
lib | ❌ (v999.0.8) | ⚠️ (v999.0.8)
app | ❌ (v999.0.8) | ❌ (v999.0.8)

**Comment by mandarini** [comment]
Hi there @imyourmanzi ! I just saw your last comment here! Thank you very very much for giving this a shot, and of course thank you for the detailed analysis that you provided after making all this research! I am sure it will come in handy in the future!!

Let me know if you ever need anything, and thank you again so much for contributing!!!

**Pull request closed without merging**
