### PR TITLE
docs(nx-cloud): edit incorrectly number of dynamic-agents

### PR DESCRIPTION
**Pull request by Abd3lwahab**
Change wrong number in nx-cloud docs which determine  number of agents for small changes which is 3 not 1

The workflow is:
```yaml
distribute-on:
  small-changeset: 3 linux-medium-js
  medium-changeset: 6 linux-medium-js
  large-changeset: 10 linux-medium-js
```

but docs says:

`Now PRs that affect a small percentage of the repo will run on 1 agent, .....`

Which is not matching the workflow and it should be 3 not 1  

https://nx.dev/ci/features/dynamic-agents#dynamically-allocate-agents

### CODE REVIEW

**Comment by Abd3lwahab** [comment]
@StalkAltan @rarmatei Review Please

**Review by rarmatei — APPROVED** [review]

**Comment by rarmatei** [comment]
thank you for this! 🎉

**Comment by Abd3lwahab** [comment]
> thank you for this! 🎉

@rarmatei  You 're welcome, 

There's workflow pending approval

**Comment by Abd3lwahab** [comment]
@rarmatei Will this be merged ?

**Review by isaacplmann — APPROVED** [review]

**Pull request merged**
