### PR TITLE
feat(react): add SVG and SVGR support for React apps

### PR DESCRIPTION
**Pull request by jaysoo**
Adds SVG and SVGR support for React apps.

- [x] Add SVGR (SVG as React component) support via `@svgr/webpack`.
- [x] Add SVG file support via `url-loader`.
- [x] Update jest config to support SVG files.
- [ ] (Maybe?) Provide our own typings that can be installed rather than relying on `custom.d.ts` to contain the correct content. This may make future changes much easier since we control the file, but we may need to create a new package for this purpose.

### CODE REVIEW

**Comment by devinshoemaker** [comment]
What's the status of this? I'd love to put it to some use. 😄

**Comment by jaysoo** [comment]
@devinshoemaker I want to spend some more time looking at adding our own typings package rather than adding `custom.d.ts`to individual projects.

**Comment by stramel** [comment]
@jaysoo Have you had anytime to look into providing your own typings yet?

The reason I ask is that there isn't a way to handle this without this PR or embedding each SVG into a component manually. Personally, I would like to see this PR go through as is to unblock this functionality. I think we could provide the typing at a later point as an enhancement to this feature.

**Comment by jaysoo** [comment]
@stramel Yes, we should publish the typings as a separate package. I'll see what I can do to get this into the next release, or the release after. For now there is a workaround if you're willing to write your own custom babel config and typings.

**Pull request merged**
