### PR TITLE
feat(next): custom next config

### LINKED ISSUE #3692: RFC: allow next.js configuration participation from builder
## Description

When executing NX next.js builders, I want modify the next.js configuration. However, nx gives me no provisions to do so directly. Instead, nx/next simply loads config using next.js builtin functions. To modify my next.js config via a builder, I must mutate my env, e.g. `process.env.TURN_ON_FEATURE`, then sniff for such an env var in my next.config.js, because no programmatic exposure let's me tune the resultant next config programmatically. This amount of indirection is a bit of a code smell.

## Motivation

To allow us to participate in next.js configuration programatically

## Suggested Implementation

To solve this let's add an option to the `NextServeBuilderOptions`. Perhaps the API could be as follows:

`NextServeBuilderOptions["customizeNextConfigFilename"] = string` which maps to a function: `(nextConfig: NextConfig) => NextConfig`

## Alternate Implementations

Rather than allow for a `string` to a file, instead, just allow for a function directly on the `NextServeBuilderOptions`. This would mean that users would need to implement a custom builder to place such a function onto the options. Simpler, but doesn't allow usage out-of-the-box with nrwl/next builder

### PR DESCRIPTION
**Pull request by benmonro**
## Current Behavior

No support for custom next configurations in next builder.

## Expected Behavior

support for custom next configurations in next builder.
## Related Issue(s)

Fixes #3692

### CODE REVIEW

**Comment by llwt** [comment]
Any thoughts on this @FrozenPandaz / @vsavkin? 

We weren't entirely sure what the best way to add programatic extension into the builder was but this API allowed us to implement the customization we needed without hard-forking the builder. If there's a better way to handle this please let us know.

**Comment by vsavkin** [comment]
@llwt taking a look, will provide feedback today

**Comment by jaysoo** [comment]
Hi @benmonro, thanks for taking time to submit this PR.

Are you able to customize the config by updating the generated `next.config.js` file for the app?

If you need to hook into different phases, you can do the following:

```
const { PHASE_PRODUCTION_BUILD } = require('next/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_BUILD) {
    console.log('PHASE_PRODUCTION_BUILD', defaultConfig);
    return {
      /* prod build options here */
    };
  }

  return {
    /* config options for all other  phases */
  };
};
```

Would that solve your issue?

**Comment by benmonro** [comment]
Hi @jaysoo unfortunately no.  If we do that then we have no way of passing args from our builder into the next config other than adding a bunch of environment variables which we are trying to avoid

**Comment by llwt** [comment]
Additionally it doesn't leave us with a great story for sharing next configuration between apps. We have multiple next apps in our monorepo that we'd like to provide central configuration for.

Currently we're relegated to a combination of relative imports into a shared config space.

A concrete example (simple-case) of something we're trying to support is an `--analyze` flag. Currently we have to:

**In the builder**
```ts
import { run as buildNext } from "@nrwl/next/src/builders/build/build.impl";
// ...

export const build: BuilderHandlerFn<Schema> = async (options, context) => {
  // ...
  process.env.ANALYZE = options.analyze.toString()
  // ...
  buildNext(...) // < from nrwl
```

**In our apps' next.config.js:**
```js
const {
  withNextBundleAnalyzer,
  // ...
} = require("../../../libs/platform/next-config"); // This relative import also sucks :) 

// ...
module.exports = (_, { defaultConfig }) =>
  pipe(
    (config) => ({
      // ... next config values
      publicRuntimeConfig: { /* ... */ }
    },
    withNextBundleAnalyzer,
    // ... other config mixins
  )(defaultConfig);
```

**In `libs/platform/next-config/with-next-bundle-analyzer.js`**

```js
export const withNextBundleAnalyzer = (config) => {
  if (ANALYZE !== "true") {
    return config;
  }
  const nextBundleAnalyzer = require("@next/bundle-analyzer");
  return nextBundleAnalyzer({
    enabled: true,
  })(config);
};
```


---

With the proposed API it all moves to our builder and gets a bit simpler:

```ts
import { run as buildNext } from "@nrwl/next/src/builders/build/build.impl";
import withNextBundleAnalyzer from "@next/bundle-analyzer";
// ...

export const build: BuilderHandlerFn<Schema> = async (options, context) => {
  const addAdditionalNextConfig = (_: NextConfigPhase, config: any) => {  
    if (options.analyze) {
      config = withNextBundleAnalyzer({ enabled: true })(config);
    }
  }

  // ...
  buildNext(..., addAdditionalNextConfig) // < from nrwl
```

**Comment by jaysoo** [comment]
@benmonro @llwt Okay I understand what you're trying to do now. Can we make some changes?

Add a `nextConfig` as a builder option to `nx/packages/next/src/builders/build/schema.json` -- similar to the `webpackConfig` option for web builder (https://github.com/nrwl/nx/blob/master/packages/web/src/builders/build/schema.json#L234).

This will be more inline with how we make our builders extensible. Let me know if you have any questions.

**Comment by benmonro** [comment]
@jaysoo are you saying that the nextConfig should be a path to a module that provides the config?  That's essentially the same problem that we have now using next.config.js in that we would have to set env vars in our builder so that the custom config could pick up those args.  or am I missing something?

**Comment by llwt** [comment]
@benmonro The way the web builder works in this case is it passes the builder options into the function exported from that configured value:

https://github.com/nrwl/nx/blob/ea71278aba9bf1581c64671dd29aee6690e75be2/packages/web/src/builders/build/build.impl.ts#L146-L149

---

@jaysoo, this was actually one of the first options we considered but it left us in a weird place of needing to dynamically modify the builder options from our builder before calling the `nrwl/next` builder. Specifically, we are generating an asset prefix from our CDN that we need available in the next config among other things.

If we went this route we'd need to venture into `type-unsafe` territory in order to pass builder options through the `nrwl/next` builder to make them available to the next config callback.

```ts
import { run as buildNext } from "@nrwl/next/src/builders/build/build.impl";
// ...

export const build: BuilderHandlerFn<Schema> = async (options, context) => {
  // Dynamically generated values
  options.nextAssetPrefix = /* ... */
  options.nextBuildId = /* ... */

  // ...
  buildNext(  // < from nrwl
    options, // < Type error due to nextAssetPrefix, nextBuildId, analyze, and any other properties being unexpected 
    context,
  )
```

The first thing that comes to mind is an "object/any" typed additional property that gets passed along to the config function. Something like:

**ourBuilder**
```ts
export const build: BuilderHandlerFn<Schema> = async (options, context) => {
  const nrwlNextBuilderOptions = omit(options, /* things nrwl isn't expecting */);

  nrwlNextBuilderOptions.nextConfig = 'example/custom-next-config.js'; /* probabbly set in workspace.json? */

   //                    vvv -- typed as "any" to allow us to pass through arbitrary values
  nrwlNextBuilderOptions.additionalNextConfigOptions = {
    analyze: options.analyze,
    nextBuildId: /* ... */
  }
  
  
  // ...
  return buildNext(nrwlNextBuilderOptions, context)
}
```

**example/custom-next-config.js**
```js
module.exports = (nextPhase, nextConfig, nextBuilderOptions, additionalNextConfigOptions) => {
  if (additionalNextConfigOptions.analyze) {
    nextConfig = withNextBundleAnalyzer({ enabled: true })(nextConfig);
  }

  return nextConfig
}
```

Is something like ☝️ what you're proposing?

**Comment by jaysoo** [comment]
@benmonro Note that `NextBuildBuilderOptions` extends `JsonObject` so you can pass arbitrary values in without type error. https://github.com/nrwl/nx/blob/master/packages/next/src/utils/types.ts#L33

Let me think about this for a bit, because your goal is basically to be able to change the next.config.js for your custom builder (that extends the default one). For example `nx build my-app --analyze` will use the  `withNextBundleAnalyzer` enhancer on the next config.

**Comment by benmonro** [comment]
@jaysoo yes that and more.  We have a number of other flags as well that we've Gathered in the builder.  Since we have them in hand in the builder, it would be much preferable to apply the additional config right there rather than having to add another layer of indirection/complexity.  I'd be happy to get on a zoom and show you our use case if that helps

**Comment by jaysoo** [comment]
@benmonro @llwt I think `nextConfig` makes the most sense since it is symmetrical to how we are handling webpack config in the web build builder.

1. In your custom builder you can do the following:

```ts
import {  BuilderContext,  BuilderOutput,  createBuilder } from '@angular-devkit/architect';
import { Observable } from 'rxjs';
import { run } from '@nrwl/next/src/builders/build/build.impl';
import { NextBuildBuilderOptions } from '@nrwl/next/src/utils/types';

export default createBuilder<NextBuildBuilderOptions>(customRun);

export function customRun(
  options: NextBuildBuilderOptions,
  context: BuilderContext
): Observable<BuilderOutput> {
  // Resolve the local module to pass as a path string
  options.nextConfig = require.resolve('./custom-config');

  return run(options, context);
}
```

2. And then in the `custom-config.js` file:

```ts
import * as withNextBundleAnalyzer from '@next/bundle-analyzer';
import { PHASE_PRODUCTION_BUILD } from 'next/dist/next-server/lib/constants';

module.exports = (phase, config, { options } /* the builder options are passed  in the context */) => {
  if (phase === PHASE_PRODUCTION_BUILD && options.analyze) {
    config = withNextBundleAnalyzer({ enabled: true })(config);
  }
  return config;
};

```

3. Finally, you can call `nx build my-app --analyze` with your custom builder and that will enhance the next config.

**Comment by benmonro** [comment]
@jaysoo that would be much appreciated if you want to take over this.  before merging can you let me try it in our environment to make sure it works with what we're doing?

Thanks
Ben

**Comment by llwt** [comment]
@jaysoo Sorry for the radio silence but that makes sense. As ben mentioned if ya'll have cycles it would be awesome for an assist on this, otherwise we can pull it back into our backlog soon-ish.

**Comment by jaysoo** [comment]
@benmonro @llwt Sounds good, I will push an update to this PR and you can test it out on your end.

**Comment by jaysoo** [comment]
@benmonro I've opened the new PR here: #3899 

Going to close this PR and move the conversation to the new PR. Let me know if it works for you or not -- I tried it locally and it's working for my own setup

**Comment by llwt** [comment]
Thank you @jaysoo! I've pushed this to the top of our backlog and we'll have someone verify shortly.

**Pull request closed without merging**
