### PR TITLE
feat(storybook): allow to specify angular target project for storybook

### LINKED ISSUE #3655: @nrwl/storybook Set Project/App to take build config
I'm running Storybook on an Angular project for a UI library. When running `nx run ui:storybook` the build configuration is taken from the `defaultProject` property in `angular.json`

```
info => Using angular project 'default-app' for configuring Storybook.
```

Is it possible to set build configs for each storybook implementation, or point the builder to a specifically configure app within the monorepo?

### PR DESCRIPTION
**Pull request by hiepxanh**
# feat(storybook): adding enviroment variable which allow storybook get angular project target

Since this PR https://github.com/storybookjs/storybook/pull/12565 already merge, and going to release with storybook 6.1.
As he said: "Basically, we now verify if there is an environment variable called "STORYBOOK_ANGULAR_PROJECT". If so, we use its value as the project name."
This PR going to add an enviroment variable call "STORYBOOK_ANGULAR_PROJECT" and the storybook going to catch that enviroment variable. Then it can recognize the project name correctly.
This PR only to work with the new storybook version, so why we not release the update first, then after they release it. Every body automatic got this feature :D voila

## Current Behavior

image

Using "default" project from `angular.json` to run storybook

## Expected Behavior
Using project target while using storybook

## Related Issue(s)
Fixes #3655 #4305

### CODE REVIEW

**Comment by hiepxanh** [comment]
Sad, why I adding enviroment variable causing fail test

**Comment by hiepxanh** [comment]
@juristr  hello sir, can you help me to verify the new code? storybook 6.1 has been release and it should work with my new code, but I dont understand, why it fail

**Comment by juristr** [comment]
Hey thx for the contribution. I'll give it a look next week

**Comment by juristr** [comment]
@hiepxanh the problem why the build fails is due to the git commit message check:

image

Can you squash your two commits and use this message:

`feat(storybook): adding environment variable for storybook to find correct angular project target`

Thx :)

**Comment by hiepxanh** [comment]
@juristr yes sir, I already pushed new commit

**Comment by hiepxanh** [comment]
@juristr  I already follow the instruction, why it still fail sir?
image

**Comment by hiepxanh** [comment]
@juristr   my yarn verified it 
image

**Comment by juristr** [comment]
@hiepxanh they aren't failing due to the commit message this time. There was some error in the pipeline, might have been a CircleCI issue. I'll restart them and then we'll see.

**Comment by hiepxanh** [comment]
thank you sir

**Comment by juristr** [comment]
@hiepxanh looks like something went wrong with your original rebase. Anyway, I fixed it and pushed again to your branch. The PR looks good to me. I'll give it a test run and then merge it.

I just want to get the upgrade to Storybook v6.1 in first as well before I merge this one.

Thx for your contribution :)

**Comment by hiepxanh** [comment]
wow! thank you so much sir, sorry for my clumsy

**Comment by hiepxanh** [comment]
@juristr dont you mind if you take a look with my PR?

**Comment by juristr** [comment]
I did, but I have to think this through more deeply. Your PR works on apps, however needs some improvements when you run storybook in libs.

Right now we're busy on preparing the Nx 11 release. I'll take a closer look immediately after that

**Comment by hiepxanh** [comment]
:D resolved conflict

**Comment by juristr** [comment]
@hiepxanh I'm looking at your PR right now. The main issue here is that in this way when you generate a storybook config for an Nx library, the according "build" won't be found, thus you get something like
 
```
ERR! architect.build is not defined for project 'ui'.
``` 

(where `ui` is my Nx lib). Because now the library config in workspace.json is being used which doesn't have a build config. Which might be fine, but changes the behavior compared to before, where some of the app's configs in the workspace would have been used.

I'm wondering whether we should give the possibility to specify a property in the `storybook` config in the `workspace.json` that allows to point to an app that should be used as the config 🤔 . I'm going to give that a quick try tomorrow and push a fix in case s.t. we can get this merged

**Comment by hiepxanh** [comment]
thank you, that is a greate idea,I think your solution should be fine 😄

**Comment by juristr** [comment]
@hiepxanh here's the solution I came up with.

a) "app" type projects will always get the `context.target.project` as that's the only thing that makes sense.

b) if "lib" type projects are being started with storybook, then the normal storybook app resolution will take place, unless you specify a different app project in the corresponding configuration in the "angular.json" (or workspace.json).
Say you have a lib `ui`, then the storybook config could look like

```
"storybook": {
  "builder": "@nrwl/storybook:storybook",
  "options": {
    "uiFramework": "@storybook/angular",
    "port": 4400,
    "appBuildConfig": "testapp", // <<<<<<<<<
    "config": {
      "configFolder": "libs/ui/.storybook"
    }
  },
  "configurations": {
    "ci": {
      "quiet": true
    }
  }
},
```

By adding `appBuildConfig` to `testapp`, then Storybook will use the `testapp` as the Angular app to fetch the config from.

What do you think? Also, if you have a better name in mind than `appBuildConfig` let me know 😅. It works locally, going to wrap it up tomorrow or latest Monday. I'll then push it up onto your branch and we merge this PR in the end, ok? Let me know what you think

**Comment by hiepxanh** [comment]
Yes, that exactly what I'm thinking of. I belive the `appBuildConfig` name should be `projectBuildConfig` since that you can point to an application or a library, for example:
- projectBuildConfig: nx-airplane
- projectBuildConfig: nx-airplane-ui 
that is look perfect :D

**Pull request merged**
