### PR TITLE
feat(angular): add tailwind support when building publishable libraries

### PR DESCRIPTION
**Pull request by leosvelperez**
## Current Behavior

When building a publishable library, Tailwind directives (e.g. `@apply`) are not processed because `ng-packagr` doesn't support Tailwind out of the box and it doesn't allow either to provide our own PostCSS configuration.

For more details see https://github.com/nrwl/nx/issues/6924#issuecomment-937900166.

## Expected Behavior

Building a publishable library that uses Tailwind should correctly process any directive found in the stylesheets.

Given `ng-packagr` doesn't support Tailwind natively (as the `@angular-devkit/build-angular:browser` does) and it doesn't allow us to specify custom PostCSS config, we need to provide a different implementation that does support Tailwind natively. This provides a similar experience to Angular applications where Tailwind just works.

## Related Issue(s)

Fixes #

### CODE REVIEW

**Review by Coly010 — APPROVED** [review]
Only make that change if you can, it's not a big deal, just something else that will need to be changed for Angular 13

**Review by juristr — CHANGES_REQUESTED** [review]
LGTM overall. I'm really wondering whether we should ping the ng-packagr folks about whether they would want to integrate this into ng-packagr directly...rather than having to duplicate a lot of the stuff on our side as well.

It was already required and kinda painful for the buildable libs... 😅

**Review by juristr — APPROVED** [review]

**Comment by fnnzzz** [comment]
Guys, hello, what about only buildable libs, in our case we're using only buildable libs for an incremental approach and used patch-package for patch the ng-packagr directly before.
I hoped this PR will be salvation, but it's not.
I could offer my help on this issue

**Comment by ohabash** [comment]
Does any one have a highlevel list of steps to take so that `nx build myPublishableLib` will include JIT and other tailwind styles?

**Pull request merged**
