### PR TITLE
fix(core): use concat in buildAllWorkspaceFiles to avoid Maximum call stack size exceeded

### PR DESCRIPTION
**Pull request by chentsulin**
Use `.concat` instead of `.push(...arr)` to avoid `Maximum call stack size exceeded`.

## Current Behavior

Got this error in an large monorepo:

```
/home/********/project/node_modules/.pnpm/nx@16.5.0/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:68
    fileData.push(...globalFiles);
             ^

RangeError: Maximum call stack size exceeded
    at buildAllWorkspaceFiles (/home/********/project/node_modules/.pnpm/nx@16.5.0/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:68:14)
    at /home/********/project/node_modules/.pnpm/nx@16.5.0/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:43:32
    at Generator.next (<anonymous>)
    at fulfilled (/home/********/project/node_modules/.pnpm/tslib@2.6.0/node_modules/tslib/tslib.js:166:62)
```

## Expected Behavior

Do not throw `RangeError: Maximum call stack size exceeded`

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by Cammisuli** [comment]
Thanks for the PR! I seen someone complain about this before, but they didn't give me much info, and the problem was fixed for them when they used a different version of Node. 

Is the Nx workspace that gave you this error open source or available for me to use as a benchmark?

**Review by Cammisuli — APPROVED** [review]

**Comment by chentsulin** [comment]
@Cammisuli It's a private repo, so I can't share with you. Sorry for that.

**Comment by Cammisuli** [comment]
@chentsulin can I get some details on the workspace? How many projects do you have, and how many global files were there as well?

**Comment by chentsulin** [comment]
@Cammisuli AFAICT, we have more than 100 packages and 30 Next.js websites.

**Pull request merged**
