### PR TITLE
docs(bundling): correct esbuild options nesting

### PR DESCRIPTION
**Pull request by vmasek**
Fixes:

- [x] correct nesting of options in ESBuild docs

### CODE REVIEW

**Comment by pumano** [comment]
@vmasek looks like build failed due to documentation, try to build docs and update snapshots (try to check package.json for commands)

**Comment by vmasek** [comment]
@pumano thanks, I did the PR quickly in GitHub online IDE but I see I need to have Rust & Cargo installed for `nx run @nx/nx-source:documentation` and updating it, so it calls for proper computer experience 😅

**Comment by pumano** [comment]
@vmasek I highly recommend install rust via https://www.rust-lang.org/tools/install because installing from brew can cause problems later

**Review by Coly010 — APPROVED** [review]

**Comment by vmasek** [comment]
@Coly010 Thanks for picking it up, I had some difficulties setting up rust and then forgot about this PR 😅

**Pull request merged**
