### PR TITLE
feat(schematics): move command-cli to a separated package

### PR DESCRIPTION
**Pull request by nweldev**
As command-line nx isn't, strickly speaking, part of the schematics, it seems logical to move it to
a new, separated ``@nrwl/cli`` package.

This will permit, to begin with, two things :
1. use the nx cli in any project : in order to permit this, we'll need to add some more flexibility, for example by permitting to configure the folders / projects architecture
2. make the nx cli compatible with angular-cli v6 (new step by step approach for #412) before the global nrwl/nx refactoring, as it could be done really faster

The next step could be to make a PR to angular/devkit or angular-cli in order to add some of the features covered by the cli (mainly "affected") to it.

For now, the e2e tests are failing, as the addition of the @nrwl/cli dependency to the package.json schematics will require a first release of this new package.

NB: as ``@nrwl/schematics`` requires ``@nrwl/cli``, the two version numbers should be always the
same.

### CODE REVIEW

**Comment by noelmace** [comment]
FYI : my use case leading to this PR is the following : 
in a mono-repository using angular-cli v6, I need, for the CI, to identify affected apps and libs between two commits. As this is exactly what nx affected is doing, I investigated the code and think that I could adapt it to angular-cli v6 multi-projects repository.

We should also identify btw what commands could be relevant outside nx projects, the ones that could not, and add some verification (maybe based on the presence of @nrwl/schematics as a dependency in package.json, maybe on the folder names) in order to block the use of this last commands in angular-cli v6 projects. This could also permit to switch between nx projects file structure and configuration and angular-cli v6 ones at runtime.

For now, I thinks only the following commands would be relevant outside nx projects : 
* ``affected`` (apps & libs) : will require to use the new angular-cli config format, in order, for example, to differentiate libraries from applications
* ``dep-graph``
* ``format``

``Lint`` could also be relevant, but I thinks this would be better to make this in codelyzer instead.

**Comment by noelmace** [comment]
You can test the e2e with the fork branch of https://github.com/noelmace/nx, but there is still a problem as ``../node_modules/.bin/ng new proj --collection=@nrwl/schematics --npmScope=proj`` (same command as the one used in ``e2e/utils.ts#newProject()``) outputs the following error :
```
Error: cliVersion is not defined
cliVersion is not defined
````

Does the e2e relies really on the published packages, or am I missing something here ?

**Comment by noelmace** [comment]
So, as @vsavkin recently did an update to Angular CLI v6, I'm currently working on resolving the related conflicts, testing it in an Angular CLI v6 project, and will make some feedbacks if necessary.

**Comment by vsavkin** [comment]
Thank you for your PR. Unfortunately, I won't be able to merge it.

We discussed creating a separate CLI package at Nrwl, and with the Angular CLI team, and we decided against it. Here are the reasons:

1. Nx is just an extension to the Angular CLI. Having a separate CLI package sends a wrong message as if Nx were a competing CLI, which it is not.

2. The users should use `ng new myworkspace --collection=@nrwl/schematics`, or `ng new myworkspace && ng add @nrwl/schematics`. The only reason to use `create-nx-workspace` is when your global node modules are messed up. We will update the docs to reflect that.

That's why, even though it is not very clean, we decided to keep create-nx-workspace where it is right now.

**Comment by noelmace** [comment]
Ok, I understand your point here, even if this PR wasn't about create-nx-workspace, but just about the `nx` CLI ("command-line" folder in schematics). Did you talked with the core team about proposing a PR to angular/cli adding some of this features, like "affected:apps" ?

**Pull request closed without merging**
