### PR TITLE
docs(nx): add storybook guide

### PR DESCRIPTION
**Pull request by isaacplmann**
_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

> _Please make sure that your commit message follows our format._

> Example: `fix(nx): must begin with lowercase`

### CODE REVIEW

**Comment by vsavkin** [comment]
Wouldn't it be better to split it into two guides: one for react and one for angular?

**Comment by isaacplmann** [comment]
@vsavkin, what are you imagining?

Should I add two separate pages under `Guides`?

Guides
- Using Storybook with Angular
- Using Storybook with React

**Comment by isaacplmann** [comment]
@vsavkin, I split the guide into two guides.  `Using Storybook with Angular` and `Using Storybook with React`

**Comment by jaripekkala** [comment]
This is exactly what I was looking for. Awesome!

Could there also be instructions how to setup the storybook initially? If you follow the guide right now you will get errors for the required dependencies not been installed.

As a Nx newbie I really like how the docs are written. They are straightforward and don't skip any required steps.

**Review by jaysoo — APPROVED** [review]

**Pull request merged**
