### PR TITLE
fix(core): fix project dependency resolution for relative imports on windows

### LINKED ISSUE #5002: Explicit project dependencies are not recognized for relative imports on windows
## Current Behavior
Explicit project dependencies are not recognized properly for relative imports between projects on windows. That leads to different project-graphs on windows systems than on unix systems and can cause much confusion.

## Expected Behavior
Explicit project dependencies should be recognized properly for relative imports on windows to get a the same project graph unindependent of the executing OS.

## Steps to Reproduce
Run the test `findTargetProjectWithImport.should be able to resolve a module by using relative paths` in this repo for the `packages/workspace/src/core/target-project-locator.spec.ts` on a windows system and it will fail, because the project dependency can not be resolved.
It seems to be caused by the path.join in this line, which replaces the slashes in the path with backslahes on windows: https://github.com/nrwl/nx/blob/593b9a9a7b8e7c2b4c1cf0c7ece6d9f375e8c212/packages/workspace/src/core/target-project-locator.ts#L63
That leads to an always failing comparison with the project path in the method `findProjectOfResolvedModule`: 
https://github.com/nrwl/nx/blob/593b9a9a7b8e7c2b4c1cf0c7ece6d9f375e8c212/packages/workspace/src/core/target-project-locator.ts#L124

### Failure Logs
#Jest test failure output:
`Error: expect(received).toEqual(expected) // deep equality

Expected: "proj"
Received: undefined

    at Object.<anonymous> (C:\Users\johannes.fischenbeck\Desktop\src\nx\packages\workspace\src\core\target-project-locator.spec.ts:232:18)
    at Object.asyncJestTest (C:\Users\johannes.fischenbeck\Desktop\src\nx\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at C:\Users\johannes.fischenbeck\Desktop\src\nx\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (C:\Users\johannes.fischenbeck\Desktop\src\nx\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at C:\Users\johannes.fischenbeck\Desktop\src\nx\node_modules\jest-jasmine2\build\queueRunner.js:75:41`

### Environment
  Node : 14.6.0
  OS   : win32 x64
  yarn : 1.19.0

  nx : Not Found
  @nrwl/angular : 11.2.10
  @nrwl/cli : 11.5.0-beta.0
  @nrwl/cypress : 11.5.0-beta.0
  @nrwl/devkit : 11.5.0-beta.0
  @nrwl/eslint-plugin-nx : 11.5.0-beta.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.0-beta.0
  @nrwl/linter : 11.5.0-beta.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.5.0-beta.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.0-beta.0
  @nrwl/web : 11.5.0-beta.0
  @nrwl/workspace : 11.5.0-beta.0
  @nrwl/storybook : 11.2.10
  @nrwl/gatsby : Not Found
  typescript : 4.0.5

### PR DESCRIPTION
**Pull request by johannesf95**
## Related Issue(s)
#5002 Explicit project dependencies are not recognized for relative imports on windows

Fixes #5002

### CODE REVIEW

**Comment by bekos** [comment]
@johannesf95 Thank you very much. It LGTM 👍  Nit, but maybe we want to replace `join` with `joinPathFragments` from `@nrwl/devkit` instead of using `posix.join` 🤔  cc: @FrozenPandaz

**Comment by johannesf95** [comment]
@bekos sure, makes more sense to use an existing helper function. Didn't know that it existed. Feel free to replace it.

**Comment by bekos** [comment]
@johannesf95 can you do it and squash your commits afterwards?

**Review by FrozenPandaz — APPROVED** [review]
LGTM! :tada: 

Thank you for your contribution!

We don't need to use the `joinPathFragments` :shrug:

**Pull request merged**
