### PR TITLE
chore(core): nx plugin submission @computas/nx-yarn

### PR DESCRIPTION
**Pull request by AndyClausen**
_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

# Community Plugin Submission

Thanks for submitting your Nx Plugin to our community plugins list. Make sure to follow these steps to ensure that your PR is approved in a timely manner.

## Steps to Submit Your Plugin
- [x]  Use the following commit message template: `chore(core): nx plugin submission [PLUGIN_NAME]`
- [x]  Update the `community/approved-plugins.json` file with a new entry for your plugin that includes `name`, `url`, `description`:

Example:

```json
// community/approved-plugins.json

[{
    "name": "@community/plugin",
    "url": "https://github.com/community/plugin",
    "description": "This plugin provides the following capabilities."
}]
```

Once merged, your will plugin will be available when running the `nx list` command, and will also be available in the Plugin browser on [nx.dev](https://nx.dev)

### CODE REVIEW

**Comment by AgentEnder** [comment]
Hey @AndyClausen! Thanks for the submission, generally we like to see some e2e tests for plugins. Can you add one for the publish process? You'll probably want to look into verdaccio for this case.

Thanks!

**Comment by AndyClausen** [comment]
I'll try to make time for it soon, thanks for the pointer!

**Review by AgentEnder — APPROVED** [review]

**Comment by AgentEnder** [comment]
Hey @AndyClausen! If you go ahead and resolve the conflict we can get this merged :), e2e is nice but its not been consistently enforced.

**Comment by AndyClausen** [comment]
> If you go ahead and resolve the conflict

Done 🚀

> e2e is nice but its not been consistently enforced.

Alright, I will still add some e2e when I have the time for it :)

**Pull request merged**
