### PR TITLE
feat(core): add presetVersion flag for the create-nx-workspace

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
## Current Behavior

Right now `create-nx-workspace` only allows to provide a strict version of the preset in the format `--preset=package@x.x.x`
## Expected Behavior

This PR enhances the flow with the following:
- adding an ability to specify more generic versions of preset package inline (e.g. `package@12` instead of `package@12.1.1`)
- adding an ability to use separate `--presetVersion` flag to gain more control: be able to specify beta version or even paths like `--presetVersion=/Users/..../dist/package.tgz`. This should also be very useful for e2e tests of those packages so that it is possible to test the preset against different versions of nx.

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
Hey @dmitry-stepanenko,

We actually had a very similar idea in the works. We are going to go with a `NX_E2E_PRESET_VERSION` environment variable.

Your logic looks great though so I just modified it to not use a Regex and not expose an option for `create-nx-workspace`. You can run `create-nx-workspace` and have `NX_E2E_PRESET_VERSION=Users/..../dist/package.tgz`.

We'll take it from here.

Thank you for your contribution!

**Comment by dmitry-stepanenko** [comment]
@FrozenPandaz thanks a lot!

**Comment by dmitry-stepanenko** [comment]
Just curious, are you going to add any new e2e logic that leverages this?

**Comment by AgentEnder** [comment]
> Just curious, are you going to add any new e2e logic that leverages this?

The e2e tests for the create-package generator will use this, see: https://github.com/nrwl/nx/pull/15994

**Review by AgentEnder — APPROVED** [review]

**Pull request merged**
