### PR TITLE
feat(fastify): added fastify plugin

### PR DESCRIPTION
**Pull request by gperdomor**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by juristr** [comment]
Hey @gperdomor, thanks a lot for the PR and hard work.

This looks awesome, we were wondering though whether it would be better suited as a [community plugin](https://nx.dev/community) rather than a native `@nrwl/*` package. The reason is mostly maintenance-related. Also in 13.4 we're introducing a new feature that allows community plugins to provide presets, which would be perfectly suited for your Fastify plugin!

Happy to chat about it and provide guidance if you're interested. Just DM me on [Twitter](https://twitter.com/juristr) or reach out at `juri AT nrwl DOT io`. Having Fastify support for Nx would be amazing!

**Comment by gperdomor** [comment]
Hi @juristr no problem... I send you a Twitter DM :D

**Comment by FrozenPandaz** [comment]
This is awesome! Please make this as a community plugin though 😄

**Comment by gperdomor** [comment]
@FrozenPandaz @juristr where can I find the docs for the new feature for provide presets?

**Pull request closed without merging**
