### PR TITLE
feat(nest): set tsconfig’s emitDecoratorMetadata=true in application schematic

### LINKED ISSUE #1996: Missing emitDecoratorMetadata=true for NestJS projects when using Angular workspace
## Expected Behavior

When adding a new NestJS application to an Angular workspace using the application schematic from the @nrwl/nest package, the application should work out of the box.

## Current Behavior

The created app does not work properly. First, it looks like everything is working fine. But as soon as typical NestJS decorators are used, unexpected behaviour can happen. For example, when adding the ValidationPipe using `@UsePipes(...)` no validation is performed at all. This is because the tsconfig.json files does not contain emitDecoratorMetadata=true.

## Failure Information (for bugs)

When using an Angular workspace - no NX workspace - emitDecoratorMetadata is not set by default since Angular 8.1 (see #1801). But emitDecoratorMetadata=true is required for NestJS applications to run properly, as described above.

Either the workspace-schematic or the NestJS application schematic should update the tsconfig accordingly.

I could provide a PR if you tell where I should add this (workspace or NestJS application schematic) and which tsconfig should be updated: in my opinion the app's tsconfig should be updated, not the global one in the root folder.

### Steps to Reproduce

1. Create a workspace with Angular 8.1.
2. Create NestJS application with schematic.
3. Add some ValidationPipe with `@UsePipes`
4. Check if validation is really performed.

### PR DESCRIPTION
**Pull request by da-mkay**
Closes #1996

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you for your PR!

The root tsconfig has emitDecoratorMetadata set to true. I believe the nest app's tsconfig inherits that one. Cause when I try it locally, everything works on latest stable release.

Maybe you can update the nest e2e test so it fails before the fix (node.test.ts)?

**Comment by da-mkay** [comment]
Did you use an nx-workspace? Because in that case the root tsconfig may already contain emitDecoratorMetadata set to true.
But when using Angular workspaces with Angular >= 8.1 like in #1996 the root tsconfig does not contain emitDecoratorMetadata, but is required by nest to work properly:

    $ ng version
    …
    Angular CLI: 8.3.4
    …
    $ ng new nxtest --create-application=false
    $ cd nxtest
    $ ng add @nrwl/workspace
    $ ng add @nrwl/nest
    $ ng g @nrwl/nest:application myapp
    $ --> no tsconfig contains emitDecoratorMetadata:true

Even if emitDecoratorMetadata is not set the nest app would start successfully, but while running you will see strange behavior like no validation is performed although using a `ValidationPipe`.

So making the test fail before the fix requires to either set up an Angular workspace or removing the emitDecoratorMetadata from the nx-workspace tsconfig manually. Neither sounds 100% appropriate. But, since your package.json already contains the Angular libs maybe I should add a new test to node.test.ts that sets up an Angular workspace, adds a nest app, adds validation to the app and checks whether validation is performed on an incoming request.
What do you think?

**Comment by vsavkin** [comment]
It makes sense. Can you add a unit test for the change? Other than that, it's LGTM.

**Comment by da-mkay** [comment]
> It makes sense. Can you add a unit test for the change? Other than that, it's LGTM.

I just added a test that fails if the fix from this PR is not included.

Another fix would be to let the ng-add schematic of @nrwl/workspace add the required options to the root tsconfig (instead of the nest application schematic). Because I noticed that the workspace schematic of @nrwl/workspace also adds a correct tsconfig. See the comment in the test.
However, I prefer the nest application schematic for that change as in this PS.

**Comment by vsavkin** [comment]
Thank you! Merged it here:  https://github.com/nrwl/nx/commit/18d0798b130a3f9d299bddb424a65affffb36c37

**Pull request closed without merging**
