### PR TITLE
fix(core): include project fileset in the filesetHash map key

### LINKED ISSUE #11700: When using `dependsOn`, inputs seems to get overridden and target does not get cache hit
## Current Behavior

Currently if you have a target that has been configured to use `dependsOn` and run a cacheable operation, then the cacheable operation's `inputs` is not respected, and instead the `inputs` of the original task are used. This causes a cache miss for the task, even though it should be cached.

For example, let's say you have a build target which is configured like the following, with a `dependsOn`:

```json
"build": {
  "executor": "@nrwl/node:webpack",
  "outputs": ["{options.outputPath}"],
  "dependsOn": ["compileProto"],
  "options": {
    "outputPath": "dist/packages/test-app",
    "main": "packages/test-app/src/main.ts",
    "tsConfig": "packages/test-app/tsconfig.app.json",
    "assets": ["packages/test-app/src/assets"]
  },
  "configurations": {
    "production": {
      "optimization": true,
      "extractLicenses": true,
      "inspect": false,
      "fileReplacements": [
        {
          "replace": "packages/test-app/src/environments/environment.ts",
          "with": "packages/test-app/src/environments/environment.prod.ts"
        }
      ]
    }
  }
},
```

And your `compileProto` target is configured like this:

```json
"compileProto": {
  "executor": "@nrwl/workspace:run-commands",
  "inputs": ["{projectRoot}/src/app/test-folder-proto/**/*.proto"],
  "outputs": ["{projectRoot}/src/app/test-folder-output"],
  "options": {
    "commands": [
      {
        "command": "timeout 5"
      },
      {
        "command": "echo \"yay\""
      }
    ],
    "parallel": false
  }
}
```

We can see that `compileProto` is confused to only look at specific `inputs` (the folder where our proto files are stored in this package). And it outputs to a specific folder of our package as well.

Now if you run `nx run test-app:compileProto`, this behaves correctly, it will cache the results unless the files in `{projectRoot}/src/app/test-folder-proto/**/*.proto` have changed.

But if you run `nx run test-app:build` this does not behave correctly, it will always re-run the `compileProto` target as long as any file in `test-app` has changed. Instead of looking at the `compileProto` inputs, I believe `inputs` is getting overridden here to `build`'s inputs.

Note that this behavior is different than if you use `run-commands` to configure this target. If you configure `build` like this:

```json
"build-other": {
  "executor": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      {
        "command": "nx run test-app:compileProto"
      },
      {
        "command": "nx run test-app:build"
      }
    ],
    "parallel": false
  }
},
```

Then this works correctly. It will only re-run compileProto if the `inputs` specified in `compileProto` have changed.

## Expected Behavior

I'd expect that using `dependsOn` has the same behavior as `run-commands`, that is that the `compileProto` target is only re-executed when the inputs of that target change.

## Steps to Reproduce

https://github.com/KyleBastien/nx-inputs-example

You can see a repro of this issue in the above repo.

You can test this by doing the following:

```bash
git clone https://github.com/KyleBastien/nx-inputs-example
npm install
# Cache the compileProto build
npx nx run test-app:compileProto
# Make a change to main.ts in test-app, then re-run the following
npx nx run test-app:compileProto
# Notice that the above outputs the cached build that we did earlier
# Now, run build to cache the test-app build
npx nx run test-app:build
# Make another change to main.ts in test-app, then re-run the following
npx nx run test-app:build
# Notice how this re-ran compileProto, even though compileProto's inputs didn't change
# Now, run build-other to cache the test-app build-other output
npx nx run test-app:build-other
# Make another change to main.ts in test-app, then re-run the following
npx nx run test-app:build-other
# Notice how this did not re-run compileProto, because compileProto's inputs didn't change
```

### Failure Logs
N/A

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : win32 x64
   npm  : 8.11.0

   nx : 14.5.10
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### PR DESCRIPTION
**Pull request by meshde**
Since the root task and any task it depends on were using the same `filesetHash` map key, the fileset
hash of the depends on tasks was being calculated as the same as that of the root task even if the
input fileset for the former is different from that of the latter. 

This was causing any target run on the depends on task to be a cache miss after changes are made to files that are in the input fileset of the root task but not that of itself.

## Current Behavior
Any target run on dependsOn tasks would result in a cache miss when there are changes to files that are not a part of the given task's input filesets but are a part of the input filesets of the root task.

Similarly any change to a file that is a part of the input filesets of the given dependsOn task but not a part of the input filesets of the root task would result in a cache hit.

## Expected Behavior
Any target run on any task should return in a cache hit or miss based solely on whether or not there are changes to that task's input filesets.

## Related Issue(s)

Fixes #11700

### CODE REVIEW

**Comment by skrtheboss** [comment]
Probably this is the better approach. But is still let #11688 open to see what @vsavkin says.

**Comment by skrtheboss** [comment]
I think this has been implemented in https://github.com/nrwl/nx/pull/12162

**Comment by FrozenPandaz** [comment]
Yes! This is essentially what was in https://github.com/nrwl/nx/pull/12162... but 19 days sooner than we noticed the issue and saw this PR :disappointed:

Though I'm closing this PR because the proposed changes aren't necessary anymore. Bravo for finding the solution! :clap:

It is our fault for not seeing this sooner. Sorry for re-doing your work.

**Comment by meshde** [comment]
@FrozenPandaz No worries, thank you! 😄

**Pull request closed without merging**
