### PR TITLE
docs(core): update documentation to reflect nx commands

### PR DESCRIPTION
**Pull request by bcabanes**
Update the documentation generation to create a map of nx commands. This map will serve nx.dev to generate a new section called "_Nx Commands_", replacing the old "_npmScripts_" sub-section.

### CODE REVIEW

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Can you remove the `npm-scripts` docs please?

**Review by isaacplmann — APPROVED** [review]
LGTM

**Comment by isaacplmann** [comment]
Oops, I didn't notice that the old npm-scripts docs were still there.  Yes, it would be good to remove those.

**Comment by bcabanes** [comment]
@FrozenPandaz Updated! No `npmScripts` left.

**Review by FrozenPandaz — APPROVED** [review]

**Pull request merged**
