### PR TITLE
feat(nx-plugin): default the import path to the npmPackageName

### PR DESCRIPTION
**Pull request by vivekmore**
Fixes #
#4700

### CODE REVIEW

**Comment by vivekmore** [comment]
if my fix looks correct I'd like some direction on how to modify existing e2e tests or even unit tests to test my change

**Comment by vsavkin** [comment]
Thank you for your PR!

I'm sorry but I don't think I'll be able to merge it.

Since the vast majority of plugins are publishable, I actually think it's important for the developer to provide the import path. We do enforce the same for other type of libs.

I think a better fix would be to document it in the plugin guide. What do you think?

**Comment by vivekmore** [comment]
I think that's fair.
I'd change the error message (upon a missed importPath) and the documentation to provide a better DX

If it's okay with your team, I'd like the opportunity to provide those changes as a part of this issue/PR

**Comment by vsavkin** [comment]
In general, I'm trying to be conservative about deriving values from other values. I know what you mean though. We do the same type of stuff in create-nx-plugin.

I thought about it more, and I think it's OK to do the same logic here. So you can remove the x-prompt and add some tests to plugin.spec.ts.I'm also OK with keeping the x-prompt and removing the logic from plugin.ts.

Sorry for the late reply and sorry for the confusion.

**Comment by vivekmore** [comment]
Thank you for your response @vsavkin !
I'll update this PR to reflect the first of your 2 suggestions:
> So you can remove the x-prompt and add some tests to plugin.spec.ts.

**Comment by vivekmore** [comment]
I was also wondering if `create-nx-plugin` was a standalone schematic for convenience.
It seems, it could be a preset of `create-nx-workspace`

**Comment by vsavkin** [comment]
Thank you! Could you rename the commit to "feat(nx-cloud): default the import path to the npmPackgeName"?

**Comment by vivekmore** [comment]
> Thank you! Could you rename the commit to "feat(nx-cloud): default the import path to the npmPackgeName"?

I used the nx-plugin instead of nx-cloud because the build failed. I hope that's okay.

**Comment by vsavkin** [comment]
Thank you!

**Pull request merged**
