### PR TITLE
fix(webpack): micro-frontend dev builds in React are not working in S…

### LINKED ISSUE #17246: [SSR Module Federation - React] - Cannot read properties of undefined (reading 'target')
### Current Behavior

I'm using NX v16.2.2

As suggested in the [documentation](https://nx.dev/recipes/module-federation/module-federation-with-ssr),

- I'm running `npx nx g @nx/react:host host --ssr` command
- To serve the application, I ran `npx nx serve host`

**One I do this, I get following error:**

image

Please note that, when I run the application on http://localhost:4200, it runs properly. However, it doesn't watch for the file changes. This issue only exists in when we configure the host and remote app with "SSR" flag.

### Expected Behavior

NX should successfully serve the application and watch for the file changes.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Configure the NX workspace to use "Integrated Monorepo"
2. Install @nx/react (npm i @nx/react)
3. Run npx nx g @nx/react:host store --ssr --remotes=product,checkout
4. Run npx nx serve store and you will notice the error.

### Nx Report

```shell
   Node   : 18.16.0
   OS     : darwin x64
   npm    : 9.5.1
   Hasher : Native

   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/react          : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
```

### Failure Logs

```shell
>  NX   Cannot read properties of undefined (reading 'target')


TypeError: Cannot read properties of undefined (reading 'target')
    at ssrDevServerExecutor_1 (/private/var/www/kolabverse/node_modules/@nx/webpack/src/executors/ssr-dev-server/ssr-dev-server.impl.js:31:40)
    at ssrDevServerExecutor_1.next (<anonymous>)
    at resume (/private/var/www/kolabverse/node_modules/tslib/tslib.js:279:48)
    at fulfill (/private/var/www/kolabverse/node_modules/tslib/tslib.js:281:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 >  NX   Running target serve for project host failed

Error: write EPIPE                                                                                                                                         1 ✘  4s
    at target._send (node:internal/child_process:865:20)
    at target.send (node:internal/child_process:738:19)
    at /private/var/www/kolabverse/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/private/var/www/kolabverse/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /private/var/www/kolabverse/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/private/var/www/kolabverse/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This works when I don't use SSR flag. But I want my micro-frontends to be able to run on SSR

### PR DESCRIPTION
**Pull request by sahilpurav**
…SR mode

[SSR Module Federation - React] - Cannot read properties of undefined (reading 'target')

closed #17246

## Current Behavior
I'm using NX v16.2.2

As suggested in the [documentation](https://nx.dev/recipes/module-federation/module-federation-with-ssr),

- I'm running `npx nx g @nx/react:host host --ssr` command
- To serve the application, I ran `npx nx serve host`

**One I do this, I get following error:**

image

Please note that, when I run the application on http://localhost:4200, it runs properly. However, it doesn't watch for the file changes. This issue only exists in when we configure the host and remote app with "SSR" flag.

## Expected Behavior
NX should successfully serve the application and watch for the file changes.

## Related Issue(s)
#17246 

Fixes #
#17246

### CODE REVIEW

**Review by mandarini — APPROVED** [review]
Nice catch! Thanks!

**Review by mandarini — APPROVED** [review]
Nice catch! Thanks!

**Comment by ojemuyiwa** [comment]
Hi guys what version is this available in?

**Comment by daton89** [comment]
is there a way to get this change? like to install `"@nx/webpack": "next"` in an already existing project or similar?

**Comment by mandarini** [comment]
When the `next` version is published, sure! But I don't think it is yet! :D It should be soon!

**Comment by mandarini** [comment]
Ohh look at that! Published 2 minutes ago @daton89 https://github.com/nrwl/nx/releases/tag/16.4.0-beta.2

**Pull request merged**
