### PR TITLE
docs(nextjs): update generator command template

### LINKED ISSUE #14687: Wrong command in the documentation
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Component generator example for Next](https://nx.dev/packages/next/generators/component#examples)

### Additional context or description
Wrong command template is given in the documentation

### PR DESCRIPTION
**Pull request by BlueIcedPen**
Update the command template for creating components without their own folder or custom folder, thus in the base components folder

## Current Behavior
The command creates the new component in a custom `foo` directory for the target project

## Expected Behavior
The command should create the new component in the default `components` directory for the target project

## Related Issue(s)

Fixes #
Closes #14687

### CODE REVIEW

**Comment by mandarini** [comment]
Hi there! Thanks for this PR. I see you only changed the generated file. Can you please change the non-generated file, instead, too?

**Comment by BlueIcedPen** [comment]
Hey @mandarini, I can't seem to locate the generator file. Any help?

**Comment by mandarini** [comment]
@BlueIcedPen [here](https://github.com/nrwl/nx/blob/master/packages/next/docs/component-examples.md) is the file you are trying to edit: `packages/next/docs/component-examples.md`

**Comment by BlueIcedPen** [comment]
@mandarini thanks so much! Updated as well now

**Review by mandarini — APPROVED** [review]

**Comment by mandarini** [comment]
Thank you for contributing!! :D

**Pull request merged**
