### PR TITLE
feat(angular): rename default ngrx-selector names to match ngrx-standard

### PR DESCRIPTION
**Pull request by michaelbe812**
## Current Behavior
Currently the generated ngrx selectors are prefixed with `get`.

## Expected Behavior
The generated selectors should match the default naming convention and be prefixed with `select`

## Related Issue(s)
-
Fixes #
-

### CODE REVIEW

**Comment by mikelgo** [comment]
Guess I need to update some tests as well. 
I will do this once you agreed with this change =)

**Comment by leosvelperez** [comment]
Hey @mikelgo! Thanks for the contribution!

The change makes sense. Please go ahead and update the failing tests. Please note you also need to update the following https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/ngrx/files/__directory__/__fileName__.facade.ts__tmpl__#L16-L18.

**Comment by mikelgo** [comment]
Hey @leosvelperez 
Glad that you like it. 

Thanks for the guidance! I will try to make all required changes by tomorrow or the day after tomorrow. 

Looking forward to my first small contribution to Nx =)

**Comment by mikelgo** [comment]
Hey @leosvelperez I updated the tests and locally it looks fine.
However here I see the 2 checks on CircleCI are failing. However I do not know really what to do here.
I see such things in the log:

```
Error: Command failed: yarn nx reset
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at runCLI (/home/circleci/repo/e2e/utils/index.ts:606:26)
    at /home/circleci/repo/e2e/utils/index.ts:418:5
    at Generator.next (<anonymous>)
    at /home/circleci/repo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/repo/node_modules/tslib/tslib.js:114:16)
    at cleanupProject (/home/circleci/repo/e2e/utils/index.ts:288:20) {
  status: 127,
  signal: null,
  output: [
    null,
    'yarn run v1.22.18\n' +
      '$ /tmp/nx-e2e--2189-YYCBuCy66XVD/angular/proj3784837/node_modules/.bin/nx reset\n' +
      'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
    '/usr/bin/env: ‘node\\r’: No such file or directory\n' +
      'error Command failed with exit code 127.\n'
  ],
  pid: 2521,
  stdout: 'yarn run v1.22.18\n' +
    '$ /tmp/nx-e2e--2189-YYCBuCy66XVD/angular/proj3784837/node_modules/.bin/nx reset\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: '/usr/bin/env: ‘node\\r’: No such file or directory\n' +
    'error Command failed with exit code 127.\n
```

**Comment by leosvelperez** [comment]
@mikelgo I haven't seen that one happening before on our e2e test. Could you try rebasing your branch with the latest master?

**Comment by mikelgo** [comment]
@leosvelperez 
updating with latest master did the trick =) 
However I need to rebase on more time (unfortunately the `sync fork` in GitHub does a merge instead of a rebase)

**Comment by mikelgo** [comment]
> @leosvelperez updating with latest master did the trick =) However I need to rebase on more time (unfortunately the `sync fork` in GitHub does a merge instead of a rebase)

I think I messed it up a little bit 😆

**Comment by leosvelperez** [comment]
@mikelgo the merge was fine, we squash the commits and merge anyways. That said, it might be better to close this one and open a new clean PR with the same changes.

**Comment by mikelgo** [comment]
@leosvelperez aah okay, good to know for the next time! =)

I will do this by today and thendirectly mention u not he new PR

**Comment by mikelgo** [comment]
@leosvelperez kindly have a look at the new clean PR: https://github.com/nrwl/nx/pull/13475

**Pull request closed without merging**
