### PR TITLE
fix(js): use path to `rootDir` when update package.json

### PR DESCRIPTION
**Pull request by xiejay97**
fix path when set rootDir
image

### CODE REVIEW

**Comment by nartc** [comment]
@xiejay97 Hi, can you rebase from latest?

**Comment by xiejay97** [comment]
> @xiejay97 Hi, can you rebase from latest?

👌

**Comment by nartc** [comment]
@xiejay97 Hi again, sorry if I missed it but which issue does this PR solve?

**Comment by xiejay97** [comment]
@nartc 

The source files in `src` dir
image

I add `"rootDir": "packages/ui/src"` to `@nrwl/js:tsc` opions and I get output 
image

But path of `main` field still depends on `projectRoot `, it should be `./index.js`
image

**Pull request closed without merging**
