### PR TITLE
WIP Permit to rebuild on source files changes

### PR DESCRIPTION
**Pull request by nweldev**
Add a new "watch" yarn script, which uses nodemon in order to automatically rerun scripts/link.sh on every change made to any typescript source file.

This make it easier to use `yarn link` when we need to test our changes in a Nx project.

### CODE REVIEW

**Comment by vsavkin** [comment]
Sorry for the late response.

I imagine this is mostly useful for rerunning unit tests, which we currently run like this:

```
"test:schematics": "yarn linknpm fast && ./scripts/test_schematics.sh",
"test:nx": "yarn linknpm fast && ./scripts/test_nx.sh",
```

As you can see we are running link there. This means that rerunning "link" separately won't help to speed up those commands.

Maybe it is better to add "watch" to those commands?

```
"test:schematics:watch": "nodemon -e ts --exec yarn test:schematics --watch packages/schematics/src",
"test:nx:watch": "nodemon -e ts --exec yarn test:x --watch packages/nx/src",
```

**Comment by noelmace** [comment]
Ok thx I'll look at it.

**Comment by vsavkin** [comment]
@noelmace any progress on this? If not, I'm going to close the PR.

**Comment by noelmace** [comment]
Sorry, just missing time for this  right now. I should have enough time to do this in two weeks, if you think this is still usefull.

**Comment by JamesHenry** [comment]
@noelmace It looks like the team are still open to this solution but I am going to close for now due to WIP status, inactivity and conflicts.

Please feel free to open a new PR if you want to go ahead with this 👍

**Pull request closed without merging**
