### PR TITLE
feat(nest): extend @nestjs/schematics in @nrwl/nest

### PR DESCRIPTION
**Pull request by yharaskrik**

### CODE REVIEW

**Review by Cammisuli — APPROVED** [review]
LGTM

**Comment by yharaskrik** [comment]
Sorry it took so long! Just a couple of things have been happening lately.

**Comment by onemargaro** [comment]
any update of this?

**Comment by yharaskrik** [comment]
@onemargaro Waiting on Nrwl to merge it in currently, I can update it to ^7 as long as Nx has updated the nest 7+ as well.

@Cammisuli would you like me to make that change? Or leave it as 6 for now?

**Comment by Cammisuli** [comment]
@yharaskrik we'll leave it as 6 for now. Migrating to a major version is outside the scope of this PR.

**Comment by yharaskrik** [comment]
Sounds great to me

**Pull request merged**
