### PR TITLE
feat(nx-plugin): add "schematic" schematic

### PR DESCRIPTION
**Pull request by devinshoemaker**
This change adds a new schematic that generates a schematic for an Nx plugin. The user can specify the name for the schematic and optionally add a custom description.

Examples:

```
nx g @nrwl/nx-plugin:schematic my-schematic --project=ionic-react
```

```
nx g @nrwl/nx-plugin:schematic my-schematic --project=ionic-react --description='My schematic description'
```

### CODE REVIEW

**Review by Cammisuli — COMMENTED** [review]
@devinshoemaker can you add a new e2e test for the "schematic" schematic?

**Comment by devinshoemaker** [comment]
@Cammisuli oops, yeah I can't believe I missed that.

**Comment by devinshoemaker** [comment]
@Cammisuli I added an e2e test, updated the plugin schematic unit tests, and rebased onto master.

**Review by Cammisuli — APPROVED** [review]
LGTM!

**Comment by devinshoemaker** [comment]
Rebased and regenerated documentation.

**Pull request merged**
