### PR TITLE
chore(core): nx plugin submission @koliveira15/nx-sonarqube

### PR DESCRIPTION
**Pull request by koliveira15**
_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

# Community Plugin Submission

Thanks for submitting your Nx Plugin to our community plugins list. Make sure to follow these steps to ensure that your PR is approved in a timely manner.

## Steps to Submit Your Plugin
- Use the following commit message template: `chore(core): nx plugin submission [PLUGIN_NAME]`
- Update the `community/approved-plugins.json` file with a new entry for your plugin that includes `name`, `url`, `description`:

Example:

```json
// community/approved-plugins.json

[{
    "name": "@community/plugin",
    "url": "https://github.com/community/plugin",
    "description": "This plugin provides the following capabilities."
}]
```

Once merged, your will plugin will be available when running the `nx list` command, and will also be available in the Plugin browser on [nx.dev](https://nx.dev)

### CODE REVIEW

**Comment by AgentEnder** [comment]
Hey @koliveira15! This looks cool, we get quite a few people asking about integrating sonarqube and it seems like this would be a good way to do it. 

Can you add some e2e tests and then I'll approve and merge this

**Comment by koliveira15** [comment]
> Hey @koliveira15! This looks cool, we get quite a few people asking about integrating sonarqube and it seems like this would be a good way to do it.
> 
> Can you add some e2e tests and then I'll approve and merge this

**Comment by koliveira15** [comment]
@AgentEnder apologies for accidently closing this. I will write the e2e tests and get back to you once complete. Thanks!

**Comment by koliveira15** [comment]
@AgentEnder I have added e2e tests [here](https://github.com/koliveira15/nx-sonarqube/blob/main/e2e/nx-sonarqube-e2e/tests/nx-sonarqube.spec.ts)

**Pull request merged**
