### PR TITLE
fix(linter): update eslint plugins for @typescript-eslint v6 naming

### LINKED ISSUE #20966: typescript-eslint v6 support did not reflect updates to configuration naming
### Current Behavior

If you are using any non-null assertions in your codebase (prior to typescript-eslint v6) these were properly showing lint errors by default based on whatever presets and plugins are pre-configured in the Nx presets. After upgrading to a version of Nx which includes this PR (https://github.com/nrwl/nx/pull/19548), those lines are no longer showing lint errors and are accepted as valid code.

Tagging @meeroslav as the author of the mentioned PR that potentially caused this regression

### Expected Behavior

I would expect that after upgrading to a version of Nx that bumps typescript-eslint to v6, that the default linting presets provided by Nx still function the same, **OR** if that is not possible because of the way typescript-eslint renamed and changed their presets, then provide a migration to replicate the previous rule-sets with the new version.

### GitHub Repo

https://github.com/rathpc/nx-typescript-eslint-v6-issue

#### Instructions to see the pre-updated behavior
1. Clone `https://github.com/rathpc/nx-typescript-eslint-v6-issue`
2. Checkout the `main` branch
3. Run `yarn` to install dependencies. (_This branch is on Nx v17.0.3 where the rule still works as expected_)
4. Run `nx run react-monorepo:lint` and you will be presented with the non-null assertion warning as it is being used in one of the files.

#### Instructions to see the post-updated behavior
1. Checkout the `17.1.3` branch
2. Run `yarn` to install dependencies. (_This branch is on Nx v17.1.3 where the rule no longer works as expected and other rules likely also fall into this issue now as well. Technically the issue is present as of 17.1.0 but that version is missing from npm_)
4. Run `nx run react-monorepo:lint` and you will **NOT** be presented with the non-null assertion warning even though it is being used in one of the files and should still show a warning as it would be expected that the default presets contain the same base rules.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx (global)        : 17.1.1
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/react          : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
```

### Failure Logs

_No response_

### Package Manager Version

yarn v1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This issue was created as a follow-up to the discord discussion here: https://discord.com/channels/1143497901675401286/1179090256314761256

Also, this reworked configuration names change (https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#reworked-configuration-names) is likely the cause of this issue as the Nx presets were not changed to accommodate this along with the update to the typescript-eslint v6 upgrade

### PR DESCRIPTION
**Pull request by rathpc**
This updates the plugins used to map correctly to the new configuration naming that @typescript-eslint v6 introduces.

## Current Behavior

Latest version of nx with `@typescript-eslint` v6 **does not** apply all of the same lint rules as v5.

## Expected Behavior

Latest version of nx with `@typescript-eslint` v6 **does** apply all of the same lint rules as v5. Two rules had been removed from the recommended scope of rules 0 `no-extra-semi` which has become deprecated in favor of a rule in the new [ESLint Stylistic](https://eslint.style/) package and `no-non-null-assertion` which is now part of the strict plugin and upgraded from a warning to an error. I opted to include those here (with their previous levels) to prevent breaking changes for others. Once we upgrade to v7, we will need to include the stylistic package anyway and proper removal and replacement can be done at that time.

## Related Issue(s)

Fixes #20966

### CODE REVIEW

**Comment by rathpc** [comment]
I am unclear why the build failures are happening because I don't believe my changes should have caused this. Perhaps because this is a fork and I don't have access to certain values?

**Comment by meeroslav** [comment]
@rathpc the build failures are because of our misconfiguration currently. I have updated now your PR to the latest master which should fix the build.

The changes look fine to me but I would like to have @JamesHenry's second opinion since he is on the @typescript-eslint team as well.

**Review by JamesHenry — CHANGES_REQUESTED** [review]
Thanks! Please add comments calling out why we are adding these rules here with a TODO to reevaluate in the next major of Nx

**Comment by rathpc** [comment]
> Thanks! Please add comments calling out why we are adding these rules here with a TODO to reevaluate in the next major of Nx

ok, thanks - I will make that change later today

**Comment by rathpc** [comment]
@JamesHenry updated, please let me know if anything else needs to be done. Thanks!

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
Thanks @rathpc

**Review by meeroslav — APPROVED** [review]

**Comment by meeroslav** [comment]
Build is failing with E2E tests that now have `lint` check broken. I will look into it later today and hopefully we can merge this in.

**Comment by rathpc** [comment]
> Build is failing with E2E tests that now have `lint` check broken. I will look into it later today and hopefully we can merge this in.

Ok thank you!

**Comment by meeroslav** [comment]
Sorry, this was accidentally closed by a broken rebase. Reopened here: https://github.com/nrwl/nx/pull/21221

Your name will still be tracked as a contributor. Thank you for the help.

**Pull request closed without merging**
