### PR TITLE
feat(node) builder should support multiple entries

### PR DESCRIPTION
**Pull request by christianallred**
## Current Behavior
Currently today, when i build a node application using default settings only one entry file is generated `main.js`

## Expected Behavior
I am not changing behavior but updating when a new flag is available. 

## Related Issue(s)
[Allow for multiple artifacts to be created via @nrwl/node:build](https://github.com/nrwl/nx/issues/4448)

Fixes #
In this pr, i allow for a new setting to be added to workspace.json that will allow for a build to generate more than one entry file. As mentioned in the issue my reasoning for this is so that i can thread more easily via node threading api, which requires a reference file in js format to spin up the new thread.

### CODE REVIEW

**Comment by Cammisuli** [comment]
Awesome, thanks for the PR!

I'll take a look as soon as I can! 😄

**Review by Cammisuli — CHANGES_REQUESTED** [review]
Again thanks for the PR!

You'll need to also add the new builder argument to the `schema.json` file under `packages/node/src/builders/build`. 
It should look something like this:
```
    "additionalEntryPoints": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "entryName": {
            "type": "string",
            "description": "Name of the additional entry file"
          },
          "entryPath": {
            "type": "string",
            "description": "Path to the additional entry file"
          }
        }
      }
    }
 ```
 This allows Nx to verify the options when they're actually ran from the workspace.json file, and for us to generate the documentation 😄 
 
 If you need any help, you can reach me on the nrwl community slack group! Thank you!

**Comment by gperdomor** [comment]
@christianallred this should solve with the TypeOrm migration problems right?

**Comment by Cammisuli** [comment]
I'm going to close this PR for now. There hasn't been a response from the author in quite some time. You can open a new PR with the requested changes when you come around to it.

**Comment by christianallred** [comment]
Sorry about that i've been super busy with other projects / real life, i'll try to get back to the requested changes when i can! hopefully in the next month or so. @gperdomor I am not sure, what is the migrtion problem?

**Comment by zetsnotdead** [comment]
@Cammisuli  @christianallred  I just want to chime in and say that this functionality would be very useful for using Nx to build Netlify Functions. 

In Netlify you need to output a function for each of the endpoint. So it would be desirable to allow the @nrwl/node:build to output something like:

```
dist/apps/netlify-functions/a-function.ts
dist/apps/netlify-functions/b-function.ts
dist/apps/netlify-functions/c-function.ts
```

As I understand right now, Nx node apps can only output this:
```
dist/apps/netlify-functions/main.ts
```

**Comment by christianallred** [comment]
yes that is the case @zetsnotdead I still plan on getting back to this, i have just been really busy with other projects. hopefully ic an do it soon :)

**Comment by christianallred** [comment]
@gperdomor  it would solve some of them but not all of them. My core reason for wanting to get this implemented is to support multiple tennant task runners. this can be seen a lot in service workers, extensions, threading. WHere you need to load a ".js" file in order to spawn a new task or invoke certain methods. It would be really nice if these could be built in the same app inside of nrwl instead of having to import them externally. That ends up causing a lot of linting and build hacks.

**Comment by christianallred** [comment]
@Cammisuli i think i might have some time this weekend to work on this finally. Would you prefer that i open a new pr or update this one?

**Pull request closed without merging**
