### PR TITLE
feat(web): added runtimeChunk option

### PR DESCRIPTION
**Pull request by TriPSs**
## Current Behavior
Runtime file is created separately for all web builds

## Expected Behavior
Option to disable this so one bundle with everything can be generated

### CODE REVIEW

**Comment by vsavkin** [comment]
@TriPSs could you rebase this PR? Thank you!

**Comment by TriPSs** [comment]
@vsavkin The rebase is done btw.

**Comment by TriPSs** [comment]
@vsavkin when can this be checked / merged? We need this option to release our bundles correctly :)

**Comment by KKrisu** [comment]
Hey, I'm waiting for the release of this. Can you please give us an update? @vsavkin

**Comment by jaysoo** [comment]
Rebased and updated PR here https://github.com/nrwl/nx/pull/5043

**Comment by KKrisu** [comment]
Hi, has this change already been released?

**Pull request closed without merging**
