### PR TITLE
feat(core): support [preferLocal] option for workspace:run-commands)

### LINKED ISSUE #5572: prefer local installed package in nx run-commands
## Description

Support local installed packages to be used by nx run-commands, just like npm scripts do.
Since run-commands is now handled by origin nodejs child_process, [npm-run-path](https://www.npmjs.com/package/npm-run-path) can easily help to make local installed packages avaliable in run-commands.

## Motivation

This will greatly decrease the plugin developing, for example, when creating plugins with some packages which didn't expose proper interface for programmatic usage, enable invoking package cli directly will be useful.

## Suggested Implementation

Add `preferLocal` option to preserved schema option, when this option is enabled, use npm-run-path to process env just like :
```javascript
if (preferLocal) {
  return npmRunPath.env({env, cwd: localDir, execPath});
}
```

Add processed env to `createProcess` [here](https://github.com/nrwl/nx/blob/master/packages/workspace/src/executors/run-commands/run-commands.impl.ts#L177).

### PR DESCRIPTION
**Pull request by linbudu599**
ISSUES CLOSED: #5572

I cannot use WSL in my windows because some personal issues, so I use `npm link` as replacement for local-registry.

This leads to a problem, when pushing files, `yarn documention` check failed with errors:

```bash
The following files appear to contain the following invalid internal links:
  {
  "docs/angular/cli/build.md": [
    "/angular/cli/run",
    "/react/cli/run",
    "/node/cli/run"
  ],
  ...
}
```
I've checked the generated documentations and wasn't clear about the reason(I use `no-verify` to skip it), if this will cause documentation broken, please let me know how to fix it.

## Current Behavior

`workspace:run-commands` support only global-avaliable packages/commands.

## Expected Behavior

Enable local installed packages execution by specifying [preferLocal] option of run-commands.

## Related Issue(s)

#5572

Fixes #

### CODE REVIEW

**Comment by vsavkin** [comment]
Hi! Thak you for your PR. 

Sorry, I think I lack some context. Isn't passing CWD going to invoke the command installed in the project?

**Comment by linbudu599** [comment]
> Hi! Thak you for your PR.
> 
> Sorry, I think I lack some context. Isn't passing CWD going to invoke the command installed in the project?

No, using CWD option works just like open a ternimal in CWD folder and execute commands, for example, even if we install nx locally, we cannot use `nx report` directly from ternimal in project CWD. NPM Scripts can invoke commands 
from installed package because it add commands exported from `/node_modules/.bin` to process.env.PATH(Path/path), see [npm/cli set-paths](https://github.com/npm/cli/blob/a4e7f4e4b4/node_modules/%40npmcli/run-script/lib/set-path.js#L25) for more details.
So if we want to execute commands from installed package, we will need to add commands exported from `/node_modules/.bin` to process.env.PATH(Path/path) just like NPM Scripts do, this is why supporting `preferLocal` option will need to use [npm-run-path](https://github.com/sindresorhus/npm-run-path/blob/main/index.js#L18).

**Comment by vsavkin** [comment]
Really sorry for the late reply. 

So preferLocal is the same as:

command: './node_modules/.bin/nx report',
cwd: 'apps/myapp'

Right?

**Comment by linbudu599** [comment]
> Really sorry for the late reply.
> 
> So preferLocal is the same as:
> 
> command: './node_modules/.bin/nx report',
> cwd: 'apps/myapp'
> 
> Right?

I think so, which is useful feature for workspace run-commands executor.

**Comment by vsavkin** [comment]
Thank you for explaining. 

I don't think we need a separate option, I think it's ok to always have it on and add the bin folder to the path. 

I want to make sure the following is true.

Given the following folder structure:

```
node_modules/
  .bin/
    webpack (version 5)
    
apps/
  myapp/
    node_modules/
      .bin/
        webpack (version 4)

```

If I have the following command: `webpack --version` registered as a target for myapp, then it will return 5 if I don't specify CWD, and it will return 4 if I specify CWD as "apps/myapp".

Could you modify run-commands.test.ts to cover this use case?

Thank you so much for explaining and for you work on this PR!

**Comment by linbudu599** [comment]
@vsavkin sorry for the really late reply...  I'll complete it this weekend, is this feature supported in previous PR ?

**Comment by vsavkin** [comment]
Merge the other PR. Thank you!

**Pull request closed without merging**
