### PR TITLE
feat(core): add support for yarn 2

### LINKED ISSUE #2386: yarn 2 Support
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites
Yarn version 2.0.0-rc.27

## Expected Behavior

Should work correctly like before

## Current Behavior

Build failure

## Failure Information (for bugs)

**An unhandled exception occurred: Cannot locate the 'node_modules' directory.
See "AppData\Local\Temp\ng-mO3oFO\angular-errors.log" for further details.**

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. yarn dlx @yarnpkg/doctor .
2. yarn install
3. yarn start

### Context

Yarn has finally released a usable version two. If you using webpack 4 you need to enable PlugNPlay which is native to webpack 5

https://yarnpkg.com/advanced/migration
https://yarnpkg.com/advanced/pnpapi

### Failure Logs

```
[error] Error: Cannot locate the 'node_modules' directory.
    at NgccProcessor.findNodeModulesDirectory (C:\dev\lec-migration\.yarn\$$virtual\@ngtools-webpack-virtual-9bdca6ad48\0\cache\@ngtools-webpack-npm-9.0.0-rc.10-6bfaf96715-1.zip\node_modules\@ngtools\webpack\src\ngcc_processor.js:113:15)
    at new NgccProcessor (C:\dev\lec-migration\.yarn\$$virtual\@ngtools-webpack-virtual-9bdca6ad48\0\cache\@ngtools-webpack-npm-9.0.0-rc.10-6bfaf96715-1.zip\node_modules\@ngtools\webpack\src\ngcc_processor.js:31:43)
    at C:\dev\lec-migration\.yarn\$$virtual\@ngtools-webpack-virtual-9bdca6ad48\0\cache\@ngtools-webpack-npm-9.0.0-rc.10-6bfaf96715-1.zip\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:554:33
    at SyncHook.eval [as call] (eval at create (C:\dev\lec-migration\.yarn\cache\tapable-npm-1.1.3-f1c2843426-1.zip\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (C:\dev\lec-migration\.yarn\cache\tapable-npm-1.1.3-f1c2843426-1.zip\node_modules\tapable\lib\Hook.js:154:20)
    at Object.webpack [as webpackFactory] (C:\dev\lec-migration\.yarn\cache\webpack-npm-4.41.2-efbe0580aa-1.zip\node_modules\webpack\lib\webpack.js:55:30)
    at createWebpack (C:\dev\lec-migration\.yarn\$$virtual\@angular-devkit-build-webpack-virtual-0beaa59de8\0\cache\@angular-devkit-build-webpack-npm-0.900.0-rc.10-7017fe1d56-1.zip\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:20:36)
    at Object.runWebpackDevServer (C:\dev\lec-migration\.yarn\$$virtual\@angular-devkit-build-webpack-virtual-0beaa59de8\0\cache\@angular-devkit-build-webpack-npm-0.900.0-rc.10-7017fe1d56-1.zip\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:46:12)
    at SwitchMapSubscriber.project (C:\dev\lec-migration\.yarn\$$virtual\@angular-devkit-build-angular-virtual-d79a835d58\0\cache\@angular-devkit-build-angular-npm-0.900.0-rc.10-f83f279b13-1.zip\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:191:32)
    at SwitchMapSubscriber._next (C:\dev\lec-migration\.yarn\cache\rxjs-npm-6.5.3-bc949c0a94-1.zip\node_modules\rxjs\internal\operators\switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (C:\dev\lec-migration\.yarn\cache\rxjs-npm-6.5.3-bc949c0a94-1.zip\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\dev\lec-migration\.yarn\cache\rxjs-npm-6.5.3-bc949c0a94-1.zip\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Other

Any other relevant information that will help us help you.

### PR DESCRIPTION
**Pull request by Jordan-Hall**
## Current Behavior
Yarn 2 not currently support due to NX not Angular 

## Expected Behavior
Both version of Yarn and NPM still works 

## Related Issue(s)
Fixes #2386

### CODE REVIEW

**Comment by Jordan-Hall** [comment]
Taking a look again this weekend. They was alot more to the require than i first thought

**Comment by vsavkin** [comment]
fyi @bekos is looking into yarn 2 support. There are a few more things that ended up being tricky there (related to create-nx-workspace), but we think we can get it right. We will keep you posted.

**Comment by Jordan-Hall** [comment]
> fyi @bekos is looking into yarn 2 support. There are a few more things that ended up being tricky there (related to create-nx-workspace), but we think we can get it right. We will keep you posted.

Thank you. I ran into issues they where so many more things that need considering. I've just not had time to head back and look yet

**Comment by bekos** [comment]
Hi @Jordan-Hall 😃  Thx for your contribution, but as @vsavkin mentioned, we have started tackling some of the issues about Yarn 2 support in other PRs, for example #3726. It's not fully working yet but you can take a look and tell us what you think.  If you don't mind, I am going to close this PR to keep things tidy 😄

**Pull request closed without merging**
