### PR TITLE
feat(nx): Allow DataPersistence to take action streams

### PR DESCRIPTION
**Pull request by texel**
Currently, DataPersistence methods such as `fetch` and
`optimisticUpdate` take a string as their first argument,
which they use to filter incoming action types. This can
lead to inflexibility in certain cases, such as when
you want to filter the action stream before it gets to
the DataPersistence handler, or when you want to handle
multiple action types with the same effect (as suggested
by Mike Ryan in his "Good Action Hygiene with NgRx talk:
https://www.youtube.com/watch?v=JmnsEvoy-gY)

This PR changes `fetch`, `optimisticUpdate` and `pessimisticUpdate`
so that the first argument to each can either be a string,
or a stream of actions.

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
Hi, thank's for the PR! I see the concern here.

I feel like that would be more of an operator than a creator (Which it currently is)

In which case, we might be able to have both co-exist...

The thing that sort of blocks it is that our callbacks are called with the latest state of the `Store`.

Thoughts?

Maybe we could discuss in an issue before you make code changes :wink:. Iterating on ideas is much easier than code.

**Comment by texel** [comment]
Haha, you’re probably right but I figured I’d start the conversation by offering some code, I’m not married to the implementation. How would you imagine that the API for an operator version would look?

**Comment by vsavkin** [comment]
I was thinking we can have something like this:

```
class MyClass {
    @Effect() getTodo = this.actions.pipe(
        ofType('GetTodo'),
        fetch({
          id: (a, state) => a.payload.id, 
          run: (a, state) => this.backend.getTodo(state.user, a.payload),
          onError: (a, e) => this.logger.log(a)
        })
    )

   ...
}
```

In this case you can use `fetch`, `optimisticUpdate`, `pessimisticUpdate`, or `navigate` with any action stream.

**Comment by texel** [comment]
@vsavkin that looks great, though as @FrozenPandaz mentioned, getting state into a bare pipeable operator like that isn't really possible without passing something in from the outside. It would be fairly straightforward if we used the `DataPersistence` instance which already has a reference to the store:

```
class MyClass {
    @Effect() getTodo = this.actions.pipe(
        ofType('GetTodo'),
        this.d.fetch({
          id: (a, state) => a.payload.id, 
          run: (a, state) => this.backend.getTodo(state.user, a.payload),
          onError: (a, e) => this.logger.log(a)
        })
    )

   ...
}
```

Of course that would require either overloading the existing methods or picking new names. Alternatively, we could stick with a simple operator, but require that the store is also passed in (this is less ergonomic though):

```
class MyClass {
    @Effect() getTodo = this.actions.pipe(
        ofType('GetTodo'),
        withLatestFrom(this.d.store),
        fetch({
          id: (a, state) => a.payload.id, 
          run: (a, state) => this.backend.getTodo(state.user, a.payload),
          onError: (a, e) => this.logger.log(a)
        })
    )

   ...
}
```

**Comment by vsavkin** [comment]
@texel it's a good point. I think it works well.  We can make the state param optional, so if you use withLatestFrom, you get the state. If you don't, you don't.

```
    @Effect() getTodo = this.actions.pipe(
        ofType('GetTodo'),
        withLatestFrom(this.store),
        fetch({
          id: (a, state) => a.payload.id, 
          run: (a, state) => this.backend.getTodo(state.user, a.payload),
          onError: (a, e) => this.logger.log(a)
        })
    )
```


We should also keep DataPersistence. It will just user the operations in the way shown above.

**Comment by texel** [comment]
Seems good, I'll work something up.

**Comment by texel** [comment]
@vsavkin @FrozenPandaz I've updated the PR– let me know what you think. If the implementation looks good, I'll likely need to add docs before merging.

**Comment by texel** [comment]
@vsavkin @FrozenPandaz any updates on this?

**Comment by vsavkin** [comment]
@texel sorry for the late reply. I like the changes.

**Pull request merged**
