### PR TITLE
fix(nextjs): fix asset prefix

### PR DESCRIPTION
**Pull request by kang-heewon**
## Current Behavior 
assets must in public folder

## Expected Behavior
assets are optionally placed in the 'public' folder.

### CODE REVIEW

**Comment by kirjai** [comment]
hey @kang-heewon , thanks for the PR! 
Can you explain the motivations behind this PR a bit more please?

Looking at the changes as they are, this stops copying shared assets into the `public` directory during the build of Next.js applications for dev and prod, and copies them into the build directory instead. 
As far as I know, Next.js only supports serving static assets from the `public` directory, [as per their documentation](https://nextjs.org/docs/basic-features/static-file-serving) 🤔

**Comment by kang-heewon** [comment]
@kirjai yes. Next.js only supports serving static assets from the public directory.
 But I don't have a way to keep build files like Dockerfile.
Since I am building from ci, the build output should include the dockerfile.
In nx, I could only find a way to use assets.
But the next builder puts the assets only in the public folder.
It would be nice if you allowed other options as well.

**Comment by kang-heewon** [comment]
Docker files can solve that way. 
However, the ci/cd configuration files used before Docker and scripts for devops still cannot be resolved.

**Comment by kirjai** [comment]
What could work in this case is if the next.js build executor supported the `"assets"` configuration option. We have other executors, like `@nrwl/web:build` that implement it. [Link to the docs](https://nx.dev/latest/react/web/build#assets). This would allow you to specify which files you want copied.
That would be our suggested way to achieve the functionality you're looking for.

If you want to take a stab at implementing this, we would suggest looking at how `@nrwl/web:build` works with the `"assets"` config option, as a starting point. and then try to port that over to the next.js build executor.

Alternatively, you could open an issue and we'll get to it at some point. I'd suggest linking this conversation / PR in that issue, for more context. 

---

As for this PR, as you can see, the end to end tests have failed, as the proposed changes break existing functionality. And since changes required to implement the functionality mentioned above are significantly different, I'm going to close this PR. 
But please don't hesitate opening a new PR if you do implement the `"assets"` config option!

**Pull request closed without merging**
