### PR TITLE
fix(nx): ng-add schematic maintenance

### PR DESCRIPTION
**Pull request by matheo**
## Current Behavior

Trying to migrate a CLI v8 project to Nx v8 I got several issues, from Error exceptions to incomplete stuff like the missing root `tsconfig.json` (because it was moved with the application) and the `tsconfig.app` and `tsconfig.spec` configurations that I've included like in a clean Nx project.

## Expected Behavior

The migration works now and I was able to continue the project with these fixes.

### CODE REVIEW

**Comment by vsavkin** [comment]
@FrozenPandaz can you take a look?

**Comment by vsavkin** [comment]
@matheo really sorry for the late reply. Could you add tests to `ng-add.spec.ts` to cover the changes?

**Comment by matheo** [comment]
@vsavkin no problem, I will do it when I have some spare time ;)

**Comment by vsavkin** [comment]
@matheo did you have a chance to take a look?

**Comment by bjufre** [comment]
@matheo @vsakin any news on this? I’ve tried adding NX to an existing Angular 8 application and got some issues that might be related.
And one of them don’t exactly know; there’s an error with trying to `.split` on undefined...

:/


bjufre

**Comment by matheo** [comment]
@bjufre can you help me to figure out your scenario:
Which root files do you have in your Angular 8 standalone application?
I need to know which `tsconfig*.json` files exist in your project

**Comment by bjufre** [comment]
@matheo the files that exist are:
**At the root of the project:**
- `tsconfig.json`

**Inside the `src` folder:**
- `src/tsconfig.app.json`
- `src/tsconfig.spec.json`

**Comment by matheo** [comment]
@bjufre that's an updated Angular app?

In a new Ng 8 project I see:
* `tsconfig.json`
* `tsconfig.app.json`
* `tsconfig.spec.json`

so I will have to add some conditionals to detect where are the `tsconfigs`.

**Comment by bjufre** [comment]
Yes I used the `ng update` tool for it. I will check a few things and get back to you.

**Comment by JGhignatti** [comment]
Hi @matheo , I'm having the same problem here.
I have an Angular 8 application, that was created with Angular 6, `ng update` to Angular 7 and then `ng update` to Angular 8.
When I run `ng add @nrwl/schematics` I get
```
warning "@nrwl/schematics > @nrwl/angular > @nrwl/cypress > fork-ts-checker-webpack-plugin@0.4.15" has unmet peer dependency "webpack@^2.3.0 || ^3.0.0 || ^4.0.0".
warning "@nrwl/schematics > @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@4.1.0" has unmet peer dependency "webpack@^4.18.1".
warning "@nrwl/schematics > @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 26 new dependencies.
info Direct dependencies
└─ @nrwl/schematics@8.6.0
info All dependencies
├─ @cypress/webpack-preprocessor@4.1.0
├─ @nrwl/angular@8.6.0
├─ @nrwl/cli@8.6.0
├─ @nrwl/cypress@8.6.0
├─ @nrwl/jest@8.6.0
├─ @nrwl/schematics@8.6.0
├─ @nrwl/tao@8.6.0
├─ @nrwl/workspace@8.6.0
├─ @types/json5@0.0.29
├─ es-abstract@1.16.0
├─ fork-ts-checker-webpack-plugin@0.4.15
├─ graphviz@0.0.8
├─ jasmine-marbles@0.6.0
├─ load-json-file@4.0.0
├─ memorystream@0.3.1
├─ pidtree@0.3.0
├─ prettier@1.16.4
├─ read-pkg@3.0.0
├─ shell-quote@1.7.2
├─ string.prototype.padend@3.0.0
├─ temp@0.4.0
├─ ts-loader@5.3.1
├─ tsconfig-paths-webpack-plugin@3.2.0
├─ tsconfig-paths@3.9.0
├─ viz.js@1.8.2
└─ webpack-node-externals@1.7.2
✨  Done in 25.31s.
Installed packages for tooling via yarn.
            Path: karma.conf.js does not exist
            Path: tsconfig.app.json does not exist
            Path: tsconfig.spec.json does not exist
            Renamed src -> apps/my-app/src
            Renamed e2e -> apps/my-app-e2e-e2e
ENOENT: no such file or directory, open 'apps/my-app/tsconfig.app.json'
```
My app's `src` folder was moved to `apps` folder, along with `e2e` folder. But that's all. I noticed that maybe my `angular.json` was not being updated in time, cause changing some paths to `apps/my-app/src/...` gave me different behaviors, but none of them worked and mostly it ended uo with `no such file or directory, open 'apps/my-app/tsconfig.app.json'`.

Currently my app has the same structure as @bjufre , 
```
At the root of the project:
tsconfig.json

Inside the src folder:
src/tsconfig.app.json
src/tsconfig.spec.json
```

One last thing tho, are we supposed to keep using `ng add @nrwl/schematics` or it should be `ng add @nrwl/workspace`?

I think when this PR goes through it will save a lot of people hahaha. Thx for that!

**Comment by matheo** [comment]
@JGhignatti thanks for that info!
I initially had some weird old config with a single `tsconfig.json` (Angular 2 project I guess), and I'm thinking that I will trust the `angular.json` config and just move all the files from the old setup to the Nx folders. Any further `tsconfig` reorganization will have to be done after the `ng add`.

And FYI, the schematic is inside the `@nrwl/workspace` package ;)

**Comment by bjufre** [comment]
@matheo moved the files around. Updated the whole project and dependencies, run the `ng add @nrwl/schematics` and this error keeps showing up: `Cannot read property 'split' of undefined`

**Comment by matheo** [comment]
@bjufre please check these values on your `angular.json` and tell me which value doesn't exist in your config:
* `projects[name].architect.test.options.karmaConfig`
* `projects[name].architect.build.options.tsConfig`
* `projects[name].architect.test.options.tsConfig`
* `projects[name].architect.server.options.tsConfig`

**Comment by bjufre** [comment]
@matheo 

- `projects[name].architect.test.options.karmaConfig` doesn't exist becuase we already migrated the proejct to using jest.
- `projects[name].architect.server.options.tsConfig` this doesn't exist as there's no target named `server`, we do have `serve` target without `tsConfig` in it.

**Comment by matheo** [comment]
@bjufre good,
I will make the karma migration optional and that will make it work for you ;)
just to be sure, can your post your `test` options please?

**Comment by bjufre** [comment]
Screenshot 2019-10-20 at 20 48 15

There you go @matheo! Let me know if I can do anything else!

**Comment by bjufre** [comment]
@matheo any idea as to when this might be ready to try and implement?

**Comment by matheo** [comment]
@bjufre I'm removing the karma config migrations in the `init` schematic, it expects something like
```
"options": {
  "main": "src/test.ts",
  "tsConfig": "tsconfig.spec.json",
  ...
}
```
but I'm making that optional.

Once I finish you can checkout this branch, and run `npm run build`/`yarn build`,
and then try it locally with `ng add ../nx/build/packages/workspace`.

**Comment by matheo** [comment]
Ok @bjufre
Now you can `git clone --single-branch --branch nx8-add https://github.com/matheo/nx.git` next to your project. Install the dependencies and run the `build` script.

Then in your Angular App you can invoke `ng add ../nx/build/packages/workspace` to get the built library. Note that if there's an error in the upgrade, you need to clean all the folders created by the schematic to run it again, because it will complain if any folder/file exists.

Looking forward for your feedback ;)

**Comment by matheo** [comment]
@vsavkin the CI is throwing a weird error:
```
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
yarn checkformat --head=$TRAVIS_PULL_REQUEST_SHA
--base=$(git merge-base HEAD $TRAVIS_BRANCH); fi" exited with 1.
```
I think this PR is ready to update Angular 8 apps correctly.

**Comment by bjufre** [comment]
@matheo getting this now:
Screenshot 2019-10-20 at 23 56 57

Any ideas as to why that might be happening?

**Comment by matheo** [comment]
@bjufre woops, I tried with `yarn` tho.

**Comment by bjufre** [comment]
@matheo Ok after `yarn run linknpm` and changing the package manager to `yarn` it seems that it worked. The only thing that I think is a bit weird is that it created a `karma.config.js` file, but NX doesn't uses it, right?

**Comment by jdpearce** [comment]
@matheo Regardng the CI error: if you run `yarn format` on your branch you should see there's some formatting fixes in `packages/workspace/src/schematics/init/init.ts` that need to be committed.

@bjufre - We build Nx with yarn, so can't guarantee that building it with npm will work perfectly. Having said that, you should be able to use any package manager you like in an Nx workspace.

**Comment by JGhignatti** [comment]
Hi, @matheo 
Followed what you said
```
git clone --single-branch --branch nx8-add https://github.com/matheo/nx.git
yarn
yarn build

// In app folder
ng add ../nx/build/packages/workspace
```

and got 

```
success Saved lockfile.
success Saved 13 new dependencies.
info Direct dependencies
└─ @nrwl/workspace@0.0.1
info All dependencies
├─ @nrwl/cli@0.0.2
├─ @nrwl/tao@0.0.1
├─ @nrwl/workspace@0.0.1
├─ es-abstract@1.16.0
├─ ignore@5.0.4
├─ load-json-file@4.0.0
├─ memorystream@0.3.1
├─ npm-run-all@4.1.5
├─ pidtree@0.3.0
├─ prettier@1.18.2
├─ read-pkg@3.0.0
├─ shell-quote@1.7.2
└─ string.prototype.padend@3.0.0
✨  Done in 14.72s.
Installed packages for tooling via yarn.
    Renamed src/tsconfig.app.json -> apps/my-app/tsconfig.app.json
    Renamed src/tsconfig.spec.json -> apps/my-app/tsconfig.spec.json
    Renamed src/karma.conf.js -> apps/my-app/karma.conf.js
    Renamed src -> apps/my-app/src
    Renamed e2e -> apps/my-app-e2e-e2e
ENOENT: no such file or directory, open 'apps/my-app-e2e/tsconfig.json'
```

Before any changes my project folder structure is
```
cypress
e2e
node_modules
src
```
`e2e` folder and (after running nx) `apps/my-app-e2e-e2e` both have `tsconfig.e2e.json`.
This `e2e` folder has nothing inside, just boilerplate. I could get rid of it and try again, but think I should share this with you.
And I don't know if I have the proper implementation for `cypress`. But so far nothing broke it.

**Comment by matheo** [comment]
@bjufre please share with me your `angular.json` to see what's happening with the `e2e` project.

**Comment by JGhignatti** [comment]
Hi, pulled new version from branch, built and tried adding it again. This time it renamed correctly `Renamed e2e -> apps/my-app-e2e`.
But got `ENOENT: no such file or directory, open 'apps/my-app-e2e/tsconfig.json'` probably because the file inside `e2e` is actually called `tsconfig.e2e.json`.
I could rename it to match the expected, but I don't know whether mine is the different or the expected.

angular.json prior any change
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "my-app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "jg",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/my-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "node_modules/font-awesome/scss/font-awesome.scss",
              "node_modules/magic-check/sass/magic-check.scss",
              "node_modules/froala-editor/css/froala_editor.pkgd.min.css",
              "node_modules/froala-editor/css/froala_style.min.css",
              "node_modules/animate.css/animate.min.css",
              "node_modules/ngx-toastr/toastr.css",
              "src/styles.scss"
            ],
            "scripts": [
              "node_modules/chart.js/dist/Chart.bundle.js",
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/froala-editor/js/froala_editor.pkgd.min.js"
            ]
          },
          "configurations": {
            "dev": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev.ts"
                },
                {
                  "replace": "src/feature-toggle/feature-toggle.ts",
                  "with": "src/feature-toggle/feature-toggle.dev.ts"
                }
              ],
              "outputHashing": "all"
            },
            "uat": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.uat.ts"
                },
                {
                  "replace": "src/feature-toggle/feature-toggle.ts",
                  "with": "src/feature-toggle/feature-toggle.uat.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "my-app:build",
            "port": 5555
          },
          "configurations": {
            "dev": {
              "browserTarget": "my-app:build:dev"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "my-app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "my-app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "my-app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "my-app:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "may-app",
  "cli": {
    "defaultCollection": "@ngrx/schematics"
  }
}

```

**Comment by matheo** [comment]
@JGhignatti thanks for the feedback
the `e2e` tsconfig was hardcoded, now it should work correctly.
This PR is probably completed now :)

**Comment by bjufre** [comment]
@matheo here is the `angular.json` file:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "lamt": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": ["src/assets", "src/favicon.ico", "src/env.js"],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/font-awesome/css/font-awesome.css",
              "node_modules/swiper/css/swiper.css",
              "src/styles/styles.scss"
            ],
            "scripts": ["node_modules/swiper/js/swiper.js"],
            "optimization": true,
            "outputHashing": "all",
            "sourceMap": false,
            "extractCss": true,
            "namedChunks": false,
            "aot": true,
            "extractLicenses": true,
            "vendorChunk": false,
            "buildOptimizer": true
          },
          "configurations": {
            "base": {
              "optimization": false,
              "outputHashing": "none",
              "sourceMap": true,
              "extractCss": false,
              "namedChunks": true,
              "aot": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },

            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "lamt:build:base"
          },
          "configurations": {
            "production": {
              "browserTarget": "lamt:build:production"
            },
            "development": {
              "browserTarget": "lamt:build:development"
            },
            "local": {
              "browserTarget": "lamt:build:local"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "lamt:build"
          }
        },
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "tsConfig": "tsconfig.spec.json",
            "no-cache": true
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["tsconfig.app.json", "tsconfig.spec.json"],
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    },
    "lamt-e2e": {
      "root": "e2e",
      "sourceRoot": "e2e",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "lamt:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["e2e/tsconfig.e2e.json"],
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    }
  },
  "defaultProject": "lamt",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "lamt",
      "styleext": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "lamt"
    }
  },
  "cli": {
    "packageManager": "yarn"
  }
}
```

**Comment by matheo** [comment]
@JGhignatti both `angular.json` are working correctly with the latest fix?

**Comment by JGhignatti** [comment]
:/ I still have `ENOENT: no such file or directory, open 'apps/my-app-e2e/tsconfig.json'`.
Confirmed that renaming `tsconfig.e2e.json` to  `tsconfig.json` once again works.

Performed git pull and yarn build on your branch

**Comment by matheo** [comment]
@JGhignatti ok, I found the issue:
https://github.com/nrwl/nx/pull/1476/files#diff-0b98ba64f361ecaf53354cdb1e7d1090L266

There are some assumptions in the code about the standard filenames,
so, those projects that are outside of the standard may have some issues.
It will be required to align the project and the config to the standard,
basically these files: `tsconfig.app.json`, `tsconfig.spec.json` and `e2e/tsconfig.json`.

**Comment by JGhignatti** [comment]
Oh, that's not a problem. Super thanks for what you've done.
How does it work from now? I'll wait for it to be deployed to use.

**Comment by matheo** [comment]
Now @vsavkin needs to review and approve this update to `ng add`
so it can be included in the next release ;)

**Comment by vsavkin** [comment]
@matheo the changes look good. Have you tested them out? I'm not sure if you could run `ng add path-to-local-package`. Did you try something like this?

**Comment by matheo** [comment]
@vsavkin yep, we tested this PR in [that way](https://github.com/nrwl/nx/pull/1476#issuecomment-544286439).

Two types of configs for `angular.json`, one with a single app with `e2e` included as an architect, and another with a separated project for `e2e` ;)

**Comment by vsavkin** [comment]
@matheo great thank you!

**Comment by davidreher** [comment]
@vsavkin any plans when this will land in least in the next release on npm?

**Pull request merged**
