### PR TITLE
fix(core):  cannot read properties of undefined (reading 'options')

### PR DESCRIPTION
**Pull request by EugeneKruglei**
## Current Behavior
While building shell - it tries to build shared libs. While trying to access build config of shared libs - it throw a error due missing options configuration in shared libs

## Expected Behavior
The project build should be successful, shared libs options should be ignored.

## Related Issue(s)
https://github.com/nrwl/nx/issues/26720

### CODE REVIEW

**Review by FrozenPandaz — APPROVED** [review]

**Comment by FrozenPandaz** [comment]
The changes look good. Could you amend your commit message to follow the commit format please?

**Comment by EugeneKruglei** [comment]
> The changes look good. Could you amend your commit message to follow the commit format please?

yes, sure

**Comment by EugeneKruglei** [comment]
@FrozenPandaz  could you pls merge this PR?

**Comment by ilona-si** [comment]
Faced the same issue

**Pull request merged**
