### PR TITLE
docs(docs): adding --with-deps option to the nx test documentation

### PR DESCRIPTION
**Pull request by spaque99**
## Current Behavior
--with-deps was not documented for nx test command.

## Expected Behavior

--with-deps is now documented for the nx test command

## Related Issue(s)

N/A

Fixes #
N/A

### CODE REVIEW

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thank you for your contribution!

These docs are generated. @bcabanes can you help see why that flag is not being documented?

**Comment by vsavkin** [comment]
with-deps is a capaiblity that works with any target (test, build, lint), so I'm not sure if this is the best place to document it.

@isaacplmann can you find a good place to record this information?

**Comment by isaacplmann** [comment]
@spaque99 I would recommend adding a section about `--with-deps` to https://github.com/nrwl/nx/blob/master/docs/angular/guides/cli-overview.md

I'd put it right before the Running Tasks for Multiple Projects section

**Comment by vsavkin** [comment]
Folks, I'm really sorry but I'm going to close this due to inactivity. If you reopen the PR, we will take a look right away. Sorry again.

**Pull request closed without merging**
