### PR TITLE
docs(storybook): best practices guide and recipe

### PR DESCRIPTION
**Pull request by mandarini**
I created a best practices guide for Storybook + Nx. How to best set up storybook to get the most out of Nx.

update:

moved the three examples out of main article and made them separate recipes

https://user-images.githubusercontent.com/6603745/191492554-3d158065-fa8d-4843-a58b-4849b712485f.mov

### CODE REVIEW

**Comment by isaacplmann** [comment]
Some really good content here, but it needs to be split up.  Each of the 3 examples should be its own recipe page, you can link to those recipes from the best practices page.  The main best practices page is actually a concept page.  I don't think we need to link to it from the "More Concepts" page though, I think the best place for it to be linked is from `/packages#storybook` under Guides.

**Comment by mandarini** [comment]
Thank you for the review @isaacplmann ! I'll fix this tomorrow, and send it over to you to make sure it follows the schema!! :D :D I thought too that it's a bit long for just one guide 😅

**Comment by mandarini** [comment]
@isaacplmann I updated my PR, I also attached a video.

[This PR](https://github.com/nrwl/nx-recipes/pull/2) needs to be merged, in order to update the links of the sample repos.

**Comment by isaacplmann** [comment]
Looks good!

**Pull request merged**
