### PR TITLE
fix(core): add queueScheduler to observable's concat method when resolving workspace's project configurations

### LINKED ISSUE #7858: Impossible to build/serve an application after migrating a workspace to project-specific configuration in Nx 13
## Current Behavior
Impossible to build/serve an application after migrating a workspace to project-specific configuration. 

## Expected Behavior
It should serve or build the application

## Steps to Reproduce
After digging some time on what could be the issue I found out that this is due to a too large collection of project configuration files on our side. We have 716 configurations. 654 of them where correctly resolved as a configuration object in the resolveInlineProjectConfigurations method located in @nrwl/tao/src/commands/ngcli-adapter.js, the rest would be kept to the string used to resolve the configuration. This is visible in the toOldFormatOrNull method in @nrwl/tao/src/shared/workspace.js that throws the error as soon as a project config is a string.
If I remove enough projects to be under 654 configuration files I can serve/build the application. As mentioned on the Slack's support channel this is not related to a project configuration in particular, this is really related to the size of the collection. I found out that this happens when trying to concat too many observables without scheduling their resolving operations (https://github.com/ReactiveX/rxjs/issues/3270)

### Failure Logs
`'project.json' files are incompatible with version 1 workspace schemas.`

### Environment
Node : 16.13.0
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : 13.2.2
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/cdk: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/material: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @ngrx/effects: 13.0.1
         @ngrx/store: 13.0.1
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @ngrx/schematics: 13.0.1
         @storybook/angular: 6.4.0-rc.3

### PR DESCRIPTION
**Pull request by vincentpalita**
Adding queueScheduler allows configurations with many project-specific configuration files to work
as expected. Without it, it may lead to the following error: "'project.json' files are incompatible
with version 1 workspace schemas.". Please see related issue here:
https://github.com/ReactiveX/rxjs/issues/3270

ISSUES CLOSED: #7858

## Current Behavior
Impossible to build/serve an application after migrating a workspace to project-specific configuration in Nx 13

## Expected Behavior
Allows to serve/build an application when workspace has a large collection of project-specific configurations.

## Related Issue(s)
#7858 

Fixes #7858

### CODE REVIEW

**Comment by AgentEnder** [comment]
@vincentpalita Can you run `nx format` on your branch and push this back up? Additionally, we are looking at changing from `concat` to `merge` for the inlining operation, can you check if this would fix the issue?

**Comment by vincentpalita** [comment]
> @vincentpalita Can you run `nx format` on your branch and push this back up? Additionally, we are looking at changing from `concat` to `merge` for the inlining operation, can you check if this would fix the issue?

I tried to run `nx format` but it doesn't change anything on the branch so I have nothing to push. I followed the recommendation of a slack message from Miro, but I think I misused the Github function because instead of rebasing from nx:master is merged (I used the update function from Github directly). So it re-ran tests and they are still KO.

About the merge, it seems your team has already done in the commit "c04686ab10d4d9160ccb15320457c42af4124237" from today!

So I guess we can close this PR. I will try the code on our repo.

**Comment by AgentEnder** [comment]
@vincentpalita I actually just ran into this on a personal project, and it **_does_** still fail with `merge`. Adding the queueScheduler unfortunately doesn't fix this either, if you have 650+ projects. I'm opening a PR now that should address this.

**Comment by vincentpalita** [comment]
@AgentEnder I am sorry, I haven't had the chance to test the code again. From what I saw/tried rapidly is that the merge should happen once and not be done inside a loop.
We can chat on slack about that if you want me to try out on our project.

**Pull request closed without merging**
