### PR TITLE
fix(webpack): use webpack-merge for plugins to preserve values, fix React SVG loader

### LINKED ISSUE #14684: Webpack/React - optimization.minimizer is not preserved between plugins
### Current Behavior

When using a webpack config with `withNx` and `withReact` plugins, the minimizer is not preserved.

* `withNx` sets Terser as the minimizer 
* `withReact` calls `withWeb`, which sets the minimizer without considering the previous ones passed.

https://github.com/nrwl/nx/blob/f4a4059e0b2884b17616839b8a6433e5b5196c73/packages/webpack/src/utils/with-web.ts#L101-L103

https://github.com/nrwl/nx/blob/f4a4059e0b2884b17616839b8a6433e5b5196c73/packages/webpack/src/utils/with-web.ts#L368-L371

### Expected Behavior

Should preserve all configuration options between plugins.

Suggestion - As a general solution, a better approach would be using `webpack-merge` in plugins as it has a smart deep-merge.
** There might be other props that are not being merged but rather overridden.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create a repo (even with 15.7.0-beta)
2. Create a React app
3. Set `optimization` to `true` (if not set) in project.json
4. Run a build and observe the configuration - `config.optimization.minimizer` has only `HashedModuleIdsPlugin`
and `CssMinimizerPlugin`

### Nx Report

```shell
15.7.0-beta.0
```

### Failure Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ghost**
## Current Behavior

This PR fixes 2 issues:
* Webpack configuration is not preserved between plugins (e.g. using `withNx` and `withReact` will override the minimizes, see [this issue](https://github.com/nrwl/nx/issues/14684)).
* SVG loader from `withWeb` plugin is preserved in React, causing SVG imports not to be created as components breaking the necessary behavior; see [this issue](https://github.com/nrwl/nx/issues/14383).

## Related Issue(s)

Fixes #14684, #14383

### CODE REVIEW

**Comment by danr-za** [comment]
tests are failing because the build is running with optimization by default, and that removes all env vars as they are tree shaken.

**Comment by jaysoo** [comment]
Hey @danr-za thanks for the PR. One thing to keep in mind is that `@nrwl/react` does not have dependencies on `webpack` or `webpack-merge` by design (because you could swap for Vite for example), so any usage of `webpack-merge` will need to be installed via `@nrwl/webpack:init` and imported dynamically via `require` in `@nrwl/react` (in the case of files exported from `src/index.ts`). Otherwise you will get an import error for projects not using webpack.

I wonder if there are small fixes we can make without the merge util. For example, if we are not `maintaining `optimization` correctly, can we fix that instead of using merge?

**Comment by danr-za** [comment]
Hey @jaysoo 

Of course, we can tackle each property separately, but I wonder whether we would have future issues caused by value overrides instead of merges.
If you prefer, I can remove the merging and fix the issues we have specifically, and we can always add merge back in the future if more issues pop up. Wdyt?

**Comment by danr-za** [comment]
Done

**Review by jaysoo — APPROVED** [review]

**Pull request merged**
