### PR TITLE
fix(testing): add Cypress ESLint plugin

### PR DESCRIPTION
**Pull request by devinshoemaker**
This fixes linting errors when using ESLint with a Cypress project that uses JavaScript.

## Current Behavior (This is the behavior we have today, before the PR is merged)

A freshly generated Cypress project with ESLint and JS will throw linting errors.

```
> nx run test-for-derek:lint 

Linting "test-for-derek"...

/Users/devinshoemaker/code/nx/playground/cypress-test/apps/test-for-derek/src/support/app.po.js
  1:34  error  'cy' is not defined  no-undef

/Users/devinshoemaker/code/nx/playground/cypress-test/apps/test-for-derek/src/integration/app.spec.js
  2:1   error  'describe' is not defined    no-undef
  3:5   error  'beforeEach' is not defined  no-undef
  3:22  error  'cy' is not defined          no-undef
  4:5   error  'it' is not defined          no-undef
  6:9   error  'cy' is not defined          no-undef

/Users/devinshoemaker/code/nx/playground/cypress-test/apps/test-for-derek/src/support/commands.js
  3:1  error  'Cypress' is not defined  no-undef
  4:5  error  'console' is not defined  no-undef

✖ 8 problems (8 errors, 0 warnings)

Lint errors found in the listed files.
```

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

A freshly generated Cypress project with ESLint and JS will not throw linting errors.

### CODE REVIEW

**Comment by Cammisuli** [comment]
@devinshoemaker I updated your branch to get the latest on master. That should fix these CI checks.

**Comment by devinshoemaker** [comment]
@Cammisuli thanks. It appears that they are still not passing at the moment, but I'm looking into it locally. 

Also, is it work creating a migration for this? I should be able to read the users `workspace.json` to see if they have any Cypress projects using ESLint, and then I can add the new dependency and update the projects `.eslintrc`.

**Comment by devinshoemaker** [comment]
I will be adding a migration for this change. Please refrain from merging until that has been pushed up.

**Comment by devinshoemaker** [comment]
A migration has been added. All the unit tests pass for me locally, and if I remember correctly, the one that failed for this PR fail intermittently in CircleCI. Let me know if there's anything that needs to be addressed for that.

**Review by Cammisuli — CHANGES_REQUESTED** [review]
Hey Devin!

Sorry it took so long to get around to this ☹️ 

Anyway, adding the cypress eslint plugin looks good for adding new projects, and those lint checks are passing. But the migration is a little too eager. It's adding the plugin to every `eslintrc` file. 

You could possibly limit the scope by checking the builder for a project to see if it's using `"builder": "@nrwl/cypress:cypress"`, or if a project has the `e2e` architect.

**Comment by devinshoemaker** [comment]
@Cammisuli you're totally right. I had intended on doing that in the first place but it must have slipped my mind. I'll resolve this soon.

**Comment by devinshoemaker** [comment]
@Cammisuli I think these adjustments should suffice.

**Review by Cammisuli — APPROVED** [review]
LGTM 🎉 

Migrations are good, and new projects have the plugin 👍

**Comment by Cammisuli** [comment]
@devinshoemaker it looks like the unit test failed now :(

**Comment by devinshoemaker** [comment]
🙃  okay all green now.

**Pull request merged**
