### PR TITLE
make vite:build executor return outfile for node executor

### LINKED ISSUE #14760: @nrwl/js:node can't work with @nrwl/vite:build
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I have a build target build by vite build executor.

"build": {
      "executor": "@nrwl/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/my-app"
      },
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production"
        }
      }
    },
    
 I want to use js:node executer to run from the build target

    "vite-serve": {
      "executor": "@nrwl/js:node",
      "defaultConfiguration": "development",
      "configurations": {
        "development": {
          "buildTarget": "my-app:build:development"
        },
        "production": {
          "buildTarget": "my-app:build:production",
          "inspect": false
        }
      }
    },

but I am not able to run it.

> nx run my-app:vite-serve:development

 >  NX   Property 'watch' does not match the schema. 'true' should be a 'object'.

 ————————————————————————————————————————————————————————————————————

 >  NX   Ran target vite-serve for project my-app (627ms)

### **Most executors are having 'watch' option with boolean type.
while vite:build executor requires 'watch' schema to be an object.**

### PR DESCRIPTION
**Pull request by lengerrong**
fixed #14760

## Current Behavior

js:node executor can't use vite:build as build target

## Expected Behavior

js:node executor should be able to use vite:build as build target

## Related Issue(s)

https://github.com/nrwl/nx/issues/14760

Fixes #
https://github.com/nrwl/nx/issues/14760

### CODE REVIEW

**Comment by mandarini** [comment]
Hi there @lengerrong ! Thank you so much for this PR! Can you see to the failure logs, and make sure it works? Thank you so much for contributing!

**Comment by mandarini** [comment]
Hi there @lengerrong ! Can you please rebase and take a look at the failing tests?

**Comment by mandarini** [comment]
Hi there @lengerrong ! Can you take a look at these failing tests?

**Comment by lengerrong** [comment]
@mandarini just resync mine forked branch.
hope this time the ci check can pass.
if still failed, I will not continue work on this one.

**Comment by mandarini** [comment]
@lengerrong yeah ok I'll take a look tomorrow.  I will fix the commit message, squash the commits etc.

I only want one favor from you @lengerrong . Can you verify that this PR achieves its goal? Does it indeed return what it needs to return?

**Comment by lengerrong** [comment]
@mandarini @jaysoo @ndcunningham 

rebase from master again. a new round build triggered.
still got the same error:

> nx run @nrwl/nx-source:root-lint

yarn run v1.22.19
$ nx workspace-lint

 >  NX   "nx workspace-lint" has been deprecated.

   Nx has been reworked to make sure that the issues workspace-lint used to catch are not longer possible.
   Remove "nx workspace-lint" from your CI.

Done in 0.21s.
packages/vite/src/executors/build/build.impl.ts

 


 >  NX   Nx Cloud: Successfully recorded command output

   You can view or share your output by visiting https://staging.nx.app/runs/QhNbW4hk07


> nx run @nrwl/nx-source:check-imports


> nx run @nrwl/nx-source:check-commit

yarn run v1.22.19
$ node ./scripts/commit-lint.js
🐟🐟🐟 Validating git commit message 🐟🐟🐟
Commit ACCEPTED 👍
Done in 0.15s.

Exited with code exit status 1
CircleCI received exit code 1


The log can't tell anything.
I did run 'yarn build' in my local, everything looks good.
image

not sure, can you review the latest code change and ignore the CI build error(unreasonable error) and approve this PR?

**Comment by mandarini** [comment]
@lengerrong yes, don't worry about the CI fails for now! Did you test this to see if it's achieving what you expect it to? Do you get the output file? Because I tried it and I am not sure it works as expected? Does it work for you?

**Comment by AgentEnder** [comment]
The CI failure is on `nx format` - you can see it here: https://staging.nx.app/branch?workspaceId=62d013ea0852fe0a2df74438&branchName=15002,master&runGroup=run-group-linux-f3fb851b-7071-4ac6-a19a-a2b0ddf89424

**Comment by lengerrong** [comment]
@mandarini 

finally got all the tests check pass.
would you have a review the change and approve it if looks good, please?

**Pull request closed without merging**
