### PR TITLE
docs(nx): update images links

### PR DESCRIPTION
**Pull request by bcabanes**
Update image links in the documentation for each flavors. This will resolved display problems on the website. The images are displayed when viewing the markdown as well.

### CODE REVIEW

**Comment by vsavkin** [comment]
@bcabanes the path should be absolute. What display problems are your seeing?

**Comment by bcabanes** [comment]
Actually, I don't think we them to be absolute, we have some logic on the markdown function for the website that update the links for images.

**Comment by mehrad-rafigh** [comment]
@vsavkin this is what I see with Chromium
image

This is what i see with Firefox Nightly
image

**Comment by vsavkin** [comment]
@bcabanes they don't need to be absolute, but they can be absolute, right? 

I actually prefer absolute paths cause I can copy and paste images without having to adjust the number of `../`

@mehrad-rafigh yeah, that's broken. This PR isn't fixing it though. We should fix the API home page instead.

**Comment by bcabanes** [comment]
@vsavkin Changed back to absolute urls. 👍

**Pull request merged**
