### PR TITLE
fix(schematics): check touchedFile path against the project files

### PR DESCRIPTION
**Pull request by MitkoTschimev**
Fix for the issue https://github.com/nrwl/nx/issues/613.

Problem was here that the path from the file (git) was checked against the project.root with "startWith" which is not working if you haven't nx in your root directory of your repository

### CODE REVIEW

**Comment by vsavkin** [comment]
@tfiwm thank you for your PR. Could you add a test, or update an existing test?

**Comment by tfiwm** [comment]
Done :)

**Comment by exequiel09** [comment]
I hope this gets merged soon 👍

**Comment by vsavkin** [comment]
Looks good! Could you squash the commits? I'll merge it after.

**Comment by tfiwm** [comment]
Created a new one with clean commits and no merges ;)
#662

**Pull request closed without merging**
