### PR TITLE
feat(nx): Add support for linux-s390x platform

### PR DESCRIPTION
**Pull request by nealef**
* packages/nx/native-packages/linux-s390x-gnu/README.md
* packages/nx/native-packages/linux-s390x-gnu/package.json
* packages/nx/native-packages/linux-s390x-gnu/project.json
* packages/nx/package.json
* packages/nx/src/native/index.js
  - Add linux-s390x-gnu as a known platform

* packages/nx/src/native/native-bindings.js
  - Add case for linux/s390x

### Related Issue(s)
[Support s390x](https://github.com/nrwl/nx/discussions/23573)

### CODE REVIEW

**Comment by FrozenPandaz** [comment]
Thanks for your work on this! I don't think we're going to release a s390x package though. However, we are working on wasm support. Could you perhaps test with the releases which were made off of this PR https://github.com/nrwl/nx/pull/22870? This should work on s390x. Please let me know if that works. Let's continue the discussion there.

**Comment by nealef** [comment]
> Thanks for your work on this! I don't think we're going to release a s390x package though. However, we are working on wasm support. Could you perhaps test with the releases which were made off of this PR #22870? This should work on s390x. Please let me know if that works. Let's continue the discussion there.

I'm doing so now. It's becoming a bit of a dependency hell as you need `nx` which needs `nx` to build itself. It also requires `naspi-rs`, `yarn@4.1.1`, and `swc`. I also need a later level of `bindgen` when building `naspi-rs`. I'm sure there'll be others.

**Comment by v1gnesh** [comment]
> I don't think we're going to release a s390x package though. 

@FrozenPandaz What if `nx` is able to add a GH Actions runner that runs  linux natively in s390x?
This can be arranged, and it can either be a managed instance or you can manage it (but hosted in IBM community cloud).

**Comment by nealef** [comment]
> > I don't think we're going to release a s390x package though.
> 
> @FrozenPandaz What if `nx` is able to add a GH Actions runner that runs linux natively in s390x? This can be arranged, and it can either be a managed instance or you can manage it (but hosted in IBM community cloud).

I can set up one anytime in a matter of a few minutes. Just need a token.

**Comment by FrozenPandaz** [comment]
So the issue with creating a s390x package isn't so much creating the binary and the code itself. It's more having yet another package for a platform which isn't widely used. The wasm branch that I pointed to should have support for s390x without having to publish yet another package and also supports any system that Node can run on.

You can test it by using `nx@0.0.0-pr-22870-b988ae5` (it's published to NPM) for all of your Nx packages. You don't have to build nx from source.

**Comment by nealef** [comment]
> So the issue with creating a s390x package isn't so much creating the binary and the code itself. It's more having yet another package built and published for a platform which isn't widely used. The wasm branch that I pointed to should have support for s390x without having to publish yet another package and also supports any system that Node can run on.
> 
> You can test it by using `nx@0.0.0-pr-22870-b988ae5` (it's published to NPM) for all of your Nx packages. You don't have to build nx from source.

I'm rapidly getting out of my depth but I'll push on. Are you suggesting that if I see something like this in the `yarn.lock` file of `grafana`:
```
"nx@npm:19.2.0":
  version: 19.2.0
  resolution: "nx@npm:19.2.0"
  dependencies:
    "@nrwl/tao": "npm:19.2.0"
    "@nx/nx-darwin-arm64": "npm:19.2.0"
    "@nx/nx-darwin-x64": "npm:19.2.0"
    "@nx/nx-freebsd-x64": "npm:19.2.0"
    "@nx/nx-linux-arm-gnueabihf": "npm:19.2.0"
    "@nx/nx-linux-arm64-gnu": "npm:19.2.0"
    "@nx/nx-linux-arm64-musl": "npm:19.2.0"
    "@nx/nx-linux-x64-gnu": "npm:19.2.0"
    "@nx/nx-linux-x64-musl": "npm:19.2.0"
    "@nx/nx-win32-arm64-msvc": "npm:19.2.0"
    "@nx/nx-win32-x64-msvc": "npm:19.2.0"
```
I should replace the `19.2.0` with `0.0.0-pr-22870-b988ae5`? Do I need to specify anything for `wasm`?

Or should I try just installing it via `npm install`? I tried that level of `nx` and got:
```
#10 [build  6/15] RUN		NPM install -g nx@0.0.0-pr-22870-b988ae5
#10 9.830 npm error code 1
#10 9.830 npm error path /usr/local/lib/node_modules/nx
#10 9.830 npm error command failed
#10 9.830 npm error command sh -c node ./bin/post-install
#10 9.830 npm error thread '<unnamed>' panicked at library/std/src/sys/sync/rwlock/futex.rs:231:9:
#10 9.830 npm error assertion failed: is_unlocked(state)
#10 9.830 npm error note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#10 9.830 npm error /usr/local/lib/node_modules/nx/src/native/native-bindings.js:359
#10 9.830 npm error     throw new Error('Failed to load native binding', { cause: loadErrors })
#10 9.830 npm error     ^
#10 9.830 npm error
#10 9.830 npm error Error: Failed to load native binding
#10 9.830 npm error     at Object.<anonymous> (/usr/local/lib/node_modules/nx/src/native/native-bindings.js:359:11)
#10 9.830 npm error     at Module._compile (node:internal/modules/cjs/loader:1369:14)
#10 9.830 npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
#10 9.830 npm error     at Module.load (node:internal/modules/cjs/loader:1206:32)
#10 9.830 npm error     at Module._load (node:internal/modules/cjs/loader:1022:12)
#10 9.830 npm error     at Module._load (/usr/local/lib/node_modules/nx/src/native/index.js:85:25)
#10 9.830 npm error     at Module.require (node:internal/modules/cjs/loader:1231:19)
#10 9.830 npm error     at require (node:internal/modules/helpers:179:18)
#10 9.830 npm error     at Object.<anonymous> (/usr/local/lib/node_modules/nx/src/native/index.js:91:21)
#10 9.830 npm error     at Module._compile (node:internal/modules/cjs/loader:1369:14) {
#10 9.830 npm error   [cause]: [
#10 9.830 npm error     Error: Cannot find module './nx.linux-s390x-gnu.node'
```

**Comment by v1gnesh** [comment]
> So the issue with creating a s390x package isn't so much creating the binary and the code itself. It's more having yet another package built and published for a platform which isn't widely used. The wasm branch that I pointed to should have support for s390x without having to publish yet another package and also supports any system that Node can run on.
> 
> You can test it by using `nx@0.0.0-pr-22870-b988ae5` (it's published to NPM) for all of your Nx packages. You don't have to build nx from source.

Urge you to please reconsider. The platform _is_ widely used, just not known as such.
It's great that you're sharing your work here, and more power to Rust tools.
Please allow us mainframers to celebrate what you've created, whether it's directly or indirectly.

**Comment by FrozenPandaz** [comment]
#22870 has been merged and published as `19.5.0`. If you update your Nx version, things should work on s390x. Please open an issue if there are any issues.

**Comment by v1gnesh** [comment]
@FrozenPandaz if you have a few moments, could you please show how to do this.
I'm pretty alien to the front-end world..

**Comment by FrozenPandaz** [comment]
@v1gnesh Sure, could you please reach out to me over the community discord and we'll set up a time? https://go.nx.dev/community

My handle is the same ^

**Comment by rposts** [comment]
@FrozenPandaz - I tried using `19.5.2` and got the following error - seems like `swc` related or am I missing something (?)
```
root@e678b9a6985b:/tmp/nx# pnpm install nx@19.5.2
 WARN  11 deprecated subdependencies found: @babel/plugin-proposal-class-properties@7.18.6, @babel/plugin-proposal-private-property-in-object@7.21.0, @npmcli/move-file@2.0.1, domexception@4.0.0, glob@6.0.4, json-schema-ref-parser@9.0.9, readdir-scoped-modules@1.1.0, reflect-metadata@0.2.1, rimraf@2.4.5, stable@0.1.8, uuid@3.4.0
Packages: +3706
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 3881, reused 3560, downloaded 2, added 35, done
node_modules/.pnpm/esbuild@0.20.0/node_modules/esbuild: Running postinstall script, done in 508ms
node_modules/.pnpm/esbuild@0.19.11/node_modules/esbuild: Running postinstall script, done in 464ms
node_modules/.pnpm/esbuild@0.20.1/node_modules/esbuild: Running postinstall script, done in 461ms
node_modules/.pnpm/cypress@13.13.0/node_modules/cypress: Running postinstall script...
node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx: Running postinstall script, failed in 465ms/.pnpm/nx@19.5.2_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx: Running postinstall script...
.../node_modules/nx postinstall$ node ./bin/post-install
│ thread '<unnamed>' panicked at library/std/src/sys/sync/rwlock/futex.rs:231:9:
│ assertion failed: is_unlocked(state)
│ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
│ /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native/native-b…
│     throw new Error('Failed to load native binding', { cause: loadErrors })
│     ^
│ Error: Failed to load native binding
│     at Object.<anonymous> (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_mod…
│     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
│     at Module.load (node:internal/modules/cjs/loader:1091:32)
│     at Module._load (node:internal/modules/cjs/loader:938:12)
│     at Module._load (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/n…
│     at Module.require (node:internal/modules/cjs/loader:1115:19)
│     at require (node:internal/modules/helpers:130:18)
│     at Object.<anonymous> (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_mod…
│     at Module._compile (node:internal/modules/cjs/loader:1241:14) {
│   [cause]: [
│     Error: Cannot find module './nx.linux-s390x-gnu.node'
│     Require stack:
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native/na…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native/in…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/daemon/cl…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/project-g…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/bin/post-inst…
│         at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
│         at Module._load (node:internal/modules/cjs/loader:901:27)
│         at Module._load (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modul…
│         at Module.require (node:internal/modules/cjs/loader:1115:19)
│         at require (node:internal/modules/helpers:130:18)
│         at requireNative (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modu…
│         at Object.<anonymous> (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node…
│         at Module._compile (node:internal/modules/cjs/loader:1241:14)
│         at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
│         at Module.load (node:internal/modules/cjs/loader:1091:32) {
│       code: 'MODULE_NOT_FOUND',
│       requireStack: [
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/daemon…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/projec…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/bin/post-i…
│       ]
│     },
│     Error: Cannot find module '@nx/nx-linux-s390x-gnu'
│     Require stack:
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native/na…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native/in…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/daemon/cl…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/project-g…
│     - /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/bin/post-inst…
│         at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
│         at Module._load (node:internal/modules/cjs/loader:901:27)
│         at Module._load (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modul…
│         at Module.require (node:internal/modules/cjs/loader:1115:19)
│         at require (node:internal/modules/helpers:130:18)
│         at requireNative (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modu…
│         at Object.<anonymous> (/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node…
│         at Module._compile (node:internal/modules/cjs/loader:1241:14)
│         at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
│         at Module.load (node:internal/modules/cjs/loader:1091:32) {
│       code: 'MODULE_NOT_FOUND',
│       requireStack: [
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/native…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/daemon…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/src/projec…
│         '/tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx/bin/post-i…
│       ]
│     }
│   ]
│ }
│ Node.js v20.9.0
└─ Failed in 466ms at /tmp/nx/node_modules/.pnpm/nx@19.5.0-beta.5_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx
node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.1_@swc+core@1.5.7/node_modules/nx: Running postinstall script...
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by nealef** [comment]
See my comment in https://github.com/nrwl/nx/issues/27031.

**Pull request closed without merging**
