### PR TITLE
fix(storybook): optional chain all includes

### LINKED ISSUE #9702: Cannot read property 'includes' of undefined storybook-configuration
## Current Behavior

`adding .storybook folder to the root directory - 
     based on the Storybook version installed (v6), we'll bootstrap a scaffold for that particular version.
adding .storybook folder to app - using Storybook version 6
Cannot read property 'includes' of undefined`
Screen Shot 2022-04-06 at 11 26 36

## Expected Behavior

I want that the storybook successfully created
## Steps to Reproduce

I am already upgrade the nx env to 13.9.7 from 13.8.5
And it not fix the problem.

### Failure Logs

`adding .storybook folder to the root directory - 
     based on the Storybook version installed (v6), we'll bootstrap a scaffold for that particular version.
adding .storybook folder to app - using Storybook version 6
Cannot read property 'includes' of undefined`
### Environment

Node : 14.19.0
   OS   : darwin x64
   npm  : 6.14.16
   
   nx : 13.9.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.7
   @nrwl/eslint-plugin-nx : 13.9.7
   @nrwl/express : 13.9.7
   @nrwl/jest : 13.9.7
   @nrwl/js : 13.9.7
   @nrwl/linter : 13.9.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.9.7
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.7
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.7
   @nrwl/web : 13.9.7
   @nrwl/workspace : 13.9.7
   typescript : 4.5.5
   rxjs : 6.6.7

### PR DESCRIPTION
**Pull request by mandarini**
ISSUES CLOSED: #9702

## Related Issue(s)
#9702

Fixes #9702

### CODE REVIEW

**Review by Coly010 — APPROVED** [review]
LGTM! 🎉

**Comment by guyindepurker** [comment]
How can i update and see this change? i try to update nx with nx and the version didn’t change for me in packge.json

**Comment by mandarini** [comment]
@guyindepurker this will be available in the next version of Nx, `13.10`, which should be available soon. Let me know if you need any help in the meantime!

**Comment by mandarini** [comment]
@guyindepurker https://github.com/nrwl/nx/releases/tag/13.10.0 `13.10.0` is out, so you should be good to go!

**Pull request merged**
