### PR TITLE
feat(nx-plugin): migrate generators to @nrwl/devkit

### PR DESCRIPTION
**Pull request by Phillip9587**
## Current Behavior

`@nrwl/nx-plugin` generators use `@angular-devkit`

## Expected Behavior

should use `@nrwl/devkit`

## Related Issue(s)

#5802 

closes #5802

### CODE REVIEW

**Comment by Phillip9587** [comment]
@Cammisuli I would need some help with the CI please. If i run the E2E tests local they succeed but they fail due to a strange issue with eslint during the CI run.

**Comment by Cammisuli** [comment]
Ok, I'll take a look as soon as I'm able to. :pray:

**Comment by Phillip9587** [comment]
@Cammisuli Thanks a lot!

**Review by Cammisuli — APPROVED** [review]
Thanks for all of your initial work @Phillip9587! Everything looks good from my testing 😄

**Pull request merged**
