### PR TITLE
chore(core): nx plugin submission [@angular-custom-builders/lite-serve]

### PR DESCRIPTION
**Pull request by mauriziovitale**
Propose e2e lite-serve plugin to be able to run the e2e on an existing dist folder without building the app again

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

# Community Plugin Submission

Thanks for submitting your Nx Plugin to our community plugins list. Make sure to follow these steps to ensure that your PR is approved in a timely manner.

## Steps to Submit Your Plugin
- Use the following commit message template: `chore(core): nx plugin submission [PLUGIN_NAME]`
- Update the `community/approved-plugins.json` file with a new entry for your plugin that includes `name`, `url`, `description`:

Example:

```json
// community/approved-plugins.json

[{
    "name": "@community/plugin",
    "url": "https://github.com/community/plugin",
    "description": "This plugin provides the following capabilities."
}]
```

Once merged, your will plugin will be available when running the `nx list` command, and will also be available in the Plugin browser on [nx.dev](https://nx.dev)

### CODE REVIEW

**Comment by Cammisuli** [comment]
Hey @mauriziovitale thanks for the PR! Can you please format the json file so that the CI can add ✅ to everything?

**Comment by mauriziovitale** [comment]
> Hey @mauriziovitale thanks for the PR! Can you please format the json file so that the CI can add ✅ to everything?

@Cammisuli done.
looking forward to hearing your feedback

**Comment by wesleygrimes** [comment]
@mauriziovitale looks good! Can you rebase really quick and then we will get it merged. Thanks!

**Comment by mauriziovitale** [comment]
> @mauriziovitale looks good! Can you rebase really quick and then we will get it merged. Thanks!

Done @wesleygrimes

**Comment by Cammisuli** [comment]
@mauriziovitale I can't seem to get this working locally. It just appears to me that the version that's published on npm isn't up to date. Currently as it is on npm, it doesn't work ☹️

**Comment by mauriziovitale** [comment]
> @mauriziovitale I can't seem to get this working locally. It just appears to me that the version that's published on npm isn't up to date. Currently as it is on npm, it doesn't work ☹️

Thanks for the feedback. I will check.

**Comment by mauriziovitale** [comment]
@Cammisuli  I have fixed the formatting error but the Unit test job is failing.

**Comment by mauriziovitale** [comment]
@Cammisuli have you had any chance to review it?

**Pull request merged**
