### PR TITLE
fix(core): Fix missing import in 'remove/schema.d.ts'

### PR DESCRIPTION
**Pull request by ivarorn85**
fix(core): Fix missing import in 'remove/schema.d.ts'

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you for the PR! Please update the commit message, otherwise it's good.

**Comment by ivarorn85** [comment]
@vsavkin is this better?

**Comment by mehrad-rafigh** [comment]
@ivarorn85 no not really. 
Your commit message should follow the Contribution guideline
I suggest you use `yarn commit` and follow the questions. Let me know if you need help

**Comment by ivarorn85** [comment]
@mehrad-rafigh, thanks for pointing me in the right direction. I hope it's ok now, if not I think I could use some help :)

**Comment by mehrad-rafigh** [comment]
@ivarorn85 no to me it looks good. The CI passed, so this can get merged

**Comment by vsavkin** [comment]
Thank you!

**Pull request merged**
