### PR TITLE
fix: storybook global preview settings

### PR DESCRIPTION
**Pull request by sergeylukin**
## Current Behavior

Global preview settings are ignored

## Expected Behavior

Global preview settings are applied

### CODE REVIEW

**Comment by mandarini** [comment]
Hi there @sergeylukin! Thank you for your contribution! Can you please fix any failing pipelines, and push again?

**Review by mandarini — APPROVED** [review]

**Comment by sergeylukin** [comment]
Sorry @mandarini for delay. Is there anything to be made on my end?

**Comment by mandarini** [comment]
Hi there @sergeylukin ! I rebased your branch and pushed again. Let's see how the pipelines do this time, and if they're still broken, can you take a look to fix them? Or I can at some point!

**Comment by sergeylukin** [comment]
Sure @mandarini will keep an eye and do my best to prevent CI/CD armageddons but please stay around lol

**Comment by mandarini** [comment]
Hi @sergeylukin ! Any news here? The test fails because we don't generate a root `preview.js`. So, a decision needs to be made, to see if we really need to add a root `preview.js` or not, since it's not necessary for everyone. Let me know what you think.

**Pull request closed without merging**
