### PR TITLE
fix(schematics): consider ExportDeclaration w/ moduleSpecifier for dependency calculation in v7

### LINKED ISSUE #1303: DepsCalculator: Cannot read property 'getText' of undefined
## Expected Behavior

No build failure. DepsCalculator considers [optional property `moduleSpecififer` in `ExportDeclaration`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2322-L2323)

## Current Behavior

```bash
$ node_modules/.bin/nx affected:test <..>
Cannot read property 'getText' of undefined
```

Caused by:

```
export { ButtonModule };
```

Seems to be a ExportDeclaration w/o a moduleSpecififer. See the TypeScript API: moduleSpecifier is an optional property.

## Failure Information (for bugs)

DepsCalculator#processFile was changed from 7.7.2 to 7.8.0 in [`3cf84ec`](https://github.com/nrwl/nx/commit/3cf84eca24ff6156d00618c1462036f32110c690#diff-c4b3f365f3a5a4299e8387c0dbe6b87fR268)

Guessing: correct if conditition is

```ts
if (ts.isImportDeclaration(node) || (ts.isExportDeclaration(node) && node.moduleSpecifier)) {
 /* ... add deps ... */
}
```

NX Version: 7.8.3

```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 11.14.0
OS: darwin x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-ng-packagr   0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.1
@angular/cdk                       7.3.7
@angular/cli                       7.3.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         5.1.0
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
```

### Steps to Reproduce

n/a

### Context

n/a

### Failure Logs

n/a

## Other

n/a

### PR DESCRIPTION
**Pull request by dherges**
Closes #1303

### CODE REVIEW

**Comment by dherges** [comment]
Confirm this change lets test run pass as expected in 7.7.2:

```
$ node_modules/.bin/nx affected:test <..>
Running test for projects:
 ...
Running test for ...
Running test for ...
Running test for ...
Running test for affected projects succeeded.
```

**Comment by FrozenPandaz** [comment]
Thanks for your contribution!

LGTM! Just run `yarn format` to format the code please. 👍

**Comment by dherges** [comment]
@FrozenPandaz will do!

**Comment by FrozenPandaz** [comment]
Looks like this is a duplicate of: #1311

**Comment by dherges** [comment]
This is the fix for Nrwl 7.x

**Pull request merged**
