### PR TITLE
chore(core): nx plugin submission @flowaccount/nx-serverless

### PR DESCRIPTION
**Pull request by wickstargazer**
linking this to issue #2670 

Regards,
Wick

### CODE REVIEW

**Review by wesleygrimes — COMMENTED** [review]
Thanks for putting this together! Looks like an exciting plugin with a lot of features. As part of the approval process we will be testing the plugin. 

A couple items I found at first are:

- Trying to run `yarn nx add @flowaccount/nx-serverless` in an nx workspace and it fails with:

Screen Shot 2020-03-16 at 10 05 01 AM

- The README states you can run `npm nx generate @flowaccount/nx-serverless:api-serverless` but I believe this only works with `yarn` `npm` doesn't work.

Will review in more detail today and get back with you.

Thanks again!

**Review by wesleygrimes — CHANGES_REQUESTED** [review]
Left some feedback

**Comment by wickstargazer** [comment]
Hi! Thankz for testing it out! :)
I have done some local tests myself, i guess i need to change the doc to `npm run`
image

for `yarn nx add @flowaccount/nx-serverless`, its working for me locally, is it because of `yarn link`? I am not good with npm and yarn yet, so any head ups or hints would be great.
Although i found a bug boostrapping ng-universal from scratch, will be fixing that in a day or two.
I will also read up on the set for `npm` without `run` and try `unlinking` yarn and test it out

Thankz!

**Comment by wesleygrimes** [comment]
> Hi! Thankz for testing it out! :)
> I have done some local tests myself, i guess i need to change the doc to `npm run`
> image
> 
> for `yarn nx add @flowaccount/nx-serverless`, its working for me locally, is it because of `yarn link`? I am not good with npm and yarn yet, so any head ups or hints would be great.
> Although i found a bug boostrapping ng-universal from scratch, will be fixing that in a day or two.
> I will also read up on the set for `npm` without `run` and try `unlinking` yarn and test it out
> 
> Thankz!

For `ng add`:

- `npx @angular/cli add @flowaccount/nx-serverless` works
- If you have angular cli installed globally or in the project then you can do `ng add @flowaccount/nx-serverless`

Regarding running the schematics and builders, you can do:

- `npx nx generate @flowaccount/nx-serverless:api-serverless`
- If you have nx cli installed globally or in project then you can just do `nx generate @flowaccount/nx-serverless:api-serverless`. This works regardless of `npm` or `yarn` usage.

**Comment by wickstargazer** [comment]
So the conclusion is i should change the Readme and we are fine?

**Comment by wesleygrimes** [comment]
> So the conclusion is i should change the Readme and we are fine?

Yeah, that's fine, I will go ahead and merge this as well.

Thanks!

**Review by wesleygrimes — APPROVED** [review]

**Comment by wickstargazer** [comment]
I have updated the main Readme! for npm i will publish a change with bug fix soon, thank you for the opportunity :)

**Pull request merged**
