### PR TITLE
docs(nx): update yarn commands in Creating First Application section

### PR DESCRIPTION
**Pull request by ahnpnl**
_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

> _Please make sure that your commit message follows our format._

> Example: `fix(nx): must begin with lowercase`

## Current Behavior (This is the behavior we have today, before the PR is merged)
`npm` commands in **Creating First Application** specify `-dev` while `yarn` commands don't. This PR is to update `yarn` commands to add `-D` to be equivalent to `npm` commands.

## Expected Behavior (This is the new behavior we can expect after the PR is merged)
`yarn` commands should have `-D` to be equivalent to `-dev` of `npm`

## Issue
**N.A.**

### CODE REVIEW

**Comment by vsavkin** [comment]
@ahnpnl thank you for your PR. Could you update the commit message to match our format?

```
docs(nx): update yarn commands in ...
```

**Comment by ahnpnl** [comment]
Hi,

I ammended the commit message but CI still failed, not sure why..

**Comment by brandonroberts** [comment]
@ahnpnl I think we should keep the usage consistent across both commands with `--dev` instead of `-D`.

**Comment by ahnpnl** [comment]
sure I will change accordingly

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @ahnpnl!

**Pull request merged**
