### PR TITLE
Implement main nest features

### PR DESCRIPTION
**Pull request by yharaskrik**
Implements schematics for:

1. pipes
2. interceptors
3. services
4. controllers
- With optional flag for a service
5. guards
6. middlewares

Update lib schematic to have a flag for all of the above. 

Lib will be generated with a module **if** global, service or controller flags are set to true for lib. If generating a middleware in a library with a controller the middleware will be configured on that controllers routes.

@Cammisuli not sure if we want to get other other PR in first (with just the lib code) or close that one and just merge this PR (when approved) as this one is based off of my last PR but has some refactoring and extra flags for the lib. I also went ahead and made a nest e2e file so that I could test the new schematics but did not move the e2e tests for application, library or anything else nest related into the nest.test.ts file. Only new code I wrote today is in there.

### CODE REVIEW

**Comment by Cammisuli** [comment]
@yharaskrik you can rebase off master, and clean up this PR to only include the new features you added.

**Comment by yharaskrik** [comment]
@Cammisuli sounds good thanks for merging the other one in. I will fix up the merge conflicts due to the refactoring and push the changes up tonight.

**Review by Cammisuli — CHANGES_REQUESTED** [review]
We can extend the `@nestjs/schematics` in the `nest/package.json`. This allows us to use all the schematics that nest provides, but wrap it in a nice bow 😄 

We'll have to mention in the docs that people would have to use `--sourceRoot` when using the nest schematics.

**Comment by Cammisuli** [comment]
@yharaskrik can you check your tests?

**Comment by yharaskrik** [comment]
Hey @Cammisuli ya sorry I haven't finished up with this yet, been trying to get bits of it done as I have time right now!

**Comment by yharaskrik** [comment]
@Cammisuli because this branch had a bunch of refactoring in it so that I could share code between all the schematics, I decided to open a separate PR with just the change we discussed #2756 

I will revisit what I have here after I here from you one what we talked about building the "joiner" schematics to make the @nestjs/schematics flags compatible with the Nx api.

**Pull request closed without merging**
