### PR TITLE
fix(nest): repair nestjs service generator schema

### LINKED ISSUE #28910: NestJS generator not working properly
### Current Behavior

When using the nx g @nx/nest:service generator, it always reports an error, and the file cannot be generated properly. Check the error log, it seems to indicate that the `path` value is empty.

Referring to some of the other nestjs generators, it seems to me that it is missing a `--path` parameter, and if I try to enter it, nx will point out that this parameter is not in the schema.

Indeed, [https://github.com/nrwl/nx/blob/master/packages/nest/src/generators/service/schema.json](https://github.com/nrwl/nx/blob/master/packages/nest/src/generators/service/schema.json)

And, it actually worked when I added path to the jsonschema specification. But this still has some other problems, and I mentioned it at the end of the issue.

### Expected Behavior

It should normally generate a typescript file.

### GitHub Repo

_No response_

### Steps to Reproduce

1. pnpm create nx-workspace my-workspace --preset=nest
2. cd apps/my-workspace/src/app
3. nx g @nx/nest:service --name auth --verbose

### Nx Report

```shell
Node           : 20.13.1
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.5.2

nx (global)        : 20.1.0
nx                 : 20.1.0
@nx/js             : 20.1.0
@nx/jest           : 20.1.0
@nx/eslint         : 20.1.0
@nx/workspace      : 20.1.0
@nx/eslint-plugin  : 20.1.0
@nx/nest           : 20.1.0
@nx/node           : 20.1.0
@nx/web            : 20.1.0
@nx/webpack        : 20.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
➜  my-workspace ✗ nx g @nx/nest:service --name auth --verbose

 NX  Generating @nx/nest:service


 NX   Cannot read properties of undefined (reading 'replace')

TypeError: Cannot read properties of undefined (reading 'replace')
    at extractNameAndDirectoryFromPath (/home/ubuntu/code/my-workspace/node_modules/.pnpm/@nx+devkit@20.1.0_nx@20.1.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@s_oybkiddel7pp5ztc5anzgdwbvy/node_modules/@nx/devkit/src/generators/artifact-name-and-directory-utils.js:69:17)
    at getNameAndDirectoryOptions (/home/ubuntu/code/my-workspace/node_modules/.pnpm/@nx+devkit@20.1.0_nx@20.1.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@s_oybkiddel7pp5ztc5anzgdwbvy/node_modules/@nx/devkit/src/generators/artifact-name-and-directory-utils.js:19:46)
    at determineArtifactNameAndDirectoryOptions (/home/ubuntu/code/my-workspace/node_modules/.pnpm/@nx+devkit@20.1.0_nx@20.1.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@s_oybkiddel7pp5ztc5anzgdwbvy/node_modules/@nx/devkit/src/generators/artifact-name-and-directory-utils.js:10:31)
    at normalizeOptions (/home/ubuntu/code/my-workspace/node_modules/.pnpm/@nx+nest@20.1.0_@babel+traverse@7.25.9_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers_y7gceewjke5qrpusjipsa3rm6y/node_modules/@nx/nest/src/generators/utils/normalize-options.js:7:124)
    at normalizeServiceOptions (/home/ubuntu/code/my-workspace/node_modules/.pnpm/@nx+nest@20.1.0_@babel+traverse@7.25.9_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers_y7gceewjke5qrpusjipsa3rm6y/node_modules/@nx/nest/src/generators/service/service.js:11:66)
    at serviceGenerator (/home/ubuntu/code/my-workspace/node_modules/.pnpm/@nx+nest@20.1.0_@babel+traverse@7.25.9_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers_y7gceewjke5qrpusjipsa3rm6y/node_modules/@nx/nest/src/generators/service/service.js:6:27)
    at /home/ubuntu/code/my-workspace/node_modules/.pnpm/nx@20.1.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_lxgbel7nnuqlogftlxczfb77ne/node_modules/nx/src/command-line/generate/generate.js:240:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/home/ubuntu/code/my-workspace/node_modules/.pnpm/nx@20.1.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_lxgbel7nnuqlogftlxczfb77ne/node_modules/nx/src/utils/handle-errors.js:8:24)
    at async Object.handler (/home/ubuntu/code/my-workspace/node_modules/.pnpm/nx@20.1.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_lxgbel7nnuqlogftlxczfb77ne/node_modules/nx/src/command-line/generate/command-object.js:13:22)
```

### Package Manager Version

pnpm 9.9.0

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

In addition to that, I would kindly ask you to indicate the correct way to use the nestjs generator, as it is very different from the way I used it during nx 16-18.
I know we've switched to the default as-provided, but it also looks like the nestjs generator doesn't support directory but uses path instead.

I've read https://nx.dev/deprecated/as-provided-vs-derived#generate-paths-and-names-asprovided, but it doesn't look like that's what actually works, which I don't understand.

For example, when I try to generate code for a project in the root directory, I use the --path option and the files are generated in the wrong path.
```
➜  my-workspace git:(main) ✗ nx g @nx/nest:guard --name auth --path apps/my-workspace/src/app

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/apps/my-workspace/src/app/app.guard.spec.ts
CREATE apps/my-workspace/src/apps/my-workspace/src/app/app.guard.ts
```
It is duplicated in the `apps/my-workspace/src` section and I have to move it manually which I think might be wrong, it should be able to work correctly, in the past I used `--directory` to deal with the problem directly, but now it seems that it no longer exists.

I saw that section included in `--path` and maybe it was the cause of the error, so I went into that folder and generated it again.

```
➜  my-workspace git:(main) ✗ cd apps/my-workspace/src 
➜  src git:(main) ✗ nx g @nx/nest:guard --name auth --path app                      

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/app/app.guard.spec.ts
CREATE apps/my-workspace/src/app/app.guard.ts
```

Now, the generated path is correct, but again, I noticed that the generated file names `app.guard.ts` and classes `AppGuard` in them do not follow the input value `auth`, but appear to be automatically inferred from the path `app`. It's not just guard, but other nestjs code generators have similar problems, such as controllers and filters.

If I want to make sure the filename is correct, I have to make sure that the last part of the path in `--path` is the filename prefix I want. Just like:
```
nx g @nx/nest:guard --name auth --path app/auth
nx g @nx/nest:guard --name auth --path auth
```

But unfortunately the two methods above fall back into the cycle of problems about paths mentioned above.

```
➜  src git:(main) ✗ nx g @nx/nest:guard --name auth --path app/auth

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/app/app/auth/auth.guard.spec.ts
CREATE apps/my-workspace/src/app/app/auth/auth.guard.ts

➜  src git:(main) ✗ nx g @nx/nest:guard --name auth --path auth    

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/auth/auth.guard.spec.ts
CREATE apps/my-workspace/src/auth/auth.guard.ts
```

It looks like I have to enter the `app` directory to generate the file at `auth/auth.guard.ts`.

This breaks the intuition of the previous generator's use of `--directory`, and `--path` forces me to infer where I should be generating files and return the up-level directory in that location.

Also, I don't want to place the generated files inside a directory, well, at least not every time, e.g. I want to generate `auth.guard.ts` instead of `auth/auth.guard.ts`, which, if memory serves me correctly, was the behavior when I used --directory before.

I ask you to show me the right way. Can I generate the code in the root directory by specifying the path? Should the name specified via --name be used as the filename and class name? How to correctly infer `--path`, or restore `--directory` behavior?

### PR DESCRIPTION
**Pull request by pawel-twardziak**
# Related Issue(s)

Fixes #28910

### CODE REVIEW

**Comment by pawel-twardziak** [comment]
Hi @FrozenPandaz & @ndcunningham I still have trouble generating documentation locally - rspack problem or something

**Comment by pawel-twardziak** [comment]
ok, my rust cargo was outdated, I am updating the documentation

**Comment by pawel-twardziak** [comment]
@FrozenPandaz @ndcunningham I have no clue why I am still getting these:

obraz

but the files has been removed and not regenerated :( 

obraz

**Comment by pawel-twardziak** [comment]
I've noticed many changes to documentation scripts - some of them are not windows compatible

**Comment by pawel-twardziak** [comment]
no way to fix it in no time. It does not work on windows. I would need more time to fix it

**Comment by pawel-twardziak** [comment]
I've finally achieved what is necessary:

obraz

**Review by ndcunningham — APPROVED** [review]
LGTM thank you!

**Pull request merged**
