### PR TITLE
fix(core): add coverage folder to caching output of tests

### PR DESCRIPTION
**Pull request by PhilippSeitz**
## Current Behavior
The coverage output does not get cached when nx cache is used 

## Expected Behavior
Our build pipelines relay on test coverage and the test result output.
We need to persist them too, in order to use NX cache for our pipelines.

### CODE REVIEW

**Comment by vsavkin** [comment]
Thank you so much for your PR!

I'd like for Nx to move from "figuring out" outputs to users explicitly declaring them in configuration. 

You can add the outputs property to the test target, similar to how we have it configured for the build target in the nx repo itself:

```
     "build": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": ["build/packages/workspace"],
          "options": {
            "commands": [
              {
                "command": "nx build-base workspace"
              },
              {
                "command": "node ./scripts/copy-readme.js workspace"
              }
            ],
            "parallel": false
          }
        }
```

Everything in the outputs array will be cached. My question is whether we should do it for the test target only or for all targets.

**Comment by PhilippSeitz** [comment]
@vsavkin  First of all thank you for the amazing work on the build caching. It saves us hours!
I'd also prefer the explicit declaration. But could not find a way to automatically add the outputs settings to newly created libraries. It is just convenient to just let it "figuring it out" since I saw that it already does it for the builds.

Is there any way to achieve this?

**Comment by vsavkin** [comment]
Sorry for the late response. It will have to be done in schematics generating apps and libs. In places like that: `packages/next/src/schematics/application/lib/add-project.ts`.

To do it consistently, we will have to do it in quite a few places (angular apps/libs, react apps/libs, web apps/libs etc..), but the changes are straightforward.

It's a bit more work than the original PR. So if you don't feel like doing, that's totally fine :) Somewhat on the core team can do it instead. If you want to do it though, we will help.

**Comment by PhilippSeitz** [comment]
@vsavkin i started working on the changes but I have only limited time for it. Help is appreciated. Especially regarding the tests.

**Comment by vsavkin** [comment]
The changes are good. We can help out: someone on the core team can finish the PR if you want. Just let me know.

**Comment by vsavkin** [comment]
@PhilippSeitz sorry for bugging you. Would you like one of us to help out or you want to wrap it up yourself?

**Comment by PhilippSeitz** [comment]
@vsavkin sorry for the late response. Thought I could finish it up, but didn't find enough time at the moment. Help is appreciated!

**Comment by bekos** [comment]
hi @PhilippSeitz and thanks a lot for your PR. Your changes are in the correct direction, but we had to increase the scope of this, in order to address and some other issues caused by such change. These will be addressed via https://github.com/nrwl/nx/pull/4094. Thanks again for your effort, it was very helpful 👍

**Pull request closed without merging**
