### PR TITLE
fix(react): timeout after 20 min waiting for remote

### LINKED ISSUE #17354: React, MFE - Timed out waiting for remote to start. Check above for any errors
### Current Behavior

After some time after successful start I get this error
Started after update to 16.3.0

### Expected Behavior

All continue work successfully 

### GitHub Repo

_No response_

### Steps to Reproduce

I checked code and looks like related to custom host option instead of standard localhost 

nx serve host --open --devRemotes={...} --ssl --host {...} --ssl-cert {...}--ssl-key {...}

### Nx Report

```shell
Node   : 18.12.1
   OS     : darwin x64
   npm    : 8.19.2
   Hasher : Native
   
   nx                 : 16.3.0
   @nx/js             : 16.3.0
   @nx/jest           : 16.3.0
   @nx/linter         : 16.3.0
   @nx/workspace      : 16.3.0
   @nx/cypress        : 16.3.0
   @nx/devkit         : 16.3.0
   @nx/eslint-plugin  : 16.3.0
   @nx/react          : 16.3.0
   @nrwl/tao          : 16.3.0
   @nx/web            : 16.3.0
   @nx/webpack        : 16.3.0
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Failure Logs

```shell
.../node_modules/@nx/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:98
                throw new Error(`Timed out waiting for remote to start. Check above for any errors.`);
                      ^

Error: Timed out waiting for remote to start. Check above for any errors.
    at .../node_modules/@nx/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:98:23
    at Generator.throw (<anonymous>)
    at rejected (.../node_modules/tslib/tslib.js:165:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project host failed

   Failed tasks:
   
   - host:serve:development
   
   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at ...
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by koenvangeert**
## Current Behavior
When using module federation the server will close after 20 minutes with the following error:

```
.../node_modules/@nx/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:98
                throw new Error(`Timed out waiting for remote to start. Check above for any errors.`);
                      ^

Error: Timed out waiting for remote to start. Check above for any errors.
    at .../node_modules/@nx/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:98:23
    at Generator.throw (<anonymous>)
    at rejected (.../node_modules/tslib/tslib.js:165:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Expected Behavior
The server keeps on running

## Cause

The following pr caused the bug to occur: https://github.com/nrwl/nx/pull/17192
The webpack dev server doesn't bind to `127.0.0.1` by default.
It only binds to `localhost` and `::1`.

## Related Issue(s)
Fixes https://github.com/nrwl/nx/issues/17354

### CODE REVIEW

**Comment by xiongemi** [comment]
thanks for submitting this pr. i think `host: 'localhost'` was already removed. i am going to close this pr.

**Comment by vadimka123** [comment]
@xiongemi , removing host: 'localhost' cause issue
Returning back will fix this bug
I manually fixing every time now by updating relevant file in my local node_modules with this change 
But I want to have merged this change ASAP

**Comment by Coly010** [comment]
Let me take a look at this :)

**Review by Coly010 — APPROVED** [review]

**Review by xiongemi — APPROVED** [review]

**Comment by DheerajMahra** [comment]
Hi team, please mentioned the release into which this issue is fixed

**Comment by DheerajMahra** [comment]
Ok, the fix is listed in 16.6.0 ore-release - https://github.com/nrwl/nx/releases/tag/16.6.0-beta.6

When are you planning to release the stable 16.6.0?

**Pull request merged**
