### PR TITLE
feat(expo): upgrade Expo to v52

### PR DESCRIPTION
**Pull request by xiongemi**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by yonitou** [comment]
Hi ! 
When do you think it will be released ?

**Comment by hassankhan** [comment]
Thanks for taking a look @xiongemi, I'll try and test out the PR this weekend

**Comment by hassankhan** [comment]
@xiongemi Got a chance to test it, its working perfectly for me 💯

**Comment by hassankhan** [comment]
It might be worth updating Expo to 52.0.16 because of some issues with Expo Router and Sentry though: https://github.com/expo/expo/pull/33344

**Comment by bennnjamin** [comment]
Will this allow us to upgrade projects created with @nx/expo with expo 51 to expo 52?

**Comment by hassankhan** [comment]
@bennnjamin It will

**Review by Coly010 — APPROVED** [review]

**Comment by xiongemi** [comment]
> Hi ! When do you think it will be released ?

it should be in 20.3.0

**Pull request merged**
