### PR TITLE
fix(web): Added WebpackError for webpack 4 compatibility

### LINKED ISSUE #6485: webpack.WebpackError is not a constructor when migrating from Nx v12.5.0 to Nx v12.6.0
Related: #6483 

## Current Behavior
After upgrading from Nx v12.5.0 to Nx v12.6.0, when I build my React app with Webpack 4 in production mode, it throws an error:
`webpack.WebpackError is not a constructor` when running the command: `yarn nx build automation --prod`. However, when building without the `--prod` flag, it works fine.

## Expected Behavior

I expect it to build. I believe this is a regression. I think what's happening is that @nrwl/web thinks I'm using Webpack 5 when really I am still using Webpack 4.

## Steps to Reproduce
1. Clone the [nx-examples repo](https://github.com/nrwl/nx-examples)
2. Run `yarn`
3. Change line 56 in `apps/cart/project.json`:
  3.1. From `"maximumWarning": "2mb",`
  3.2. To this:  `"maximumWarning": "2b",`
5. Try to build the cart app in production mode: `yarn nx build cart --prod`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```
$ nx build cart --prod

> nx run cart:build:production
webpack.WebpackError is not a constructor

———————————————————————————————————————————————

>  NX   ERROR  Running target "cart:build" failed

  Failed tasks:

  - cart:build:production

  Hint: run the command with --verbose for more details.
```

### Environment
```
  Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : 12.6.4
  @nrwl/cli : 12.6.4
  @nrwl/cypress : 12.6.4
  @nrwl/devkit : 12.6.4
  @nrwl/eslint-plugin-nx : 12.6.4
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.4
  @nrwl/linter : 12.6.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.5
  @nrwl/react : 12.6.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.4
  @nrwl/web : 12.6.4
  @nrwl/workspace : 12.6.4
  @nrwl/storybook : 12.6.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### PR DESCRIPTION
**Pull request by ashwinGokhale**
## Current Behavior
webpack.WebpackError does not exist for when using webpack 4

## Expected Behavior
Added WebpackError for webpack 4 compatibility

## Related Issue(s)

Fixes #6485

### CODE REVIEW

**Comment by ashwinGokhale** [comment]
@jaysoo could you take a look? Without this fix any warnings when building w/ webpack 4 will fail.

**Comment by ashwinGokhale** [comment]
@jaysoo @FrozenPandaz could you please take a look? I think this is an important bug fix

**Comment by ashwinGokhale** [comment]
@jaysoo @FrozenPandaz @vsavkin it’s been 3 weeks since I created my PR. Any chance someone can take a look?

**Review by jaysoo — APPROVED** [review]

**Comment by jaysoo** [comment]
It'll be in Nx 12.8.0. Thanks for submitting the PR!

**Comment by montogeek** [comment]
Wouldn't be a good idea to add a TODO or note to this change to remove it once Webpack 4 is not supported anymore by Nx?

**Pull request merged**
