### PR TITLE
fix(workspace): exit process with exit code 1 on any failed task including dependency

### LINKED ISSUE #6630: Workspaces run command: Command fails without exit code 1 if failed task is not target (i.e. task is dependency)
## Current Behavior
 Command fails without exit code 1 (i.e. with exit code 1) if failed task is not target (i.e. task is dependency)

## Expected Behavior
Tasks run as dependencies to target task should also fail with exit code 1.

## Steps to Reproduce
1. Clone [this repo](https://github.com/MaximSagan/nx-multi-app-workspace), which is a minimal repo crated with `npx create-nx-workspace` (selected Angular, called default app `ng-app1`, selected defaults), `nx generate @nrwl/angular:app ng-app2`, adding ng-app2 as an implicit dependency for `ng-app1` in `nx.json`, and intentionally breaking `ng-app2` so that it fails the build (by referencing an nonexistent component in the template).
2. Run `ng build ng-app2`, and observe build failure
```
>  NX   ERROR  Running target "ng-app2:build" failed
   Failed tasks:
   - ng-app2:build:production
```
3. Confirm that the exit code for the above step was `1` (`echo $?` if you are using bash).
4. Run `ng build ng-app1`. `ng-app2` will build first as it is a dependency of `ng-app2` and observe the same build failure as in step 2.
```
>  NX   ERROR  Running target "ng-app1:build" failed
   Failed tasks:
   - ng-app2:build:production
```
5. Check the exit code for the above step (`echo $?` if you are using bash), and you should find that it was `0`.

### Environment
Node: v14.17.1
@nrwl/workspace: 12.6.0-beta.10 (also occurring on earlier minor versions)

### PR DESCRIPTION
**Pull request by MaximSagan**
Fixes #6630

### CODE REVIEW

**Review by FrozenPandaz — CHANGES_REQUESTED** [review]
Thank you for taking a look at this issue!

This solution works :+1:  but I think the correct solution is a bit deeper :wink:.

On [line 97](https://github.com/nrwl/nx/pull/6631/files#diff-47f8c3726fea1ea1307be6189b8d30ea248bc55a2377dc5bd0605e03972c220fL97)

When a `Dependency Failed` event comes back, this should set the workspaceResult.

Could you make the change please? If not, I can take over from here. 

Thank you again for fixing the issue!

**Comment by MaximSagan** [comment]
@FrozenPandaz
I suppose setting the workspace result here should also be preceded by the same conditional it is in the other two cases (i.e. checking that the task is a target)? If so, we can take that conditional out of the switch statement.
Also, are you suggesting the [additional checks](https://github.com/nrwl/nx/pull/6631/files#diff-47f8c3726fea1ea1307be6189b8d30ea248bc55a2377dc5bd0605e03972c220fR137-R138) I added in the conditional for `process.exit(1)` should be unnecessary?

**Comment by MaximSagan** [comment]
@FrozenPandaz
Something seems to have happened with the CircleCI agents (taking a look at the logs, doesn't seem to be related to my changes), and I don't seem to have sufficient privileges to re-run the pipeline.
https://app.circleci.com/pipelines/github/nrwl/nx?branch=pull%2F6631

**Comment by MaximSagan** [comment]
@FrozenPandaz I believe I've made the appropriate changes. Could I get you to review this?

**Comment by vojtesaak** [comment]
@FrozenPandaz it would be nice to get it merged soon :)

**Review by FrozenPandaz — APPROVED** [review]
Yes, thank you so much! LGTM! :tada:

**Pull request merged**
